// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.equipment

import java.time.LocalDate
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EquipmentCreateBulkParamsTest {

    @Test
    fun create() {
        EquipmentCreateBulkParams.builder()
            .addBody(
                EquipmentCreateBulkParams.Body.builder()
                    .classificationMarking("U")
                    .countryCode("IQ")
                    .dataMode(EquipmentCreateBulkParams.Body.DataMode.TEST)
                    .lat(39.019242)
                    .lon(-104.251659)
                    .source("Bluestaq")
                    .id("0167f577-e06c-358e-85aa-0a07a730bdd0")
                    .airDefArea("AL006")
                    .allegiance("OTHR")
                    .altAllegiance("HL")
                    .altCountryCode("IZ")
                    .altEqpId("ORIG-EQP-ID")
                    .classRating("1")
                    .condition("RDY")
                    .conditionAvail("A")
                    .coord("340000000N0430000000E")
                    .coordDatum("WGS")
                    .coordDerivAcc(12.345)
                    .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                    .createdBy("some.user")
                    .elevMsl(123.45)
                    .elevMslConfLvl(50)
                    .elevMslDerivAcc(12.34)
                    .eqpCode("X12345")
                    .eqpIdNum("001")
                    .eval(7)
                    .fpa("NOB")
                    .function("OCC")
                    .functPrimary("JG")
                    .geoidalMslSep(12.34)
                    .ident("FRIEND")
                    .idOperatingUnit("UNIT-ID")
                    .idParentEquipment("PARENT-EQUIPMENT-ID")
                    .idSite("SITE-ID")
                    .locReason("GR")
                    .milGrid("4QFJ12345678")
                    .milGridSys("UTM")
                    .nomen("AMPHIBIOUS WARFARE SHIP")
                    .operAreaPrimary("Territorial Sea")
                    .operStatus("OPR")
                    .origin("THIRD_PARTY_DATASOURCE")
                    .polSubdiv("IZ07")
                    .qtyOh(7)
                    .recStatus("A")
                    .referenceDoc("Provider Reference Documentation")
                    .resProd("RT")
                    .reviewDate(LocalDate.parse("2008-06-10"))
                    .seqNum(5)
                    .addSrcId("SRC_ID_1")
                    .addSrcTyp("AIRCRAFT")
                    .symCode("SOGPU----------")
                    .utm("19P4390691376966")
                    .wac("0427")
                    .build()
            )
            .build()
    }

    @Test
    fun body() {
        val params =
            EquipmentCreateBulkParams.builder()
                .addBody(
                    EquipmentCreateBulkParams.Body.builder()
                        .classificationMarking("U")
                        .countryCode("IQ")
                        .dataMode(EquipmentCreateBulkParams.Body.DataMode.TEST)
                        .lat(39.019242)
                        .lon(-104.251659)
                        .source("Bluestaq")
                        .id("0167f577-e06c-358e-85aa-0a07a730bdd0")
                        .airDefArea("AL006")
                        .allegiance("OTHR")
                        .altAllegiance("HL")
                        .altCountryCode("IZ")
                        .altEqpId("ORIG-EQP-ID")
                        .classRating("1")
                        .condition("RDY")
                        .conditionAvail("A")
                        .coord("340000000N0430000000E")
                        .coordDatum("WGS")
                        .coordDerivAcc(12.345)
                        .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                        .createdBy("some.user")
                        .elevMsl(123.45)
                        .elevMslConfLvl(50)
                        .elevMslDerivAcc(12.34)
                        .eqpCode("X12345")
                        .eqpIdNum("001")
                        .eval(7)
                        .fpa("NOB")
                        .function("OCC")
                        .functPrimary("JG")
                        .geoidalMslSep(12.34)
                        .ident("FRIEND")
                        .idOperatingUnit("UNIT-ID")
                        .idParentEquipment("PARENT-EQUIPMENT-ID")
                        .idSite("SITE-ID")
                        .locReason("GR")
                        .milGrid("4QFJ12345678")
                        .milGridSys("UTM")
                        .nomen("AMPHIBIOUS WARFARE SHIP")
                        .operAreaPrimary("Territorial Sea")
                        .operStatus("OPR")
                        .origin("THIRD_PARTY_DATASOURCE")
                        .polSubdiv("IZ07")
                        .qtyOh(7)
                        .recStatus("A")
                        .referenceDoc("Provider Reference Documentation")
                        .resProd("RT")
                        .reviewDate(LocalDate.parse("2008-06-10"))
                        .seqNum(5)
                        .addSrcId("SRC_ID_1")
                        .addSrcTyp("AIRCRAFT")
                        .symCode("SOGPU----------")
                        .utm("19P4390691376966")
                        .wac("0427")
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body)
            .containsExactly(
                EquipmentCreateBulkParams.Body.builder()
                    .classificationMarking("U")
                    .countryCode("IQ")
                    .dataMode(EquipmentCreateBulkParams.Body.DataMode.TEST)
                    .lat(39.019242)
                    .lon(-104.251659)
                    .source("Bluestaq")
                    .id("0167f577-e06c-358e-85aa-0a07a730bdd0")
                    .airDefArea("AL006")
                    .allegiance("OTHR")
                    .altAllegiance("HL")
                    .altCountryCode("IZ")
                    .altEqpId("ORIG-EQP-ID")
                    .classRating("1")
                    .condition("RDY")
                    .conditionAvail("A")
                    .coord("340000000N0430000000E")
                    .coordDatum("WGS")
                    .coordDerivAcc(12.345)
                    .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                    .createdBy("some.user")
                    .elevMsl(123.45)
                    .elevMslConfLvl(50)
                    .elevMslDerivAcc(12.34)
                    .eqpCode("X12345")
                    .eqpIdNum("001")
                    .eval(7)
                    .fpa("NOB")
                    .function("OCC")
                    .functPrimary("JG")
                    .geoidalMslSep(12.34)
                    .ident("FRIEND")
                    .idOperatingUnit("UNIT-ID")
                    .idParentEquipment("PARENT-EQUIPMENT-ID")
                    .idSite("SITE-ID")
                    .locReason("GR")
                    .milGrid("4QFJ12345678")
                    .milGridSys("UTM")
                    .nomen("AMPHIBIOUS WARFARE SHIP")
                    .operAreaPrimary("Territorial Sea")
                    .operStatus("OPR")
                    .origin("THIRD_PARTY_DATASOURCE")
                    .polSubdiv("IZ07")
                    .qtyOh(7)
                    .recStatus("A")
                    .referenceDoc("Provider Reference Documentation")
                    .resProd("RT")
                    .reviewDate(LocalDate.parse("2008-06-10"))
                    .seqNum(5)
                    .addSrcId("SRC_ID_1")
                    .addSrcTyp("AIRCRAFT")
                    .symCode("SOGPU----------")
                    .utm("19P4390691376966")
                    .wac("0427")
                    .build()
            )
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            EquipmentCreateBulkParams.builder()
                .addBody(
                    EquipmentCreateBulkParams.Body.builder()
                        .classificationMarking("U")
                        .countryCode("IQ")
                        .dataMode(EquipmentCreateBulkParams.Body.DataMode.TEST)
                        .lat(39.019242)
                        .lon(-104.251659)
                        .source("Bluestaq")
                        .build()
                )
                .build()

        val body = params._body()

        assertThat(body)
            .containsExactly(
                EquipmentCreateBulkParams.Body.builder()
                    .classificationMarking("U")
                    .countryCode("IQ")
                    .dataMode(EquipmentCreateBulkParams.Body.DataMode.TEST)
                    .lat(39.019242)
                    .lon(-104.251659)
                    .source("Bluestaq")
                    .build()
            )
    }
}
