// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.sgi

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SgiListResponseTest {

    @Test
    fun create() {
        val sgiListResponse =
            SgiListResponse.builder()
                .classificationMarking("U")
                .dataMode(SgiListResponse.DataMode.TEST)
                .effectiveDate(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .sgiDate(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .source("Bluestaq")
                .id("SGI-ID")
                .analyzerAttenuation(5.1)
                .ap(1.23)
                .apDuration(3)
                .coeffDegree(listOf(1, 2, 3))
                .coeffOrder(listOf(1, 2, 3))
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .ctce(listOf(1.23, 342.3, 1.32))
                .ctci(listOf(1.23, 342.3, 1.32))
                .dst(1.23)
                .dtc(1.23)
                .e10(1.23)
                .e54(1.23)
                .f10(1.23)
                .f10High(187.5)
                .f10Low(185.5)
                .f54(1.23)
                .f81(1.23)
                .gamma(25)
                .idSensor("57c96c97-e076-48af-a068-73ee2cb37e65")
                .kIndex(1)
                .kp(4.66)
                .kpDuration(3)
                .m10(1.23)
                .m54(1.23)
                .mode(1)
                .normFactor(2.12679e-7)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("ORIG")
                .origSensorId("ORIGSENSOR-ID")
                .precedence(SgiListResponse.Precedence.R)
                .rawFileUri("rawFileURI")
                .rbDuration(24)
                .rbIndex(1.02947164506)
                .rbRegionCode(2)
                .s10(1.23)
                .s54(1.23)
                .state(SgiListResponse.State.I)
                .stationName("Boulder")
                .stce(listOf(1.23, 342.3, 1.32))
                .stci(listOf(1.23, 342.3, 1.32))
                .sunspotNum(151.1)
                .sunspotNumHigh(152.1)
                .sunspotNumLow(150.1)
                .transactionId("TRANSACTION-ID")
                .type("JBH09")
                .y10(1.23)
                .y54(1.23)
                .build()

        assertThat(sgiListResponse.classificationMarking()).isEqualTo("U")
        assertThat(sgiListResponse.dataMode()).isEqualTo(SgiListResponse.DataMode.TEST)
        assertThat(sgiListResponse.effectiveDate())
            .isEqualTo(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(sgiListResponse.sgiDate())
            .isEqualTo(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(sgiListResponse.source()).isEqualTo("Bluestaq")
        assertThat(sgiListResponse.id()).contains("SGI-ID")
        assertThat(sgiListResponse.analyzerAttenuation()).contains(5.1)
        assertThat(sgiListResponse.ap()).contains(1.23)
        assertThat(sgiListResponse.apDuration()).contains(3)
        assertThat(sgiListResponse.coeffDegree().getOrNull()).containsExactly(1, 2, 3)
        assertThat(sgiListResponse.coeffOrder().getOrNull()).containsExactly(1, 2, 3)
        assertThat(sgiListResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(sgiListResponse.createdBy()).contains("some.user")
        assertThat(sgiListResponse.ctce().getOrNull()).containsExactly(1.23, 342.3, 1.32)
        assertThat(sgiListResponse.ctci().getOrNull()).containsExactly(1.23, 342.3, 1.32)
        assertThat(sgiListResponse.dst()).contains(1.23)
        assertThat(sgiListResponse.dtc()).contains(1.23)
        assertThat(sgiListResponse.e10()).contains(1.23)
        assertThat(sgiListResponse.e54()).contains(1.23)
        assertThat(sgiListResponse.f10()).contains(1.23)
        assertThat(sgiListResponse.f10High()).contains(187.5)
        assertThat(sgiListResponse.f10Low()).contains(185.5)
        assertThat(sgiListResponse.f54()).contains(1.23)
        assertThat(sgiListResponse.f81()).contains(1.23)
        assertThat(sgiListResponse.gamma()).contains(25)
        assertThat(sgiListResponse.idSensor()).contains("57c96c97-e076-48af-a068-73ee2cb37e65")
        assertThat(sgiListResponse.kIndex()).contains(1)
        assertThat(sgiListResponse.kp()).contains(4.66)
        assertThat(sgiListResponse.kpDuration()).contains(3)
        assertThat(sgiListResponse.m10()).contains(1.23)
        assertThat(sgiListResponse.m54()).contains(1.23)
        assertThat(sgiListResponse.mode()).contains(1)
        assertThat(sgiListResponse.normFactor()).contains(2.12679e-7)
        assertThat(sgiListResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(sgiListResponse.origNetwork()).contains("ORIG")
        assertThat(sgiListResponse.origSensorId()).contains("ORIGSENSOR-ID")
        assertThat(sgiListResponse.precedence()).contains(SgiListResponse.Precedence.R)
        assertThat(sgiListResponse.rawFileUri()).contains("rawFileURI")
        assertThat(sgiListResponse.rbDuration()).contains(24)
        assertThat(sgiListResponse.rbIndex()).contains(1.02947164506)
        assertThat(sgiListResponse.rbRegionCode()).contains(2)
        assertThat(sgiListResponse.s10()).contains(1.23)
        assertThat(sgiListResponse.s54()).contains(1.23)
        assertThat(sgiListResponse.state()).contains(SgiListResponse.State.I)
        assertThat(sgiListResponse.stationName()).contains("Boulder")
        assertThat(sgiListResponse.stce().getOrNull()).containsExactly(1.23, 342.3, 1.32)
        assertThat(sgiListResponse.stci().getOrNull()).containsExactly(1.23, 342.3, 1.32)
        assertThat(sgiListResponse.sunspotNum()).contains(151.1)
        assertThat(sgiListResponse.sunspotNumHigh()).contains(152.1)
        assertThat(sgiListResponse.sunspotNumLow()).contains(150.1)
        assertThat(sgiListResponse.transactionId()).contains("TRANSACTION-ID")
        assertThat(sgiListResponse.type()).contains("JBH09")
        assertThat(sgiListResponse.y10()).contains(1.23)
        assertThat(sgiListResponse.y54()).contains(1.23)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val sgiListResponse =
            SgiListResponse.builder()
                .classificationMarking("U")
                .dataMode(SgiListResponse.DataMode.TEST)
                .effectiveDate(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .sgiDate(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .source("Bluestaq")
                .id("SGI-ID")
                .analyzerAttenuation(5.1)
                .ap(1.23)
                .apDuration(3)
                .coeffDegree(listOf(1, 2, 3))
                .coeffOrder(listOf(1, 2, 3))
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .ctce(listOf(1.23, 342.3, 1.32))
                .ctci(listOf(1.23, 342.3, 1.32))
                .dst(1.23)
                .dtc(1.23)
                .e10(1.23)
                .e54(1.23)
                .f10(1.23)
                .f10High(187.5)
                .f10Low(185.5)
                .f54(1.23)
                .f81(1.23)
                .gamma(25)
                .idSensor("57c96c97-e076-48af-a068-73ee2cb37e65")
                .kIndex(1)
                .kp(4.66)
                .kpDuration(3)
                .m10(1.23)
                .m54(1.23)
                .mode(1)
                .normFactor(2.12679e-7)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("ORIG")
                .origSensorId("ORIGSENSOR-ID")
                .precedence(SgiListResponse.Precedence.R)
                .rawFileUri("rawFileURI")
                .rbDuration(24)
                .rbIndex(1.02947164506)
                .rbRegionCode(2)
                .s10(1.23)
                .s54(1.23)
                .state(SgiListResponse.State.I)
                .stationName("Boulder")
                .stce(listOf(1.23, 342.3, 1.32))
                .stci(listOf(1.23, 342.3, 1.32))
                .sunspotNum(151.1)
                .sunspotNumHigh(152.1)
                .sunspotNumLow(150.1)
                .transactionId("TRANSACTION-ID")
                .type("JBH09")
                .y10(1.23)
                .y54(1.23)
                .build()

        val roundtrippedSgiListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(sgiListResponse),
                jacksonTypeRef<SgiListResponse>(),
            )

        assertThat(roundtrippedSgiListResponse).isEqualTo(sgiListResponse)
    }
}
