// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.dropzone

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class DropzoneTupleResponseTest {

    @Test
    fun create() {
        val dropzoneTupleResponse =
            DropzoneTupleResponse.builder()
                .classificationMarking("U")
                .dataMode(DropzoneTupleResponse.DataMode.TEST)
                .lat(33.54)
                .lon(-117.162)
                .name("Viper DZ")
                .source("Bluestaq")
                .id("3f28f60b-3a50-2aef-ac88-8e9d0e39912b")
                .altCountryCode("USA")
                .altCountryName("United States of America")
                .approvalDate(OffsetDateTime.parse("2018-01-05T16:00:00.123Z"))
                .code("DZ")
                .countryCode("US")
                .countryName("United States")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .expirationDate(OffsetDateTime.parse("2022-12-09T16:00:00.123Z"))
                .extIdentifier("1001")
                .idSite("a150b3ee-884b-b9ac-60a0-6408b4b16088")
                .lastUpdate(OffsetDateTime.parse("2022-11-07T18:44:41.123Z"))
                .length(549.1)
                .majcom("United States Northern Command")
                .nearestLoc("March AFB")
                .operationalApprovalDate(OffsetDateTime.parse("2018-01-05T16:00:00.123Z"))
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .pointName("CENTER POINT")
                .radius(495.1)
                .recertDate(OffsetDateTime.parse("2022-07-05T16:00:00.123Z"))
                .remark("The text of the remark.")
                .sourceDl("AXE")
                .stateAbbr("CA")
                .stateName("CALIFORNIA")
                .surveyDate(OffsetDateTime.parse("2017-12-09T16:00:00.123Z"))
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .width(549.1)
                .zarId("1001")
                .build()

        assertThat(dropzoneTupleResponse.classificationMarking()).isEqualTo("U")
        assertThat(dropzoneTupleResponse.dataMode()).isEqualTo(DropzoneTupleResponse.DataMode.TEST)
        assertThat(dropzoneTupleResponse.lat()).isEqualTo(33.54)
        assertThat(dropzoneTupleResponse.lon()).isEqualTo(-117.162)
        assertThat(dropzoneTupleResponse.name()).isEqualTo("Viper DZ")
        assertThat(dropzoneTupleResponse.source()).isEqualTo("Bluestaq")
        assertThat(dropzoneTupleResponse.id()).contains("3f28f60b-3a50-2aef-ac88-8e9d0e39912b")
        assertThat(dropzoneTupleResponse.altCountryCode()).contains("USA")
        assertThat(dropzoneTupleResponse.altCountryName()).contains("United States of America")
        assertThat(dropzoneTupleResponse.approvalDate())
            .contains(OffsetDateTime.parse("2018-01-05T16:00:00.123Z"))
        assertThat(dropzoneTupleResponse.code()).contains("DZ")
        assertThat(dropzoneTupleResponse.countryCode()).contains("US")
        assertThat(dropzoneTupleResponse.countryName()).contains("United States")
        assertThat(dropzoneTupleResponse.createdAt())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(dropzoneTupleResponse.createdBy()).contains("some.user")
        assertThat(dropzoneTupleResponse.expirationDate())
            .contains(OffsetDateTime.parse("2022-12-09T16:00:00.123Z"))
        assertThat(dropzoneTupleResponse.extIdentifier()).contains("1001")
        assertThat(dropzoneTupleResponse.idSite()).contains("a150b3ee-884b-b9ac-60a0-6408b4b16088")
        assertThat(dropzoneTupleResponse.lastUpdate())
            .contains(OffsetDateTime.parse("2022-11-07T18:44:41.123Z"))
        assertThat(dropzoneTupleResponse.length()).contains(549.1)
        assertThat(dropzoneTupleResponse.majcom()).contains("United States Northern Command")
        assertThat(dropzoneTupleResponse.nearestLoc()).contains("March AFB")
        assertThat(dropzoneTupleResponse.operationalApprovalDate())
            .contains(OffsetDateTime.parse("2018-01-05T16:00:00.123Z"))
        assertThat(dropzoneTupleResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(dropzoneTupleResponse.origNetwork()).contains("OPS1")
        assertThat(dropzoneTupleResponse.pointName()).contains("CENTER POINT")
        assertThat(dropzoneTupleResponse.radius()).contains(495.1)
        assertThat(dropzoneTupleResponse.recertDate())
            .contains(OffsetDateTime.parse("2022-07-05T16:00:00.123Z"))
        assertThat(dropzoneTupleResponse.remark()).contains("The text of the remark.")
        assertThat(dropzoneTupleResponse.sourceDl()).contains("AXE")
        assertThat(dropzoneTupleResponse.stateAbbr()).contains("CA")
        assertThat(dropzoneTupleResponse.stateName()).contains("CALIFORNIA")
        assertThat(dropzoneTupleResponse.surveyDate())
            .contains(OffsetDateTime.parse("2017-12-09T16:00:00.123Z"))
        assertThat(dropzoneTupleResponse.updatedAt())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(dropzoneTupleResponse.updatedBy()).contains("some.user")
        assertThat(dropzoneTupleResponse.width()).contains(549.1)
        assertThat(dropzoneTupleResponse.zarId()).contains("1001")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val dropzoneTupleResponse =
            DropzoneTupleResponse.builder()
                .classificationMarking("U")
                .dataMode(DropzoneTupleResponse.DataMode.TEST)
                .lat(33.54)
                .lon(-117.162)
                .name("Viper DZ")
                .source("Bluestaq")
                .id("3f28f60b-3a50-2aef-ac88-8e9d0e39912b")
                .altCountryCode("USA")
                .altCountryName("United States of America")
                .approvalDate(OffsetDateTime.parse("2018-01-05T16:00:00.123Z"))
                .code("DZ")
                .countryCode("US")
                .countryName("United States")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .expirationDate(OffsetDateTime.parse("2022-12-09T16:00:00.123Z"))
                .extIdentifier("1001")
                .idSite("a150b3ee-884b-b9ac-60a0-6408b4b16088")
                .lastUpdate(OffsetDateTime.parse("2022-11-07T18:44:41.123Z"))
                .length(549.1)
                .majcom("United States Northern Command")
                .nearestLoc("March AFB")
                .operationalApprovalDate(OffsetDateTime.parse("2018-01-05T16:00:00.123Z"))
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .pointName("CENTER POINT")
                .radius(495.1)
                .recertDate(OffsetDateTime.parse("2022-07-05T16:00:00.123Z"))
                .remark("The text of the remark.")
                .sourceDl("AXE")
                .stateAbbr("CA")
                .stateName("CALIFORNIA")
                .surveyDate(OffsetDateTime.parse("2017-12-09T16:00:00.123Z"))
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .width(549.1)
                .zarId("1001")
                .build()

        val roundtrippedDropzoneTupleResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(dropzoneTupleResponse),
                jacksonTypeRef<DropzoneTupleResponse>(),
            )

        assertThat(roundtrippedDropzoneTupleResponse).isEqualTo(dropzoneTupleResponse)
    }
}
