configured_endpoints: 1547
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/bluestaq%2Funifieddatalibrary-09bd422d5ac1ece2c30dd9d0dd59b8ce3ac2cefcb4aa8a06d04cd4d0693c762e.yml
openapi_spec_hash: da701c9aeea552200a9ba34cc695664e
config_hash: b82b8704cd8de9933000e2d3e8c2bffc
