// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.ionoobservation

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class IonOobservationListResponseTest {

    @Test
    fun create() {
        val ionOobservationListResponse =
            IonOobservationListResponse.builder()
                .classificationMarking("U")
                .dataMode(IonOobservationListResponse.DataMode.TEST)
                .source("Bluestaq")
                .startTimeUtc(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .stationId("STATION-ID")
                .system("Example hardware type")
                .systemInfo("Example settings")
                .id("IONOOBSERVATION-ID")
                .amplitude(
                    IonOobservationListResponse.Amplitude.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(4)
                        .addDimension(5)
                        .notes("NOTES")
                        .build()
                )
                .antennaElementPosition(
                    IonOobservationListResponse.AntennaElementPosition.builder()
                        .addData(listOf(1.23, 0.123))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(3)
                        .addDimension(4)
                        .build()
                )
                .antennaElementPositionCoordinateSystem(
                    IonOobservationListResponse.AntennaElementPositionCoordinateSystem.J2000
                )
                .artistFlags(listOf(1, 2, 3))
                .azimuth(
                    IonOobservationListResponse.Azimuth.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .b0(68.07)
                .b1(1.87)
                .addCharAtt(
                    IonOobservationListResponse.CharAtt.builder()
                        .charName("hprimeF2")
                        .addClimateModelInputParam("ISSN1 88.1")
                        .addClimateModelInputParam("Option 2")
                        .climateModelName("IRI")
                        .addClimateModelOption("URSI-88")
                        .addClimateModelOption("No storm")
                        .d("K")
                        .lowerBound(1.26)
                        .q("T")
                        .uncertaintyBoundType("1sigma")
                        .upperBound(2.57)
                        .ursiId("04")
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .d(1.1)
                .d1(1.94)
                .datum(
                    IonOobservationListResponse.Datum.builder()
                        .data(listOf(1.1, 2.1, 3.1))
                        .notes("NOTES")
                        .build()
                )
                .deltafoF2(1.1)
                .densityProfile(
                    IonOobservationListResponse.DensityProfile.builder()
                        .iri(
                            IonOobservationListResponse.DensityProfile.Iri.builder()
                                .b0(245.1)
                                .b1(3.45)
                                .chi(35.1)
                                .d1(0.0)
                                .description(
                                    "Full altitude range of 1D vertical plasma density profile for D, E, and F regions of the ionosphere provided by IRI, in which model parameters are replaced with observed ionogram-derived data where available."
                                )
                                .fp1(0.0474732023322638)
                                .fp2(-0.00112685246984002)
                                .fp30(0.00827559450035957)
                                .fp3U(0.000201178475411428)
                                .ha(50.1)
                                .hdx(85.6)
                                .hmD(81.1)
                                .hmE(99.8)
                                .hmF1(210.3)
                                .hmF2(265.42)
                                .hValTop(116.2)
                                .hz(142.7)
                                .nmD(937543116.1)
                                .nmE(154164.1)
                                .nmF1(210486.0)
                                .nmF2(313283.1)
                                .nValB(147025.1)
                                .build()
                        )
                        .parabolic(
                            IonOobservationListResponse.DensityProfile.Parabolic.builder()
                                .description("Best-fit algorithm in NHPC software.")
                                .addParabolicItem(
                                    IonOobservationListResponse.DensityProfile.Parabolic
                                        .ParabolicItem
                                        .builder()
                                        .f(3.621)
                                        .layer("E")
                                        .y(11.1)
                                        .z(110.2)
                                        .build()
                                )
                                .build()
                        )
                        .quasiParabolic(
                            IonOobservationListResponse.DensityProfile.QuasiParabolic.builder()
                                .description(
                                    "Array of the best-fit 3-parameter quasi-parabolas defined via A, B, C coefficients, f^2=A/r^2+B/r+C"
                                )
                                .earthRadius(6370.1)
                                .addQuasiParabolicSegment(
                                    IonOobservationListResponse.DensityProfile.QuasiParabolic
                                        .QuasiParabolicSegment
                                        .builder()
                                        .a(-550273940000.0)
                                        .b(169837632.0)
                                        .c(13104.63)
                                        .error(0.0016)
                                        .index(12)
                                        .rb(6460.1)
                                        .re(6480.001)
                                        .build()
                                )
                                .build()
                        )
                        .shiftedChebyshev(
                            IonOobservationListResponse.DensityProfile.ShiftedChebyshev.builder()
                                .description(
                                    "Best-fit Huang-Reinisch formalism based on shifted Chebyshev expansion."
                                )
                                .addShiftedChebyshev(
                                    IonOobservationListResponse.DensityProfile.ShiftedChebyshev
                                        .InnerShiftedChebyshev
                                        .builder()
                                        .coeffs(listOf(-11.2, -10.536, 3.357, -0.888, 0.155))
                                        .error(0.02)
                                        .fstart(0.2)
                                        .fstop(1.39)
                                        .layer("F2")
                                        .n(5)
                                        .peakheight(110.1)
                                        .zhalfNm(210.1)
                                        .build()
                                )
                                .build()
                        )
                        .topsideExtensionChapmanConst(
                            IonOobservationListResponse.DensityProfile.TopsideExtensionChapmanConst
                                .builder()
                                .chi(35.1)
                                .description(
                                    "Constant scale height Chapman topside layer determined using bottomside peak density parameters and placed chi km above the ionosonde-determined peak height."
                                )
                                .hmF2(265.42)
                                .nmF2(313283.1)
                                .scaleF2(45.191)
                                .build()
                        )
                        .topsideExtensionVaryChap(
                            IonOobservationListResponse.DensityProfile.TopsideExtensionVaryChap
                                .builder()
                                .alpha(30.1)
                                .beta(30.1)
                                .chi(30.1)
                                .description(
                                    "Constant scale height Chapman topside layer determined using bottomside peak density parameters and placed chi km above the ionosonde-determined peak height."
                                )
                                .hmF2(265.42)
                                .ht(30.1)
                                .nmF2(313283.1)
                                .scaleF2(45.191)
                                .build()
                        )
                        .addValleyModelCoeff(39.597)
                        .addValleyModelCoeff(0.1777)
                        .valleyModelDescription(
                            "2-parameter UMLCAR model with width W in km and depth D in MHz, no fitting."
                        )
                        .build()
                )
                .doppler(
                    IonOobservationListResponse.Doppler.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .downE(1.1)
                .downEs(1.1)
                .downF(1.1)
                .electronDensity(listOf(1.1, 2.1, 3.1))
                .electronDensityUncertainty(listOf(0.8, 0.2, 0.5))
                .elevation(
                    IonOobservationListResponse.Elevation.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(2)
                        .addDimension(3)
                        .notes("NOTES")
                        .build()
                )
                .fbEs(34.867)
                .fe(1.23)
                .ff(0.075)
                .fhprimeF(2.5)
                .fhprimeF2(2.5)
                .fmin(2.025)
                .fminE(2.025)
                .fminEs(1.1)
                .fminF(2.7)
                .fmuf(1.1)
                .foE(1.1)
                .foEa(45.764)
                .foEp(1.1)
                .foEs(2.35)
                .foF1(8.2)
                .foF1p(1.1)
                .foF2(6.75)
                .foF2p(1.1)
                .foP(87.21)
                .frequency(
                    IonOobservationListResponse.Frequency.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .fxE(1.1)
                .fxF1(4.2)
                .fxF2(4.5)
                .fxI(7.525)
                .height(listOf(1.1, 2.1, 3.1))
                .hmE(215.643)
                .hmF1(230.128)
                .hmF2(240.498)
                .hprimeE(98.47)
                .hprimeEa(102.6)
                .hprimeEs(95.0)
                .hprimeF(238.5)
                .hprimeF1(230.1)
                .hprimeF2(238.5)
                .hprimefMuf(1.1)
                .hprimeP(89.45)
                .idSensor("SENSOR-ID")
                .luf(1.1)
                .md(1.1)
                .mufd(1.1)
                .neProfileName("NH")
                .neProfileVersion(4.32)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("ORIG")
                .origSensorId("ORIGSENSOR-ID")
                .phase(
                    IonOobservationListResponse.Phase.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .plasmaFrequency(listOf(1.1, 2.1, 3.1))
                .plasmaFrequencyUncertainty(listOf(0.8, 0.2, 0.5))
                .platformName("Millstone Hill")
                .polarization(
                    IonOobservationListResponse.Polarization.builder()
                        .addData(
                            listOf(
                                listOf(
                                    listOf(
                                        listOf(
                                            listOf(
                                                listOf(
                                                    IonOobservationListResponse.Polarization
                                                        .UnnamedSchemaWithArrayParent0
                                                        .X,
                                                    IonOobservationListResponse.Polarization
                                                        .UnnamedSchemaWithArrayParent0
                                                        .O,
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .power(
                    IonOobservationListResponse.Power.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .qe(0.95)
                .qf(1.83)
                .range(
                    IonOobservationListResponse.Range.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .addReceiveCoordinate(listOf(45.5, 179.3, 35.6))
                .addReceiveCoordinate(listOf(-80.2, -20.5, 43.2))
                .receiveSensorType(IonOobservationListResponse.ReceiveSensorType.MOBILE)
                .restrictedFrequency(listOf(12.5, 34.5, 45.3))
                .restrictedFrequencyNotes("Example notes")
                .scaleHeightF2Peak(35.613)
                .scalerInfo(
                    IonOobservationListResponse.ScalerInfo.builder()
                        .confidenceLevel(11)
                        .confidenceScore(75)
                        .name("ARTIST-4")
                        .organization("UML")
                        .type("MANUAL")
                        .version(500200.1)
                        .build()
                )
                .stokes(
                    IonOobservationListResponse.Stokes.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAMES1")
                        .addDimensionName("NAMES2")
                        .addDimension(2)
                        .addDimension(3)
                        .notes("NOTES")
                        .addS(1.0)
                        .addS(2.0)
                        .build()
                )
                .systemNotes("Example notes")
                .tec(24.673)
                .tidAzimuth(listOf(1.1, 2.1, 3.1))
                .tidPeriods(listOf(1.1, 2.1, 3.1))
                .tidPhaseSpeeds(listOf(1.1, 2.1, 3.1))
                .time(
                    IonOobservationListResponse.Time.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .traceGeneric(
                    IonOobservationListResponse.TraceGeneric.builder()
                        .addData(listOf(listOf(1.23, 1.0903)))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .notes("NOTES")
                        .build()
                )
                .addTransmitCoordinate(listOf(45.5, 179.3, 35.6))
                .addTransmitCoordinate(listOf(-80.2, -20.5, 43.2))
                .transmitSensorType(IonOobservationListResponse.TransmitSensorType.MOBILE)
                .typeEs("Auroral")
                .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .yE(1.722)
                .yF1(55.645)
                .yF2(62.178)
                .zhalfNm(240.498)
                .zmE(91.744)
                .build()

        assertThat(ionOobservationListResponse.classificationMarking()).isEqualTo("U")
        assertThat(ionOobservationListResponse.dataMode())
            .isEqualTo(IonOobservationListResponse.DataMode.TEST)
        assertThat(ionOobservationListResponse.source()).isEqualTo("Bluestaq")
        assertThat(ionOobservationListResponse.startTimeUtc())
            .isEqualTo(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
        assertThat(ionOobservationListResponse.stationId()).isEqualTo("STATION-ID")
        assertThat(ionOobservationListResponse.system()).isEqualTo("Example hardware type")
        assertThat(ionOobservationListResponse.systemInfo()).isEqualTo("Example settings")
        assertThat(ionOobservationListResponse.id()).contains("IONOOBSERVATION-ID")
        assertThat(ionOobservationListResponse.amplitude())
            .contains(
                IonOobservationListResponse.Amplitude.builder()
                    .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                    .addDimensionName("NAME1")
                    .addDimensionName("NAME2")
                    .addDimension(4)
                    .addDimension(5)
                    .notes("NOTES")
                    .build()
            )
        assertThat(ionOobservationListResponse.antennaElementPosition())
            .contains(
                IonOobservationListResponse.AntennaElementPosition.builder()
                    .addData(listOf(1.23, 0.123))
                    .addDimensionName("NAME1")
                    .addDimensionName("NAME2")
                    .addDimension(3)
                    .addDimension(4)
                    .build()
            )
        assertThat(ionOobservationListResponse.antennaElementPositionCoordinateSystem())
            .contains(IonOobservationListResponse.AntennaElementPositionCoordinateSystem.J2000)
        assertThat(ionOobservationListResponse.artistFlags().getOrNull()).containsExactly(1, 2, 3)
        assertThat(ionOobservationListResponse.azimuth())
            .contains(
                IonOobservationListResponse.Azimuth.builder()
                    .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                    .addDimensionName("NAME1")
                    .addDimensionName("NAME2")
                    .addDimension(1)
                    .addDimension(2)
                    .notes("NOTES")
                    .build()
            )
        assertThat(ionOobservationListResponse.b0()).contains(68.07)
        assertThat(ionOobservationListResponse.b1()).contains(1.87)
        assertThat(ionOobservationListResponse.charAtts().getOrNull())
            .containsExactly(
                IonOobservationListResponse.CharAtt.builder()
                    .charName("hprimeF2")
                    .addClimateModelInputParam("ISSN1 88.1")
                    .addClimateModelInputParam("Option 2")
                    .climateModelName("IRI")
                    .addClimateModelOption("URSI-88")
                    .addClimateModelOption("No storm")
                    .d("K")
                    .lowerBound(1.26)
                    .q("T")
                    .uncertaintyBoundType("1sigma")
                    .upperBound(2.57)
                    .ursiId("04")
                    .build()
            )
        assertThat(ionOobservationListResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(ionOobservationListResponse.createdBy()).contains("some.user")
        assertThat(ionOobservationListResponse.d()).contains(1.1)
        assertThat(ionOobservationListResponse.d1()).contains(1.94)
        assertThat(ionOobservationListResponse.datum())
            .contains(
                IonOobservationListResponse.Datum.builder()
                    .data(listOf(1.1, 2.1, 3.1))
                    .notes("NOTES")
                    .build()
            )
        assertThat(ionOobservationListResponse.deltafoF2()).contains(1.1)
        assertThat(ionOobservationListResponse.densityProfile())
            .contains(
                IonOobservationListResponse.DensityProfile.builder()
                    .iri(
                        IonOobservationListResponse.DensityProfile.Iri.builder()
                            .b0(245.1)
                            .b1(3.45)
                            .chi(35.1)
                            .d1(0.0)
                            .description(
                                "Full altitude range of 1D vertical plasma density profile for D, E, and F regions of the ionosphere provided by IRI, in which model parameters are replaced with observed ionogram-derived data where available."
                            )
                            .fp1(0.0474732023322638)
                            .fp2(-0.00112685246984002)
                            .fp30(0.00827559450035957)
                            .fp3U(0.000201178475411428)
                            .ha(50.1)
                            .hdx(85.6)
                            .hmD(81.1)
                            .hmE(99.8)
                            .hmF1(210.3)
                            .hmF2(265.42)
                            .hValTop(116.2)
                            .hz(142.7)
                            .nmD(937543116.1)
                            .nmE(154164.1)
                            .nmF1(210486.0)
                            .nmF2(313283.1)
                            .nValB(147025.1)
                            .build()
                    )
                    .parabolic(
                        IonOobservationListResponse.DensityProfile.Parabolic.builder()
                            .description("Best-fit algorithm in NHPC software.")
                            .addParabolicItem(
                                IonOobservationListResponse.DensityProfile.Parabolic.ParabolicItem
                                    .builder()
                                    .f(3.621)
                                    .layer("E")
                                    .y(11.1)
                                    .z(110.2)
                                    .build()
                            )
                            .build()
                    )
                    .quasiParabolic(
                        IonOobservationListResponse.DensityProfile.QuasiParabolic.builder()
                            .description(
                                "Array of the best-fit 3-parameter quasi-parabolas defined via A, B, C coefficients, f^2=A/r^2+B/r+C"
                            )
                            .earthRadius(6370.1)
                            .addQuasiParabolicSegment(
                                IonOobservationListResponse.DensityProfile.QuasiParabolic
                                    .QuasiParabolicSegment
                                    .builder()
                                    .a(-550273940000.0)
                                    .b(169837632.0)
                                    .c(13104.63)
                                    .error(0.0016)
                                    .index(12)
                                    .rb(6460.1)
                                    .re(6480.001)
                                    .build()
                            )
                            .build()
                    )
                    .shiftedChebyshev(
                        IonOobservationListResponse.DensityProfile.ShiftedChebyshev.builder()
                            .description(
                                "Best-fit Huang-Reinisch formalism based on shifted Chebyshev expansion."
                            )
                            .addShiftedChebyshev(
                                IonOobservationListResponse.DensityProfile.ShiftedChebyshev
                                    .InnerShiftedChebyshev
                                    .builder()
                                    .coeffs(listOf(-11.2, -10.536, 3.357, -0.888, 0.155))
                                    .error(0.02)
                                    .fstart(0.2)
                                    .fstop(1.39)
                                    .layer("F2")
                                    .n(5)
                                    .peakheight(110.1)
                                    .zhalfNm(210.1)
                                    .build()
                            )
                            .build()
                    )
                    .topsideExtensionChapmanConst(
                        IonOobservationListResponse.DensityProfile.TopsideExtensionChapmanConst
                            .builder()
                            .chi(35.1)
                            .description(
                                "Constant scale height Chapman topside layer determined using bottomside peak density parameters and placed chi km above the ionosonde-determined peak height."
                            )
                            .hmF2(265.42)
                            .nmF2(313283.1)
                            .scaleF2(45.191)
                            .build()
                    )
                    .topsideExtensionVaryChap(
                        IonOobservationListResponse.DensityProfile.TopsideExtensionVaryChap
                            .builder()
                            .alpha(30.1)
                            .beta(30.1)
                            .chi(30.1)
                            .description(
                                "Constant scale height Chapman topside layer determined using bottomside peak density parameters and placed chi km above the ionosonde-determined peak height."
                            )
                            .hmF2(265.42)
                            .ht(30.1)
                            .nmF2(313283.1)
                            .scaleF2(45.191)
                            .build()
                    )
                    .addValleyModelCoeff(39.597)
                    .addValleyModelCoeff(0.1777)
                    .valleyModelDescription(
                        "2-parameter UMLCAR model with width W in km and depth D in MHz, no fitting."
                    )
                    .build()
            )
        assertThat(ionOobservationListResponse.doppler())
            .contains(
                IonOobservationListResponse.Doppler.builder()
                    .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                    .addDimensionName("NAME1")
                    .addDimensionName("NAME2")
                    .addDimension(1)
                    .addDimension(2)
                    .notes("NOTES")
                    .build()
            )
        assertThat(ionOobservationListResponse.downE()).contains(1.1)
        assertThat(ionOobservationListResponse.downEs()).contains(1.1)
        assertThat(ionOobservationListResponse.downF()).contains(1.1)
        assertThat(ionOobservationListResponse.electronDensity().getOrNull())
            .containsExactly(1.1, 2.1, 3.1)
        assertThat(ionOobservationListResponse.electronDensityUncertainty().getOrNull())
            .containsExactly(0.8, 0.2, 0.5)
        assertThat(ionOobservationListResponse.elevation())
            .contains(
                IonOobservationListResponse.Elevation.builder()
                    .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                    .addDimensionName("NAME1")
                    .addDimensionName("NAME2")
                    .addDimension(2)
                    .addDimension(3)
                    .notes("NOTES")
                    .build()
            )
        assertThat(ionOobservationListResponse.fbEs()).contains(34.867)
        assertThat(ionOobservationListResponse.fe()).contains(1.23)
        assertThat(ionOobservationListResponse.ff()).contains(0.075)
        assertThat(ionOobservationListResponse.fhprimeF()).contains(2.5)
        assertThat(ionOobservationListResponse.fhprimeF2()).contains(2.5)
        assertThat(ionOobservationListResponse.fmin()).contains(2.025)
        assertThat(ionOobservationListResponse.fminE()).contains(2.025)
        assertThat(ionOobservationListResponse.fminEs()).contains(1.1)
        assertThat(ionOobservationListResponse.fminF()).contains(2.7)
        assertThat(ionOobservationListResponse.fmuf()).contains(1.1)
        assertThat(ionOobservationListResponse.foE()).contains(1.1)
        assertThat(ionOobservationListResponse.foEa()).contains(45.764)
        assertThat(ionOobservationListResponse.foEp()).contains(1.1)
        assertThat(ionOobservationListResponse.foEs()).contains(2.35)
        assertThat(ionOobservationListResponse.foF1()).contains(8.2)
        assertThat(ionOobservationListResponse.foF1p()).contains(1.1)
        assertThat(ionOobservationListResponse.foF2()).contains(6.75)
        assertThat(ionOobservationListResponse.foF2p()).contains(1.1)
        assertThat(ionOobservationListResponse.foP()).contains(87.21)
        assertThat(ionOobservationListResponse.frequency())
            .contains(
                IonOobservationListResponse.Frequency.builder()
                    .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                    .addDimensionName("NAME1")
                    .addDimensionName("NAME2")
                    .addDimension(1)
                    .addDimension(2)
                    .notes("NOTES")
                    .build()
            )
        assertThat(ionOobservationListResponse.fxE()).contains(1.1)
        assertThat(ionOobservationListResponse.fxF1()).contains(4.2)
        assertThat(ionOobservationListResponse.fxF2()).contains(4.5)
        assertThat(ionOobservationListResponse.fxI()).contains(7.525)
        assertThat(ionOobservationListResponse.height().getOrNull()).containsExactly(1.1, 2.1, 3.1)
        assertThat(ionOobservationListResponse.hmE()).contains(215.643)
        assertThat(ionOobservationListResponse.hmF1()).contains(230.128)
        assertThat(ionOobservationListResponse.hmF2()).contains(240.498)
        assertThat(ionOobservationListResponse.hprimeE()).contains(98.47)
        assertThat(ionOobservationListResponse.hprimeEa()).contains(102.6)
        assertThat(ionOobservationListResponse.hprimeEs()).contains(95.0)
        assertThat(ionOobservationListResponse.hprimeF()).contains(238.5)
        assertThat(ionOobservationListResponse.hprimeF1()).contains(230.1)
        assertThat(ionOobservationListResponse.hprimeF2()).contains(238.5)
        assertThat(ionOobservationListResponse.hprimefMuf()).contains(1.1)
        assertThat(ionOobservationListResponse.hprimeP()).contains(89.45)
        assertThat(ionOobservationListResponse.idSensor()).contains("SENSOR-ID")
        assertThat(ionOobservationListResponse.luf()).contains(1.1)
        assertThat(ionOobservationListResponse.md()).contains(1.1)
        assertThat(ionOobservationListResponse.mufd()).contains(1.1)
        assertThat(ionOobservationListResponse.neProfileName()).contains("NH")
        assertThat(ionOobservationListResponse.neProfileVersion()).contains(4.32)
        assertThat(ionOobservationListResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(ionOobservationListResponse.origNetwork()).contains("ORIG")
        assertThat(ionOobservationListResponse.origSensorId()).contains("ORIGSENSOR-ID")
        assertThat(ionOobservationListResponse.phase())
            .contains(
                IonOobservationListResponse.Phase.builder()
                    .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                    .addDimensionName("NAME1")
                    .addDimensionName("NAME2")
                    .addDimension(1)
                    .addDimension(2)
                    .notes("NOTES")
                    .build()
            )
        assertThat(ionOobservationListResponse.plasmaFrequency().getOrNull())
            .containsExactly(1.1, 2.1, 3.1)
        assertThat(ionOobservationListResponse.plasmaFrequencyUncertainty().getOrNull())
            .containsExactly(0.8, 0.2, 0.5)
        assertThat(ionOobservationListResponse.platformName()).contains("Millstone Hill")
        assertThat(ionOobservationListResponse.polarization())
            .contains(
                IonOobservationListResponse.Polarization.builder()
                    .addData(
                        listOf(
                            listOf(
                                listOf(
                                    listOf(
                                        listOf(
                                            listOf(
                                                IonOobservationListResponse.Polarization
                                                    .UnnamedSchemaWithArrayParent0
                                                    .X,
                                                IonOobservationListResponse.Polarization
                                                    .UnnamedSchemaWithArrayParent0
                                                    .O,
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                    .addDimensionName("NAME1")
                    .addDimensionName("NAME2")
                    .addDimension(1)
                    .addDimension(2)
                    .notes("NOTES")
                    .build()
            )
        assertThat(ionOobservationListResponse.power())
            .contains(
                IonOobservationListResponse.Power.builder()
                    .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                    .addDimensionName("NAME1")
                    .addDimensionName("NAME2")
                    .addDimension(1)
                    .addDimension(2)
                    .notes("NOTES")
                    .build()
            )
        assertThat(ionOobservationListResponse.qe()).contains(0.95)
        assertThat(ionOobservationListResponse.qf()).contains(1.83)
        assertThat(ionOobservationListResponse.range())
            .contains(
                IonOobservationListResponse.Range.builder()
                    .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                    .addDimensionName("NAME1")
                    .addDimensionName("NAME2")
                    .addDimension(1)
                    .addDimension(2)
                    .notes("NOTES")
                    .build()
            )
        assertThat(ionOobservationListResponse.receiveCoordinates().getOrNull())
            .containsExactly(listOf(45.5, 179.3, 35.6), listOf(-80.2, -20.5, 43.2))
        assertThat(ionOobservationListResponse.receiveSensorType())
            .contains(IonOobservationListResponse.ReceiveSensorType.MOBILE)
        assertThat(ionOobservationListResponse.restrictedFrequency().getOrNull())
            .containsExactly(12.5, 34.5, 45.3)
        assertThat(ionOobservationListResponse.restrictedFrequencyNotes()).contains("Example notes")
        assertThat(ionOobservationListResponse.scaleHeightF2Peak()).contains(35.613)
        assertThat(ionOobservationListResponse.scalerInfo())
            .contains(
                IonOobservationListResponse.ScalerInfo.builder()
                    .confidenceLevel(11)
                    .confidenceScore(75)
                    .name("ARTIST-4")
                    .organization("UML")
                    .type("MANUAL")
                    .version(500200.1)
                    .build()
            )
        assertThat(ionOobservationListResponse.stokes())
            .contains(
                IonOobservationListResponse.Stokes.builder()
                    .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                    .addDimensionName("NAMES1")
                    .addDimensionName("NAMES2")
                    .addDimension(2)
                    .addDimension(3)
                    .notes("NOTES")
                    .addS(1.0)
                    .addS(2.0)
                    .build()
            )
        assertThat(ionOobservationListResponse.systemNotes()).contains("Example notes")
        assertThat(ionOobservationListResponse.tec()).contains(24.673)
        assertThat(ionOobservationListResponse.tidAzimuth().getOrNull())
            .containsExactly(1.1, 2.1, 3.1)
        assertThat(ionOobservationListResponse.tidPeriods().getOrNull())
            .containsExactly(1.1, 2.1, 3.1)
        assertThat(ionOobservationListResponse.tidPhaseSpeeds().getOrNull())
            .containsExactly(1.1, 2.1, 3.1)
        assertThat(ionOobservationListResponse.time())
            .contains(
                IonOobservationListResponse.Time.builder()
                    .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                    .addDimensionName("NAME1")
                    .addDimensionName("NAME2")
                    .addDimension(1)
                    .addDimension(2)
                    .notes("NOTES")
                    .build()
            )
        assertThat(ionOobservationListResponse.traceGeneric())
            .contains(
                IonOobservationListResponse.TraceGeneric.builder()
                    .addData(listOf(listOf(1.23, 1.0903)))
                    .addDimensionName("NAME1")
                    .addDimensionName("NAME2")
                    .notes("NOTES")
                    .build()
            )
        assertThat(ionOobservationListResponse.transmitCoordinates().getOrNull())
            .containsExactly(listOf(45.5, 179.3, 35.6), listOf(-80.2, -20.5, 43.2))
        assertThat(ionOobservationListResponse.transmitSensorType())
            .contains(IonOobservationListResponse.TransmitSensorType.MOBILE)
        assertThat(ionOobservationListResponse.typeEs()).contains("Auroral")
        assertThat(ionOobservationListResponse.updatedAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(ionOobservationListResponse.updatedBy()).contains("some.user")
        assertThat(ionOobservationListResponse.yE()).contains(1.722)
        assertThat(ionOobservationListResponse.yF1()).contains(55.645)
        assertThat(ionOobservationListResponse.yF2()).contains(62.178)
        assertThat(ionOobservationListResponse.zhalfNm()).contains(240.498)
        assertThat(ionOobservationListResponse.zmE()).contains(91.744)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val ionOobservationListResponse =
            IonOobservationListResponse.builder()
                .classificationMarking("U")
                .dataMode(IonOobservationListResponse.DataMode.TEST)
                .source("Bluestaq")
                .startTimeUtc(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .stationId("STATION-ID")
                .system("Example hardware type")
                .systemInfo("Example settings")
                .id("IONOOBSERVATION-ID")
                .amplitude(
                    IonOobservationListResponse.Amplitude.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(4)
                        .addDimension(5)
                        .notes("NOTES")
                        .build()
                )
                .antennaElementPosition(
                    IonOobservationListResponse.AntennaElementPosition.builder()
                        .addData(listOf(1.23, 0.123))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(3)
                        .addDimension(4)
                        .build()
                )
                .antennaElementPositionCoordinateSystem(
                    IonOobservationListResponse.AntennaElementPositionCoordinateSystem.J2000
                )
                .artistFlags(listOf(1, 2, 3))
                .azimuth(
                    IonOobservationListResponse.Azimuth.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .b0(68.07)
                .b1(1.87)
                .addCharAtt(
                    IonOobservationListResponse.CharAtt.builder()
                        .charName("hprimeF2")
                        .addClimateModelInputParam("ISSN1 88.1")
                        .addClimateModelInputParam("Option 2")
                        .climateModelName("IRI")
                        .addClimateModelOption("URSI-88")
                        .addClimateModelOption("No storm")
                        .d("K")
                        .lowerBound(1.26)
                        .q("T")
                        .uncertaintyBoundType("1sigma")
                        .upperBound(2.57)
                        .ursiId("04")
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .d(1.1)
                .d1(1.94)
                .datum(
                    IonOobservationListResponse.Datum.builder()
                        .data(listOf(1.1, 2.1, 3.1))
                        .notes("NOTES")
                        .build()
                )
                .deltafoF2(1.1)
                .densityProfile(
                    IonOobservationListResponse.DensityProfile.builder()
                        .iri(
                            IonOobservationListResponse.DensityProfile.Iri.builder()
                                .b0(245.1)
                                .b1(3.45)
                                .chi(35.1)
                                .d1(0.0)
                                .description(
                                    "Full altitude range of 1D vertical plasma density profile for D, E, and F regions of the ionosphere provided by IRI, in which model parameters are replaced with observed ionogram-derived data where available."
                                )
                                .fp1(0.0474732023322638)
                                .fp2(-0.00112685246984002)
                                .fp30(0.00827559450035957)
                                .fp3U(0.000201178475411428)
                                .ha(50.1)
                                .hdx(85.6)
                                .hmD(81.1)
                                .hmE(99.8)
                                .hmF1(210.3)
                                .hmF2(265.42)
                                .hValTop(116.2)
                                .hz(142.7)
                                .nmD(937543116.1)
                                .nmE(154164.1)
                                .nmF1(210486.0)
                                .nmF2(313283.1)
                                .nValB(147025.1)
                                .build()
                        )
                        .parabolic(
                            IonOobservationListResponse.DensityProfile.Parabolic.builder()
                                .description("Best-fit algorithm in NHPC software.")
                                .addParabolicItem(
                                    IonOobservationListResponse.DensityProfile.Parabolic
                                        .ParabolicItem
                                        .builder()
                                        .f(3.621)
                                        .layer("E")
                                        .y(11.1)
                                        .z(110.2)
                                        .build()
                                )
                                .build()
                        )
                        .quasiParabolic(
                            IonOobservationListResponse.DensityProfile.QuasiParabolic.builder()
                                .description(
                                    "Array of the best-fit 3-parameter quasi-parabolas defined via A, B, C coefficients, f^2=A/r^2+B/r+C"
                                )
                                .earthRadius(6370.1)
                                .addQuasiParabolicSegment(
                                    IonOobservationListResponse.DensityProfile.QuasiParabolic
                                        .QuasiParabolicSegment
                                        .builder()
                                        .a(-550273940000.0)
                                        .b(169837632.0)
                                        .c(13104.63)
                                        .error(0.0016)
                                        .index(12)
                                        .rb(6460.1)
                                        .re(6480.001)
                                        .build()
                                )
                                .build()
                        )
                        .shiftedChebyshev(
                            IonOobservationListResponse.DensityProfile.ShiftedChebyshev.builder()
                                .description(
                                    "Best-fit Huang-Reinisch formalism based on shifted Chebyshev expansion."
                                )
                                .addShiftedChebyshev(
                                    IonOobservationListResponse.DensityProfile.ShiftedChebyshev
                                        .InnerShiftedChebyshev
                                        .builder()
                                        .coeffs(listOf(-11.2, -10.536, 3.357, -0.888, 0.155))
                                        .error(0.02)
                                        .fstart(0.2)
                                        .fstop(1.39)
                                        .layer("F2")
                                        .n(5)
                                        .peakheight(110.1)
                                        .zhalfNm(210.1)
                                        .build()
                                )
                                .build()
                        )
                        .topsideExtensionChapmanConst(
                            IonOobservationListResponse.DensityProfile.TopsideExtensionChapmanConst
                                .builder()
                                .chi(35.1)
                                .description(
                                    "Constant scale height Chapman topside layer determined using bottomside peak density parameters and placed chi km above the ionosonde-determined peak height."
                                )
                                .hmF2(265.42)
                                .nmF2(313283.1)
                                .scaleF2(45.191)
                                .build()
                        )
                        .topsideExtensionVaryChap(
                            IonOobservationListResponse.DensityProfile.TopsideExtensionVaryChap
                                .builder()
                                .alpha(30.1)
                                .beta(30.1)
                                .chi(30.1)
                                .description(
                                    "Constant scale height Chapman topside layer determined using bottomside peak density parameters and placed chi km above the ionosonde-determined peak height."
                                )
                                .hmF2(265.42)
                                .ht(30.1)
                                .nmF2(313283.1)
                                .scaleF2(45.191)
                                .build()
                        )
                        .addValleyModelCoeff(39.597)
                        .addValleyModelCoeff(0.1777)
                        .valleyModelDescription(
                            "2-parameter UMLCAR model with width W in km and depth D in MHz, no fitting."
                        )
                        .build()
                )
                .doppler(
                    IonOobservationListResponse.Doppler.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .downE(1.1)
                .downEs(1.1)
                .downF(1.1)
                .electronDensity(listOf(1.1, 2.1, 3.1))
                .electronDensityUncertainty(listOf(0.8, 0.2, 0.5))
                .elevation(
                    IonOobservationListResponse.Elevation.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(2)
                        .addDimension(3)
                        .notes("NOTES")
                        .build()
                )
                .fbEs(34.867)
                .fe(1.23)
                .ff(0.075)
                .fhprimeF(2.5)
                .fhprimeF2(2.5)
                .fmin(2.025)
                .fminE(2.025)
                .fminEs(1.1)
                .fminF(2.7)
                .fmuf(1.1)
                .foE(1.1)
                .foEa(45.764)
                .foEp(1.1)
                .foEs(2.35)
                .foF1(8.2)
                .foF1p(1.1)
                .foF2(6.75)
                .foF2p(1.1)
                .foP(87.21)
                .frequency(
                    IonOobservationListResponse.Frequency.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .fxE(1.1)
                .fxF1(4.2)
                .fxF2(4.5)
                .fxI(7.525)
                .height(listOf(1.1, 2.1, 3.1))
                .hmE(215.643)
                .hmF1(230.128)
                .hmF2(240.498)
                .hprimeE(98.47)
                .hprimeEa(102.6)
                .hprimeEs(95.0)
                .hprimeF(238.5)
                .hprimeF1(230.1)
                .hprimeF2(238.5)
                .hprimefMuf(1.1)
                .hprimeP(89.45)
                .idSensor("SENSOR-ID")
                .luf(1.1)
                .md(1.1)
                .mufd(1.1)
                .neProfileName("NH")
                .neProfileVersion(4.32)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("ORIG")
                .origSensorId("ORIGSENSOR-ID")
                .phase(
                    IonOobservationListResponse.Phase.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .plasmaFrequency(listOf(1.1, 2.1, 3.1))
                .plasmaFrequencyUncertainty(listOf(0.8, 0.2, 0.5))
                .platformName("Millstone Hill")
                .polarization(
                    IonOobservationListResponse.Polarization.builder()
                        .addData(
                            listOf(
                                listOf(
                                    listOf(
                                        listOf(
                                            listOf(
                                                listOf(
                                                    IonOobservationListResponse.Polarization
                                                        .UnnamedSchemaWithArrayParent0
                                                        .X,
                                                    IonOobservationListResponse.Polarization
                                                        .UnnamedSchemaWithArrayParent0
                                                        .O,
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .power(
                    IonOobservationListResponse.Power.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .qe(0.95)
                .qf(1.83)
                .range(
                    IonOobservationListResponse.Range.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .addReceiveCoordinate(listOf(45.5, 179.3, 35.6))
                .addReceiveCoordinate(listOf(-80.2, -20.5, 43.2))
                .receiveSensorType(IonOobservationListResponse.ReceiveSensorType.MOBILE)
                .restrictedFrequency(listOf(12.5, 34.5, 45.3))
                .restrictedFrequencyNotes("Example notes")
                .scaleHeightF2Peak(35.613)
                .scalerInfo(
                    IonOobservationListResponse.ScalerInfo.builder()
                        .confidenceLevel(11)
                        .confidenceScore(75)
                        .name("ARTIST-4")
                        .organization("UML")
                        .type("MANUAL")
                        .version(500200.1)
                        .build()
                )
                .stokes(
                    IonOobservationListResponse.Stokes.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAMES1")
                        .addDimensionName("NAMES2")
                        .addDimension(2)
                        .addDimension(3)
                        .notes("NOTES")
                        .addS(1.0)
                        .addS(2.0)
                        .build()
                )
                .systemNotes("Example notes")
                .tec(24.673)
                .tidAzimuth(listOf(1.1, 2.1, 3.1))
                .tidPeriods(listOf(1.1, 2.1, 3.1))
                .tidPhaseSpeeds(listOf(1.1, 2.1, 3.1))
                .time(
                    IonOobservationListResponse.Time.builder()
                        .addData(listOf(listOf(listOf(listOf(listOf(listOf(0.02, 0.034)))))))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .addDimension(1)
                        .addDimension(2)
                        .notes("NOTES")
                        .build()
                )
                .traceGeneric(
                    IonOobservationListResponse.TraceGeneric.builder()
                        .addData(listOf(listOf(1.23, 1.0903)))
                        .addDimensionName("NAME1")
                        .addDimensionName("NAME2")
                        .notes("NOTES")
                        .build()
                )
                .addTransmitCoordinate(listOf(45.5, 179.3, 35.6))
                .addTransmitCoordinate(listOf(-80.2, -20.5, 43.2))
                .transmitSensorType(IonOobservationListResponse.TransmitSensorType.MOBILE)
                .typeEs("Auroral")
                .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .yE(1.722)
                .yF1(55.645)
                .yF2(62.178)
                .zhalfNm(240.498)
                .zmE(91.744)
                .build()

        val roundtrippedIonOobservationListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(ionOobservationListResponse),
                jacksonTypeRef<IonOobservationListResponse>(),
            )

        assertThat(roundtrippedIonOobservationListResponse).isEqualTo(ionOobservationListResponse)
    }
}
