// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.airloadplans

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AirloadplanAbridgedTest {

    @Test
    fun create() {
        val airloadplanAbridged =
            AirloadplanAbridged.builder()
                .classificationMarking("U")
                .dataMode(AirloadplanAbridged.DataMode.TEST)
                .estDepTime(OffsetDateTime.parse("2024-01-01T01:00:00.123Z"))
                .source("source")
                .id("0457f578-e29c-312e-85aa-0a04a430bdd0")
                .aclOnboard(500.1)
                .aclReleased(200.1)
                .aircraftMds("C17A")
                .addAirLoadPlanHazmatActual(
                    AirloadplanAbridged.AirLoadPlanHazmatActual.builder()
                        .ashc("RFL")
                        .cgc("A")
                        .classDiv("1.1")
                        .hazDescription("CORROSIVE OXIDIZER")
                        .hazmatRemarks("Hazmat remarks")
                        .hazNum("2031")
                        .hazNumType("UN")
                        .hazOffIcao("MBPV")
                        .hazOffItin(300)
                        .hazOnIcao("LIRQ")
                        .hazOnItin(50)
                        .hazPieces(29)
                        .hazTcn("M1358232245912XXX")
                        .hazWeight(22.1)
                        .itemName("NITRIC ACID")
                        .lotNum("1234A")
                        .netExpWt(12.1)
                        .build()
                )
                .addAirLoadPlanHr(
                    AirloadplanAbridged.AirLoadPlanHr.builder()
                        .container("Metal")
                        .escort("Jane Doe")
                        .hrEstArrTime(OffsetDateTime.parse("2024-01-01T01:00:00.123Z"))
                        .hrOffIcao("KDEN")
                        .hrOffItin(200)
                        .hrOnIcao("KCOS")
                        .hrOnItin(100)
                        .hrRemarks("HR remarks")
                        .name("John Doe")
                        .rank("Captain")
                        .recAgency("Agency name")
                        .service("Air Force")
                        .viewable(true)
                        .build()
                )
                .addAirLoadPlanPalletDetail(
                    AirloadplanAbridged.AirLoadPlanPalletDetail.builder()
                        .category("AMCMICAP")
                        .pp("2")
                        .ppDescription("Ammunition")
                        .ppOffIcao("MBPV")
                        .ppPieces(3)
                        .ppRemarks("Pallet remarks")
                        .ppTcn("M1358232245912XXX")
                        .ppWeight(100.1)
                        .specialInterest(true)
                        .build()
                )
                .addAirLoadPlanPaxCargo(
                    AirloadplanAbridged.AirLoadPlanPaxCargo.builder()
                        .ambPax(5)
                        .attPax(6)
                        .availablePax(20)
                        .bagWeight(2000.1)
                        .civPax(3)
                        .dvPax(2)
                        .fnPax(1)
                        .groupCargoWeight(5000.1)
                        .groupType("OFFTHIS")
                        .litPax(4)
                        .mailWeight(200.1)
                        .numPallet(20)
                        .palletWeight(400.1)
                        .paxWeight(8000.1)
                        .requiredPax(20)
                        .build()
                )
                .addAirLoadPlanUlnActual(
                    AirloadplanAbridged.AirLoadPlanUlnActual.builder()
                        .numAmbulatory(10)
                        .numAttendant(10)
                        .numLitter(10)
                        .numPax(44)
                        .offloadId(300)
                        .offloadLoCode("KHOP")
                        .onloadId(200)
                        .onloadLoCode("KCHS")
                        .oplan("5027A")
                        .projName("CENTINTRA21")
                        .uln("T01ME01")
                        .ulnCargoWeight(1000.1)
                        .ulnRemarks("ULN actuals remark")
                        .build()
                )
                .arrAirfield("W99")
                .arrIcao("ETAR")
                .availableTime(OffsetDateTime.parse("2024-01-01T02:00:00.123Z"))
                .basicMoment(2500.1)
                .basicWeight(100.1)
                .briefTime(OffsetDateTime.parse("2024-01-01T01:00:00.123Z"))
                .callSign("RCH1234")
                .cargoBayFsMax(20.1)
                .cargoBayFsMin(10.1)
                .cargoBayWidth(3.1)
                .cargoConfig("C-1")
                .cargoMoment(2500.1)
                .cargoVolume(50.1)
                .cargoWeight(100.1)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .crewSize(5)
                .depAirfield("W99")
                .depIcao("KCHS")
                .equipConfig("Standard")
                .estArrTime(OffsetDateTime.parse("2024-01-01T02:00:00.123Z"))
                .estLandingFuelMoment(2500.1)
                .estLandingFuelWeight(100.1)
                .externalId("dec7a61a-cd97-4af0-b7bc-f4c3bb33341b")
                .fuelMoment(2500.1)
                .fuelWeight(100.1)
                .grossCg(38.8)
                .grossMoment(2500.1)
                .grossWeight(100.1)
                .idMission("412bebb6-a45e-029c-ca51-e29f8a442b12")
                .idSortie("823acfbe6-f36a-157b-ef32-b47c9b589c4")
                .landingCg(38.2)
                .landingMoment(2500.1)
                .landingWeight(100.1)
                .legNum(200)
                .loadmasterName("John Smith")
                .loadmasterRank("Staff Sergeant")
                .loadRemarks("Load remarks")
                .missionNumber("AJM123456123")
                .operatingMoment(2500.1)
                .operatingWeight(100.1)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .ppOnboard(18)
                .ppReleased(5)
                .schedTime(OffsetDateTime.parse("2024-01-01T02:30:00.123Z"))
                .seatsOnboard(20)
                .seatsReleased(15)
                .sourceDl("AXE")
                .tailNumber("77187")
                .tankConfig("ER")
                .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .utilCode("AD")
                .zeroFuelCg(39.5)
                .zeroFuelMoment(2500.1)
                .zeroFuelWeight(100.1)
                .build()

        assertThat(airloadplanAbridged.classificationMarking()).isEqualTo("U")
        assertThat(airloadplanAbridged.dataMode()).isEqualTo(AirloadplanAbridged.DataMode.TEST)
        assertThat(airloadplanAbridged.estDepTime())
            .isEqualTo(OffsetDateTime.parse("2024-01-01T01:00:00.123Z"))
        assertThat(airloadplanAbridged.source()).isEqualTo("source")
        assertThat(airloadplanAbridged.id()).contains("0457f578-e29c-312e-85aa-0a04a430bdd0")
        assertThat(airloadplanAbridged.aclOnboard()).contains(500.1)
        assertThat(airloadplanAbridged.aclReleased()).contains(200.1)
        assertThat(airloadplanAbridged.aircraftMds()).contains("C17A")
        assertThat(airloadplanAbridged.airLoadPlanHazmatActuals().getOrNull())
            .containsExactly(
                AirloadplanAbridged.AirLoadPlanHazmatActual.builder()
                    .ashc("RFL")
                    .cgc("A")
                    .classDiv("1.1")
                    .hazDescription("CORROSIVE OXIDIZER")
                    .hazmatRemarks("Hazmat remarks")
                    .hazNum("2031")
                    .hazNumType("UN")
                    .hazOffIcao("MBPV")
                    .hazOffItin(300)
                    .hazOnIcao("LIRQ")
                    .hazOnItin(50)
                    .hazPieces(29)
                    .hazTcn("M1358232245912XXX")
                    .hazWeight(22.1)
                    .itemName("NITRIC ACID")
                    .lotNum("1234A")
                    .netExpWt(12.1)
                    .build()
            )
        assertThat(airloadplanAbridged.airLoadPlanHr().getOrNull())
            .containsExactly(
                AirloadplanAbridged.AirLoadPlanHr.builder()
                    .container("Metal")
                    .escort("Jane Doe")
                    .hrEstArrTime(OffsetDateTime.parse("2024-01-01T01:00:00.123Z"))
                    .hrOffIcao("KDEN")
                    .hrOffItin(200)
                    .hrOnIcao("KCOS")
                    .hrOnItin(100)
                    .hrRemarks("HR remarks")
                    .name("John Doe")
                    .rank("Captain")
                    .recAgency("Agency name")
                    .service("Air Force")
                    .viewable(true)
                    .build()
            )
        assertThat(airloadplanAbridged.airLoadPlanPalletDetails().getOrNull())
            .containsExactly(
                AirloadplanAbridged.AirLoadPlanPalletDetail.builder()
                    .category("AMCMICAP")
                    .pp("2")
                    .ppDescription("Ammunition")
                    .ppOffIcao("MBPV")
                    .ppPieces(3)
                    .ppRemarks("Pallet remarks")
                    .ppTcn("M1358232245912XXX")
                    .ppWeight(100.1)
                    .specialInterest(true)
                    .build()
            )
        assertThat(airloadplanAbridged.airLoadPlanPaxCargo().getOrNull())
            .containsExactly(
                AirloadplanAbridged.AirLoadPlanPaxCargo.builder()
                    .ambPax(5)
                    .attPax(6)
                    .availablePax(20)
                    .bagWeight(2000.1)
                    .civPax(3)
                    .dvPax(2)
                    .fnPax(1)
                    .groupCargoWeight(5000.1)
                    .groupType("OFFTHIS")
                    .litPax(4)
                    .mailWeight(200.1)
                    .numPallet(20)
                    .palletWeight(400.1)
                    .paxWeight(8000.1)
                    .requiredPax(20)
                    .build()
            )
        assertThat(airloadplanAbridged.airLoadPlanUlnActuals().getOrNull())
            .containsExactly(
                AirloadplanAbridged.AirLoadPlanUlnActual.builder()
                    .numAmbulatory(10)
                    .numAttendant(10)
                    .numLitter(10)
                    .numPax(44)
                    .offloadId(300)
                    .offloadLoCode("KHOP")
                    .onloadId(200)
                    .onloadLoCode("KCHS")
                    .oplan("5027A")
                    .projName("CENTINTRA21")
                    .uln("T01ME01")
                    .ulnCargoWeight(1000.1)
                    .ulnRemarks("ULN actuals remark")
                    .build()
            )
        assertThat(airloadplanAbridged.arrAirfield()).contains("W99")
        assertThat(airloadplanAbridged.arrIcao()).contains("ETAR")
        assertThat(airloadplanAbridged.availableTime())
            .contains(OffsetDateTime.parse("2024-01-01T02:00:00.123Z"))
        assertThat(airloadplanAbridged.basicMoment()).contains(2500.1)
        assertThat(airloadplanAbridged.basicWeight()).contains(100.1)
        assertThat(airloadplanAbridged.briefTime())
            .contains(OffsetDateTime.parse("2024-01-01T01:00:00.123Z"))
        assertThat(airloadplanAbridged.callSign()).contains("RCH1234")
        assertThat(airloadplanAbridged.cargoBayFsMax()).contains(20.1)
        assertThat(airloadplanAbridged.cargoBayFsMin()).contains(10.1)
        assertThat(airloadplanAbridged.cargoBayWidth()).contains(3.1)
        assertThat(airloadplanAbridged.cargoConfig()).contains("C-1")
        assertThat(airloadplanAbridged.cargoMoment()).contains(2500.1)
        assertThat(airloadplanAbridged.cargoVolume()).contains(50.1)
        assertThat(airloadplanAbridged.cargoWeight()).contains(100.1)
        assertThat(airloadplanAbridged.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(airloadplanAbridged.createdBy()).contains("some.user")
        assertThat(airloadplanAbridged.crewSize()).contains(5)
        assertThat(airloadplanAbridged.depAirfield()).contains("W99")
        assertThat(airloadplanAbridged.depIcao()).contains("KCHS")
        assertThat(airloadplanAbridged.equipConfig()).contains("Standard")
        assertThat(airloadplanAbridged.estArrTime())
            .contains(OffsetDateTime.parse("2024-01-01T02:00:00.123Z"))
        assertThat(airloadplanAbridged.estLandingFuelMoment()).contains(2500.1)
        assertThat(airloadplanAbridged.estLandingFuelWeight()).contains(100.1)
        assertThat(airloadplanAbridged.externalId())
            .contains("dec7a61a-cd97-4af0-b7bc-f4c3bb33341b")
        assertThat(airloadplanAbridged.fuelMoment()).contains(2500.1)
        assertThat(airloadplanAbridged.fuelWeight()).contains(100.1)
        assertThat(airloadplanAbridged.grossCg()).contains(38.8)
        assertThat(airloadplanAbridged.grossMoment()).contains(2500.1)
        assertThat(airloadplanAbridged.grossWeight()).contains(100.1)
        assertThat(airloadplanAbridged.idMission()).contains("412bebb6-a45e-029c-ca51-e29f8a442b12")
        assertThat(airloadplanAbridged.idSortie()).contains("823acfbe6-f36a-157b-ef32-b47c9b589c4")
        assertThat(airloadplanAbridged.landingCg()).contains(38.2)
        assertThat(airloadplanAbridged.landingMoment()).contains(2500.1)
        assertThat(airloadplanAbridged.landingWeight()).contains(100.1)
        assertThat(airloadplanAbridged.legNum()).contains(200)
        assertThat(airloadplanAbridged.loadmasterName()).contains("John Smith")
        assertThat(airloadplanAbridged.loadmasterRank()).contains("Staff Sergeant")
        assertThat(airloadplanAbridged.loadRemarks()).contains("Load remarks")
        assertThat(airloadplanAbridged.missionNumber()).contains("AJM123456123")
        assertThat(airloadplanAbridged.operatingMoment()).contains(2500.1)
        assertThat(airloadplanAbridged.operatingWeight()).contains(100.1)
        assertThat(airloadplanAbridged.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(airloadplanAbridged.origNetwork()).contains("OPS1")
        assertThat(airloadplanAbridged.ppOnboard()).contains(18)
        assertThat(airloadplanAbridged.ppReleased()).contains(5)
        assertThat(airloadplanAbridged.schedTime())
            .contains(OffsetDateTime.parse("2024-01-01T02:30:00.123Z"))
        assertThat(airloadplanAbridged.seatsOnboard()).contains(20)
        assertThat(airloadplanAbridged.seatsReleased()).contains(15)
        assertThat(airloadplanAbridged.sourceDl()).contains("AXE")
        assertThat(airloadplanAbridged.tailNumber()).contains("77187")
        assertThat(airloadplanAbridged.tankConfig()).contains("ER")
        assertThat(airloadplanAbridged.updatedAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(airloadplanAbridged.updatedBy()).contains("some.user")
        assertThat(airloadplanAbridged.utilCode()).contains("AD")
        assertThat(airloadplanAbridged.zeroFuelCg()).contains(39.5)
        assertThat(airloadplanAbridged.zeroFuelMoment()).contains(2500.1)
        assertThat(airloadplanAbridged.zeroFuelWeight()).contains(100.1)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val airloadplanAbridged =
            AirloadplanAbridged.builder()
                .classificationMarking("U")
                .dataMode(AirloadplanAbridged.DataMode.TEST)
                .estDepTime(OffsetDateTime.parse("2024-01-01T01:00:00.123Z"))
                .source("source")
                .id("0457f578-e29c-312e-85aa-0a04a430bdd0")
                .aclOnboard(500.1)
                .aclReleased(200.1)
                .aircraftMds("C17A")
                .addAirLoadPlanHazmatActual(
                    AirloadplanAbridged.AirLoadPlanHazmatActual.builder()
                        .ashc("RFL")
                        .cgc("A")
                        .classDiv("1.1")
                        .hazDescription("CORROSIVE OXIDIZER")
                        .hazmatRemarks("Hazmat remarks")
                        .hazNum("2031")
                        .hazNumType("UN")
                        .hazOffIcao("MBPV")
                        .hazOffItin(300)
                        .hazOnIcao("LIRQ")
                        .hazOnItin(50)
                        .hazPieces(29)
                        .hazTcn("M1358232245912XXX")
                        .hazWeight(22.1)
                        .itemName("NITRIC ACID")
                        .lotNum("1234A")
                        .netExpWt(12.1)
                        .build()
                )
                .addAirLoadPlanHr(
                    AirloadplanAbridged.AirLoadPlanHr.builder()
                        .container("Metal")
                        .escort("Jane Doe")
                        .hrEstArrTime(OffsetDateTime.parse("2024-01-01T01:00:00.123Z"))
                        .hrOffIcao("KDEN")
                        .hrOffItin(200)
                        .hrOnIcao("KCOS")
                        .hrOnItin(100)
                        .hrRemarks("HR remarks")
                        .name("John Doe")
                        .rank("Captain")
                        .recAgency("Agency name")
                        .service("Air Force")
                        .viewable(true)
                        .build()
                )
                .addAirLoadPlanPalletDetail(
                    AirloadplanAbridged.AirLoadPlanPalletDetail.builder()
                        .category("AMCMICAP")
                        .pp("2")
                        .ppDescription("Ammunition")
                        .ppOffIcao("MBPV")
                        .ppPieces(3)
                        .ppRemarks("Pallet remarks")
                        .ppTcn("M1358232245912XXX")
                        .ppWeight(100.1)
                        .specialInterest(true)
                        .build()
                )
                .addAirLoadPlanPaxCargo(
                    AirloadplanAbridged.AirLoadPlanPaxCargo.builder()
                        .ambPax(5)
                        .attPax(6)
                        .availablePax(20)
                        .bagWeight(2000.1)
                        .civPax(3)
                        .dvPax(2)
                        .fnPax(1)
                        .groupCargoWeight(5000.1)
                        .groupType("OFFTHIS")
                        .litPax(4)
                        .mailWeight(200.1)
                        .numPallet(20)
                        .palletWeight(400.1)
                        .paxWeight(8000.1)
                        .requiredPax(20)
                        .build()
                )
                .addAirLoadPlanUlnActual(
                    AirloadplanAbridged.AirLoadPlanUlnActual.builder()
                        .numAmbulatory(10)
                        .numAttendant(10)
                        .numLitter(10)
                        .numPax(44)
                        .offloadId(300)
                        .offloadLoCode("KHOP")
                        .onloadId(200)
                        .onloadLoCode("KCHS")
                        .oplan("5027A")
                        .projName("CENTINTRA21")
                        .uln("T01ME01")
                        .ulnCargoWeight(1000.1)
                        .ulnRemarks("ULN actuals remark")
                        .build()
                )
                .arrAirfield("W99")
                .arrIcao("ETAR")
                .availableTime(OffsetDateTime.parse("2024-01-01T02:00:00.123Z"))
                .basicMoment(2500.1)
                .basicWeight(100.1)
                .briefTime(OffsetDateTime.parse("2024-01-01T01:00:00.123Z"))
                .callSign("RCH1234")
                .cargoBayFsMax(20.1)
                .cargoBayFsMin(10.1)
                .cargoBayWidth(3.1)
                .cargoConfig("C-1")
                .cargoMoment(2500.1)
                .cargoVolume(50.1)
                .cargoWeight(100.1)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .crewSize(5)
                .depAirfield("W99")
                .depIcao("KCHS")
                .equipConfig("Standard")
                .estArrTime(OffsetDateTime.parse("2024-01-01T02:00:00.123Z"))
                .estLandingFuelMoment(2500.1)
                .estLandingFuelWeight(100.1)
                .externalId("dec7a61a-cd97-4af0-b7bc-f4c3bb33341b")
                .fuelMoment(2500.1)
                .fuelWeight(100.1)
                .grossCg(38.8)
                .grossMoment(2500.1)
                .grossWeight(100.1)
                .idMission("412bebb6-a45e-029c-ca51-e29f8a442b12")
                .idSortie("823acfbe6-f36a-157b-ef32-b47c9b589c4")
                .landingCg(38.2)
                .landingMoment(2500.1)
                .landingWeight(100.1)
                .legNum(200)
                .loadmasterName("John Smith")
                .loadmasterRank("Staff Sergeant")
                .loadRemarks("Load remarks")
                .missionNumber("AJM123456123")
                .operatingMoment(2500.1)
                .operatingWeight(100.1)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .ppOnboard(18)
                .ppReleased(5)
                .schedTime(OffsetDateTime.parse("2024-01-01T02:30:00.123Z"))
                .seatsOnboard(20)
                .seatsReleased(15)
                .sourceDl("AXE")
                .tailNumber("77187")
                .tankConfig("ER")
                .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .utilCode("AD")
                .zeroFuelCg(39.5)
                .zeroFuelMoment(2500.1)
                .zeroFuelWeight(100.1)
                .build()

        val roundtrippedAirloadplanAbridged =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(airloadplanAbridged),
                jacksonTypeRef<AirloadplanAbridged>(),
            )

        assertThat(roundtrippedAirloadplanAbridged).isEqualTo(airloadplanAbridged)
    }
}
