// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.linkstatus.datalink

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class DatalinkListResponseTest {

    @Test
    fun create() {
        val datalinkListResponse =
            DatalinkListResponse.builder()
                .classificationMarking("U")
                .dataMode(DatalinkListResponse.DataMode.TEST)
                .opExName("DESERT WIND")
                .originator("USCENTCOM")
                .source("Bluestaq")
                .startTime(OffsetDateTime.parse("2024-01-07T13:55:43.123Z"))
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .addAckInstUnit("AOC EXT 2345")
                .addAckInstUnit("317 AW")
                .ackReq(true)
                .altDiff(20)
                .canxId("ABSTAT")
                .canxOriginator("505 AOC")
                .canxSerialNum("ABC1234567")
                .addCanxSiC("RDU")
                .addCanxSiC("X234BS")
                .canxSpecialNotation("PASEP")
                .canxTs(OffsetDateTime.parse("2024-01-07T13:55:43.123Z"))
                .addClassReason("15C")
                .addClassReason("15D")
                .classSource("USJFCOM EXORD SOLID WASTE 98")
                .consecDecorr(3)
                .courseDiff(60)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .addDecExemptCode("X1")
                .addDecExemptCode("X2")
                .addDecInstDate("AT EXERCISE ENDEX")
                .addDecInstDate("DATE:25NOV1997")
                .decorrWinMult(1.7)
                .geoDatum("EUR-T")
                .jreCallSign("CHARLIE ONE")
                .jreDetails("JRE details")
                .jrePriAdd(71777)
                .jreSecAdd(77771)
                .jreUnitDes("CVN-72")
                .maxGeoPosQual(12)
                .maxTrackQual(12)
                .mgmtCode("VICTOR")
                .mgmtCodeMeaning("ORBIT AT POINT BRAVO")
                .minGeoPosQual(3)
                .minTrackQual(6)
                .month("OCT")
                .addMultiDuty(
                    DatalinkListResponse.MultiDuty.builder()
                        .duty("SICO")
                        .addDutyTeleFreqNum("TEL:804-555-4142")
                        .addDutyTeleFreqNum("TEL:804-867-5309")
                        .addMultiDutyVoiceCoord(
                            DatalinkListResponse.MultiDuty.MultiDutyVoiceCoord.builder()
                                .multiCommPri("P")
                                .multiFreqDes("ST300A")
                                .addMultiTeleFreqNum("TEL:804-555-4142")
                                .addMultiTeleFreqNum("TEL:804-867-5309")
                                .multiVoiceNetDes("VPN")
                                .build()
                        )
                        .name("POPOVICH")
                        .rank("LCDR")
                        .unitDes("SHIP:STENNIS")
                        .build()
                )
                .addNonLinkUnitDe("CS:GRAY GHOST")
                .addNonLinkUnitDe("CS:WHITE WHALE")
                .opExInfo("CONTROL")
                .opExInfoAlt("ORANGE")
                .addOp(
                    DatalinkListResponse.Op.builder()
                        .linkDetails("Link details")
                        .linkName("Link-16")
                        .linkStartTime(OffsetDateTime.parse("2024-01-07T13:55:43.123Z"))
                        .linkStopTime(OffsetDateTime.parse("2024-01-08T13:55:43.123Z"))
                        .linkStopTimeMod("AFTER")
                        .build()
                )
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .planOrigNum("SACEUR 106")
                .pocCallSign("4077 MASH")
                .pocLat(45.23)
                .pocLocName("CAMP SWAMPY")
                .pocLon(179.1)
                .pocName("F. BURNS")
                .addPocNum("TEL:804-555-4142")
                .addPocNum("TEL:804-867-5309")
                .pocRank("MAJ")
                .qualifier("CHG")
                .qualSn(1)
                .rawFileUri("Example URI")
                .addReference(
                    DatalinkListResponse.Reference.builder()
                        .refOriginator("CENTCOM")
                        .refSerialId("A")
                        .refSerialNum("1402001")
                        .addRefSiC("RDU")
                        .addRefSiC("C-123-92")
                        .refSpecialNotation("NOTAL")
                        .refTs(OffsetDateTime.parse("2024-01-07T13:55:43.123Z"))
                        .refType("ABSTAT")
                        .build()
                )
                .addRefPoint(
                    DatalinkListResponse.RefPoint.builder()
                        .effEventTime(OffsetDateTime.parse("2024-01-08T13:55:43.123Z"))
                        .refDes("L5")
                        .refLat(45.23)
                        .refLocName("FORT BRAGG")
                        .refLon(179.1)
                        .refPointType("DLRP")
                        .build()
                )
                .addRemark(
                    DatalinkListResponse.Remark.builder()
                        .text("Example data link remarks")
                        .type("CONTINGENCY PROCEDURES")
                        .build()
                )
                .resTrackQual(3)
                .serialNum("1201003")
                .sourceDl("AXE")
                .addSpecTrack(
                    DatalinkListResponse.SpecTrack.builder()
                        .specTrackNum("12345")
                        .specTrackNumDesc("SAM SITE CHARLIE")
                        .build()
                )
                .speedDiff(50)
                .stopTime(OffsetDateTime.parse("2024-01-08T13:55:43.123Z"))
                .stopTimeMod("AFTER")
                .sysDefaultCode("MAN")
                .addTrackNumBlockLl(1234)
                .addTrackNumBlockLl(2345)
                .addTrackNumBlock("0200-0300")
                .addTrackNumBlock("0400-4412")
                .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .addVoiceCoord(
                    DatalinkListResponse.VoiceCoord.builder()
                        .commPri("P")
                        .freqDes("ST300A")
                        .addTeleFreqNum("TEL:804-555-4142")
                        .addTeleFreqNum("TEL:804-867-5309")
                        .voiceNetDes("VPN")
                        .build()
                )
                .winSizeMin(1.25)
                .winSizeMult(2.1)
                .build()

        assertThat(datalinkListResponse.classificationMarking()).isEqualTo("U")
        assertThat(datalinkListResponse.dataMode()).isEqualTo(DatalinkListResponse.DataMode.TEST)
        assertThat(datalinkListResponse.opExName()).isEqualTo("DESERT WIND")
        assertThat(datalinkListResponse.originator()).isEqualTo("USCENTCOM")
        assertThat(datalinkListResponse.source()).isEqualTo("Bluestaq")
        assertThat(datalinkListResponse.startTime())
            .isEqualTo(OffsetDateTime.parse("2024-01-07T13:55:43.123Z"))
        assertThat(datalinkListResponse.id()).contains("026dd511-8ba5-47d3-9909-836149f87686")
        assertThat(datalinkListResponse.ackInstUnits().getOrNull())
            .containsExactly("AOC EXT 2345", "317 AW")
        assertThat(datalinkListResponse.ackReq()).contains(true)
        assertThat(datalinkListResponse.altDiff()).contains(20)
        assertThat(datalinkListResponse.canxId()).contains("ABSTAT")
        assertThat(datalinkListResponse.canxOriginator()).contains("505 AOC")
        assertThat(datalinkListResponse.canxSerialNum()).contains("ABC1234567")
        assertThat(datalinkListResponse.canxSiCs().getOrNull()).containsExactly("RDU", "X234BS")
        assertThat(datalinkListResponse.canxSpecialNotation()).contains("PASEP")
        assertThat(datalinkListResponse.canxTs())
            .contains(OffsetDateTime.parse("2024-01-07T13:55:43.123Z"))
        assertThat(datalinkListResponse.classReasons().getOrNull()).containsExactly("15C", "15D")
        assertThat(datalinkListResponse.classSource()).contains("USJFCOM EXORD SOLID WASTE 98")
        assertThat(datalinkListResponse.consecDecorr()).contains(3)
        assertThat(datalinkListResponse.courseDiff()).contains(60)
        assertThat(datalinkListResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(datalinkListResponse.createdBy()).contains("some.user")
        assertThat(datalinkListResponse.decExemptCodes().getOrNull()).containsExactly("X1", "X2")
        assertThat(datalinkListResponse.decInstDates().getOrNull())
            .containsExactly("AT EXERCISE ENDEX", "DATE:25NOV1997")
        assertThat(datalinkListResponse.decorrWinMult()).contains(1.7)
        assertThat(datalinkListResponse.geoDatum()).contains("EUR-T")
        assertThat(datalinkListResponse.jreCallSign()).contains("CHARLIE ONE")
        assertThat(datalinkListResponse.jreDetails()).contains("JRE details")
        assertThat(datalinkListResponse.jrePriAdd()).contains(71777)
        assertThat(datalinkListResponse.jreSecAdd()).contains(77771)
        assertThat(datalinkListResponse.jreUnitDes()).contains("CVN-72")
        assertThat(datalinkListResponse.maxGeoPosQual()).contains(12)
        assertThat(datalinkListResponse.maxTrackQual()).contains(12)
        assertThat(datalinkListResponse.mgmtCode()).contains("VICTOR")
        assertThat(datalinkListResponse.mgmtCodeMeaning()).contains("ORBIT AT POINT BRAVO")
        assertThat(datalinkListResponse.minGeoPosQual()).contains(3)
        assertThat(datalinkListResponse.minTrackQual()).contains(6)
        assertThat(datalinkListResponse.month()).contains("OCT")
        assertThat(datalinkListResponse.multiDuty().getOrNull())
            .containsExactly(
                DatalinkListResponse.MultiDuty.builder()
                    .duty("SICO")
                    .addDutyTeleFreqNum("TEL:804-555-4142")
                    .addDutyTeleFreqNum("TEL:804-867-5309")
                    .addMultiDutyVoiceCoord(
                        DatalinkListResponse.MultiDuty.MultiDutyVoiceCoord.builder()
                            .multiCommPri("P")
                            .multiFreqDes("ST300A")
                            .addMultiTeleFreqNum("TEL:804-555-4142")
                            .addMultiTeleFreqNum("TEL:804-867-5309")
                            .multiVoiceNetDes("VPN")
                            .build()
                    )
                    .name("POPOVICH")
                    .rank("LCDR")
                    .unitDes("SHIP:STENNIS")
                    .build()
            )
        assertThat(datalinkListResponse.nonLinkUnitDes().getOrNull())
            .containsExactly("CS:GRAY GHOST", "CS:WHITE WHALE")
        assertThat(datalinkListResponse.opExInfo()).contains("CONTROL")
        assertThat(datalinkListResponse.opExInfoAlt()).contains("ORANGE")
        assertThat(datalinkListResponse.ops().getOrNull())
            .containsExactly(
                DatalinkListResponse.Op.builder()
                    .linkDetails("Link details")
                    .linkName("Link-16")
                    .linkStartTime(OffsetDateTime.parse("2024-01-07T13:55:43.123Z"))
                    .linkStopTime(OffsetDateTime.parse("2024-01-08T13:55:43.123Z"))
                    .linkStopTimeMod("AFTER")
                    .build()
            )
        assertThat(datalinkListResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(datalinkListResponse.origNetwork()).contains("OPS1")
        assertThat(datalinkListResponse.planOrigNum()).contains("SACEUR 106")
        assertThat(datalinkListResponse.pocCallSign()).contains("4077 MASH")
        assertThat(datalinkListResponse.pocLat()).contains(45.23)
        assertThat(datalinkListResponse.pocLocName()).contains("CAMP SWAMPY")
        assertThat(datalinkListResponse.pocLon()).contains(179.1)
        assertThat(datalinkListResponse.pocName()).contains("F. BURNS")
        assertThat(datalinkListResponse.pocNums().getOrNull())
            .containsExactly("TEL:804-555-4142", "TEL:804-867-5309")
        assertThat(datalinkListResponse.pocRank()).contains("MAJ")
        assertThat(datalinkListResponse.qualifier()).contains("CHG")
        assertThat(datalinkListResponse.qualSn()).contains(1)
        assertThat(datalinkListResponse.rawFileUri()).contains("Example URI")
        assertThat(datalinkListResponse.references().getOrNull())
            .containsExactly(
                DatalinkListResponse.Reference.builder()
                    .refOriginator("CENTCOM")
                    .refSerialId("A")
                    .refSerialNum("1402001")
                    .addRefSiC("RDU")
                    .addRefSiC("C-123-92")
                    .refSpecialNotation("NOTAL")
                    .refTs(OffsetDateTime.parse("2024-01-07T13:55:43.123Z"))
                    .refType("ABSTAT")
                    .build()
            )
        assertThat(datalinkListResponse.refPoints().getOrNull())
            .containsExactly(
                DatalinkListResponse.RefPoint.builder()
                    .effEventTime(OffsetDateTime.parse("2024-01-08T13:55:43.123Z"))
                    .refDes("L5")
                    .refLat(45.23)
                    .refLocName("FORT BRAGG")
                    .refLon(179.1)
                    .refPointType("DLRP")
                    .build()
            )
        assertThat(datalinkListResponse.remarks().getOrNull())
            .containsExactly(
                DatalinkListResponse.Remark.builder()
                    .text("Example data link remarks")
                    .type("CONTINGENCY PROCEDURES")
                    .build()
            )
        assertThat(datalinkListResponse.resTrackQual()).contains(3)
        assertThat(datalinkListResponse.serialNum()).contains("1201003")
        assertThat(datalinkListResponse.sourceDl()).contains("AXE")
        assertThat(datalinkListResponse.specTracks().getOrNull())
            .containsExactly(
                DatalinkListResponse.SpecTrack.builder()
                    .specTrackNum("12345")
                    .specTrackNumDesc("SAM SITE CHARLIE")
                    .build()
            )
        assertThat(datalinkListResponse.speedDiff()).contains(50)
        assertThat(datalinkListResponse.stopTime())
            .contains(OffsetDateTime.parse("2024-01-08T13:55:43.123Z"))
        assertThat(datalinkListResponse.stopTimeMod()).contains("AFTER")
        assertThat(datalinkListResponse.sysDefaultCode()).contains("MAN")
        assertThat(datalinkListResponse.trackNumBlockLLs().getOrNull()).containsExactly(1234, 2345)
        assertThat(datalinkListResponse.trackNumBlocks().getOrNull())
            .containsExactly("0200-0300", "0400-4412")
        assertThat(datalinkListResponse.updatedAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(datalinkListResponse.updatedBy()).contains("some.user")
        assertThat(datalinkListResponse.voiceCoord().getOrNull())
            .containsExactly(
                DatalinkListResponse.VoiceCoord.builder()
                    .commPri("P")
                    .freqDes("ST300A")
                    .addTeleFreqNum("TEL:804-555-4142")
                    .addTeleFreqNum("TEL:804-867-5309")
                    .voiceNetDes("VPN")
                    .build()
            )
        assertThat(datalinkListResponse.winSizeMin()).contains(1.25)
        assertThat(datalinkListResponse.winSizeMult()).contains(2.1)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val datalinkListResponse =
            DatalinkListResponse.builder()
                .classificationMarking("U")
                .dataMode(DatalinkListResponse.DataMode.TEST)
                .opExName("DESERT WIND")
                .originator("USCENTCOM")
                .source("Bluestaq")
                .startTime(OffsetDateTime.parse("2024-01-07T13:55:43.123Z"))
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .addAckInstUnit("AOC EXT 2345")
                .addAckInstUnit("317 AW")
                .ackReq(true)
                .altDiff(20)
                .canxId("ABSTAT")
                .canxOriginator("505 AOC")
                .canxSerialNum("ABC1234567")
                .addCanxSiC("RDU")
                .addCanxSiC("X234BS")
                .canxSpecialNotation("PASEP")
                .canxTs(OffsetDateTime.parse("2024-01-07T13:55:43.123Z"))
                .addClassReason("15C")
                .addClassReason("15D")
                .classSource("USJFCOM EXORD SOLID WASTE 98")
                .consecDecorr(3)
                .courseDiff(60)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .addDecExemptCode("X1")
                .addDecExemptCode("X2")
                .addDecInstDate("AT EXERCISE ENDEX")
                .addDecInstDate("DATE:25NOV1997")
                .decorrWinMult(1.7)
                .geoDatum("EUR-T")
                .jreCallSign("CHARLIE ONE")
                .jreDetails("JRE details")
                .jrePriAdd(71777)
                .jreSecAdd(77771)
                .jreUnitDes("CVN-72")
                .maxGeoPosQual(12)
                .maxTrackQual(12)
                .mgmtCode("VICTOR")
                .mgmtCodeMeaning("ORBIT AT POINT BRAVO")
                .minGeoPosQual(3)
                .minTrackQual(6)
                .month("OCT")
                .addMultiDuty(
                    DatalinkListResponse.MultiDuty.builder()
                        .duty("SICO")
                        .addDutyTeleFreqNum("TEL:804-555-4142")
                        .addDutyTeleFreqNum("TEL:804-867-5309")
                        .addMultiDutyVoiceCoord(
                            DatalinkListResponse.MultiDuty.MultiDutyVoiceCoord.builder()
                                .multiCommPri("P")
                                .multiFreqDes("ST300A")
                                .addMultiTeleFreqNum("TEL:804-555-4142")
                                .addMultiTeleFreqNum("TEL:804-867-5309")
                                .multiVoiceNetDes("VPN")
                                .build()
                        )
                        .name("POPOVICH")
                        .rank("LCDR")
                        .unitDes("SHIP:STENNIS")
                        .build()
                )
                .addNonLinkUnitDe("CS:GRAY GHOST")
                .addNonLinkUnitDe("CS:WHITE WHALE")
                .opExInfo("CONTROL")
                .opExInfoAlt("ORANGE")
                .addOp(
                    DatalinkListResponse.Op.builder()
                        .linkDetails("Link details")
                        .linkName("Link-16")
                        .linkStartTime(OffsetDateTime.parse("2024-01-07T13:55:43.123Z"))
                        .linkStopTime(OffsetDateTime.parse("2024-01-08T13:55:43.123Z"))
                        .linkStopTimeMod("AFTER")
                        .build()
                )
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .planOrigNum("SACEUR 106")
                .pocCallSign("4077 MASH")
                .pocLat(45.23)
                .pocLocName("CAMP SWAMPY")
                .pocLon(179.1)
                .pocName("F. BURNS")
                .addPocNum("TEL:804-555-4142")
                .addPocNum("TEL:804-867-5309")
                .pocRank("MAJ")
                .qualifier("CHG")
                .qualSn(1)
                .rawFileUri("Example URI")
                .addReference(
                    DatalinkListResponse.Reference.builder()
                        .refOriginator("CENTCOM")
                        .refSerialId("A")
                        .refSerialNum("1402001")
                        .addRefSiC("RDU")
                        .addRefSiC("C-123-92")
                        .refSpecialNotation("NOTAL")
                        .refTs(OffsetDateTime.parse("2024-01-07T13:55:43.123Z"))
                        .refType("ABSTAT")
                        .build()
                )
                .addRefPoint(
                    DatalinkListResponse.RefPoint.builder()
                        .effEventTime(OffsetDateTime.parse("2024-01-08T13:55:43.123Z"))
                        .refDes("L5")
                        .refLat(45.23)
                        .refLocName("FORT BRAGG")
                        .refLon(179.1)
                        .refPointType("DLRP")
                        .build()
                )
                .addRemark(
                    DatalinkListResponse.Remark.builder()
                        .text("Example data link remarks")
                        .type("CONTINGENCY PROCEDURES")
                        .build()
                )
                .resTrackQual(3)
                .serialNum("1201003")
                .sourceDl("AXE")
                .addSpecTrack(
                    DatalinkListResponse.SpecTrack.builder()
                        .specTrackNum("12345")
                        .specTrackNumDesc("SAM SITE CHARLIE")
                        .build()
                )
                .speedDiff(50)
                .stopTime(OffsetDateTime.parse("2024-01-08T13:55:43.123Z"))
                .stopTimeMod("AFTER")
                .sysDefaultCode("MAN")
                .addTrackNumBlockLl(1234)
                .addTrackNumBlockLl(2345)
                .addTrackNumBlock("0200-0300")
                .addTrackNumBlock("0400-4412")
                .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .addVoiceCoord(
                    DatalinkListResponse.VoiceCoord.builder()
                        .commPri("P")
                        .freqDes("ST300A")
                        .addTeleFreqNum("TEL:804-555-4142")
                        .addTeleFreqNum("TEL:804-867-5309")
                        .voiceNetDes("VPN")
                        .build()
                )
                .winSizeMin(1.25)
                .winSizeMult(2.1)
                .build()

        val roundtrippedDatalinkListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(datalinkListResponse),
                jacksonTypeRef<DatalinkListResponse>(),
            )

        assertThat(roundtrippedDatalinkListResponse).isEqualTo(datalinkListResponse)
    }
}
