// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.effectresponses

import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EffectResponseCreateParamsTest {

    @Test
    fun create() {
        EffectResponseCreateParams.builder()
            .classificationMarking("U")
            .dataMode(EffectResponseCreateParams.DataMode.TEST)
            .source("Bluestaq")
            .type("COA")
            .id("EFFECTRESPONSE-ID")
            .addActionsList(
                EffectResponseCreateParams.ActionsList.builder()
                    .actionActorSrcId("ACTIONACTORSRC-ID")
                    .actionActorSrcType("AIRCRAFT")
                    .actionEndTime(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                    .actionId("ACTION-ID")
                    .addActionMetric(
                        EffectResponseCreateParams.ActionsList.ActionMetric.builder()
                            .domainValue(10.1)
                            .metricType("GoalAchievement")
                            .provenance("Example metric")
                            .relativeValue(10.1)
                            .build()
                    )
                    .actionStartTime(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                    .actorInterceptAlt(1.1)
                    .actorInterceptLat(45.1)
                    .actorInterceptLon(180.1)
                    .effector("SENSOR1")
                    .summary("Example summary")
                    .targetSrcId("TARGETSRC-ID")
                    .targetSrcType("POI")
                    .totEndTime(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                    .totStartTime(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                    .weaponInterceptAlt(1.1)
                    .weaponInterceptLat(45.1)
                    .weaponInterceptLon(180.1)
                    .build()
            )
            .actorSrcId("RC-ID")
            .actorSrcType("AIRCRAFT")
            .addCoaMetric(
                EffectResponseCreateParams.CoaMetric.builder()
                    .domainValue(10.1)
                    .metricType("GoalAchievement")
                    .provenance("Example metric")
                    .relativeValue(10.1)
                    .build()
            )
            .collateralDamageEst(0.5)
            .createdAt(OffsetDateTime.parse("2021-01-01T16:00:00.123Z"))
            .createdBy("some.user")
            .decisionDeadline(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
            .addExternalAction("ACTION1")
            .addExternalAction("ACTION2")
            .externalRequestId("EXTERNALREQUEST-ID")
            .idEffectRequest("EFFECTREQUEST-ID")
            .munitionId("MUNITION-ID")
            .munitionType("Dummy")
            .origin("THIRD_PARTY_DATASOURCE")
            .origNetwork("OPS1")
            .probabilityOfKill(0.7)
            .redTargetSrcId("REDTARGETSRC-ID")
            .redTargetSrcType("POI")
            .redTimeToOverhead(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
            .shotsRequired(10)
            .build()
    }

    @Test
    fun body() {
        val params =
            EffectResponseCreateParams.builder()
                .classificationMarking("U")
                .dataMode(EffectResponseCreateParams.DataMode.TEST)
                .source("Bluestaq")
                .type("COA")
                .id("EFFECTRESPONSE-ID")
                .addActionsList(
                    EffectResponseCreateParams.ActionsList.builder()
                        .actionActorSrcId("ACTIONACTORSRC-ID")
                        .actionActorSrcType("AIRCRAFT")
                        .actionEndTime(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                        .actionId("ACTION-ID")
                        .addActionMetric(
                            EffectResponseCreateParams.ActionsList.ActionMetric.builder()
                                .domainValue(10.1)
                                .metricType("GoalAchievement")
                                .provenance("Example metric")
                                .relativeValue(10.1)
                                .build()
                        )
                        .actionStartTime(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                        .actorInterceptAlt(1.1)
                        .actorInterceptLat(45.1)
                        .actorInterceptLon(180.1)
                        .effector("SENSOR1")
                        .summary("Example summary")
                        .targetSrcId("TARGETSRC-ID")
                        .targetSrcType("POI")
                        .totEndTime(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                        .totStartTime(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                        .weaponInterceptAlt(1.1)
                        .weaponInterceptLat(45.1)
                        .weaponInterceptLon(180.1)
                        .build()
                )
                .actorSrcId("RC-ID")
                .actorSrcType("AIRCRAFT")
                .addCoaMetric(
                    EffectResponseCreateParams.CoaMetric.builder()
                        .domainValue(10.1)
                        .metricType("GoalAchievement")
                        .provenance("Example metric")
                        .relativeValue(10.1)
                        .build()
                )
                .collateralDamageEst(0.5)
                .createdAt(OffsetDateTime.parse("2021-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .decisionDeadline(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                .addExternalAction("ACTION1")
                .addExternalAction("ACTION2")
                .externalRequestId("EXTERNALREQUEST-ID")
                .idEffectRequest("EFFECTREQUEST-ID")
                .munitionId("MUNITION-ID")
                .munitionType("Dummy")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .probabilityOfKill(0.7)
                .redTargetSrcId("REDTARGETSRC-ID")
                .redTargetSrcType("POI")
                .redTimeToOverhead(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                .shotsRequired(10)
                .build()

        val body = params._body()

        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(EffectResponseCreateParams.DataMode.TEST)
        assertThat(body.source()).isEqualTo("Bluestaq")
        assertThat(body.type()).isEqualTo("COA")
        assertThat(body.id()).contains("EFFECTRESPONSE-ID")
        assertThat(body.actionsList().getOrNull())
            .containsExactly(
                EffectResponseCreateParams.ActionsList.builder()
                    .actionActorSrcId("ACTIONACTORSRC-ID")
                    .actionActorSrcType("AIRCRAFT")
                    .actionEndTime(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                    .actionId("ACTION-ID")
                    .addActionMetric(
                        EffectResponseCreateParams.ActionsList.ActionMetric.builder()
                            .domainValue(10.1)
                            .metricType("GoalAchievement")
                            .provenance("Example metric")
                            .relativeValue(10.1)
                            .build()
                    )
                    .actionStartTime(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                    .actorInterceptAlt(1.1)
                    .actorInterceptLat(45.1)
                    .actorInterceptLon(180.1)
                    .effector("SENSOR1")
                    .summary("Example summary")
                    .targetSrcId("TARGETSRC-ID")
                    .targetSrcType("POI")
                    .totEndTime(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                    .totStartTime(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
                    .weaponInterceptAlt(1.1)
                    .weaponInterceptLat(45.1)
                    .weaponInterceptLon(180.1)
                    .build()
            )
        assertThat(body.actorSrcId()).contains("RC-ID")
        assertThat(body.actorSrcType()).contains("AIRCRAFT")
        assertThat(body.coaMetrics().getOrNull())
            .containsExactly(
                EffectResponseCreateParams.CoaMetric.builder()
                    .domainValue(10.1)
                    .metricType("GoalAchievement")
                    .provenance("Example metric")
                    .relativeValue(10.1)
                    .build()
            )
        assertThat(body.collateralDamageEst()).contains(0.5)
        assertThat(body.createdAt()).contains(OffsetDateTime.parse("2021-01-01T16:00:00.123Z"))
        assertThat(body.createdBy()).contains("some.user")
        assertThat(body.decisionDeadline())
            .contains(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
        assertThat(body.externalActions().getOrNull()).containsExactly("ACTION1", "ACTION2")
        assertThat(body.externalRequestId()).contains("EXTERNALREQUEST-ID")
        assertThat(body.idEffectRequest()).contains("EFFECTREQUEST-ID")
        assertThat(body.munitionId()).contains("MUNITION-ID")
        assertThat(body.munitionType()).contains("Dummy")
        assertThat(body.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(body.origNetwork()).contains("OPS1")
        assertThat(body.probabilityOfKill()).contains(0.7)
        assertThat(body.redTargetSrcId()).contains("REDTARGETSRC-ID")
        assertThat(body.redTargetSrcType()).contains("POI")
        assertThat(body.redTimeToOverhead())
            .contains(OffsetDateTime.parse("2021-01-01T00:00:00.123456Z"))
        assertThat(body.shotsRequired()).contains(10)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            EffectResponseCreateParams.builder()
                .classificationMarking("U")
                .dataMode(EffectResponseCreateParams.DataMode.TEST)
                .source("Bluestaq")
                .type("COA")
                .build()

        val body = params._body()

        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(EffectResponseCreateParams.DataMode.TEST)
        assertThat(body.source()).isEqualTo("Bluestaq")
        assertThat(body.type()).isEqualTo("COA")
    }
}
