// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.services.blocking

import com.unifieddatalibrary.api.TestServerExtension
import com.unifieddatalibrary.api.client.okhttp.UnifieddatalibraryOkHttpClient
import com.unifieddatalibrary.api.models.starcatalog.StarCatalogCountParams
import com.unifieddatalibrary.api.models.starcatalog.StarCatalogCreateBulkParams
import com.unifieddatalibrary.api.models.starcatalog.StarCatalogCreateParams
import com.unifieddatalibrary.api.models.starcatalog.StarCatalogGetParams
import com.unifieddatalibrary.api.models.starcatalog.StarCatalogTupleParams
import com.unifieddatalibrary.api.models.starcatalog.StarCatalogUnvalidatedPublishParams
import com.unifieddatalibrary.api.models.starcatalog.StarCatalogUpdateParams
import java.time.OffsetDateTime
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(TestServerExtension::class)
internal class StarCatalogServiceTest {

    @Test
    fun create() {
        val client =
            UnifieddatalibraryOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val starCatalogService = client.starCatalog()

        starCatalogService.create(
            StarCatalogCreateParams.builder()
                .astrometryOrigin("GA")
                .classificationMarking("U")
                .csId(12345L)
                .dataMode(StarCatalogCreateParams.DataMode.TEST)
                .dec(21.8)
                .ra(14.43)
                .source("Bluestaq")
                .starEpoch(2018.864)
                .id("STAR-CAT-DATASET-ID")
                .aavsoVsxId(2387137)
                .abgmag(11.24)
                .abgmagOrigin("PS")
                .abgmagUnc(0.023)
                .abimag(11.24)
                .abimagOrigin("GA")
                .abimagUnc(0.023)
                .abrmag(11.24)
                .abrmagOrigin("SK")
                .abrmagUnc(0.023)
                .abymag(11.24)
                .abymagOrigin("AP")
                .abymagUnc(0.023)
                .abzmag(11.24)
                .abzmagOrigin("AP")
                .abzmagUnc(0.023)
                .allWisEccInd("0000")
                .allWiseId("WISEA J152743.04+624823.6")
                .allWisEnaInd(1)
                .allWisEphQualInd("AAAA")
                .apassId("175-0082419")
                .astrometricExcessNoise(921.2857)
                .astrometricExcessNoiseSig(194326670.1)
                .bmag(27.004)
                .bmagOrigin("AP")
                .bmagUnc(9.999)
                .bpmag(0.04559)
                .bpmagUnc(0.2227)
                .carrascoCatId(1244)
                .catVersion("1.23 DR3")
                .catWise2020Id("3584p196_b0-084425")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .decUnc(40.996)
                .ducatiCatId("AB ORI")
                .gaiadr3CatId(89012345678901L)
                .gmag(0.0046)
                .gmagUnc(0.00292)
                .gncCatId(12345)
                .healpixIndex(196607)
                .hipCatId(12345)
                .hmag(12.126)
                .hmagOrigin("UL")
                .hmagUnc(5.722)
                .imag(22.46249)
                .imagOrigin("HI")
                .imagUnc(1.2000417)
                .jmag(9.515)
                .jmagOrigin("TP")
                .jmagUnc(7.559)
                .kmag(13.545)
                .kmagOrigin("UC")
                .kmagUnc(0.052)
                .morphologyInd(5)
                .multFlag(true)
                .multiplicity("2")
                .neighborDec(89.99)
                .neighborDistance(201.406)
                .neighborFlag(false)
                .neighborId(2456L)
                .neighborRa(359.99)
                .nonSingleStar("7")
                .numNeighbors(519)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .panStarrsId(215993386231483000L)
                .parallax(-6.8)
                .parallaxUnc(82.35)
                .pmdec(-970.1003)
                .pmdecUnc(1.22)
                .pmra(1000.45)
                .pmraUnc(5.6)
                .pmUncFlag(false)
                .posUncFlag(false)
                .ps1astrometryCorrectionFlag(7)
                .ps1ObjInfoFlag(2005196800)
                .ps1QualityFlag(239)
                .raUnc(509.466)
                .rmag(22.657284)
                .rmagOrigin("GA")
                .rmagUnc(0.053)
                .rpmag(8.0047)
                .rpmagUnc(1.233)
                .ruwe(116.016365)
                .sdaCatId(3015023687L)
                .sgmag(28.663515)
                .sgmagUnc(2.3097522)
                .shift(4.548)
                .shiftFlag(false)
                .shiftFwhm1(0.157)
                .shiftFwhm6(1.065)
                .skyMapperId(505176683)
                .twoMassId("A1B2C3D4E5")
                .twoMassPhQualInd("AAAA")
                .twoMassReadFlag("111")
                .twoMassXscId("5000540")
                .tychoDscId(9537000661L)
                .uhsId(460074663768L)
                .ukidssGcsId(442466709194L)
                .ukidssGpsId(439491265503L)
                .ukidssLasId(433883403451L)
                .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .varFlag(true)
                .variability("1")
                .vhsId(473820608583L)
                .vmag(25.829414)
                .vmagOrigin("CR")
                .vmagUnc(2.055)
                .w1mag(15.782)
                .w1magOrigin("CA")
                .w1magUnc(0.042)
                .w1sat(0.993)
                .w2mag(16.523)
                .w2magOrigin("CA")
                .w2magUnc(0.021)
                .w2sat(0.962)
                .w3mag(11.541)
                .w3magOrigin("AL")
                .w3magUnc(0.159)
                .w3sat(0.999)
                .w4mag(9.007)
                .w4magOrigin("AL")
                .w4magUnc(0.468)
                .w4sat(0.523)
                .wdsCatId("155506")
                .build()
        )
    }

    @Test
    fun update() {
        val client =
            UnifieddatalibraryOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val starCatalogService = client.starCatalog()

        starCatalogService.update(
            StarCatalogUpdateParams.builder()
                .pathId("id")
                .astrometryOrigin("GA")
                .classificationMarking("U")
                .csId(12345L)
                .dataMode(StarCatalogUpdateParams.DataMode.TEST)
                .dec(21.8)
                .ra(14.43)
                .source("Bluestaq")
                .starEpoch(2018.864)
                .bodyId("STAR-CAT-DATASET-ID")
                .aavsoVsxId(2387137)
                .abgmag(11.24)
                .abgmagOrigin("PS")
                .abgmagUnc(0.023)
                .abimag(11.24)
                .abimagOrigin("GA")
                .abimagUnc(0.023)
                .abrmag(11.24)
                .abrmagOrigin("SK")
                .abrmagUnc(0.023)
                .abymag(11.24)
                .abymagOrigin("AP")
                .abymagUnc(0.023)
                .abzmag(11.24)
                .abzmagOrigin("AP")
                .abzmagUnc(0.023)
                .allWisEccInd("0000")
                .allWiseId("WISEA J152743.04+624823.6")
                .allWisEnaInd(1)
                .allWisEphQualInd("AAAA")
                .apassId("175-0082419")
                .astrometricExcessNoise(921.2857)
                .astrometricExcessNoiseSig(194326670.1)
                .bmag(27.004)
                .bmagOrigin("AP")
                .bmagUnc(9.999)
                .bpmag(0.04559)
                .bpmagUnc(0.2227)
                .carrascoCatId(1244)
                .catVersion("1.23 DR3")
                .catWise2020Id("3584p196_b0-084425")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .decUnc(40.996)
                .ducatiCatId("AB ORI")
                .gaiadr3CatId(89012345678901L)
                .gmag(0.0046)
                .gmagUnc(0.00292)
                .gncCatId(12345)
                .healpixIndex(196607)
                .hipCatId(12345)
                .hmag(12.126)
                .hmagOrigin("UL")
                .hmagUnc(5.722)
                .imag(22.46249)
                .imagOrigin("HI")
                .imagUnc(1.2000417)
                .jmag(9.515)
                .jmagOrigin("TP")
                .jmagUnc(7.559)
                .kmag(13.545)
                .kmagOrigin("UC")
                .kmagUnc(0.052)
                .morphologyInd(5)
                .multFlag(true)
                .multiplicity("2")
                .neighborDec(89.99)
                .neighborDistance(201.406)
                .neighborFlag(false)
                .neighborId(2456L)
                .neighborRa(359.99)
                .nonSingleStar("7")
                .numNeighbors(519)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .panStarrsId(215993386231483000L)
                .parallax(-6.8)
                .parallaxUnc(82.35)
                .pmdec(-970.1003)
                .pmdecUnc(1.22)
                .pmra(1000.45)
                .pmraUnc(5.6)
                .pmUncFlag(false)
                .posUncFlag(false)
                .ps1astrometryCorrectionFlag(7)
                .ps1ObjInfoFlag(2005196800)
                .ps1QualityFlag(239)
                .raUnc(509.466)
                .rmag(22.657284)
                .rmagOrigin("GA")
                .rmagUnc(0.053)
                .rpmag(8.0047)
                .rpmagUnc(1.233)
                .ruwe(116.016365)
                .sdaCatId(3015023687L)
                .sgmag(28.663515)
                .sgmagUnc(2.3097522)
                .shift(4.548)
                .shiftFlag(false)
                .shiftFwhm1(0.157)
                .shiftFwhm6(1.065)
                .skyMapperId(505176683)
                .twoMassId("A1B2C3D4E5")
                .twoMassPhQualInd("AAAA")
                .twoMassReadFlag("111")
                .twoMassXscId("5000540")
                .tychoDscId(9537000661L)
                .uhsId(460074663768L)
                .ukidssGcsId(442466709194L)
                .ukidssGpsId(439491265503L)
                .ukidssLasId(433883403451L)
                .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .varFlag(true)
                .variability("1")
                .vhsId(473820608583L)
                .vmag(25.829414)
                .vmagOrigin("CR")
                .vmagUnc(2.055)
                .w1mag(15.782)
                .w1magOrigin("CA")
                .w1magUnc(0.042)
                .w1sat(0.993)
                .w2mag(16.523)
                .w2magOrigin("CA")
                .w2magUnc(0.021)
                .w2sat(0.962)
                .w3mag(11.541)
                .w3magOrigin("AL")
                .w3magUnc(0.159)
                .w3sat(0.999)
                .w4mag(9.007)
                .w4magOrigin("AL")
                .w4magUnc(0.468)
                .w4sat(0.523)
                .wdsCatId("155506")
                .build()
        )
    }

    @Test
    fun list() {
        val client =
            UnifieddatalibraryOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val starCatalogService = client.starCatalog()

        val page = starCatalogService.list()

        page.items().forEach { it.validate() }
    }

    @Test
    fun delete() {
        val client =
            UnifieddatalibraryOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val starCatalogService = client.starCatalog()

        starCatalogService.delete("id")
    }

    @Test
    fun count() {
        val client =
            UnifieddatalibraryOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val starCatalogService = client.starCatalog()

        starCatalogService.count(
            StarCatalogCountParams.builder().dec(0.0).firstResult(0L).maxResults(0L).ra(0.0).build()
        )
    }

    @Test
    fun createBulk() {
        val client =
            UnifieddatalibraryOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val starCatalogService = client.starCatalog()

        starCatalogService.createBulk(
            listOf(
                StarCatalogCreateBulkParams.Body.builder()
                    .astrometryOrigin("GA")
                    .classificationMarking("U")
                    .csId(12345L)
                    .dataMode(StarCatalogCreateBulkParams.Body.DataMode.TEST)
                    .dec(21.8)
                    .ra(14.43)
                    .source("Bluestaq")
                    .starEpoch(2018.864)
                    .id("STAR-CAT-DATASET-ID")
                    .aavsoVsxId(2387137)
                    .abgmag(11.24)
                    .abgmagOrigin("PS")
                    .abgmagUnc(0.023)
                    .abimag(11.24)
                    .abimagOrigin("GA")
                    .abimagUnc(0.023)
                    .abrmag(11.24)
                    .abrmagOrigin("SK")
                    .abrmagUnc(0.023)
                    .abymag(11.24)
                    .abymagOrigin("AP")
                    .abymagUnc(0.023)
                    .abzmag(11.24)
                    .abzmagOrigin("AP")
                    .abzmagUnc(0.023)
                    .allWisEccInd("0000")
                    .allWiseId("WISEA J152743.04+624823.6")
                    .allWisEnaInd(1)
                    .allWisEphQualInd("AAAA")
                    .apassId("175-0082419")
                    .astrometricExcessNoise(921.2857)
                    .astrometricExcessNoiseSig(194326670.1)
                    .bmag(27.004)
                    .bmagOrigin("AP")
                    .bmagUnc(9.999)
                    .bpmag(0.04559)
                    .bpmagUnc(0.2227)
                    .carrascoCatId(1244)
                    .catVersion("1.23 DR3")
                    .catWise2020Id("3584p196_b0-084425")
                    .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                    .createdBy("some.user")
                    .decUnc(40.996)
                    .ducatiCatId("AB ORI")
                    .gaiadr3CatId(89012345678901L)
                    .gmag(0.0046)
                    .gmagUnc(0.00292)
                    .gncCatId(12345)
                    .healpixIndex(196607)
                    .hipCatId(12345)
                    .hmag(12.126)
                    .hmagOrigin("UL")
                    .hmagUnc(5.722)
                    .imag(22.46249)
                    .imagOrigin("HI")
                    .imagUnc(1.2000417)
                    .jmag(9.515)
                    .jmagOrigin("TP")
                    .jmagUnc(7.559)
                    .kmag(13.545)
                    .kmagOrigin("UC")
                    .kmagUnc(0.052)
                    .morphologyInd(5)
                    .multFlag(true)
                    .multiplicity("2")
                    .neighborDec(89.99)
                    .neighborDistance(201.406)
                    .neighborFlag(false)
                    .neighborId(2456L)
                    .neighborRa(359.99)
                    .nonSingleStar("7")
                    .numNeighbors(519)
                    .origin("THIRD_PARTY_DATASOURCE")
                    .origNetwork("OPS1")
                    .panStarrsId(215993386231483000L)
                    .parallax(-6.8)
                    .parallaxUnc(82.35)
                    .pmdec(-970.1003)
                    .pmdecUnc(1.22)
                    .pmra(1000.45)
                    .pmraUnc(5.6)
                    .pmUncFlag(false)
                    .posUncFlag(false)
                    .ps1astrometryCorrectionFlag(7)
                    .ps1ObjInfoFlag(2005196800)
                    .ps1QualityFlag(239)
                    .raUnc(509.466)
                    .rmag(22.657284)
                    .rmagOrigin("GA")
                    .rmagUnc(0.053)
                    .rpmag(8.0047)
                    .rpmagUnc(1.233)
                    .ruwe(116.016365)
                    .sdaCatId(3015023687L)
                    .sgmag(28.663515)
                    .sgmagUnc(2.3097522)
                    .shift(4.548)
                    .shiftFlag(false)
                    .shiftFwhm1(0.157)
                    .shiftFwhm6(1.065)
                    .skyMapperId(505176683)
                    .twoMassId("A1B2C3D4E5")
                    .twoMassPhQualInd("AAAA")
                    .twoMassReadFlag("111")
                    .twoMassXscId("5000540")
                    .tychoDscId(9537000661L)
                    .uhsId(460074663768L)
                    .ukidssGcsId(442466709194L)
                    .ukidssGpsId(439491265503L)
                    .ukidssLasId(433883403451L)
                    .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                    .updatedBy("some.user")
                    .varFlag(true)
                    .variability("1")
                    .vhsId(473820608583L)
                    .vmag(25.829414)
                    .vmagOrigin("CR")
                    .vmagUnc(2.055)
                    .w1mag(15.782)
                    .w1magOrigin("CA")
                    .w1magUnc(0.042)
                    .w1sat(0.993)
                    .w2mag(16.523)
                    .w2magOrigin("CA")
                    .w2magUnc(0.021)
                    .w2sat(0.962)
                    .w3mag(11.541)
                    .w3magOrigin("AL")
                    .w3magUnc(0.159)
                    .w3sat(0.999)
                    .w4mag(9.007)
                    .w4magOrigin("AL")
                    .w4magUnc(0.468)
                    .w4sat(0.523)
                    .wdsCatId("155506")
                    .build()
            )
        )
    }

    @Test
    fun get() {
        val client =
            UnifieddatalibraryOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val starCatalogService = client.starCatalog()

        val starCatalog =
            starCatalogService.get(
                StarCatalogGetParams.builder().id("id").firstResult(0L).maxResults(0L).build()
            )

        starCatalog.validate()
    }

    @Test
    fun queryhelp() {
        val client =
            UnifieddatalibraryOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val starCatalogService = client.starCatalog()

        val response = starCatalogService.queryhelp()

        response.validate()
    }

    @Test
    fun tuple() {
        val client =
            UnifieddatalibraryOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val starCatalogService = client.starCatalog()

        val response =
            starCatalogService.tuple(
                StarCatalogTupleParams.builder()
                    .columns("columns")
                    .dec(0.0)
                    .firstResult(0L)
                    .maxResults(0L)
                    .ra(0.0)
                    .build()
            )

        response.forEach { it.validate() }
    }

    @Test
    fun unvalidatedPublish() {
        val client =
            UnifieddatalibraryOkHttpClient.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val starCatalogService = client.starCatalog()

        starCatalogService.unvalidatedPublish(
            listOf(
                StarCatalogUnvalidatedPublishParams.Body.builder()
                    .astrometryOrigin("GA")
                    .classificationMarking("U")
                    .csId(12345L)
                    .dataMode(StarCatalogUnvalidatedPublishParams.Body.DataMode.TEST)
                    .dec(21.8)
                    .ra(14.43)
                    .source("Bluestaq")
                    .starEpoch(2018.864)
                    .id("STAR-CAT-DATASET-ID")
                    .aavsoVsxId(2387137)
                    .abgmag(11.24)
                    .abgmagOrigin("PS")
                    .abgmagUnc(0.023)
                    .abimag(11.24)
                    .abimagOrigin("GA")
                    .abimagUnc(0.023)
                    .abrmag(11.24)
                    .abrmagOrigin("SK")
                    .abrmagUnc(0.023)
                    .abymag(11.24)
                    .abymagOrigin("AP")
                    .abymagUnc(0.023)
                    .abzmag(11.24)
                    .abzmagOrigin("AP")
                    .abzmagUnc(0.023)
                    .allWisEccInd("0000")
                    .allWiseId("WISEA J152743.04+624823.6")
                    .allWisEnaInd(1)
                    .allWisEphQualInd("AAAA")
                    .apassId("175-0082419")
                    .astrometricExcessNoise(921.2857)
                    .astrometricExcessNoiseSig(194326670.1)
                    .bmag(27.004)
                    .bmagOrigin("AP")
                    .bmagUnc(9.999)
                    .bpmag(0.04559)
                    .bpmagUnc(0.2227)
                    .carrascoCatId(1244)
                    .catVersion("1.23 DR3")
                    .catWise2020Id("3584p196_b0-084425")
                    .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                    .createdBy("some.user")
                    .decUnc(40.996)
                    .ducatiCatId("AB ORI")
                    .gaiadr3CatId(89012345678901L)
                    .gmag(0.0046)
                    .gmagUnc(0.00292)
                    .gncCatId(12345)
                    .healpixIndex(196607)
                    .hipCatId(12345)
                    .hmag(12.126)
                    .hmagOrigin("UL")
                    .hmagUnc(5.722)
                    .imag(22.46249)
                    .imagOrigin("HI")
                    .imagUnc(1.2000417)
                    .jmag(9.515)
                    .jmagOrigin("TP")
                    .jmagUnc(7.559)
                    .kmag(13.545)
                    .kmagOrigin("UC")
                    .kmagUnc(0.052)
                    .morphologyInd(5)
                    .multFlag(true)
                    .multiplicity("2")
                    .neighborDec(89.99)
                    .neighborDistance(201.406)
                    .neighborFlag(false)
                    .neighborId(2456L)
                    .neighborRa(359.99)
                    .nonSingleStar("7")
                    .numNeighbors(519)
                    .origin("THIRD_PARTY_DATASOURCE")
                    .origNetwork("OPS1")
                    .panStarrsId(215993386231483000L)
                    .parallax(-6.8)
                    .parallaxUnc(82.35)
                    .pmdec(-970.1003)
                    .pmdecUnc(1.22)
                    .pmra(1000.45)
                    .pmraUnc(5.6)
                    .pmUncFlag(false)
                    .posUncFlag(false)
                    .ps1astrometryCorrectionFlag(7)
                    .ps1ObjInfoFlag(2005196800)
                    .ps1QualityFlag(239)
                    .raUnc(509.466)
                    .rmag(22.657284)
                    .rmagOrigin("GA")
                    .rmagUnc(0.053)
                    .rpmag(8.0047)
                    .rpmagUnc(1.233)
                    .ruwe(116.016365)
                    .sdaCatId(3015023687L)
                    .sgmag(28.663515)
                    .sgmagUnc(2.3097522)
                    .shift(4.548)
                    .shiftFlag(false)
                    .shiftFwhm1(0.157)
                    .shiftFwhm6(1.065)
                    .skyMapperId(505176683)
                    .twoMassId("A1B2C3D4E5")
                    .twoMassPhQualInd("AAAA")
                    .twoMassReadFlag("111")
                    .twoMassXscId("5000540")
                    .tychoDscId(9537000661L)
                    .uhsId(460074663768L)
                    .ukidssGcsId(442466709194L)
                    .ukidssGpsId(439491265503L)
                    .ukidssLasId(433883403451L)
                    .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                    .updatedBy("some.user")
                    .varFlag(true)
                    .variability("1")
                    .vhsId(473820608583L)
                    .vmag(25.829414)
                    .vmagOrigin("CR")
                    .vmagUnc(2.055)
                    .w1mag(15.782)
                    .w1magOrigin("CA")
                    .w1magUnc(0.042)
                    .w1sat(0.993)
                    .w2mag(16.523)
                    .w2magOrigin("CA")
                    .w2magUnc(0.021)
                    .w2sat(0.962)
                    .w3mag(11.541)
                    .w3magOrigin("AL")
                    .w3magUnc(0.159)
                    .w3sat(0.999)
                    .w4mag(9.007)
                    .w4magOrigin("AL")
                    .w4magUnc(0.468)
                    .w4sat(0.523)
                    .wdsCatId("155506")
                    .build()
            )
        )
    }
}
