// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.observations.monoradar

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class MonoradarTupleResponseTest {

    @Test
    fun create() {
        val monoradarTupleResponse =
            MonoradarTupleResponse.builder()
                .classificationMarking("U")
                .dataMode(MonoradarTupleResponse.DataMode.TEST)
                .msgfmt("CAT48")
                .msgts(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .msgtyp("BCN")
                .source("Bluestaq")
                .ts(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .id("MONORADAR-ID")
                .acp(100)
                .addr("ADDR-ID")
                .af(true)
                .aims(true)
                .alt3d(100.23)
                .artsqual("QUALITY")
                .az(100.23)
                .azdelt(44.23)
                .bcnhits(12)
                .addCartpo(1.2)
                .addCartpo(2.2)
                .cdm("CDM")
                .code7500(false)
                .code7600(false)
                .code7700(false)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .faa(true)
                .grndspd(30.23)
                .hdng(30.23)
                .idSensor("REF-SENSOR-ID")
                .m1("MISSION_CODE")
                .m1g(true)
                .m1v("M1V")
                .m2("MILITARY_ID_CODE")
                .m2g(true)
                .m2v("M2V")
                .m2xv("M2XV")
                .m3a("AIRCRAFT_ID")
                .m3ag(true)
                .m3av("M3AV")
                .m3axv("M3AXV")
                .m4("ID_FRIEND")
                .m4d1d2("STATUS")
                .m4v("M4V")
                .mah("MAH")
                .mc(100.23)
                .mcg(true)
                .mcv("MCV")
                .milemrgcy(false)
                .mrgrpt(true)
                .mscommb("MSCOMMB")
                .mti(true)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("ORIG")
                .origSensorId("ORIGSENSOR-ID")
                .psrrl(44.23)
                .rad("RAD")
                .rng(100.23)
                .rngdelt(44.23)
                .sac(10)
                .senalt(100.23)
                .senlat(45.23)
                .senlon(45.23)
                .sic(40)
                .spi(true)
                .ssrl(44.23)
                .addTag("TAG1")
                .addTag("TAG2")
                .tgtconf("CONFIDENCE")
                .tgtcorr("CORRELATION")
                .tgtid("TGT-ID")
                .tis(0.4)
                .trkelig("ELIGIBILITY")
                .trknum(30)
                .tti("TTI")
                .addWectc("WARNING")
                .addWectc("WARNING")
                .build()

        assertThat(monoradarTupleResponse.classificationMarking()).isEqualTo("U")
        assertThat(monoradarTupleResponse.dataMode())
            .isEqualTo(MonoradarTupleResponse.DataMode.TEST)
        assertThat(monoradarTupleResponse.msgfmt()).isEqualTo("CAT48")
        assertThat(monoradarTupleResponse.msgts())
            .isEqualTo(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
        assertThat(monoradarTupleResponse.msgtyp()).isEqualTo("BCN")
        assertThat(monoradarTupleResponse.source()).isEqualTo("Bluestaq")
        assertThat(monoradarTupleResponse.ts())
            .isEqualTo(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
        assertThat(monoradarTupleResponse.id()).contains("MONORADAR-ID")
        assertThat(monoradarTupleResponse.acp()).contains(100)
        assertThat(monoradarTupleResponse.addr()).contains("ADDR-ID")
        assertThat(monoradarTupleResponse.af()).contains(true)
        assertThat(monoradarTupleResponse.aims()).contains(true)
        assertThat(monoradarTupleResponse.alt3d()).contains(100.23)
        assertThat(monoradarTupleResponse.artsqual()).contains("QUALITY")
        assertThat(monoradarTupleResponse.az()).contains(100.23)
        assertThat(monoradarTupleResponse.azdelt()).contains(44.23)
        assertThat(monoradarTupleResponse.bcnhits()).contains(12)
        assertThat(monoradarTupleResponse.cartpos().getOrNull()).containsExactly(1.2, 2.2)
        assertThat(monoradarTupleResponse.cdm()).contains("CDM")
        assertThat(monoradarTupleResponse.code7500()).contains(false)
        assertThat(monoradarTupleResponse.code7600()).contains(false)
        assertThat(monoradarTupleResponse.code7700()).contains(false)
        assertThat(monoradarTupleResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(monoradarTupleResponse.createdBy()).contains("some.user")
        assertThat(monoradarTupleResponse.faa()).contains(true)
        assertThat(monoradarTupleResponse.grndspd()).contains(30.23)
        assertThat(monoradarTupleResponse.hdng()).contains(30.23)
        assertThat(monoradarTupleResponse.idSensor()).contains("REF-SENSOR-ID")
        assertThat(monoradarTupleResponse.m1()).contains("MISSION_CODE")
        assertThat(monoradarTupleResponse.m1g()).contains(true)
        assertThat(monoradarTupleResponse.m1v()).contains("M1V")
        assertThat(monoradarTupleResponse.m2()).contains("MILITARY_ID_CODE")
        assertThat(monoradarTupleResponse.m2g()).contains(true)
        assertThat(monoradarTupleResponse.m2v()).contains("M2V")
        assertThat(monoradarTupleResponse.m2xv()).contains("M2XV")
        assertThat(monoradarTupleResponse.m3a()).contains("AIRCRAFT_ID")
        assertThat(monoradarTupleResponse.m3ag()).contains(true)
        assertThat(monoradarTupleResponse.m3av()).contains("M3AV")
        assertThat(monoradarTupleResponse.m3axv()).contains("M3AXV")
        assertThat(monoradarTupleResponse.m4()).contains("ID_FRIEND")
        assertThat(monoradarTupleResponse.m4d1d2()).contains("STATUS")
        assertThat(monoradarTupleResponse.m4v()).contains("M4V")
        assertThat(monoradarTupleResponse.mah()).contains("MAH")
        assertThat(monoradarTupleResponse.mc()).contains(100.23)
        assertThat(monoradarTupleResponse.mcg()).contains(true)
        assertThat(monoradarTupleResponse.mcv()).contains("MCV")
        assertThat(monoradarTupleResponse.milemrgcy()).contains(false)
        assertThat(monoradarTupleResponse.mrgrpt()).contains(true)
        assertThat(monoradarTupleResponse.mscommb()).contains("MSCOMMB")
        assertThat(monoradarTupleResponse.mti()).contains(true)
        assertThat(monoradarTupleResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(monoradarTupleResponse.origNetwork()).contains("ORIG")
        assertThat(monoradarTupleResponse.origSensorId()).contains("ORIGSENSOR-ID")
        assertThat(monoradarTupleResponse.psrrl()).contains(44.23)
        assertThat(monoradarTupleResponse.rad()).contains("RAD")
        assertThat(monoradarTupleResponse.rng()).contains(100.23)
        assertThat(monoradarTupleResponse.rngdelt()).contains(44.23)
        assertThat(monoradarTupleResponse.sac()).contains(10)
        assertThat(monoradarTupleResponse.senalt()).contains(100.23)
        assertThat(monoradarTupleResponse.senlat()).contains(45.23)
        assertThat(monoradarTupleResponse.senlon()).contains(45.23)
        assertThat(monoradarTupleResponse.sic()).contains(40)
        assertThat(monoradarTupleResponse.spi()).contains(true)
        assertThat(monoradarTupleResponse.ssrl()).contains(44.23)
        assertThat(monoradarTupleResponse.tags().getOrNull()).containsExactly("TAG1", "TAG2")
        assertThat(monoradarTupleResponse.tgtconf()).contains("CONFIDENCE")
        assertThat(monoradarTupleResponse.tgtcorr()).contains("CORRELATION")
        assertThat(monoradarTupleResponse.tgtid()).contains("TGT-ID")
        assertThat(monoradarTupleResponse.tis()).contains(0.4)
        assertThat(monoradarTupleResponse.trkelig()).contains("ELIGIBILITY")
        assertThat(monoradarTupleResponse.trknum()).contains(30)
        assertThat(monoradarTupleResponse.tti()).contains("TTI")
        assertThat(monoradarTupleResponse.wectc().getOrNull()).containsExactly("WARNING", "WARNING")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val monoradarTupleResponse =
            MonoradarTupleResponse.builder()
                .classificationMarking("U")
                .dataMode(MonoradarTupleResponse.DataMode.TEST)
                .msgfmt("CAT48")
                .msgts(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .msgtyp("BCN")
                .source("Bluestaq")
                .ts(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .id("MONORADAR-ID")
                .acp(100)
                .addr("ADDR-ID")
                .af(true)
                .aims(true)
                .alt3d(100.23)
                .artsqual("QUALITY")
                .az(100.23)
                .azdelt(44.23)
                .bcnhits(12)
                .addCartpo(1.2)
                .addCartpo(2.2)
                .cdm("CDM")
                .code7500(false)
                .code7600(false)
                .code7700(false)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .faa(true)
                .grndspd(30.23)
                .hdng(30.23)
                .idSensor("REF-SENSOR-ID")
                .m1("MISSION_CODE")
                .m1g(true)
                .m1v("M1V")
                .m2("MILITARY_ID_CODE")
                .m2g(true)
                .m2v("M2V")
                .m2xv("M2XV")
                .m3a("AIRCRAFT_ID")
                .m3ag(true)
                .m3av("M3AV")
                .m3axv("M3AXV")
                .m4("ID_FRIEND")
                .m4d1d2("STATUS")
                .m4v("M4V")
                .mah("MAH")
                .mc(100.23)
                .mcg(true)
                .mcv("MCV")
                .milemrgcy(false)
                .mrgrpt(true)
                .mscommb("MSCOMMB")
                .mti(true)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("ORIG")
                .origSensorId("ORIGSENSOR-ID")
                .psrrl(44.23)
                .rad("RAD")
                .rng(100.23)
                .rngdelt(44.23)
                .sac(10)
                .senalt(100.23)
                .senlat(45.23)
                .senlon(45.23)
                .sic(40)
                .spi(true)
                .ssrl(44.23)
                .addTag("TAG1")
                .addTag("TAG2")
                .tgtconf("CONFIDENCE")
                .tgtcorr("CORRELATION")
                .tgtid("TGT-ID")
                .tis(0.4)
                .trkelig("ELIGIBILITY")
                .trknum(30)
                .tti("TTI")
                .addWectc("WARNING")
                .addWectc("WARNING")
                .build()

        val roundtrippedMonoradarTupleResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(monoradarTupleResponse),
                jacksonTypeRef<MonoradarTupleResponse>(),
            )

        assertThat(roundtrippedMonoradarTupleResponse).isEqualTo(monoradarTupleResponse)
    }
}
