// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.observations.monoradar

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class MonoradarListResponseTest {

    @Test
    fun create() {
        val monoradarListResponse =
            MonoradarListResponse.builder()
                .classificationMarking("U")
                .dataMode(MonoradarListResponse.DataMode.TEST)
                .msgfmt("CAT48")
                .msgts(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .msgtyp("BCN")
                .source("Bluestaq")
                .ts(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .id("MONORADAR-ID")
                .acp(100)
                .addr("ADDR-ID")
                .af(true)
                .aims(true)
                .alt3d(100.23)
                .artsqual("QUALITY")
                .az(100.23)
                .azdelt(44.23)
                .bcnhits(12)
                .addCartpo(1.2)
                .addCartpo(2.2)
                .cdm("CDM")
                .code7500(false)
                .code7600(false)
                .code7700(false)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .faa(true)
                .grndspd(30.23)
                .hdng(30.23)
                .idSensor("REF-SENSOR-ID")
                .m1("MISSION_CODE")
                .m1g(true)
                .m1v("M1V")
                .m2("MILITARY_ID_CODE")
                .m2g(true)
                .m2v("M2V")
                .m2xv("M2XV")
                .m3a("AIRCRAFT_ID")
                .m3ag(true)
                .m3av("M3AV")
                .m3axv("M3AXV")
                .m4("ID_FRIEND")
                .m4d1d2("STATUS")
                .m4v("M4V")
                .mah("MAH")
                .mc(100.23)
                .mcg(true)
                .mcv("MCV")
                .milemrgcy(false)
                .mrgrpt(true)
                .mscommb("MSCOMMB")
                .mti(true)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .origSensorId("ORIGSENSOR-ID")
                .psrrl(44.23)
                .rad("RAD")
                .rng(100.23)
                .rngdelt(44.23)
                .sac(10)
                .senalt(100.23)
                .senlat(45.23)
                .senlon(45.23)
                .sic(40)
                .spi(true)
                .ssrl(44.23)
                .addTag("TAG1")
                .addTag("TAG2")
                .tgtconf("CONFIDENCE")
                .tgtcorr("CORRELATION")
                .tgtid("TGT-ID")
                .tis(0.4)
                .trkelig("ELIGIBILITY")
                .trknum(30)
                .tti("TTI")
                .addWectc("WARNING")
                .addWectc("WARNING")
                .build()

        assertThat(monoradarListResponse.classificationMarking()).isEqualTo("U")
        assertThat(monoradarListResponse.dataMode()).isEqualTo(MonoradarListResponse.DataMode.TEST)
        assertThat(monoradarListResponse.msgfmt()).isEqualTo("CAT48")
        assertThat(monoradarListResponse.msgts())
            .isEqualTo(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
        assertThat(monoradarListResponse.msgtyp()).isEqualTo("BCN")
        assertThat(monoradarListResponse.source()).isEqualTo("Bluestaq")
        assertThat(monoradarListResponse.ts())
            .isEqualTo(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
        assertThat(monoradarListResponse.id()).contains("MONORADAR-ID")
        assertThat(monoradarListResponse.acp()).contains(100)
        assertThat(monoradarListResponse.addr()).contains("ADDR-ID")
        assertThat(monoradarListResponse.af()).contains(true)
        assertThat(monoradarListResponse.aims()).contains(true)
        assertThat(monoradarListResponse.alt3d()).contains(100.23)
        assertThat(monoradarListResponse.artsqual()).contains("QUALITY")
        assertThat(monoradarListResponse.az()).contains(100.23)
        assertThat(monoradarListResponse.azdelt()).contains(44.23)
        assertThat(monoradarListResponse.bcnhits()).contains(12)
        assertThat(monoradarListResponse.cartpos().getOrNull()).containsExactly(1.2, 2.2)
        assertThat(monoradarListResponse.cdm()).contains("CDM")
        assertThat(monoradarListResponse.code7500()).contains(false)
        assertThat(monoradarListResponse.code7600()).contains(false)
        assertThat(monoradarListResponse.code7700()).contains(false)
        assertThat(monoradarListResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(monoradarListResponse.createdBy()).contains("some.user")
        assertThat(monoradarListResponse.faa()).contains(true)
        assertThat(monoradarListResponse.grndspd()).contains(30.23)
        assertThat(monoradarListResponse.hdng()).contains(30.23)
        assertThat(monoradarListResponse.idSensor()).contains("REF-SENSOR-ID")
        assertThat(monoradarListResponse.m1()).contains("MISSION_CODE")
        assertThat(monoradarListResponse.m1g()).contains(true)
        assertThat(monoradarListResponse.m1v()).contains("M1V")
        assertThat(monoradarListResponse.m2()).contains("MILITARY_ID_CODE")
        assertThat(monoradarListResponse.m2g()).contains(true)
        assertThat(monoradarListResponse.m2v()).contains("M2V")
        assertThat(monoradarListResponse.m2xv()).contains("M2XV")
        assertThat(monoradarListResponse.m3a()).contains("AIRCRAFT_ID")
        assertThat(monoradarListResponse.m3ag()).contains(true)
        assertThat(monoradarListResponse.m3av()).contains("M3AV")
        assertThat(monoradarListResponse.m3axv()).contains("M3AXV")
        assertThat(monoradarListResponse.m4()).contains("ID_FRIEND")
        assertThat(monoradarListResponse.m4d1d2()).contains("STATUS")
        assertThat(monoradarListResponse.m4v()).contains("M4V")
        assertThat(monoradarListResponse.mah()).contains("MAH")
        assertThat(monoradarListResponse.mc()).contains(100.23)
        assertThat(monoradarListResponse.mcg()).contains(true)
        assertThat(monoradarListResponse.mcv()).contains("MCV")
        assertThat(monoradarListResponse.milemrgcy()).contains(false)
        assertThat(monoradarListResponse.mrgrpt()).contains(true)
        assertThat(monoradarListResponse.mscommb()).contains("MSCOMMB")
        assertThat(monoradarListResponse.mti()).contains(true)
        assertThat(monoradarListResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(monoradarListResponse.origNetwork()).contains("OPS1")
        assertThat(monoradarListResponse.origSensorId()).contains("ORIGSENSOR-ID")
        assertThat(monoradarListResponse.psrrl()).contains(44.23)
        assertThat(monoradarListResponse.rad()).contains("RAD")
        assertThat(monoradarListResponse.rng()).contains(100.23)
        assertThat(monoradarListResponse.rngdelt()).contains(44.23)
        assertThat(monoradarListResponse.sac()).contains(10)
        assertThat(monoradarListResponse.senalt()).contains(100.23)
        assertThat(monoradarListResponse.senlat()).contains(45.23)
        assertThat(monoradarListResponse.senlon()).contains(45.23)
        assertThat(monoradarListResponse.sic()).contains(40)
        assertThat(monoradarListResponse.spi()).contains(true)
        assertThat(monoradarListResponse.ssrl()).contains(44.23)
        assertThat(monoradarListResponse.tags().getOrNull()).containsExactly("TAG1", "TAG2")
        assertThat(monoradarListResponse.tgtconf()).contains("CONFIDENCE")
        assertThat(monoradarListResponse.tgtcorr()).contains("CORRELATION")
        assertThat(monoradarListResponse.tgtid()).contains("TGT-ID")
        assertThat(monoradarListResponse.tis()).contains(0.4)
        assertThat(monoradarListResponse.trkelig()).contains("ELIGIBILITY")
        assertThat(monoradarListResponse.trknum()).contains(30)
        assertThat(monoradarListResponse.tti()).contains("TTI")
        assertThat(monoradarListResponse.wectc().getOrNull()).containsExactly("WARNING", "WARNING")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val monoradarListResponse =
            MonoradarListResponse.builder()
                .classificationMarking("U")
                .dataMode(MonoradarListResponse.DataMode.TEST)
                .msgfmt("CAT48")
                .msgts(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .msgtyp("BCN")
                .source("Bluestaq")
                .ts(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .id("MONORADAR-ID")
                .acp(100)
                .addr("ADDR-ID")
                .af(true)
                .aims(true)
                .alt3d(100.23)
                .artsqual("QUALITY")
                .az(100.23)
                .azdelt(44.23)
                .bcnhits(12)
                .addCartpo(1.2)
                .addCartpo(2.2)
                .cdm("CDM")
                .code7500(false)
                .code7600(false)
                .code7700(false)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .faa(true)
                .grndspd(30.23)
                .hdng(30.23)
                .idSensor("REF-SENSOR-ID")
                .m1("MISSION_CODE")
                .m1g(true)
                .m1v("M1V")
                .m2("MILITARY_ID_CODE")
                .m2g(true)
                .m2v("M2V")
                .m2xv("M2XV")
                .m3a("AIRCRAFT_ID")
                .m3ag(true)
                .m3av("M3AV")
                .m3axv("M3AXV")
                .m4("ID_FRIEND")
                .m4d1d2("STATUS")
                .m4v("M4V")
                .mah("MAH")
                .mc(100.23)
                .mcg(true)
                .mcv("MCV")
                .milemrgcy(false)
                .mrgrpt(true)
                .mscommb("MSCOMMB")
                .mti(true)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .origSensorId("ORIGSENSOR-ID")
                .psrrl(44.23)
                .rad("RAD")
                .rng(100.23)
                .rngdelt(44.23)
                .sac(10)
                .senalt(100.23)
                .senlat(45.23)
                .senlon(45.23)
                .sic(40)
                .spi(true)
                .ssrl(44.23)
                .addTag("TAG1")
                .addTag("TAG2")
                .tgtconf("CONFIDENCE")
                .tgtcorr("CORRELATION")
                .tgtid("TGT-ID")
                .tis(0.4)
                .trkelig("ELIGIBILITY")
                .trknum(30)
                .tti("TTI")
                .addWectc("WARNING")
                .addWectc("WARNING")
                .build()

        val roundtrippedMonoradarListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(monoradarListResponse),
                jacksonTypeRef<MonoradarListResponse>(),
            )

        assertThat(roundtrippedMonoradarListResponse).isEqualTo(monoradarListResponse)
    }
}
