// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.missionassignment

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class MissionAssignmentUpdateParamsTest {

    @Test
    fun create() {
        MissionAssignmentUpdateParams.builder()
            .pathId("id")
            .classificationMarking("U")
            .dataMode(MissionAssignmentUpdateParams.DataMode.TEST)
            .mad("MAD")
            .source("Bluestaq")
            .ts(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
            .bodyId("MISSIONASSIGNMENT-ID")
            .c1associateddmpis(3)
            .c2air("C2AIR")
            .c2alt(3)
            .c2crs(3)
            .c2exerciseindicator("C2EXERCISE")
            .c2exercisemof("MOF")
            .c2id("C2ID")
            .c2idamplifyingdescriptor("C2IDAMP")
            .c2lnd("C2LND")
            .c2spc("C2SPC")
            .c2spd(3)
            .c2specialinterestindicator("C2SPECIAL")
            .c2sur("C2SUR")
            .c3elv(10.23)
            .c3lat(10.23)
            .c3lon(10.23)
            .c3ptl("C3PTL")
            .c3ptnum("C3PTNUM")
            .c4colon(5)
            .c4def("C4DEF")
            .c4egress(4)
            .c4mod(5)
            .c4numberofstores(3)
            .c4runin(5)
            .c4tgt("C4TGT")
            .c4timediscrete("C4TIMED")
            .c4tm(4)
            .c4typeofstores(2)
            .c5colon(5)
            .c5elevationlsbs(5)
            .c5haeadj(5)
            .c5latlsb(5)
            .c5lonlsb(5)
            .c5tgtbrng(5)
            .c5tw(5)
            .c6dspc("C6DSPC")
            .c6dspct("C6DSPCT")
            .c6fplpm("C6FPLPM")
            .c6intel(5)
            .c6laser(5)
            .c6longpm("C6LONGPM")
            .c6tnr3(5)
            .c7elang2(5.23)
            .c7in3p(3)
            .c7tnor("C7TNOR")
            .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
            .createdBy("some.user")
            .env("ENV")
            .index(5)
            .lat(45.23)
            .lon(45.23)
            .orginx("ORIGIN")
            .origin("THIRD_PARTY_DATASOURCE")
            .origNetwork("OPS1")
            .rc("RC-123")
            .rr(2)
            .sz("STRENGTH")
            .tno("TRACK_NUMBER")
            .trkId("TRK-ID")
            .twenv("THREAT_WARNING")
            .build()
    }

    @Test
    fun pathParams() {
        val params =
            MissionAssignmentUpdateParams.builder()
                .pathId("id")
                .classificationMarking("U")
                .dataMode(MissionAssignmentUpdateParams.DataMode.TEST)
                .mad("MAD")
                .source("Bluestaq")
                .ts(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .build()

        assertThat(params._pathParam(0)).isEqualTo("id")
        // out-of-bound path param
        assertThat(params._pathParam(1)).isEqualTo("")
    }

    @Test
    fun body() {
        val params =
            MissionAssignmentUpdateParams.builder()
                .pathId("id")
                .classificationMarking("U")
                .dataMode(MissionAssignmentUpdateParams.DataMode.TEST)
                .mad("MAD")
                .source("Bluestaq")
                .ts(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .bodyId("MISSIONASSIGNMENT-ID")
                .c1associateddmpis(3)
                .c2air("C2AIR")
                .c2alt(3)
                .c2crs(3)
                .c2exerciseindicator("C2EXERCISE")
                .c2exercisemof("MOF")
                .c2id("C2ID")
                .c2idamplifyingdescriptor("C2IDAMP")
                .c2lnd("C2LND")
                .c2spc("C2SPC")
                .c2spd(3)
                .c2specialinterestindicator("C2SPECIAL")
                .c2sur("C2SUR")
                .c3elv(10.23)
                .c3lat(10.23)
                .c3lon(10.23)
                .c3ptl("C3PTL")
                .c3ptnum("C3PTNUM")
                .c4colon(5)
                .c4def("C4DEF")
                .c4egress(4)
                .c4mod(5)
                .c4numberofstores(3)
                .c4runin(5)
                .c4tgt("C4TGT")
                .c4timediscrete("C4TIMED")
                .c4tm(4)
                .c4typeofstores(2)
                .c5colon(5)
                .c5elevationlsbs(5)
                .c5haeadj(5)
                .c5latlsb(5)
                .c5lonlsb(5)
                .c5tgtbrng(5)
                .c5tw(5)
                .c6dspc("C6DSPC")
                .c6dspct("C6DSPCT")
                .c6fplpm("C6FPLPM")
                .c6intel(5)
                .c6laser(5)
                .c6longpm("C6LONGPM")
                .c6tnr3(5)
                .c7elang2(5.23)
                .c7in3p(3)
                .c7tnor("C7TNOR")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .env("ENV")
                .index(5)
                .lat(45.23)
                .lon(45.23)
                .orginx("ORIGIN")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .rc("RC-123")
                .rr(2)
                .sz("STRENGTH")
                .tno("TRACK_NUMBER")
                .trkId("TRK-ID")
                .twenv("THREAT_WARNING")
                .build()

        val body = params._body()

        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(MissionAssignmentUpdateParams.DataMode.TEST)
        assertThat(body.mad()).isEqualTo("MAD")
        assertThat(body.source()).isEqualTo("Bluestaq")
        assertThat(body.ts()).isEqualTo(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
        assertThat(body.bodyId()).contains("MISSIONASSIGNMENT-ID")
        assertThat(body.c1associateddmpis()).contains(3)
        assertThat(body.c2air()).contains("C2AIR")
        assertThat(body.c2alt()).contains(3)
        assertThat(body.c2crs()).contains(3)
        assertThat(body.c2exerciseindicator()).contains("C2EXERCISE")
        assertThat(body.c2exercisemof()).contains("MOF")
        assertThat(body.c2id()).contains("C2ID")
        assertThat(body.c2idamplifyingdescriptor()).contains("C2IDAMP")
        assertThat(body.c2lnd()).contains("C2LND")
        assertThat(body.c2spc()).contains("C2SPC")
        assertThat(body.c2spd()).contains(3)
        assertThat(body.c2specialinterestindicator()).contains("C2SPECIAL")
        assertThat(body.c2sur()).contains("C2SUR")
        assertThat(body.c3elv()).contains(10.23)
        assertThat(body.c3lat()).contains(10.23)
        assertThat(body.c3lon()).contains(10.23)
        assertThat(body.c3ptl()).contains("C3PTL")
        assertThat(body.c3ptnum()).contains("C3PTNUM")
        assertThat(body.c4colon()).contains(5)
        assertThat(body.c4def()).contains("C4DEF")
        assertThat(body.c4egress()).contains(4)
        assertThat(body.c4mod()).contains(5)
        assertThat(body.c4numberofstores()).contains(3)
        assertThat(body.c4runin()).contains(5)
        assertThat(body.c4tgt()).contains("C4TGT")
        assertThat(body.c4timediscrete()).contains("C4TIMED")
        assertThat(body.c4tm()).contains(4)
        assertThat(body.c4typeofstores()).contains(2)
        assertThat(body.c5colon()).contains(5)
        assertThat(body.c5elevationlsbs()).contains(5)
        assertThat(body.c5haeadj()).contains(5)
        assertThat(body.c5latlsb()).contains(5)
        assertThat(body.c5lonlsb()).contains(5)
        assertThat(body.c5tgtbrng()).contains(5)
        assertThat(body.c5tw()).contains(5)
        assertThat(body.c6dspc()).contains("C6DSPC")
        assertThat(body.c6dspct()).contains("C6DSPCT")
        assertThat(body.c6fplpm()).contains("C6FPLPM")
        assertThat(body.c6intel()).contains(5)
        assertThat(body.c6laser()).contains(5)
        assertThat(body.c6longpm()).contains("C6LONGPM")
        assertThat(body.c6tnr3()).contains(5)
        assertThat(body.c7elang2()).contains(5.23)
        assertThat(body.c7in3p()).contains(3)
        assertThat(body.c7tnor()).contains("C7TNOR")
        assertThat(body.createdAt()).contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(body.createdBy()).contains("some.user")
        assertThat(body.env()).contains("ENV")
        assertThat(body.index()).contains(5)
        assertThat(body.lat()).contains(45.23)
        assertThat(body.lon()).contains(45.23)
        assertThat(body.orginx()).contains("ORIGIN")
        assertThat(body.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(body.origNetwork()).contains("OPS1")
        assertThat(body.rc()).contains("RC-123")
        assertThat(body.rr()).contains(2)
        assertThat(body.sz()).contains("STRENGTH")
        assertThat(body.tno()).contains("TRACK_NUMBER")
        assertThat(body.trkId()).contains("TRK-ID")
        assertThat(body.twenv()).contains("THREAT_WARNING")
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            MissionAssignmentUpdateParams.builder()
                .pathId("id")
                .classificationMarking("U")
                .dataMode(MissionAssignmentUpdateParams.DataMode.TEST)
                .mad("MAD")
                .source("Bluestaq")
                .ts(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .build()

        val body = params._body()

        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(MissionAssignmentUpdateParams.DataMode.TEST)
        assertThat(body.mad()).isEqualTo("MAD")
        assertThat(body.source()).isEqualTo("Bluestaq")
        assertThat(body.ts()).isEqualTo(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
    }
}
