// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.track

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TrackListResponseTest {

    @Test
    fun create() {
        val trackListResponse =
            TrackListResponse.builder()
                .classificationMarking("U")
                .dataMode(TrackListResponse.DataMode.TEST)
                .source("Bluestaq")
                .ts(OffsetDateTime.parse("2021-06-07T14:17:39.653043Z"))
                .id("TRACK-ID")
                .alt(2024.15)
                .asset("asset")
                .assetNat("US")
                .attitude(listOf(10.1, 0.1, 1.1))
                .attitudeRate(listOf(0.0003, 1e-7, 0.00003))
                .callSign("callSign")
                .cntct("Contact Info")
                .contextKeys(listOf("MsnID_DescLabel", "msnVer", "serVer", "velTs", "accelTs"))
                .contextValues(
                    listOf(
                        "MissionID Descriptive Label text",
                        "1",
                        "001.9b",
                        "2024-06-07T14:17:39.234Z",
                        "2024-06-07T14:17:39.123Z",
                    )
                )
                .course(215.2)
                .cov(listOf(1.1, 2.2, 3.3))
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .ecefAcc(listOf(-0.0265, -0.2764, -0.1773))
                .ecefPos(listOf(-1273011.47, -48108810.77, 3979360.49))
                .ecefVel(listOf(25.635, -1.097, 57.373))
                .eNuAcc(listOf(0.0003, 0.014, 0.0003))
                .eNuGroundVel(listOf(1.23, 2.34, 3.45))
                .eNuPos(listOf(1.23, 2.34, 3.45))
                .eNuVel(listOf(1.23, 2.34, 3.45))
                .env("LAND")
                .envConf(1.23)
                .errEllp(listOf(1.23, 2.34, 3.45))
                .hdng(215.7)
                .identAmp("ZOMBIE")
                .identCred(0)
                .identRel(0)
                .jSeries("J12.5")
                .lat(38.8353)
                .lcAcc(listOf(1.23, 2.34, 3.45))
                .lco(listOf(1.23, 2.34, 3.45))
                .lcPos(listOf(1.23, 2.34, 3.45))
                .lcs(listOf(1.23, 2.34, 3.45))
                .lcVel(listOf(1.23, 2.34, 3.45))
                .lon(-104.8216)
                .m1(11)
                .m1v(1)
                .m2(1234)
                .m2v(1)
                .m3a(2636)
                .m3av(1)
                .modType("MASINT")
                .msgTs(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .msnId("msnId")
                .multiSource(true)
                .objAct("HOLDING")
                .objDescription("Object description text.")
                .objId("objId")
                .objIdent("FRIEND")
                .objNat("NATO")
                .objPlat("COMBAT_VEHICLE")
                .objSpec("LIGHT_TANK")
                .objType("WATERCRAFT")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .sen("sen")
                .senQual("senQual")
                .sourceDl("AXE")
                .spd(62.9921)
                .addSrcId("f7c70cc8-f9b7-4467-b4ad-3904e360e842")
                .addSrcId("1da3fab000014e3133709830937387405")
                .addSrcTyp("MTI")
                .addSrcTyp("POI")
                .strength(14)
                .addTag("TAG1")
                .addTag("TAG2")
                .trkConf(0.67)
                .trkId("trkId")
                .trkItmId("38f3a71f-4bba-4d58-9765-c1b93212aff1")
                .trkNum("trkNum")
                .trkPtType("MEASURED")
                .trkQual(0)
                .trkStat("INITIATING")
                .vertUnc(4.56)
                .wanderAng(1.23)
                .build()

        assertThat(trackListResponse.classificationMarking()).isEqualTo("U")
        assertThat(trackListResponse.dataMode()).isEqualTo(TrackListResponse.DataMode.TEST)
        assertThat(trackListResponse.source()).isEqualTo("Bluestaq")
        assertThat(trackListResponse.ts())
            .isEqualTo(OffsetDateTime.parse("2021-06-07T14:17:39.653043Z"))
        assertThat(trackListResponse.id()).contains("TRACK-ID")
        assertThat(trackListResponse.alt()).contains(2024.15)
        assertThat(trackListResponse.asset()).contains("asset")
        assertThat(trackListResponse.assetNat()).contains("US")
        assertThat(trackListResponse.attitude().getOrNull()).containsExactly(10.1, 0.1, 1.1)
        assertThat(trackListResponse.attitudeRate().getOrNull())
            .containsExactly(0.0003, 1e-7, 0.00003)
        assertThat(trackListResponse.callSign()).contains("callSign")
        assertThat(trackListResponse.cntct()).contains("Contact Info")
        assertThat(trackListResponse.contextKeys().getOrNull())
            .containsExactly("MsnID_DescLabel", "msnVer", "serVer", "velTs", "accelTs")
        assertThat(trackListResponse.contextValues().getOrNull())
            .containsExactly(
                "MissionID Descriptive Label text",
                "1",
                "001.9b",
                "2024-06-07T14:17:39.234Z",
                "2024-06-07T14:17:39.123Z",
            )
        assertThat(trackListResponse.course()).contains(215.2)
        assertThat(trackListResponse.cov().getOrNull()).containsExactly(1.1, 2.2, 3.3)
        assertThat(trackListResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(trackListResponse.createdBy()).contains("some.user")
        assertThat(trackListResponse.ecefAcc().getOrNull())
            .containsExactly(-0.0265, -0.2764, -0.1773)
        assertThat(trackListResponse.ecefPos().getOrNull())
            .containsExactly(-1273011.47, -48108810.77, 3979360.49)
        assertThat(trackListResponse.ecefVel().getOrNull()).containsExactly(25.635, -1.097, 57.373)
        assertThat(trackListResponse.eNuAcc().getOrNull()).containsExactly(0.0003, 0.014, 0.0003)
        assertThat(trackListResponse.eNuGroundVel().getOrNull()).containsExactly(1.23, 2.34, 3.45)
        assertThat(trackListResponse.eNuPos().getOrNull()).containsExactly(1.23, 2.34, 3.45)
        assertThat(trackListResponse.eNuVel().getOrNull()).containsExactly(1.23, 2.34, 3.45)
        assertThat(trackListResponse.env()).contains("LAND")
        assertThat(trackListResponse.envConf()).contains(1.23)
        assertThat(trackListResponse.errEllp().getOrNull()).containsExactly(1.23, 2.34, 3.45)
        assertThat(trackListResponse.hdng()).contains(215.7)
        assertThat(trackListResponse.identAmp()).contains("ZOMBIE")
        assertThat(trackListResponse.identCred()).contains(0)
        assertThat(trackListResponse.identRel()).contains(0)
        assertThat(trackListResponse.jSeries()).contains("J12.5")
        assertThat(trackListResponse.lat()).contains(38.8353)
        assertThat(trackListResponse.lcAcc().getOrNull()).containsExactly(1.23, 2.34, 3.45)
        assertThat(trackListResponse.lco().getOrNull()).containsExactly(1.23, 2.34, 3.45)
        assertThat(trackListResponse.lcPos().getOrNull()).containsExactly(1.23, 2.34, 3.45)
        assertThat(trackListResponse.lcs().getOrNull()).containsExactly(1.23, 2.34, 3.45)
        assertThat(trackListResponse.lcVel().getOrNull()).containsExactly(1.23, 2.34, 3.45)
        assertThat(trackListResponse.lon()).contains(-104.8216)
        assertThat(trackListResponse.m1()).contains(11)
        assertThat(trackListResponse.m1v()).contains(1)
        assertThat(trackListResponse.m2()).contains(1234)
        assertThat(trackListResponse.m2v()).contains(1)
        assertThat(trackListResponse.m3a()).contains(2636)
        assertThat(trackListResponse.m3av()).contains(1)
        assertThat(trackListResponse.modType()).contains("MASINT")
        assertThat(trackListResponse.msgTs())
            .contains(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
        assertThat(trackListResponse.msnId()).contains("msnId")
        assertThat(trackListResponse.multiSource()).contains(true)
        assertThat(trackListResponse.objAct()).contains("HOLDING")
        assertThat(trackListResponse.objDescription()).contains("Object description text.")
        assertThat(trackListResponse.objId()).contains("objId")
        assertThat(trackListResponse.objIdent()).contains("FRIEND")
        assertThat(trackListResponse.objNat()).contains("NATO")
        assertThat(trackListResponse.objPlat()).contains("COMBAT_VEHICLE")
        assertThat(trackListResponse.objSpec()).contains("LIGHT_TANK")
        assertThat(trackListResponse.objType()).contains("WATERCRAFT")
        assertThat(trackListResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(trackListResponse.origNetwork()).contains("OPS1")
        assertThat(trackListResponse.sen()).contains("sen")
        assertThat(trackListResponse.senQual()).contains("senQual")
        assertThat(trackListResponse.sourceDl()).contains("AXE")
        assertThat(trackListResponse.spd()).contains(62.9921)
        assertThat(trackListResponse.srcIds().getOrNull())
            .containsExactly(
                "f7c70cc8-f9b7-4467-b4ad-3904e360e842",
                "1da3fab000014e3133709830937387405",
            )
        assertThat(trackListResponse.srcTyps().getOrNull()).containsExactly("MTI", "POI")
        assertThat(trackListResponse.strength()).contains(14)
        assertThat(trackListResponse.tags().getOrNull()).containsExactly("TAG1", "TAG2")
        assertThat(trackListResponse.trkConf()).contains(0.67)
        assertThat(trackListResponse.trkId()).contains("trkId")
        assertThat(trackListResponse.trkItmId()).contains("38f3a71f-4bba-4d58-9765-c1b93212aff1")
        assertThat(trackListResponse.trkNum()).contains("trkNum")
        assertThat(trackListResponse.trkPtType()).contains("MEASURED")
        assertThat(trackListResponse.trkQual()).contains(0)
        assertThat(trackListResponse.trkStat()).contains("INITIATING")
        assertThat(trackListResponse.vertUnc()).contains(4.56)
        assertThat(trackListResponse.wanderAng()).contains(1.23)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val trackListResponse =
            TrackListResponse.builder()
                .classificationMarking("U")
                .dataMode(TrackListResponse.DataMode.TEST)
                .source("Bluestaq")
                .ts(OffsetDateTime.parse("2021-06-07T14:17:39.653043Z"))
                .id("TRACK-ID")
                .alt(2024.15)
                .asset("asset")
                .assetNat("US")
                .attitude(listOf(10.1, 0.1, 1.1))
                .attitudeRate(listOf(0.0003, 1e-7, 0.00003))
                .callSign("callSign")
                .cntct("Contact Info")
                .contextKeys(listOf("MsnID_DescLabel", "msnVer", "serVer", "velTs", "accelTs"))
                .contextValues(
                    listOf(
                        "MissionID Descriptive Label text",
                        "1",
                        "001.9b",
                        "2024-06-07T14:17:39.234Z",
                        "2024-06-07T14:17:39.123Z",
                    )
                )
                .course(215.2)
                .cov(listOf(1.1, 2.2, 3.3))
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .ecefAcc(listOf(-0.0265, -0.2764, -0.1773))
                .ecefPos(listOf(-1273011.47, -48108810.77, 3979360.49))
                .ecefVel(listOf(25.635, -1.097, 57.373))
                .eNuAcc(listOf(0.0003, 0.014, 0.0003))
                .eNuGroundVel(listOf(1.23, 2.34, 3.45))
                .eNuPos(listOf(1.23, 2.34, 3.45))
                .eNuVel(listOf(1.23, 2.34, 3.45))
                .env("LAND")
                .envConf(1.23)
                .errEllp(listOf(1.23, 2.34, 3.45))
                .hdng(215.7)
                .identAmp("ZOMBIE")
                .identCred(0)
                .identRel(0)
                .jSeries("J12.5")
                .lat(38.8353)
                .lcAcc(listOf(1.23, 2.34, 3.45))
                .lco(listOf(1.23, 2.34, 3.45))
                .lcPos(listOf(1.23, 2.34, 3.45))
                .lcs(listOf(1.23, 2.34, 3.45))
                .lcVel(listOf(1.23, 2.34, 3.45))
                .lon(-104.8216)
                .m1(11)
                .m1v(1)
                .m2(1234)
                .m2v(1)
                .m3a(2636)
                .m3av(1)
                .modType("MASINT")
                .msgTs(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                .msnId("msnId")
                .multiSource(true)
                .objAct("HOLDING")
                .objDescription("Object description text.")
                .objId("objId")
                .objIdent("FRIEND")
                .objNat("NATO")
                .objPlat("COMBAT_VEHICLE")
                .objSpec("LIGHT_TANK")
                .objType("WATERCRAFT")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .sen("sen")
                .senQual("senQual")
                .sourceDl("AXE")
                .spd(62.9921)
                .addSrcId("f7c70cc8-f9b7-4467-b4ad-3904e360e842")
                .addSrcId("1da3fab000014e3133709830937387405")
                .addSrcTyp("MTI")
                .addSrcTyp("POI")
                .strength(14)
                .addTag("TAG1")
                .addTag("TAG2")
                .trkConf(0.67)
                .trkId("trkId")
                .trkItmId("38f3a71f-4bba-4d58-9765-c1b93212aff1")
                .trkNum("trkNum")
                .trkPtType("MEASURED")
                .trkQual(0)
                .trkStat("INITIATING")
                .vertUnc(4.56)
                .wanderAng(1.23)
                .build()

        val roundtrippedTrackListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(trackListResponse),
                jacksonTypeRef<TrackListResponse>(),
            )

        assertThat(roundtrippedTrackListResponse).isEqualTo(trackListResponse)
    }
}
