// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.aircraftstatuses

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AircraftstatusAbridgedTest {

    @Test
    fun create() {
        val aircraftstatusAbridged =
            AircraftstatusAbridged.builder()
                .classificationMarking("U")
                .dataMode(AircraftstatusAbridged.DataMode.TEST)
                .idAircraft("29232269-e4c2-45c9-aa21-039a33209340")
                .source("Bluestaq")
                .id("0167f577-e06c-358e-85aa-0a07a730bdd0")
                .additionalSys(listOf("ATOMS", "TUDL", "BLOS1"))
                .airToAirStatus(AircraftstatusAbridged.AirToAirStatus.OPERATIONAL)
                .airToGroundStatus(AircraftstatusAbridged.AirToGroundStatus.OPERATIONAL)
                .alphaStatusCode("A2")
                .altAircraftId("ORIG-AIRCRAFT-ID")
                .contaminationStatus("CLEAR")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .currentIcao("KCHS")
                .currentState("AVAILABLE")
                .earliestTaEndTime(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .etic(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .flightPhase("Landing")
                .fuel(10)
                .fuelFunction("Burn")
                .fuelStatus("DELIVERED")
                .geoLoc("AJJY")
                .groundStatus("ALERT")
                .gunCapable(true)
                .gunRdsMax(550)
                .gunRdsMin(150)
                .gunRdsType("7.62 MM")
                .idAirfield("b89430e3-97d9-408c-9c89-fd3840c4b84d")
                .idPoi("0e52f081-a2e3-4b73-b822-88b882232691")
                .addInventory("AIM-9 SIDEWINDER")
                .addInventory("AIM-120 AMRAAM")
                .addInventoryMax(2)
                .addInventoryMax(2)
                .addInventoryMin(1)
                .addInventoryMin(2)
                .lastInspectionDate(OffsetDateTime.parse("2024-09-09T16:00:00.123Z"))
                .lastUpdatedBy("some.user")
                .maintPoc("PSUP NIGHT SHIFT 800-555-4412")
                .maintPriority("1")
                .maintStatus("maintenance status")
                .maintStatusDriver("SCREW STUCK IN LEFT NLG TIRE")
                .maintStatusUpdate(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .missionReadiness("ABLE")
                .mxRemark("COM2 INOP")
                .nextIcao("PHNL")
                .notes("Some notes for aircraft A")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .parkLocation("B1")
                .parkLocationSystem("GDSS")
                .previousIcao("EGLL")
                .sourceDl("AXE")
                .taStartTime(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .troubleshootEtic(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .addUnavailableSy("CMDS")
                .addUnavailableSy("AOC")
                .build()

        assertThat(aircraftstatusAbridged.classificationMarking()).isEqualTo("U")
        assertThat(aircraftstatusAbridged.dataMode())
            .isEqualTo(AircraftstatusAbridged.DataMode.TEST)
        assertThat(aircraftstatusAbridged.idAircraft())
            .isEqualTo("29232269-e4c2-45c9-aa21-039a33209340")
        assertThat(aircraftstatusAbridged.source()).isEqualTo("Bluestaq")
        assertThat(aircraftstatusAbridged.id()).contains("0167f577-e06c-358e-85aa-0a07a730bdd0")
        assertThat(aircraftstatusAbridged.additionalSys().getOrNull())
            .containsExactly("ATOMS", "TUDL", "BLOS1")
        assertThat(aircraftstatusAbridged.airToAirStatus())
            .contains(AircraftstatusAbridged.AirToAirStatus.OPERATIONAL)
        assertThat(aircraftstatusAbridged.airToGroundStatus())
            .contains(AircraftstatusAbridged.AirToGroundStatus.OPERATIONAL)
        assertThat(aircraftstatusAbridged.alphaStatusCode()).contains("A2")
        assertThat(aircraftstatusAbridged.altAircraftId()).contains("ORIG-AIRCRAFT-ID")
        assertThat(aircraftstatusAbridged.contaminationStatus()).contains("CLEAR")
        assertThat(aircraftstatusAbridged.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(aircraftstatusAbridged.createdBy()).contains("some.user")
        assertThat(aircraftstatusAbridged.currentIcao()).contains("KCHS")
        assertThat(aircraftstatusAbridged.currentState()).contains("AVAILABLE")
        assertThat(aircraftstatusAbridged.earliestTaEndTime())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(aircraftstatusAbridged.etic())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(aircraftstatusAbridged.flightPhase()).contains("Landing")
        assertThat(aircraftstatusAbridged.fuel()).contains(10)
        assertThat(aircraftstatusAbridged.fuelFunction()).contains("Burn")
        assertThat(aircraftstatusAbridged.fuelStatus()).contains("DELIVERED")
        assertThat(aircraftstatusAbridged.geoLoc()).contains("AJJY")
        assertThat(aircraftstatusAbridged.groundStatus()).contains("ALERT")
        assertThat(aircraftstatusAbridged.gunCapable()).contains(true)
        assertThat(aircraftstatusAbridged.gunRdsMax()).contains(550)
        assertThat(aircraftstatusAbridged.gunRdsMin()).contains(150)
        assertThat(aircraftstatusAbridged.gunRdsType()).contains("7.62 MM")
        assertThat(aircraftstatusAbridged.idAirfield())
            .contains("b89430e3-97d9-408c-9c89-fd3840c4b84d")
        assertThat(aircraftstatusAbridged.idPoi()).contains("0e52f081-a2e3-4b73-b822-88b882232691")
        assertThat(aircraftstatusAbridged.inventory().getOrNull())
            .containsExactly("AIM-9 SIDEWINDER", "AIM-120 AMRAAM")
        assertThat(aircraftstatusAbridged.inventoryMax().getOrNull()).containsExactly(2, 2)
        assertThat(aircraftstatusAbridged.inventoryMin().getOrNull()).containsExactly(1, 2)
        assertThat(aircraftstatusAbridged.lastInspectionDate())
            .contains(OffsetDateTime.parse("2024-09-09T16:00:00.123Z"))
        assertThat(aircraftstatusAbridged.lastUpdatedBy()).contains("some.user")
        assertThat(aircraftstatusAbridged.maintPoc()).contains("PSUP NIGHT SHIFT 800-555-4412")
        assertThat(aircraftstatusAbridged.maintPriority()).contains("1")
        assertThat(aircraftstatusAbridged.maintStatus()).contains("maintenance status")
        assertThat(aircraftstatusAbridged.maintStatusDriver())
            .contains("SCREW STUCK IN LEFT NLG TIRE")
        assertThat(aircraftstatusAbridged.maintStatusUpdate())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(aircraftstatusAbridged.missionReadiness()).contains("ABLE")
        assertThat(aircraftstatusAbridged.mxRemark()).contains("COM2 INOP")
        assertThat(aircraftstatusAbridged.nextIcao()).contains("PHNL")
        assertThat(aircraftstatusAbridged.notes()).contains("Some notes for aircraft A")
        assertThat(aircraftstatusAbridged.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(aircraftstatusAbridged.origNetwork()).contains("OPS1")
        assertThat(aircraftstatusAbridged.parkLocation()).contains("B1")
        assertThat(aircraftstatusAbridged.parkLocationSystem()).contains("GDSS")
        assertThat(aircraftstatusAbridged.previousIcao()).contains("EGLL")
        assertThat(aircraftstatusAbridged.sourceDl()).contains("AXE")
        assertThat(aircraftstatusAbridged.taStartTime())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(aircraftstatusAbridged.troubleshootEtic())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(aircraftstatusAbridged.unavailableSys().getOrNull())
            .containsExactly("CMDS", "AOC")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val aircraftstatusAbridged =
            AircraftstatusAbridged.builder()
                .classificationMarking("U")
                .dataMode(AircraftstatusAbridged.DataMode.TEST)
                .idAircraft("29232269-e4c2-45c9-aa21-039a33209340")
                .source("Bluestaq")
                .id("0167f577-e06c-358e-85aa-0a07a730bdd0")
                .additionalSys(listOf("ATOMS", "TUDL", "BLOS1"))
                .airToAirStatus(AircraftstatusAbridged.AirToAirStatus.OPERATIONAL)
                .airToGroundStatus(AircraftstatusAbridged.AirToGroundStatus.OPERATIONAL)
                .alphaStatusCode("A2")
                .altAircraftId("ORIG-AIRCRAFT-ID")
                .contaminationStatus("CLEAR")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .currentIcao("KCHS")
                .currentState("AVAILABLE")
                .earliestTaEndTime(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .etic(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .flightPhase("Landing")
                .fuel(10)
                .fuelFunction("Burn")
                .fuelStatus("DELIVERED")
                .geoLoc("AJJY")
                .groundStatus("ALERT")
                .gunCapable(true)
                .gunRdsMax(550)
                .gunRdsMin(150)
                .gunRdsType("7.62 MM")
                .idAirfield("b89430e3-97d9-408c-9c89-fd3840c4b84d")
                .idPoi("0e52f081-a2e3-4b73-b822-88b882232691")
                .addInventory("AIM-9 SIDEWINDER")
                .addInventory("AIM-120 AMRAAM")
                .addInventoryMax(2)
                .addInventoryMax(2)
                .addInventoryMin(1)
                .addInventoryMin(2)
                .lastInspectionDate(OffsetDateTime.parse("2024-09-09T16:00:00.123Z"))
                .lastUpdatedBy("some.user")
                .maintPoc("PSUP NIGHT SHIFT 800-555-4412")
                .maintPriority("1")
                .maintStatus("maintenance status")
                .maintStatusDriver("SCREW STUCK IN LEFT NLG TIRE")
                .maintStatusUpdate(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .missionReadiness("ABLE")
                .mxRemark("COM2 INOP")
                .nextIcao("PHNL")
                .notes("Some notes for aircraft A")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .parkLocation("B1")
                .parkLocationSystem("GDSS")
                .previousIcao("EGLL")
                .sourceDl("AXE")
                .taStartTime(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .troubleshootEtic(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .addUnavailableSy("CMDS")
                .addUnavailableSy("AOC")
                .build()

        val roundtrippedAircraftstatusAbridged =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(aircraftstatusAbridged),
                jacksonTypeRef<AircraftstatusAbridged>(),
            )

        assertThat(roundtrippedAircraftstatusAbridged).isEqualTo(aircraftstatusAbridged)
    }
}
