// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.hazard

import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class HazardCreateParamsTest {

    @Test
    fun create() {
        HazardCreateParams.builder()
            .addAlarm("Alarm1")
            .addAlarm("Alarm2")
            .addAlarmValue(2.7)
            .addAlarmValue(2.9)
            .classificationMarking("U")
            .dataMode(HazardCreateParams.DataMode.TEST)
            .detectTime(OffsetDateTime.parse("2022-03-07T14:51:39.653Z"))
            .detectType("Chemical")
            .source("Bluestaq")
            .id("HAZARD-ID")
            .a(238)
            .activity(120.1)
            .bottleId("6264")
            .casRn("64-17-5")
            .channel("Skin")
            .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
            .createdBy("some.user")
            .ctrnTime(1.077)
            .density(18900.2)
            .dep(1.084)
            .depCtrn(86.1)
            .dose(1.12)
            .doseRate(1.0000001865)
            .duration(14400)
            .gBar(2.5)
            .harmful(false)
            .hBar(3.1)
            .idPoi("POI-ID")
            .idTrack("TRACK-ID")
            .massFrac(0.029)
            .matCat(3)
            .matClass("Nerve Agent")
            .matName("VX")
            .matType("21")
            .origin("THIRD_PARTY_DATASOURCE")
            .origNetwork("ORIG")
            .ppm(27129)
            .radCtrn(1.31)
            .addReading("Rad1")
            .addReading("Rad2")
            .addReadingUnit("Gray")
            .addReadingUnit("Gray")
            .addReadingValue(107.2)
            .addReadingValue(124.1)
            .z(92)
            .build()
    }

    @Test
    fun body() {
        val params =
            HazardCreateParams.builder()
                .addAlarm("Alarm1")
                .addAlarm("Alarm2")
                .addAlarmValue(2.7)
                .addAlarmValue(2.9)
                .classificationMarking("U")
                .dataMode(HazardCreateParams.DataMode.TEST)
                .detectTime(OffsetDateTime.parse("2022-03-07T14:51:39.653Z"))
                .detectType("Chemical")
                .source("Bluestaq")
                .id("HAZARD-ID")
                .a(238)
                .activity(120.1)
                .bottleId("6264")
                .casRn("64-17-5")
                .channel("Skin")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .ctrnTime(1.077)
                .density(18900.2)
                .dep(1.084)
                .depCtrn(86.1)
                .dose(1.12)
                .doseRate(1.0000001865)
                .duration(14400)
                .gBar(2.5)
                .harmful(false)
                .hBar(3.1)
                .idPoi("POI-ID")
                .idTrack("TRACK-ID")
                .massFrac(0.029)
                .matCat(3)
                .matClass("Nerve Agent")
                .matName("VX")
                .matType("21")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("ORIG")
                .ppm(27129)
                .radCtrn(1.31)
                .addReading("Rad1")
                .addReading("Rad2")
                .addReadingUnit("Gray")
                .addReadingUnit("Gray")
                .addReadingValue(107.2)
                .addReadingValue(124.1)
                .z(92)
                .build()

        val body = params._body()

        assertThat(body.alarms()).containsExactly("Alarm1", "Alarm2")
        assertThat(body.alarmValues()).containsExactly(2.7, 2.9)
        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(HazardCreateParams.DataMode.TEST)
        assertThat(body.detectTime()).isEqualTo(OffsetDateTime.parse("2022-03-07T14:51:39.653Z"))
        assertThat(body.detectType()).isEqualTo("Chemical")
        assertThat(body.source()).isEqualTo("Bluestaq")
        assertThat(body.id()).contains("HAZARD-ID")
        assertThat(body.a()).contains(238)
        assertThat(body.activity()).contains(120.1)
        assertThat(body.bottleId()).contains("6264")
        assertThat(body.casRn()).contains("64-17-5")
        assertThat(body.channel()).contains("Skin")
        assertThat(body.createdAt()).contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(body.createdBy()).contains("some.user")
        assertThat(body.ctrnTime()).contains(1.077)
        assertThat(body.density()).contains(18900.2)
        assertThat(body.dep()).contains(1.084)
        assertThat(body.depCtrn()).contains(86.1)
        assertThat(body.dose()).contains(1.12)
        assertThat(body.doseRate()).contains(1.0000001865)
        assertThat(body.duration()).contains(14400)
        assertThat(body.gBar()).contains(2.5)
        assertThat(body.harmful()).contains(false)
        assertThat(body.hBar()).contains(3.1)
        assertThat(body.idPoi()).contains("POI-ID")
        assertThat(body.idTrack()).contains("TRACK-ID")
        assertThat(body.massFrac()).contains(0.029)
        assertThat(body.matCat()).contains(3)
        assertThat(body.matClass()).contains("Nerve Agent")
        assertThat(body.matName()).contains("VX")
        assertThat(body.matType()).contains("21")
        assertThat(body.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(body.origNetwork()).contains("ORIG")
        assertThat(body.ppm()).contains(27129)
        assertThat(body.radCtrn()).contains(1.31)
        assertThat(body.readings().getOrNull()).containsExactly("Rad1", "Rad2")
        assertThat(body.readingUnits().getOrNull()).containsExactly("Gray", "Gray")
        assertThat(body.readingValues().getOrNull()).containsExactly(107.2, 124.1)
        assertThat(body.z()).contains(92)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            HazardCreateParams.builder()
                .addAlarm("Alarm1")
                .addAlarm("Alarm2")
                .addAlarmValue(2.7)
                .addAlarmValue(2.9)
                .classificationMarking("U")
                .dataMode(HazardCreateParams.DataMode.TEST)
                .detectTime(OffsetDateTime.parse("2022-03-07T14:51:39.653Z"))
                .detectType("Chemical")
                .source("Bluestaq")
                .build()

        val body = params._body()

        assertThat(body.alarms()).containsExactly("Alarm1", "Alarm2")
        assertThat(body.alarmValues()).containsExactly(2.7, 2.9)
        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(HazardCreateParams.DataMode.TEST)
        assertThat(body.detectTime()).isEqualTo(OffsetDateTime.parse("2022-03-07T14:51:39.653Z"))
        assertThat(body.detectType()).isEqualTo("Chemical")
        assertThat(body.source()).isEqualTo("Bluestaq")
    }
}
