// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.hazard

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class HazardGetResponseTest {

    @Test
    fun create() {
        val hazardGetResponse =
            HazardGetResponse.builder()
                .addAlarm("Alarm1")
                .addAlarm("Alarm2")
                .addAlarmValue(2.7)
                .addAlarmValue(2.9)
                .classificationMarking("U")
                .dataMode(HazardGetResponse.DataMode.TEST)
                .detectTime(OffsetDateTime.parse("2022-03-07T14:51:39.653Z"))
                .detectType("Chemical")
                .source("Bluestaq")
                .id("HAZARD-ID")
                .a(238)
                .activity(120.1)
                .bottleId("6264")
                .casRn("64-17-5")
                .channel("Skin")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .ctrnTime(1.077)
                .density(18900.2)
                .dep(1.084)
                .depCtrn(86.1)
                .dose(1.12)
                .doseRate(1.0000001865)
                .duration(14400)
                .gBar(2.5)
                .harmful(false)
                .hBar(3.1)
                .idPoi("POI-ID")
                .idTrack("TRACK-ID")
                .massFrac(0.029)
                .matCat(3)
                .matClass("Nerve Agent")
                .matName("VX")
                .matType("21")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("ORIG")
                .ppm(27129)
                .radCtrn(1.31)
                .addReading("Rad1")
                .addReading("Rad2")
                .addReadingUnit("Gray")
                .addReadingUnit("Gray")
                .addReadingValue(107.2)
                .addReadingValue(124.1)
                .z(92)
                .build()

        assertThat(hazardGetResponse.alarms()).containsExactly("Alarm1", "Alarm2")
        assertThat(hazardGetResponse.alarmValues()).containsExactly(2.7, 2.9)
        assertThat(hazardGetResponse.classificationMarking()).isEqualTo("U")
        assertThat(hazardGetResponse.dataMode()).isEqualTo(HazardGetResponse.DataMode.TEST)
        assertThat(hazardGetResponse.detectTime())
            .isEqualTo(OffsetDateTime.parse("2022-03-07T14:51:39.653Z"))
        assertThat(hazardGetResponse.detectType()).isEqualTo("Chemical")
        assertThat(hazardGetResponse.source()).isEqualTo("Bluestaq")
        assertThat(hazardGetResponse.id()).contains("HAZARD-ID")
        assertThat(hazardGetResponse.a()).contains(238)
        assertThat(hazardGetResponse.activity()).contains(120.1)
        assertThat(hazardGetResponse.bottleId()).contains("6264")
        assertThat(hazardGetResponse.casRn()).contains("64-17-5")
        assertThat(hazardGetResponse.channel()).contains("Skin")
        assertThat(hazardGetResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(hazardGetResponse.createdBy()).contains("some.user")
        assertThat(hazardGetResponse.ctrnTime()).contains(1.077)
        assertThat(hazardGetResponse.density()).contains(18900.2)
        assertThat(hazardGetResponse.dep()).contains(1.084)
        assertThat(hazardGetResponse.depCtrn()).contains(86.1)
        assertThat(hazardGetResponse.dose()).contains(1.12)
        assertThat(hazardGetResponse.doseRate()).contains(1.0000001865)
        assertThat(hazardGetResponse.duration()).contains(14400)
        assertThat(hazardGetResponse.gBar()).contains(2.5)
        assertThat(hazardGetResponse.harmful()).contains(false)
        assertThat(hazardGetResponse.hBar()).contains(3.1)
        assertThat(hazardGetResponse.idPoi()).contains("POI-ID")
        assertThat(hazardGetResponse.idTrack()).contains("TRACK-ID")
        assertThat(hazardGetResponse.massFrac()).contains(0.029)
        assertThat(hazardGetResponse.matCat()).contains(3)
        assertThat(hazardGetResponse.matClass()).contains("Nerve Agent")
        assertThat(hazardGetResponse.matName()).contains("VX")
        assertThat(hazardGetResponse.matType()).contains("21")
        assertThat(hazardGetResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(hazardGetResponse.origNetwork()).contains("ORIG")
        assertThat(hazardGetResponse.ppm()).contains(27129)
        assertThat(hazardGetResponse.radCtrn()).contains(1.31)
        assertThat(hazardGetResponse.readings().getOrNull()).containsExactly("Rad1", "Rad2")
        assertThat(hazardGetResponse.readingUnits().getOrNull()).containsExactly("Gray", "Gray")
        assertThat(hazardGetResponse.readingValues().getOrNull()).containsExactly(107.2, 124.1)
        assertThat(hazardGetResponse.z()).contains(92)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val hazardGetResponse =
            HazardGetResponse.builder()
                .addAlarm("Alarm1")
                .addAlarm("Alarm2")
                .addAlarmValue(2.7)
                .addAlarmValue(2.9)
                .classificationMarking("U")
                .dataMode(HazardGetResponse.DataMode.TEST)
                .detectTime(OffsetDateTime.parse("2022-03-07T14:51:39.653Z"))
                .detectType("Chemical")
                .source("Bluestaq")
                .id("HAZARD-ID")
                .a(238)
                .activity(120.1)
                .bottleId("6264")
                .casRn("64-17-5")
                .channel("Skin")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .ctrnTime(1.077)
                .density(18900.2)
                .dep(1.084)
                .depCtrn(86.1)
                .dose(1.12)
                .doseRate(1.0000001865)
                .duration(14400)
                .gBar(2.5)
                .harmful(false)
                .hBar(3.1)
                .idPoi("POI-ID")
                .idTrack("TRACK-ID")
                .massFrac(0.029)
                .matCat(3)
                .matClass("Nerve Agent")
                .matName("VX")
                .matType("21")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("ORIG")
                .ppm(27129)
                .radCtrn(1.31)
                .addReading("Rad1")
                .addReading("Rad2")
                .addReadingUnit("Gray")
                .addReadingUnit("Gray")
                .addReadingValue(107.2)
                .addReadingValue(124.1)
                .z(92)
                .build()

        val roundtrippedHazardGetResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(hazardGetResponse),
                jacksonTypeRef<HazardGetResponse>(),
            )

        assertThat(roundtrippedHazardGetResponse).isEqualTo(hazardGetResponse)
    }
}
