// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.services.async

import com.unifieddatalibrary.api.TestServerExtension
import com.unifieddatalibrary.api.client.okhttp.UnifieddatalibraryOkHttpClientAsync
import com.unifieddatalibrary.api.models.conjunctions.ConjunctionCountParams
import com.unifieddatalibrary.api.models.conjunctions.ConjunctionCreateBulkParams
import com.unifieddatalibrary.api.models.conjunctions.ConjunctionCreateUdlParams
import com.unifieddatalibrary.api.models.conjunctions.ConjunctionGetHistoryParams
import com.unifieddatalibrary.api.models.conjunctions.ConjunctionListParams
import com.unifieddatalibrary.api.models.conjunctions.ConjunctionRetrieveParams
import com.unifieddatalibrary.api.models.conjunctions.ConjunctionTupleParams
import com.unifieddatalibrary.api.models.conjunctions.ConjunctionUnvalidatedPublishParams
import com.unifieddatalibrary.api.models.conjunctions.ConjunctionUploadConjunctionDataMessageParams
import java.time.OffsetDateTime
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(TestServerExtension::class)
internal class ConjunctionServiceAsyncTest {

    @Test
    fun retrieve() {
        val client =
            UnifieddatalibraryOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val conjunctionServiceAsync = client.conjunctions()

        val conjunctionFullFuture =
            conjunctionServiceAsync.retrieve(
                ConjunctionRetrieveParams.builder().id("id").firstResult(0L).maxResults(0L).build()
            )

        val conjunctionFull = conjunctionFullFuture.get()
        conjunctionFull.validate()
    }

    @Test
    fun list() {
        val client =
            UnifieddatalibraryOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val conjunctionServiceAsync = client.conjunctions()

        val pageFuture =
            conjunctionServiceAsync.list(
                ConjunctionListParams.builder()
                    .tca(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .build()
            )

        val page = pageFuture.get()
        page.items().forEach { it.validate() }
    }

    @Test
    fun count() {
        val client =
            UnifieddatalibraryOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val conjunctionServiceAsync = client.conjunctions()

        val responseFuture =
            conjunctionServiceAsync.count(
                ConjunctionCountParams.builder()
                    .tca(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .firstResult(0L)
                    .maxResults(0L)
                    .build()
            )

        val response = responseFuture.get()
    }

    @Test
    fun createUdl() {
        val client =
            UnifieddatalibraryOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val conjunctionServiceAsync = client.conjunctions()

        val future =
            conjunctionServiceAsync.createUdl(
                ConjunctionCreateUdlParams.builder()
                    .convertPosVel(true)
                    .classificationMarking("U")
                    .dataMode(ConjunctionCreateUdlParams.DataMode.TEST)
                    .source("Bluestaq")
                    .tca(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                    .id("CONJUNCTION-ID")
                    .ccir("Example notes")
                    .cdAoM1(0.016386)
                    .cdAoM2(0.016386)
                    .collisionProb(0.5)
                    .collisionProbMethod("FOSTER-1992")
                    .comments("Example notes")
                    .concernNotes("Example notes")
                    .crAoM1(0.013814)
                    .crAoM2(0.013814)
                    .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                    .createdBy("some.user")
                    .descriptor("sample_descriptor here")
                    .ephemName1("MEME_SPCFT_ABC_2180000_ops_nomnvr_unclassified.oem")
                    .ephemName2("MEME_SPCFT_DEF_2170000_ops_nomnvr_unclassified.txt")
                    .esId1("a2ae2356-6d83-4e4b-896d-ddd1958800fa")
                    .esId2("6fa31433-8beb-4b9b-8bf9-326dbd041c3f")
                    .eventId("some.user")
                    .idOnOrbit1("ONORBIT1-ID")
                    .idOnOrbit2("ONORBIT2-ID")
                    .idStateVector1("REF-STATEVECTOR1-ID")
                    .idStateVector2("REF-STATEVECTOR2-ID")
                    .largeCovWarning(false)
                    .largeRelPosWarning(false)
                    .lastObTime1(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                    .lastObTime2(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                    .messageFor("Message for space craft A")
                    .messageId("MESSAGE-ID")
                    .missDistance(1.1)
                    .origIdOnOrbit1("ORIGONORBIT1-ID")
                    .origIdOnOrbit2("ORIGONORBIT2-ID")
                    .origin("THIRD_PARTY_DATASOURCE")
                    .originator("some.user")
                    .origNetwork("ORIG")
                    .ownerContacted(false)
                    .penetrationLevelSigma(1.1)
                    .rawFileUri("Example link")
                    .relPosN(1.1)
                    .relPosR(1.1)
                    .relPosT(1.1)
                    .relVelMag(1.1)
                    .relVelN(1.1)
                    .relVelR(1.1)
                    .relVelT(1.1)
                    .satNo1(1)
                    .satNo2(2)
                    .screenEntryTime(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                    .screenExitTime(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                    .screenVolumeX(1.1)
                    .screenVolumeY(1.1)
                    .screenVolumeZ(1.1)
                    .smallCovWarning(false)
                    .smallRelVelWarning(false)
                    .stateDeptNotified(false)
                    .stateVector1(
                        ConjunctionCreateUdlParams.StateVector1.builder()
                            .classificationMarking("U")
                            .dataMode(ConjunctionCreateUdlParams.StateVector1.DataMode.TEST)
                            .epoch(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
                            .source("Bluestaq")
                            .actualOdSpan(3.5)
                            .algorithm("SAMPLE_ALGORITHM")
                            .alt1ReferenceFrame("TEME")
                            .alt2ReferenceFrame("EFG/TDR")
                            .area(5.065)
                            .bDot(1.23)
                            .cmOffset(1.23)
                            .cov(listOf(1.1, 2.4, 3.8, 4.2, 5.5, 6.0))
                            .covMethod("CALCULATED")
                            .covReferenceFrame(
                                ConjunctionCreateUdlParams.StateVector1.CovReferenceFrame.J2000
                            )
                            .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                            .createdBy("some.user")
                            .descriptor("descriptor")
                            .dragArea(4.739)
                            .dragCoeff(0.0224391269775)
                            .dragModel("JAC70")
                            .edr(1.23)
                            .addEqCov(1.1)
                            .addEqCov(2.2)
                            .errorControl(1.23)
                            .fixedStep(true)
                            .geopotentialModel("EGM-96")
                            .iau1980Terms(4)
                            .idOnOrbit("ONORBIT-ID")
                            .idOrbitDetermination("026dd511-8ba5-47d3-9909-836149f87686")
                            .idStateVector("STATEVECTOR-ID")
                            .integratorMode("integratorMode")
                            .inTrackThrust(true)
                            .lastObEnd(OffsetDateTime.parse("2022-11-09T11:20:21.247192Z"))
                            .lastObStart(OffsetDateTime.parse("2022-11-09T11:20:21.247192Z"))
                            .leapSecondTime(OffsetDateTime.parse("2021-01-01T01:01:01.123Z"))
                            .lunarSolar(true)
                            .mass(164.5)
                            .obsAvailable(376)
                            .obsUsed(374)
                            .origin("THIRD_PARTY_DATASOURCE")
                            .origNetwork("ORIG")
                            .origObjectId("ORIGOBJECT-ID")
                            .partials("ANALYTIC")
                            .pedigree("CONJUNCTION")
                            .polarMotionX(1.23)
                            .polarMotionY(1.23)
                            .posUnc(0.333399744452)
                            .rawFileUri("rawFileURI")
                            .recOdSpan(3.5)
                            .referenceFrame(
                                ConjunctionCreateUdlParams.StateVector1.ReferenceFrame.J2000
                            )
                            .residualsAcc(99.5)
                            .revNo(7205)
                            .rms(0.991)
                            .satNo(12)
                            .addSigmaPosUvw(1.23)
                            .addSigmaPosUvw(4.56)
                            .addSigmaVelUvw(1.23)
                            .addSigmaVelUvw(4.56)
                            .solarFluxApAvg(1.23)
                            .solarFluxF10(1.23)
                            .solarFluxF10Avg(1.23)
                            .solarRadPress(true)
                            .solarRadPressCoeff(0.0244394)
                            .solidEarthTides(true)
                            .addSourcedData("DATA1")
                            .addSourcedData("DATA2")
                            .addSourcedDataType(
                                ConjunctionCreateUdlParams.StateVector1.SourcedDataType.RADAR
                            )
                            .sourceDl("AXE")
                            .srpArea(4.311)
                            .stepMode("AUTO")
                            .stepSize(1.23)
                            .stepSizeSelection("AUTO")
                            .addTag("TAG1")
                            .addTag("TAG2")
                            .taiUtc(1.23)
                            .thrustAccel(1.23)
                            .tracksAvail(163)
                            .tracksUsed(163)
                            .transactionId("transactionId")
                            .uct(true)
                            .ut1Rate(1.23)
                            .ut1Utc(1.23)
                            .velUnc(0.000004)
                            .xaccel(-2.12621392)
                            .xpos(-1118.577381)
                            .xposAlt1(-1145.688502)
                            .xposAlt2(-1456.915926)
                            .xvel(-4.25242784)
                            .xvelAlt1(-4.270832252)
                            .xvelAlt2(-1.219814294)
                            .yaccel(2.645553717)
                            .ypos(3026.231084)
                            .yposAlt1(3020.729572)
                            .yposAlt2(-2883.540406)
                            .yvel(5.291107434)
                            .yvelAlt1(5.27074276)
                            .yvelAlt2(-6.602080212)
                            .zaccel(-1.06310696)
                            .zpos(6167.831808)
                            .zposAlt1(6165.55187)
                            .zposAlt2(6165.55187)
                            .zvel(-3.356493869)
                            .zvelAlt1(-3.365155181)
                            .zvelAlt2(-3.365155181)
                            .build()
                    )
                    .stateVector2(
                        ConjunctionCreateUdlParams.StateVector2.builder()
                            .classificationMarking("U")
                            .dataMode(ConjunctionCreateUdlParams.StateVector2.DataMode.TEST)
                            .epoch(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
                            .source("Bluestaq")
                            .actualOdSpan(3.5)
                            .algorithm("SAMPLE_ALGORITHM")
                            .alt1ReferenceFrame("TEME")
                            .alt2ReferenceFrame("EFG/TDR")
                            .area(5.065)
                            .bDot(1.23)
                            .cmOffset(1.23)
                            .cov(listOf(1.1, 2.4, 3.8, 4.2, 5.5, 6.0))
                            .covMethod("CALCULATED")
                            .covReferenceFrame(
                                ConjunctionCreateUdlParams.StateVector2.CovReferenceFrame.J2000
                            )
                            .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                            .createdBy("some.user")
                            .descriptor("descriptor")
                            .dragArea(4.739)
                            .dragCoeff(0.0224391269775)
                            .dragModel("JAC70")
                            .edr(1.23)
                            .addEqCov(1.1)
                            .addEqCov(2.2)
                            .errorControl(1.23)
                            .fixedStep(true)
                            .geopotentialModel("EGM-96")
                            .iau1980Terms(4)
                            .idOnOrbit("ONORBIT-ID")
                            .idOrbitDetermination("026dd511-8ba5-47d3-9909-836149f87686")
                            .idStateVector("STATEVECTOR-ID")
                            .integratorMode("integratorMode")
                            .inTrackThrust(true)
                            .lastObEnd(OffsetDateTime.parse("2022-11-09T11:20:21.247192Z"))
                            .lastObStart(OffsetDateTime.parse("2022-11-09T11:20:21.247192Z"))
                            .leapSecondTime(OffsetDateTime.parse("2021-01-01T01:01:01.123Z"))
                            .lunarSolar(true)
                            .mass(164.5)
                            .obsAvailable(376)
                            .obsUsed(374)
                            .origin("THIRD_PARTY_DATASOURCE")
                            .origNetwork("ORIG")
                            .origObjectId("ORIGOBJECT-ID")
                            .partials("ANALYTIC")
                            .pedigree("CONJUNCTION")
                            .polarMotionX(1.23)
                            .polarMotionY(1.23)
                            .posUnc(0.333399744452)
                            .rawFileUri("rawFileURI")
                            .recOdSpan(3.5)
                            .referenceFrame(
                                ConjunctionCreateUdlParams.StateVector2.ReferenceFrame.J2000
                            )
                            .residualsAcc(99.5)
                            .revNo(7205)
                            .rms(0.991)
                            .satNo(12)
                            .addSigmaPosUvw(1.23)
                            .addSigmaPosUvw(4.56)
                            .addSigmaVelUvw(1.23)
                            .addSigmaVelUvw(4.56)
                            .solarFluxApAvg(1.23)
                            .solarFluxF10(1.23)
                            .solarFluxF10Avg(1.23)
                            .solarRadPress(true)
                            .solarRadPressCoeff(0.0244394)
                            .solidEarthTides(true)
                            .addSourcedData("DATA1")
                            .addSourcedData("DATA2")
                            .addSourcedDataType(
                                ConjunctionCreateUdlParams.StateVector2.SourcedDataType.RADAR
                            )
                            .sourceDl("AXE")
                            .srpArea(4.311)
                            .stepMode("AUTO")
                            .stepSize(1.23)
                            .stepSizeSelection("AUTO")
                            .addTag("TAG1")
                            .addTag("TAG2")
                            .taiUtc(1.23)
                            .thrustAccel(1.23)
                            .tracksAvail(163)
                            .tracksUsed(163)
                            .transactionId("transactionId")
                            .uct(true)
                            .ut1Rate(1.23)
                            .ut1Utc(1.23)
                            .velUnc(0.000004)
                            .xaccel(-2.12621392)
                            .xpos(-1118.577381)
                            .xposAlt1(-1145.688502)
                            .xposAlt2(-1456.915926)
                            .xvel(-4.25242784)
                            .xvelAlt1(-4.270832252)
                            .xvelAlt2(-1.219814294)
                            .yaccel(2.645553717)
                            .ypos(3026.231084)
                            .yposAlt1(3020.729572)
                            .yposAlt2(-2883.540406)
                            .yvel(5.291107434)
                            .yvelAlt1(5.27074276)
                            .yvelAlt2(-6.602080212)
                            .zaccel(-1.06310696)
                            .zpos(6167.831808)
                            .zposAlt1(6165.55187)
                            .zposAlt2(6165.55187)
                            .zvel(-3.356493869)
                            .zvelAlt1(-3.365155181)
                            .zvelAlt2(-3.365155181)
                            .build()
                    )
                    .addTag("PROVIDER_TAG1")
                    .addTag("PROVIDER_TAG1")
                    .thrustAccel1(0.033814)
                    .thrustAccel2(0.033814)
                    .transactionId("TRANSACTION-ID")
                    .type("CONJUNCTION")
                    .uvwWarn(false)
                    .volEntryTime(OffsetDateTime.parse("2021-01-01T01:02:01.123456Z"))
                    .volExitTime(OffsetDateTime.parse("2021-01-01T01:02:28.123456Z"))
                    .volShape("ELLIPSOID")
                    .build()
            )

        val response = future.get()
    }

    @Test
    fun createBulk() {
        val client =
            UnifieddatalibraryOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val conjunctionServiceAsync = client.conjunctions()

        val future =
            conjunctionServiceAsync.createBulk(
                ConjunctionCreateBulkParams.builder()
                    .addBody(
                        ConjunctionCreateBulkParams.Body.builder()
                            .classificationMarking("U")
                            .dataMode(ConjunctionCreateBulkParams.Body.DataMode.TEST)
                            .source("Bluestaq")
                            .tca(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                            .id("CONJUNCTION-ID")
                            .ccir("Example notes")
                            .cdAoM1(0.016386)
                            .cdAoM2(0.016386)
                            .collisionProb(0.5)
                            .collisionProbMethod("FOSTER-1992")
                            .comments("Example notes")
                            .concernNotes("Example notes")
                            .crAoM1(0.013814)
                            .crAoM2(0.013814)
                            .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                            .createdBy("some.user")
                            .descriptor("sample_descriptor here")
                            .ephemName1("MEME_SPCFT_ABC_2180000_ops_nomnvr_unclassified.oem")
                            .ephemName2("MEME_SPCFT_DEF_2170000_ops_nomnvr_unclassified.txt")
                            .esId1("a2ae2356-6d83-4e4b-896d-ddd1958800fa")
                            .esId2("6fa31433-8beb-4b9b-8bf9-326dbd041c3f")
                            .eventId("some.user")
                            .idOnOrbit1("ONORBIT1-ID")
                            .idOnOrbit2("ONORBIT2-ID")
                            .idStateVector1("REF-STATEVECTOR1-ID")
                            .idStateVector2("REF-STATEVECTOR2-ID")
                            .largeCovWarning(false)
                            .largeRelPosWarning(false)
                            .lastObTime1(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                            .lastObTime2(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                            .messageFor("Message for space craft A")
                            .messageId("MESSAGE-ID")
                            .missDistance(1.1)
                            .origIdOnOrbit1("ORIGONORBIT1-ID")
                            .origIdOnOrbit2("ORIGONORBIT2-ID")
                            .origin("THIRD_PARTY_DATASOURCE")
                            .originator("some.user")
                            .origNetwork("ORIG")
                            .ownerContacted(false)
                            .penetrationLevelSigma(1.1)
                            .rawFileUri("Example link")
                            .relPosN(1.1)
                            .relPosR(1.1)
                            .relPosT(1.1)
                            .relVelMag(1.1)
                            .relVelN(1.1)
                            .relVelR(1.1)
                            .relVelT(1.1)
                            .satNo1(1)
                            .satNo2(2)
                            .screenEntryTime(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                            .screenExitTime(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                            .screenVolumeX(1.1)
                            .screenVolumeY(1.1)
                            .screenVolumeZ(1.1)
                            .smallCovWarning(false)
                            .smallRelVelWarning(false)
                            .stateDeptNotified(false)
                            .stateVector1(
                                ConjunctionCreateBulkParams.Body.StateVector1.builder()
                                    .classificationMarking("U")
                                    .dataMode(
                                        ConjunctionCreateBulkParams.Body.StateVector1.DataMode.TEST
                                    )
                                    .epoch(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
                                    .source("Bluestaq")
                                    .actualOdSpan(3.5)
                                    .algorithm("SAMPLE_ALGORITHM")
                                    .alt1ReferenceFrame("TEME")
                                    .alt2ReferenceFrame("EFG/TDR")
                                    .area(5.065)
                                    .bDot(1.23)
                                    .cmOffset(1.23)
                                    .cov(listOf(1.1, 2.4, 3.8, 4.2, 5.5, 6.0))
                                    .covMethod("CALCULATED")
                                    .covReferenceFrame(
                                        ConjunctionCreateBulkParams.Body.StateVector1
                                            .CovReferenceFrame
                                            .J2000
                                    )
                                    .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                                    .createdBy("some.user")
                                    .descriptor("descriptor")
                                    .dragArea(4.739)
                                    .dragCoeff(0.0224391269775)
                                    .dragModel("JAC70")
                                    .edr(1.23)
                                    .addEqCov(1.1)
                                    .addEqCov(2.2)
                                    .errorControl(1.23)
                                    .fixedStep(true)
                                    .geopotentialModel("EGM-96")
                                    .iau1980Terms(4)
                                    .idOnOrbit("ONORBIT-ID")
                                    .idOrbitDetermination("026dd511-8ba5-47d3-9909-836149f87686")
                                    .idStateVector("STATEVECTOR-ID")
                                    .integratorMode("integratorMode")
                                    .inTrackThrust(true)
                                    .lastObEnd(OffsetDateTime.parse("2022-11-09T11:20:21.247192Z"))
                                    .lastObStart(
                                        OffsetDateTime.parse("2022-11-09T11:20:21.247192Z")
                                    )
                                    .leapSecondTime(
                                        OffsetDateTime.parse("2021-01-01T01:01:01.123Z")
                                    )
                                    .lunarSolar(true)
                                    .mass(164.5)
                                    .obsAvailable(376)
                                    .obsUsed(374)
                                    .origin("THIRD_PARTY_DATASOURCE")
                                    .origNetwork("ORIG")
                                    .origObjectId("ORIGOBJECT-ID")
                                    .partials("ANALYTIC")
                                    .pedigree("CONJUNCTION")
                                    .polarMotionX(1.23)
                                    .polarMotionY(1.23)
                                    .posUnc(0.333399744452)
                                    .rawFileUri("rawFileURI")
                                    .recOdSpan(3.5)
                                    .referenceFrame(
                                        ConjunctionCreateBulkParams.Body.StateVector1.ReferenceFrame
                                            .J2000
                                    )
                                    .residualsAcc(99.5)
                                    .revNo(7205)
                                    .rms(0.991)
                                    .satNo(12)
                                    .addSigmaPosUvw(1.23)
                                    .addSigmaPosUvw(4.56)
                                    .addSigmaVelUvw(1.23)
                                    .addSigmaVelUvw(4.56)
                                    .solarFluxApAvg(1.23)
                                    .solarFluxF10(1.23)
                                    .solarFluxF10Avg(1.23)
                                    .solarRadPress(true)
                                    .solarRadPressCoeff(0.0244394)
                                    .solidEarthTides(true)
                                    .addSourcedData("DATA1")
                                    .addSourcedData("DATA2")
                                    .addSourcedDataType(
                                        ConjunctionCreateBulkParams.Body.StateVector1
                                            .SourcedDataType
                                            .RADAR
                                    )
                                    .sourceDl("AXE")
                                    .srpArea(4.311)
                                    .stepMode("AUTO")
                                    .stepSize(1.23)
                                    .stepSizeSelection("AUTO")
                                    .addTag("TAG1")
                                    .addTag("TAG2")
                                    .taiUtc(1.23)
                                    .thrustAccel(1.23)
                                    .tracksAvail(163)
                                    .tracksUsed(163)
                                    .transactionId("transactionId")
                                    .uct(true)
                                    .ut1Rate(1.23)
                                    .ut1Utc(1.23)
                                    .velUnc(0.000004)
                                    .xaccel(-2.12621392)
                                    .xpos(-1118.577381)
                                    .xposAlt1(-1145.688502)
                                    .xposAlt2(-1456.915926)
                                    .xvel(-4.25242784)
                                    .xvelAlt1(-4.270832252)
                                    .xvelAlt2(-1.219814294)
                                    .yaccel(2.645553717)
                                    .ypos(3026.231084)
                                    .yposAlt1(3020.729572)
                                    .yposAlt2(-2883.540406)
                                    .yvel(5.291107434)
                                    .yvelAlt1(5.27074276)
                                    .yvelAlt2(-6.602080212)
                                    .zaccel(-1.06310696)
                                    .zpos(6167.831808)
                                    .zposAlt1(6165.55187)
                                    .zposAlt2(6165.55187)
                                    .zvel(-3.356493869)
                                    .zvelAlt1(-3.365155181)
                                    .zvelAlt2(-3.365155181)
                                    .build()
                            )
                            .stateVector2(
                                ConjunctionCreateBulkParams.Body.StateVector2.builder()
                                    .classificationMarking("U")
                                    .dataMode(
                                        ConjunctionCreateBulkParams.Body.StateVector2.DataMode.TEST
                                    )
                                    .epoch(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
                                    .source("Bluestaq")
                                    .actualOdSpan(3.5)
                                    .algorithm("SAMPLE_ALGORITHM")
                                    .alt1ReferenceFrame("TEME")
                                    .alt2ReferenceFrame("EFG/TDR")
                                    .area(5.065)
                                    .bDot(1.23)
                                    .cmOffset(1.23)
                                    .cov(listOf(1.1, 2.4, 3.8, 4.2, 5.5, 6.0))
                                    .covMethod("CALCULATED")
                                    .covReferenceFrame(
                                        ConjunctionCreateBulkParams.Body.StateVector2
                                            .CovReferenceFrame
                                            .J2000
                                    )
                                    .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                                    .createdBy("some.user")
                                    .descriptor("descriptor")
                                    .dragArea(4.739)
                                    .dragCoeff(0.0224391269775)
                                    .dragModel("JAC70")
                                    .edr(1.23)
                                    .addEqCov(1.1)
                                    .addEqCov(2.2)
                                    .errorControl(1.23)
                                    .fixedStep(true)
                                    .geopotentialModel("EGM-96")
                                    .iau1980Terms(4)
                                    .idOnOrbit("ONORBIT-ID")
                                    .idOrbitDetermination("026dd511-8ba5-47d3-9909-836149f87686")
                                    .idStateVector("STATEVECTOR-ID")
                                    .integratorMode("integratorMode")
                                    .inTrackThrust(true)
                                    .lastObEnd(OffsetDateTime.parse("2022-11-09T11:20:21.247192Z"))
                                    .lastObStart(
                                        OffsetDateTime.parse("2022-11-09T11:20:21.247192Z")
                                    )
                                    .leapSecondTime(
                                        OffsetDateTime.parse("2021-01-01T01:01:01.123Z")
                                    )
                                    .lunarSolar(true)
                                    .mass(164.5)
                                    .obsAvailable(376)
                                    .obsUsed(374)
                                    .origin("THIRD_PARTY_DATASOURCE")
                                    .origNetwork("ORIG")
                                    .origObjectId("ORIGOBJECT-ID")
                                    .partials("ANALYTIC")
                                    .pedigree("CONJUNCTION")
                                    .polarMotionX(1.23)
                                    .polarMotionY(1.23)
                                    .posUnc(0.333399744452)
                                    .rawFileUri("rawFileURI")
                                    .recOdSpan(3.5)
                                    .referenceFrame(
                                        ConjunctionCreateBulkParams.Body.StateVector2.ReferenceFrame
                                            .J2000
                                    )
                                    .residualsAcc(99.5)
                                    .revNo(7205)
                                    .rms(0.991)
                                    .satNo(12)
                                    .addSigmaPosUvw(1.23)
                                    .addSigmaPosUvw(4.56)
                                    .addSigmaVelUvw(1.23)
                                    .addSigmaVelUvw(4.56)
                                    .solarFluxApAvg(1.23)
                                    .solarFluxF10(1.23)
                                    .solarFluxF10Avg(1.23)
                                    .solarRadPress(true)
                                    .solarRadPressCoeff(0.0244394)
                                    .solidEarthTides(true)
                                    .addSourcedData("DATA1")
                                    .addSourcedData("DATA2")
                                    .addSourcedDataType(
                                        ConjunctionCreateBulkParams.Body.StateVector2
                                            .SourcedDataType
                                            .RADAR
                                    )
                                    .sourceDl("AXE")
                                    .srpArea(4.311)
                                    .stepMode("AUTO")
                                    .stepSize(1.23)
                                    .stepSizeSelection("AUTO")
                                    .addTag("TAG1")
                                    .addTag("TAG2")
                                    .taiUtc(1.23)
                                    .thrustAccel(1.23)
                                    .tracksAvail(163)
                                    .tracksUsed(163)
                                    .transactionId("transactionId")
                                    .uct(true)
                                    .ut1Rate(1.23)
                                    .ut1Utc(1.23)
                                    .velUnc(0.000004)
                                    .xaccel(-2.12621392)
                                    .xpos(-1118.577381)
                                    .xposAlt1(-1145.688502)
                                    .xposAlt2(-1456.915926)
                                    .xvel(-4.25242784)
                                    .xvelAlt1(-4.270832252)
                                    .xvelAlt2(-1.219814294)
                                    .yaccel(2.645553717)
                                    .ypos(3026.231084)
                                    .yposAlt1(3020.729572)
                                    .yposAlt2(-2883.540406)
                                    .yvel(5.291107434)
                                    .yvelAlt1(5.27074276)
                                    .yvelAlt2(-6.602080212)
                                    .zaccel(-1.06310696)
                                    .zpos(6167.831808)
                                    .zposAlt1(6165.55187)
                                    .zposAlt2(6165.55187)
                                    .zvel(-3.356493869)
                                    .zvelAlt1(-3.365155181)
                                    .zvelAlt2(-3.365155181)
                                    .build()
                            )
                            .addTag("PROVIDER_TAG1")
                            .addTag("PROVIDER_TAG1")
                            .thrustAccel1(0.033814)
                            .thrustAccel2(0.033814)
                            .transactionId("TRANSACTION-ID")
                            .type("CONJUNCTION")
                            .uvwWarn(false)
                            .volEntryTime(OffsetDateTime.parse("2021-01-01T01:02:01.123456Z"))
                            .volExitTime(OffsetDateTime.parse("2021-01-01T01:02:28.123456Z"))
                            .volShape("ELLIPSOID")
                            .build()
                    )
                    .build()
            )

        val response = future.get()
    }

    @Test
    fun getHistory() {
        val client =
            UnifieddatalibraryOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val conjunctionServiceAsync = client.conjunctions()

        val conjunctionFullsFuture =
            conjunctionServiceAsync.getHistory(
                ConjunctionGetHistoryParams.builder()
                    .tca(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .columns("columns")
                    .firstResult(0L)
                    .maxResults(0L)
                    .build()
            )

        val conjunctionFulls = conjunctionFullsFuture.get()
        conjunctionFulls.forEach { it.validate() }
    }

    @Test
    fun queryhelp() {
        val client =
            UnifieddatalibraryOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val conjunctionServiceAsync = client.conjunctions()

        val responseFuture = conjunctionServiceAsync.queryhelp()

        val response = responseFuture.get()
        response.validate()
    }

    @Test
    fun tuple() {
        val client =
            UnifieddatalibraryOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val conjunctionServiceAsync = client.conjunctions()

        val conjunctionFullsFuture =
            conjunctionServiceAsync.tuple(
                ConjunctionTupleParams.builder()
                    .columns("columns")
                    .tca(OffsetDateTime.parse("2019-12-27T18:11:19.117Z"))
                    .firstResult(0L)
                    .maxResults(0L)
                    .build()
            )

        val conjunctionFulls = conjunctionFullsFuture.get()
        conjunctionFulls.forEach { it.validate() }
    }

    @Test
    fun unvalidatedPublish() {
        val client =
            UnifieddatalibraryOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val conjunctionServiceAsync = client.conjunctions()

        val future =
            conjunctionServiceAsync.unvalidatedPublish(
                ConjunctionUnvalidatedPublishParams.builder()
                    .addBody(
                        ConjunctionUnvalidatedPublishParams.Body.builder()
                            .classificationMarking("U")
                            .dataMode(ConjunctionUnvalidatedPublishParams.Body.DataMode.TEST)
                            .source("Bluestaq")
                            .tca(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                            .id("CONJUNCTION-ID")
                            .ccir("Example notes")
                            .cdAoM1(0.016386)
                            .cdAoM2(0.016386)
                            .collisionProb(0.5)
                            .collisionProbMethod("FOSTER-1992")
                            .comments("Example notes")
                            .concernNotes("Example notes")
                            .crAoM1(0.013814)
                            .crAoM2(0.013814)
                            .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                            .createdBy("some.user")
                            .descriptor("sample_descriptor here")
                            .ephemName1("MEME_SPCFT_ABC_2180000_ops_nomnvr_unclassified.oem")
                            .ephemName2("MEME_SPCFT_DEF_2170000_ops_nomnvr_unclassified.txt")
                            .esId1("a2ae2356-6d83-4e4b-896d-ddd1958800fa")
                            .esId2("6fa31433-8beb-4b9b-8bf9-326dbd041c3f")
                            .eventId("some.user")
                            .idOnOrbit1("ONORBIT1-ID")
                            .idOnOrbit2("ONORBIT2-ID")
                            .idStateVector1("REF-STATEVECTOR1-ID")
                            .idStateVector2("REF-STATEVECTOR2-ID")
                            .largeCovWarning(false)
                            .largeRelPosWarning(false)
                            .lastObTime1(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                            .lastObTime2(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                            .messageFor("Message for space craft A")
                            .messageId("MESSAGE-ID")
                            .missDistance(1.1)
                            .origIdOnOrbit1("ORIGONORBIT1-ID")
                            .origIdOnOrbit2("ORIGONORBIT2-ID")
                            .origin("THIRD_PARTY_DATASOURCE")
                            .originator("some.user")
                            .origNetwork("ORIG")
                            .ownerContacted(false)
                            .penetrationLevelSigma(1.1)
                            .rawFileUri("Example link")
                            .relPosN(1.1)
                            .relPosR(1.1)
                            .relPosT(1.1)
                            .relVelMag(1.1)
                            .relVelN(1.1)
                            .relVelR(1.1)
                            .relVelT(1.1)
                            .satNo1(1)
                            .satNo2(2)
                            .screenEntryTime(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                            .screenExitTime(OffsetDateTime.parse("2021-01-01T01:01:01.123456Z"))
                            .screenVolumeX(1.1)
                            .screenVolumeY(1.1)
                            .screenVolumeZ(1.1)
                            .smallCovWarning(false)
                            .smallRelVelWarning(false)
                            .stateDeptNotified(false)
                            .stateVector1(
                                ConjunctionUnvalidatedPublishParams.Body.StateVector1.builder()
                                    .classificationMarking("U")
                                    .dataMode(
                                        ConjunctionUnvalidatedPublishParams.Body.StateVector1
                                            .DataMode
                                            .TEST
                                    )
                                    .epoch(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
                                    .source("Bluestaq")
                                    .actualOdSpan(3.5)
                                    .algorithm("SAMPLE_ALGORITHM")
                                    .alt1ReferenceFrame("TEME")
                                    .alt2ReferenceFrame("EFG/TDR")
                                    .area(5.065)
                                    .bDot(1.23)
                                    .cmOffset(1.23)
                                    .cov(listOf(1.1, 2.4, 3.8, 4.2, 5.5, 6.0))
                                    .covMethod("CALCULATED")
                                    .covReferenceFrame(
                                        ConjunctionUnvalidatedPublishParams.Body.StateVector1
                                            .CovReferenceFrame
                                            .J2000
                                    )
                                    .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                                    .createdBy("some.user")
                                    .descriptor("descriptor")
                                    .dragArea(4.739)
                                    .dragCoeff(0.0224391269775)
                                    .dragModel("JAC70")
                                    .edr(1.23)
                                    .addEqCov(1.1)
                                    .addEqCov(2.2)
                                    .errorControl(1.23)
                                    .fixedStep(true)
                                    .geopotentialModel("EGM-96")
                                    .iau1980Terms(4)
                                    .idOnOrbit("ONORBIT-ID")
                                    .idOrbitDetermination("026dd511-8ba5-47d3-9909-836149f87686")
                                    .idStateVector("STATEVECTOR-ID")
                                    .integratorMode("integratorMode")
                                    .inTrackThrust(true)
                                    .lastObEnd(OffsetDateTime.parse("2022-11-09T11:20:21.247192Z"))
                                    .lastObStart(
                                        OffsetDateTime.parse("2022-11-09T11:20:21.247192Z")
                                    )
                                    .leapSecondTime(
                                        OffsetDateTime.parse("2021-01-01T01:01:01.123Z")
                                    )
                                    .lunarSolar(true)
                                    .mass(164.5)
                                    .obsAvailable(376)
                                    .obsUsed(374)
                                    .origin("THIRD_PARTY_DATASOURCE")
                                    .origNetwork("ORIG")
                                    .origObjectId("ORIGOBJECT-ID")
                                    .partials("ANALYTIC")
                                    .pedigree("CONJUNCTION")
                                    .polarMotionX(1.23)
                                    .polarMotionY(1.23)
                                    .posUnc(0.333399744452)
                                    .rawFileUri("rawFileURI")
                                    .recOdSpan(3.5)
                                    .referenceFrame(
                                        ConjunctionUnvalidatedPublishParams.Body.StateVector1
                                            .ReferenceFrame
                                            .J2000
                                    )
                                    .residualsAcc(99.5)
                                    .revNo(7205)
                                    .rms(0.991)
                                    .satNo(12)
                                    .addSigmaPosUvw(1.23)
                                    .addSigmaPosUvw(4.56)
                                    .addSigmaVelUvw(1.23)
                                    .addSigmaVelUvw(4.56)
                                    .solarFluxApAvg(1.23)
                                    .solarFluxF10(1.23)
                                    .solarFluxF10Avg(1.23)
                                    .solarRadPress(true)
                                    .solarRadPressCoeff(0.0244394)
                                    .solidEarthTides(true)
                                    .addSourcedData("DATA1")
                                    .addSourcedData("DATA2")
                                    .addSourcedDataType(
                                        ConjunctionUnvalidatedPublishParams.Body.StateVector1
                                            .SourcedDataType
                                            .RADAR
                                    )
                                    .sourceDl("AXE")
                                    .srpArea(4.311)
                                    .stepMode("AUTO")
                                    .stepSize(1.23)
                                    .stepSizeSelection("AUTO")
                                    .addTag("TAG1")
                                    .addTag("TAG2")
                                    .taiUtc(1.23)
                                    .thrustAccel(1.23)
                                    .tracksAvail(163)
                                    .tracksUsed(163)
                                    .transactionId("transactionId")
                                    .uct(true)
                                    .ut1Rate(1.23)
                                    .ut1Utc(1.23)
                                    .velUnc(0.000004)
                                    .xaccel(-2.12621392)
                                    .xpos(-1118.577381)
                                    .xposAlt1(-1145.688502)
                                    .xposAlt2(-1456.915926)
                                    .xvel(-4.25242784)
                                    .xvelAlt1(-4.270832252)
                                    .xvelAlt2(-1.219814294)
                                    .yaccel(2.645553717)
                                    .ypos(3026.231084)
                                    .yposAlt1(3020.729572)
                                    .yposAlt2(-2883.540406)
                                    .yvel(5.291107434)
                                    .yvelAlt1(5.27074276)
                                    .yvelAlt2(-6.602080212)
                                    .zaccel(-1.06310696)
                                    .zpos(6167.831808)
                                    .zposAlt1(6165.55187)
                                    .zposAlt2(6165.55187)
                                    .zvel(-3.356493869)
                                    .zvelAlt1(-3.365155181)
                                    .zvelAlt2(-3.365155181)
                                    .build()
                            )
                            .stateVector2(
                                ConjunctionUnvalidatedPublishParams.Body.StateVector2.builder()
                                    .classificationMarking("U")
                                    .dataMode(
                                        ConjunctionUnvalidatedPublishParams.Body.StateVector2
                                            .DataMode
                                            .TEST
                                    )
                                    .epoch(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
                                    .source("Bluestaq")
                                    .actualOdSpan(3.5)
                                    .algorithm("SAMPLE_ALGORITHM")
                                    .alt1ReferenceFrame("TEME")
                                    .alt2ReferenceFrame("EFG/TDR")
                                    .area(5.065)
                                    .bDot(1.23)
                                    .cmOffset(1.23)
                                    .cov(listOf(1.1, 2.4, 3.8, 4.2, 5.5, 6.0))
                                    .covMethod("CALCULATED")
                                    .covReferenceFrame(
                                        ConjunctionUnvalidatedPublishParams.Body.StateVector2
                                            .CovReferenceFrame
                                            .J2000
                                    )
                                    .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                                    .createdBy("some.user")
                                    .descriptor("descriptor")
                                    .dragArea(4.739)
                                    .dragCoeff(0.0224391269775)
                                    .dragModel("JAC70")
                                    .edr(1.23)
                                    .addEqCov(1.1)
                                    .addEqCov(2.2)
                                    .errorControl(1.23)
                                    .fixedStep(true)
                                    .geopotentialModel("EGM-96")
                                    .iau1980Terms(4)
                                    .idOnOrbit("ONORBIT-ID")
                                    .idOrbitDetermination("026dd511-8ba5-47d3-9909-836149f87686")
                                    .idStateVector("STATEVECTOR-ID")
                                    .integratorMode("integratorMode")
                                    .inTrackThrust(true)
                                    .lastObEnd(OffsetDateTime.parse("2022-11-09T11:20:21.247192Z"))
                                    .lastObStart(
                                        OffsetDateTime.parse("2022-11-09T11:20:21.247192Z")
                                    )
                                    .leapSecondTime(
                                        OffsetDateTime.parse("2021-01-01T01:01:01.123Z")
                                    )
                                    .lunarSolar(true)
                                    .mass(164.5)
                                    .obsAvailable(376)
                                    .obsUsed(374)
                                    .origin("THIRD_PARTY_DATASOURCE")
                                    .origNetwork("ORIG")
                                    .origObjectId("ORIGOBJECT-ID")
                                    .partials("ANALYTIC")
                                    .pedigree("CONJUNCTION")
                                    .polarMotionX(1.23)
                                    .polarMotionY(1.23)
                                    .posUnc(0.333399744452)
                                    .rawFileUri("rawFileURI")
                                    .recOdSpan(3.5)
                                    .referenceFrame(
                                        ConjunctionUnvalidatedPublishParams.Body.StateVector2
                                            .ReferenceFrame
                                            .J2000
                                    )
                                    .residualsAcc(99.5)
                                    .revNo(7205)
                                    .rms(0.991)
                                    .satNo(12)
                                    .addSigmaPosUvw(1.23)
                                    .addSigmaPosUvw(4.56)
                                    .addSigmaVelUvw(1.23)
                                    .addSigmaVelUvw(4.56)
                                    .solarFluxApAvg(1.23)
                                    .solarFluxF10(1.23)
                                    .solarFluxF10Avg(1.23)
                                    .solarRadPress(true)
                                    .solarRadPressCoeff(0.0244394)
                                    .solidEarthTides(true)
                                    .addSourcedData("DATA1")
                                    .addSourcedData("DATA2")
                                    .addSourcedDataType(
                                        ConjunctionUnvalidatedPublishParams.Body.StateVector2
                                            .SourcedDataType
                                            .RADAR
                                    )
                                    .sourceDl("AXE")
                                    .srpArea(4.311)
                                    .stepMode("AUTO")
                                    .stepSize(1.23)
                                    .stepSizeSelection("AUTO")
                                    .addTag("TAG1")
                                    .addTag("TAG2")
                                    .taiUtc(1.23)
                                    .thrustAccel(1.23)
                                    .tracksAvail(163)
                                    .tracksUsed(163)
                                    .transactionId("transactionId")
                                    .uct(true)
                                    .ut1Rate(1.23)
                                    .ut1Utc(1.23)
                                    .velUnc(0.000004)
                                    .xaccel(-2.12621392)
                                    .xpos(-1118.577381)
                                    .xposAlt1(-1145.688502)
                                    .xposAlt2(-1456.915926)
                                    .xvel(-4.25242784)
                                    .xvelAlt1(-4.270832252)
                                    .xvelAlt2(-1.219814294)
                                    .yaccel(2.645553717)
                                    .ypos(3026.231084)
                                    .yposAlt1(3020.729572)
                                    .yposAlt2(-2883.540406)
                                    .yvel(5.291107434)
                                    .yvelAlt1(5.27074276)
                                    .yvelAlt2(-6.602080212)
                                    .zaccel(-1.06310696)
                                    .zpos(6167.831808)
                                    .zposAlt1(6165.55187)
                                    .zposAlt2(6165.55187)
                                    .zvel(-3.356493869)
                                    .zvelAlt1(-3.365155181)
                                    .zvelAlt2(-3.365155181)
                                    .build()
                            )
                            .addTag("PROVIDER_TAG1")
                            .addTag("PROVIDER_TAG1")
                            .thrustAccel1(0.033814)
                            .thrustAccel2(0.033814)
                            .transactionId("TRANSACTION-ID")
                            .type("CONJUNCTION")
                            .uvwWarn(false)
                            .volEntryTime(OffsetDateTime.parse("2021-01-01T01:02:01.123456Z"))
                            .volExitTime(OffsetDateTime.parse("2021-01-01T01:02:28.123456Z"))
                            .volShape("ELLIPSOID")
                            .build()
                    )
                    .build()
            )

        val response = future.get()
    }

    @Test
    fun uploadConjunctionDataMessage() {
        val client =
            UnifieddatalibraryOkHttpClientAsync.builder()
                .baseUrl(TestServerExtension.BASE_URL)
                .password("My Password")
                .username("My Username")
                .build()
        val conjunctionServiceAsync = client.conjunctions()

        val future =
            conjunctionServiceAsync.uploadConjunctionDataMessage(
                ConjunctionUploadConjunctionDataMessageParams.builder()
                    .classification("classification")
                    .dataMode(ConjunctionUploadConjunctionDataMessageParams.DataMode.REAL)
                    .filename("filename")
                    .source("source")
                    .tags("tags")
                    .fileContent("some content")
                    .build()
            )

        val response = future.get()
    }
}
