// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.item

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.LocalDate
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ItemTupleResponseTest {

    @Test
    fun create() {
        val itemTupleResponse =
            ItemTupleResponse.builder()
                .classificationMarking("U")
                .dataMode(ItemTupleResponse.DataMode.TEST)
                .scanCode("12345ABCD")
                .source("Bluestaq")
                .type("CARGO")
                .id("22f1f6da-a568-655a-ea37-76d013d04853")
                .addAccSysKey("System key1")
                .addAccSysKey("System key2")
                .accSysNotes("Accepting System Notes")
                .accSystem("Accepting System")
                .addAccSysValue("System value1")
                .addAccSysValue("System value2")
                .airdrop(true)
                .altDataFormat("Alt Data Format")
                .cargoType("PALLET")
                .centerlineOffset(3.1)
                .cg(112.014)
                .commodityCode("2304116")
                .commoditySys("STCC")
                .container(true)
                .createdAt(OffsetDateTime.parse("2023-03-21T16:00:00.123Z"))
                .createdBy("some.user")
                .departure("CHS")
                .destination("RMS")
                .dvCode("DV-2")
                .fs(412.1)
                .addHazCode(1.1)
                .addHazCode(1.2)
                .height(1.1)
                .idAirLoadPlan("1038c389-d38e-270f-51cc-6a12e905abe8")
                .addItemContain("2UJ8843K")
                .addItemContain("745YV1T65")
                .addKey("key1")
                .addKey("key2")
                .lastArrDate(LocalDate.parse("2023-03-13"))
                .length(1.1)
                .moment(4000.1)
                .name("Product Name")
                .netExpWt(51.437)
                .notes("Example notes")
                .numPalletPos(2)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .productCode("530500234")
                .productSys("NSN")
                .receivingBranch("Air Force")
                .receivingUnit("50 SBN")
                .scGenTool("bID")
                .sourceDl("AXE")
                .tcn("M1358232245912XXX")
                .uln("T01ME01")
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .addValue("value1")
                .addValue("value2")
                .volume(7.8902)
                .weight(5443.335)
                .weightTs(OffsetDateTime.parse("2023-03-13T16:06:00.123Z"))
                .width(1.1)
                .build()

        assertThat(itemTupleResponse.classificationMarking()).isEqualTo("U")
        assertThat(itemTupleResponse.dataMode()).isEqualTo(ItemTupleResponse.DataMode.TEST)
        assertThat(itemTupleResponse.scanCode()).isEqualTo("12345ABCD")
        assertThat(itemTupleResponse.source()).isEqualTo("Bluestaq")
        assertThat(itemTupleResponse.type()).isEqualTo("CARGO")
        assertThat(itemTupleResponse.id()).contains("22f1f6da-a568-655a-ea37-76d013d04853")
        assertThat(itemTupleResponse.accSysKeys().getOrNull())
            .containsExactly("System key1", "System key2")
        assertThat(itemTupleResponse.accSysNotes()).contains("Accepting System Notes")
        assertThat(itemTupleResponse.accSystem()).contains("Accepting System")
        assertThat(itemTupleResponse.accSysValues().getOrNull())
            .containsExactly("System value1", "System value2")
        assertThat(itemTupleResponse.airdrop()).contains(true)
        assertThat(itemTupleResponse.altDataFormat()).contains("Alt Data Format")
        assertThat(itemTupleResponse.cargoType()).contains("PALLET")
        assertThat(itemTupleResponse.centerlineOffset()).contains(3.1)
        assertThat(itemTupleResponse.cg()).contains(112.014)
        assertThat(itemTupleResponse.commodityCode()).contains("2304116")
        assertThat(itemTupleResponse.commoditySys()).contains("STCC")
        assertThat(itemTupleResponse.container()).contains(true)
        assertThat(itemTupleResponse.createdAt())
            .contains(OffsetDateTime.parse("2023-03-21T16:00:00.123Z"))
        assertThat(itemTupleResponse.createdBy()).contains("some.user")
        assertThat(itemTupleResponse.departure()).contains("CHS")
        assertThat(itemTupleResponse.destination()).contains("RMS")
        assertThat(itemTupleResponse.dvCode()).contains("DV-2")
        assertThat(itemTupleResponse.fs()).contains(412.1)
        assertThat(itemTupleResponse.hazCodes().getOrNull()).containsExactly(1.1, 1.2)
        assertThat(itemTupleResponse.height()).contains(1.1)
        assertThat(itemTupleResponse.idAirLoadPlan())
            .contains("1038c389-d38e-270f-51cc-6a12e905abe8")
        assertThat(itemTupleResponse.itemContains().getOrNull())
            .containsExactly("2UJ8843K", "745YV1T65")
        assertThat(itemTupleResponse.keys().getOrNull()).containsExactly("key1", "key2")
        assertThat(itemTupleResponse.lastArrDate()).contains(LocalDate.parse("2023-03-13"))
        assertThat(itemTupleResponse.length()).contains(1.1)
        assertThat(itemTupleResponse.moment()).contains(4000.1)
        assertThat(itemTupleResponse.name()).contains("Product Name")
        assertThat(itemTupleResponse.netExpWt()).contains(51.437)
        assertThat(itemTupleResponse.notes()).contains("Example notes")
        assertThat(itemTupleResponse.numPalletPos()).contains(2)
        assertThat(itemTupleResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(itemTupleResponse.origNetwork()).contains("OPS1")
        assertThat(itemTupleResponse.productCode()).contains("530500234")
        assertThat(itemTupleResponse.productSys()).contains("NSN")
        assertThat(itemTupleResponse.receivingBranch()).contains("Air Force")
        assertThat(itemTupleResponse.receivingUnit()).contains("50 SBN")
        assertThat(itemTupleResponse.scGenTool()).contains("bID")
        assertThat(itemTupleResponse.sourceDl()).contains("AXE")
        assertThat(itemTupleResponse.tcn()).contains("M1358232245912XXX")
        assertThat(itemTupleResponse.uln()).contains("T01ME01")
        assertThat(itemTupleResponse.updatedAt())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(itemTupleResponse.updatedBy()).contains("some.user")
        assertThat(itemTupleResponse.values().getOrNull()).containsExactly("value1", "value2")
        assertThat(itemTupleResponse.volume()).contains(7.8902)
        assertThat(itemTupleResponse.weight()).contains(5443.335)
        assertThat(itemTupleResponse.weightTs())
            .contains(OffsetDateTime.parse("2023-03-13T16:06:00.123Z"))
        assertThat(itemTupleResponse.width()).contains(1.1)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val itemTupleResponse =
            ItemTupleResponse.builder()
                .classificationMarking("U")
                .dataMode(ItemTupleResponse.DataMode.TEST)
                .scanCode("12345ABCD")
                .source("Bluestaq")
                .type("CARGO")
                .id("22f1f6da-a568-655a-ea37-76d013d04853")
                .addAccSysKey("System key1")
                .addAccSysKey("System key2")
                .accSysNotes("Accepting System Notes")
                .accSystem("Accepting System")
                .addAccSysValue("System value1")
                .addAccSysValue("System value2")
                .airdrop(true)
                .altDataFormat("Alt Data Format")
                .cargoType("PALLET")
                .centerlineOffset(3.1)
                .cg(112.014)
                .commodityCode("2304116")
                .commoditySys("STCC")
                .container(true)
                .createdAt(OffsetDateTime.parse("2023-03-21T16:00:00.123Z"))
                .createdBy("some.user")
                .departure("CHS")
                .destination("RMS")
                .dvCode("DV-2")
                .fs(412.1)
                .addHazCode(1.1)
                .addHazCode(1.2)
                .height(1.1)
                .idAirLoadPlan("1038c389-d38e-270f-51cc-6a12e905abe8")
                .addItemContain("2UJ8843K")
                .addItemContain("745YV1T65")
                .addKey("key1")
                .addKey("key2")
                .lastArrDate(LocalDate.parse("2023-03-13"))
                .length(1.1)
                .moment(4000.1)
                .name("Product Name")
                .netExpWt(51.437)
                .notes("Example notes")
                .numPalletPos(2)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .productCode("530500234")
                .productSys("NSN")
                .receivingBranch("Air Force")
                .receivingUnit("50 SBN")
                .scGenTool("bID")
                .sourceDl("AXE")
                .tcn("M1358232245912XXX")
                .uln("T01ME01")
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .addValue("value1")
                .addValue("value2")
                .volume(7.8902)
                .weight(5443.335)
                .weightTs(OffsetDateTime.parse("2023-03-13T16:06:00.123Z"))
                .width(1.1)
                .build()

        val roundtrippedItemTupleResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(itemTupleResponse),
                jacksonTypeRef<ItemTupleResponse>(),
            )

        assertThat(roundtrippedItemTupleResponse).isEqualTo(itemTupleResponse)
    }
}
