// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.item

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.LocalDate
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class ItemListResponseTest {

    @Test
    fun create() {
        val itemListResponse =
            ItemListResponse.builder()
                .classificationMarking("U")
                .dataMode(ItemListResponse.DataMode.TEST)
                .scanCode("12345ABCD")
                .source("Bluestaq")
                .type("CARGO")
                .id("22f1f6da-a568-655a-ea37-76d013d04853")
                .addAccSysKey("System key1")
                .addAccSysKey("System key2")
                .accSysNotes("Accepting System Notes")
                .accSystem("Accepting System")
                .addAccSysValue("System value1")
                .addAccSysValue("System value2")
                .airdrop(true)
                .altDataFormat("Alt Data Format")
                .cargoType("PALLET")
                .centerlineOffset(3.1)
                .cg(112.014)
                .commodityCode("2304116")
                .commoditySys("STCC")
                .container(true)
                .createdAt(OffsetDateTime.parse("2023-03-21T16:00:00.123Z"))
                .createdBy("some.user")
                .departure("CHS")
                .destination("RMS")
                .dvCode("DV-2")
                .fs(412.1)
                .addHazCode(1.1)
                .addHazCode(1.2)
                .height(1.1)
                .idAirLoadPlan("1038c389-d38e-270f-51cc-6a12e905abe8")
                .addItemContain("2UJ8843K")
                .addItemContain("745YV1T65")
                .addKey("key1")
                .addKey("key2")
                .lastArrDate(LocalDate.parse("2023-03-13"))
                .length(1.1)
                .moment(4000.1)
                .name("Product Name")
                .netExpWt(51.437)
                .notes("Example notes")
                .numPalletPos(2)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .productCode("530500234")
                .productSys("NSN")
                .receivingBranch("Air Force")
                .receivingUnit("50 SBN")
                .scGenTool("bID")
                .sourceDl("AXE")
                .tcn("M1358232245912XXX")
                .uln("T01ME01")
                .addValue("value1")
                .addValue("value2")
                .volume(7.8902)
                .weight(5443.335)
                .weightTs(OffsetDateTime.parse("2023-03-13T16:06:00.123Z"))
                .width(1.1)
                .build()

        assertThat(itemListResponse.classificationMarking()).isEqualTo("U")
        assertThat(itemListResponse.dataMode()).isEqualTo(ItemListResponse.DataMode.TEST)
        assertThat(itemListResponse.scanCode()).isEqualTo("12345ABCD")
        assertThat(itemListResponse.source()).isEqualTo("Bluestaq")
        assertThat(itemListResponse.type()).isEqualTo("CARGO")
        assertThat(itemListResponse.id()).contains("22f1f6da-a568-655a-ea37-76d013d04853")
        assertThat(itemListResponse.accSysKeys().getOrNull())
            .containsExactly("System key1", "System key2")
        assertThat(itemListResponse.accSysNotes()).contains("Accepting System Notes")
        assertThat(itemListResponse.accSystem()).contains("Accepting System")
        assertThat(itemListResponse.accSysValues().getOrNull())
            .containsExactly("System value1", "System value2")
        assertThat(itemListResponse.airdrop()).contains(true)
        assertThat(itemListResponse.altDataFormat()).contains("Alt Data Format")
        assertThat(itemListResponse.cargoType()).contains("PALLET")
        assertThat(itemListResponse.centerlineOffset()).contains(3.1)
        assertThat(itemListResponse.cg()).contains(112.014)
        assertThat(itemListResponse.commodityCode()).contains("2304116")
        assertThat(itemListResponse.commoditySys()).contains("STCC")
        assertThat(itemListResponse.container()).contains(true)
        assertThat(itemListResponse.createdAt())
            .contains(OffsetDateTime.parse("2023-03-21T16:00:00.123Z"))
        assertThat(itemListResponse.createdBy()).contains("some.user")
        assertThat(itemListResponse.departure()).contains("CHS")
        assertThat(itemListResponse.destination()).contains("RMS")
        assertThat(itemListResponse.dvCode()).contains("DV-2")
        assertThat(itemListResponse.fs()).contains(412.1)
        assertThat(itemListResponse.hazCodes().getOrNull()).containsExactly(1.1, 1.2)
        assertThat(itemListResponse.height()).contains(1.1)
        assertThat(itemListResponse.idAirLoadPlan())
            .contains("1038c389-d38e-270f-51cc-6a12e905abe8")
        assertThat(itemListResponse.itemContains().getOrNull())
            .containsExactly("2UJ8843K", "745YV1T65")
        assertThat(itemListResponse.keys().getOrNull()).containsExactly("key1", "key2")
        assertThat(itemListResponse.lastArrDate()).contains(LocalDate.parse("2023-03-13"))
        assertThat(itemListResponse.length()).contains(1.1)
        assertThat(itemListResponse.moment()).contains(4000.1)
        assertThat(itemListResponse.name()).contains("Product Name")
        assertThat(itemListResponse.netExpWt()).contains(51.437)
        assertThat(itemListResponse.notes()).contains("Example notes")
        assertThat(itemListResponse.numPalletPos()).contains(2)
        assertThat(itemListResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(itemListResponse.origNetwork()).contains("OPS1")
        assertThat(itemListResponse.productCode()).contains("530500234")
        assertThat(itemListResponse.productSys()).contains("NSN")
        assertThat(itemListResponse.receivingBranch()).contains("Air Force")
        assertThat(itemListResponse.receivingUnit()).contains("50 SBN")
        assertThat(itemListResponse.scGenTool()).contains("bID")
        assertThat(itemListResponse.sourceDl()).contains("AXE")
        assertThat(itemListResponse.tcn()).contains("M1358232245912XXX")
        assertThat(itemListResponse.uln()).contains("T01ME01")
        assertThat(itemListResponse.values().getOrNull()).containsExactly("value1", "value2")
        assertThat(itemListResponse.volume()).contains(7.8902)
        assertThat(itemListResponse.weight()).contains(5443.335)
        assertThat(itemListResponse.weightTs())
            .contains(OffsetDateTime.parse("2023-03-13T16:06:00.123Z"))
        assertThat(itemListResponse.width()).contains(1.1)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val itemListResponse =
            ItemListResponse.builder()
                .classificationMarking("U")
                .dataMode(ItemListResponse.DataMode.TEST)
                .scanCode("12345ABCD")
                .source("Bluestaq")
                .type("CARGO")
                .id("22f1f6da-a568-655a-ea37-76d013d04853")
                .addAccSysKey("System key1")
                .addAccSysKey("System key2")
                .accSysNotes("Accepting System Notes")
                .accSystem("Accepting System")
                .addAccSysValue("System value1")
                .addAccSysValue("System value2")
                .airdrop(true)
                .altDataFormat("Alt Data Format")
                .cargoType("PALLET")
                .centerlineOffset(3.1)
                .cg(112.014)
                .commodityCode("2304116")
                .commoditySys("STCC")
                .container(true)
                .createdAt(OffsetDateTime.parse("2023-03-21T16:00:00.123Z"))
                .createdBy("some.user")
                .departure("CHS")
                .destination("RMS")
                .dvCode("DV-2")
                .fs(412.1)
                .addHazCode(1.1)
                .addHazCode(1.2)
                .height(1.1)
                .idAirLoadPlan("1038c389-d38e-270f-51cc-6a12e905abe8")
                .addItemContain("2UJ8843K")
                .addItemContain("745YV1T65")
                .addKey("key1")
                .addKey("key2")
                .lastArrDate(LocalDate.parse("2023-03-13"))
                .length(1.1)
                .moment(4000.1)
                .name("Product Name")
                .netExpWt(51.437)
                .notes("Example notes")
                .numPalletPos(2)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .productCode("530500234")
                .productSys("NSN")
                .receivingBranch("Air Force")
                .receivingUnit("50 SBN")
                .scGenTool("bID")
                .sourceDl("AXE")
                .tcn("M1358232245912XXX")
                .uln("T01ME01")
                .addValue("value1")
                .addValue("value2")
                .volume(7.8902)
                .weight(5443.335)
                .weightTs(OffsetDateTime.parse("2023-03-13T16:06:00.123Z"))
                .width(1.1)
                .build()

        val roundtrippedItemListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(itemListResponse),
                jacksonTypeRef<ItemListResponse>(),
            )

        assertThat(roundtrippedItemListResponse).isEqualTo(itemListResponse)
    }
}
