// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.airoperations.airtaskingorders

import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AirTaskingOrderCreateParamsTest {

    @Test
    fun create() {
        AirTaskingOrderCreateParams.builder()
            .beginTs(OffsetDateTime.parse("2023-10-25T12:00:00.123Z"))
            .classificationMarking("U")
            .dataMode(AirTaskingOrderCreateParams.DataMode.TEST)
            .opExerName("DESERT WIND")
            .source("Bluestaq")
            .id("POI-ID")
            .ackReqInd("YES")
            .ackUnitInstructions("INST:45TS")
            .addAcMsnTasking(
                AirTaskingOrderCreateParams.AcMsnTasking.builder()
                    .countryCode("US")
                    .taskedService("A")
                    .unitDesignator("AMPHIB5DIV")
                    .addAcMsnLocSeg(
                        AirTaskingOrderCreateParams.AcMsnTasking.AcMsnLocSeg.builder()
                            .startTime(OffsetDateTime.parse("2021-10-25T12:00:00.123Z"))
                            .airMsnPri("1A")
                            .alt(210)
                            .areaGeoRad(1000)
                            .endTime(OffsetDateTime.parse("2021-10-25T12:00:00.123Z"))
                            .msnLocName("KLSV")
                            .msnLocPtBarT("330T-PT ALFA-50NM")
                            .msnLocPtLat(35.123)
                            .msnLocPtLon(79.01)
                            .msnLocPtName("PT ALFA")
                            .build()
                    )
                    .alertStatus(30)
                    .amcMsnNum("AMC:JJXD123HA045")
                    .depLocLat(35.123)
                    .depLocLon(79.2354)
                    .depLocName("ICAO:KBIF")
                    .depLocUtm("32WDL123123")
                    .depTime(OffsetDateTime.parse("2021-10-25T12:00:00.123Z"))
                    .addIndAcTasking(
                        AirTaskingOrderCreateParams.AcMsnTasking.IndAcTasking.builder()
                            .acftType("F35A")
                            .callSign("EAGLE47")
                            .iffSifMode1Code("111")
                            .iffSifMode2Code("20147")
                            .iffSifMode3Code("30147")
                            .addJuAddress(12345)
                            .addJuAddress(65432)
                            .link16CallSign("EE47")
                            .numAcft(2)
                            .priConfigCode("6A2W3")
                            .secConfigCode("2S2WG")
                            .tacanChan(123)
                            .build()
                    )
                    .msnCommander("MC")
                    .msnNum("D123HA")
                    .pkgId("ZZ")
                    .priMsnType("CAS")
                    .addRcvyLocLat(48.8584)
                    .addRcvyLocLat(40.7554)
                    .addRcvyLocLon(2.2945)
                    .addRcvyLocLon(-73.9866)
                    .addRcvyLocName("ARRLOC:KBIF")
                    .addRcvyLocName("ARRLOC:KDZ7")
                    .addRcvyLocUtm("ARRUTMO:32WDL123123")
                    .addRcvyLocUtm("ARRUTMO:32WDL321321")
                    .addRcvyTime(OffsetDateTime.parse("2021-10-25T16:00:00.234Z"))
                    .addRcvyTime(OffsetDateTime.parse("2021-10-26T16:00:00.234Z"))
                    .resMsnInd("N")
                    .secMsnType("SEAD")
                    .unitLocName("ICAO:KXXQ")
                    .build()
            )
            .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
            .createdBy("some.user")
            .endTs(OffsetDateTime.parse("2023-10-27T12:00:00.123Z"))
            .addGenText(
                AirTaskingOrderCreateParams.GenText.builder()
                    .text("FREE-TEXT")
                    .textInd("OPENING REMARKS")
                    .build()
            )
            .msgMonth("OCT")
            .msgOriginator("USCENTCOM")
            .msgQualifier("CHG")
            .msgSn("ATO A")
            .addNavalFltOp(
                AirTaskingOrderCreateParams.NavalFltOp.builder()
                    .shipName("USS WASP")
                    .fltOpStart(OffsetDateTime.parse("2021-02-25T12:00:00.123Z"))
                    .fltOpStop(OffsetDateTime.parse("2021-02-25T12:00:00.123Z"))
                    .addSchdLaunchRcvyTime(OffsetDateTime.parse("2021-02-25T12:00:00.123Z"))
                    .build()
            )
            .origin("THIRD_PARTY_DATASOURCE")
            .origNetwork("ORIG")
            .rawFileUri("Example URI")
            .sourceDl("AXE")
            .build()
    }

    @Test
    fun body() {
        val params =
            AirTaskingOrderCreateParams.builder()
                .beginTs(OffsetDateTime.parse("2023-10-25T12:00:00.123Z"))
                .classificationMarking("U")
                .dataMode(AirTaskingOrderCreateParams.DataMode.TEST)
                .opExerName("DESERT WIND")
                .source("Bluestaq")
                .id("POI-ID")
                .ackReqInd("YES")
                .ackUnitInstructions("INST:45TS")
                .addAcMsnTasking(
                    AirTaskingOrderCreateParams.AcMsnTasking.builder()
                        .countryCode("US")
                        .taskedService("A")
                        .unitDesignator("AMPHIB5DIV")
                        .addAcMsnLocSeg(
                            AirTaskingOrderCreateParams.AcMsnTasking.AcMsnLocSeg.builder()
                                .startTime(OffsetDateTime.parse("2021-10-25T12:00:00.123Z"))
                                .airMsnPri("1A")
                                .alt(210)
                                .areaGeoRad(1000)
                                .endTime(OffsetDateTime.parse("2021-10-25T12:00:00.123Z"))
                                .msnLocName("KLSV")
                                .msnLocPtBarT("330T-PT ALFA-50NM")
                                .msnLocPtLat(35.123)
                                .msnLocPtLon(79.01)
                                .msnLocPtName("PT ALFA")
                                .build()
                        )
                        .alertStatus(30)
                        .amcMsnNum("AMC:JJXD123HA045")
                        .depLocLat(35.123)
                        .depLocLon(79.2354)
                        .depLocName("ICAO:KBIF")
                        .depLocUtm("32WDL123123")
                        .depTime(OffsetDateTime.parse("2021-10-25T12:00:00.123Z"))
                        .addIndAcTasking(
                            AirTaskingOrderCreateParams.AcMsnTasking.IndAcTasking.builder()
                                .acftType("F35A")
                                .callSign("EAGLE47")
                                .iffSifMode1Code("111")
                                .iffSifMode2Code("20147")
                                .iffSifMode3Code("30147")
                                .addJuAddress(12345)
                                .addJuAddress(65432)
                                .link16CallSign("EE47")
                                .numAcft(2)
                                .priConfigCode("6A2W3")
                                .secConfigCode("2S2WG")
                                .tacanChan(123)
                                .build()
                        )
                        .msnCommander("MC")
                        .msnNum("D123HA")
                        .pkgId("ZZ")
                        .priMsnType("CAS")
                        .addRcvyLocLat(48.8584)
                        .addRcvyLocLat(40.7554)
                        .addRcvyLocLon(2.2945)
                        .addRcvyLocLon(-73.9866)
                        .addRcvyLocName("ARRLOC:KBIF")
                        .addRcvyLocName("ARRLOC:KDZ7")
                        .addRcvyLocUtm("ARRUTMO:32WDL123123")
                        .addRcvyLocUtm("ARRUTMO:32WDL321321")
                        .addRcvyTime(OffsetDateTime.parse("2021-10-25T16:00:00.234Z"))
                        .addRcvyTime(OffsetDateTime.parse("2021-10-26T16:00:00.234Z"))
                        .resMsnInd("N")
                        .secMsnType("SEAD")
                        .unitLocName("ICAO:KXXQ")
                        .build()
                )
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .endTs(OffsetDateTime.parse("2023-10-27T12:00:00.123Z"))
                .addGenText(
                    AirTaskingOrderCreateParams.GenText.builder()
                        .text("FREE-TEXT")
                        .textInd("OPENING REMARKS")
                        .build()
                )
                .msgMonth("OCT")
                .msgOriginator("USCENTCOM")
                .msgQualifier("CHG")
                .msgSn("ATO A")
                .addNavalFltOp(
                    AirTaskingOrderCreateParams.NavalFltOp.builder()
                        .shipName("USS WASP")
                        .fltOpStart(OffsetDateTime.parse("2021-02-25T12:00:00.123Z"))
                        .fltOpStop(OffsetDateTime.parse("2021-02-25T12:00:00.123Z"))
                        .addSchdLaunchRcvyTime(OffsetDateTime.parse("2021-02-25T12:00:00.123Z"))
                        .build()
                )
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("ORIG")
                .rawFileUri("Example URI")
                .sourceDl("AXE")
                .build()

        val body = params._body()

        assertThat(body.beginTs()).isEqualTo(OffsetDateTime.parse("2023-10-25T12:00:00.123Z"))
        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(AirTaskingOrderCreateParams.DataMode.TEST)
        assertThat(body.opExerName()).isEqualTo("DESERT WIND")
        assertThat(body.source()).isEqualTo("Bluestaq")
        assertThat(body.id()).contains("POI-ID")
        assertThat(body.ackReqInd()).contains("YES")
        assertThat(body.ackUnitInstructions()).contains("INST:45TS")
        assertThat(body.acMsnTasking().getOrNull())
            .containsExactly(
                AirTaskingOrderCreateParams.AcMsnTasking.builder()
                    .countryCode("US")
                    .taskedService("A")
                    .unitDesignator("AMPHIB5DIV")
                    .addAcMsnLocSeg(
                        AirTaskingOrderCreateParams.AcMsnTasking.AcMsnLocSeg.builder()
                            .startTime(OffsetDateTime.parse("2021-10-25T12:00:00.123Z"))
                            .airMsnPri("1A")
                            .alt(210)
                            .areaGeoRad(1000)
                            .endTime(OffsetDateTime.parse("2021-10-25T12:00:00.123Z"))
                            .msnLocName("KLSV")
                            .msnLocPtBarT("330T-PT ALFA-50NM")
                            .msnLocPtLat(35.123)
                            .msnLocPtLon(79.01)
                            .msnLocPtName("PT ALFA")
                            .build()
                    )
                    .alertStatus(30)
                    .amcMsnNum("AMC:JJXD123HA045")
                    .depLocLat(35.123)
                    .depLocLon(79.2354)
                    .depLocName("ICAO:KBIF")
                    .depLocUtm("32WDL123123")
                    .depTime(OffsetDateTime.parse("2021-10-25T12:00:00.123Z"))
                    .addIndAcTasking(
                        AirTaskingOrderCreateParams.AcMsnTasking.IndAcTasking.builder()
                            .acftType("F35A")
                            .callSign("EAGLE47")
                            .iffSifMode1Code("111")
                            .iffSifMode2Code("20147")
                            .iffSifMode3Code("30147")
                            .addJuAddress(12345)
                            .addJuAddress(65432)
                            .link16CallSign("EE47")
                            .numAcft(2)
                            .priConfigCode("6A2W3")
                            .secConfigCode("2S2WG")
                            .tacanChan(123)
                            .build()
                    )
                    .msnCommander("MC")
                    .msnNum("D123HA")
                    .pkgId("ZZ")
                    .priMsnType("CAS")
                    .addRcvyLocLat(48.8584)
                    .addRcvyLocLat(40.7554)
                    .addRcvyLocLon(2.2945)
                    .addRcvyLocLon(-73.9866)
                    .addRcvyLocName("ARRLOC:KBIF")
                    .addRcvyLocName("ARRLOC:KDZ7")
                    .addRcvyLocUtm("ARRUTMO:32WDL123123")
                    .addRcvyLocUtm("ARRUTMO:32WDL321321")
                    .addRcvyTime(OffsetDateTime.parse("2021-10-25T16:00:00.234Z"))
                    .addRcvyTime(OffsetDateTime.parse("2021-10-26T16:00:00.234Z"))
                    .resMsnInd("N")
                    .secMsnType("SEAD")
                    .unitLocName("ICAO:KXXQ")
                    .build()
            )
        assertThat(body.createdAt()).contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(body.createdBy()).contains("some.user")
        assertThat(body.endTs()).contains(OffsetDateTime.parse("2023-10-27T12:00:00.123Z"))
        assertThat(body.genText().getOrNull())
            .containsExactly(
                AirTaskingOrderCreateParams.GenText.builder()
                    .text("FREE-TEXT")
                    .textInd("OPENING REMARKS")
                    .build()
            )
        assertThat(body.msgMonth()).contains("OCT")
        assertThat(body.msgOriginator()).contains("USCENTCOM")
        assertThat(body.msgQualifier()).contains("CHG")
        assertThat(body.msgSn()).contains("ATO A")
        assertThat(body.navalFltOps().getOrNull())
            .containsExactly(
                AirTaskingOrderCreateParams.NavalFltOp.builder()
                    .shipName("USS WASP")
                    .fltOpStart(OffsetDateTime.parse("2021-02-25T12:00:00.123Z"))
                    .fltOpStop(OffsetDateTime.parse("2021-02-25T12:00:00.123Z"))
                    .addSchdLaunchRcvyTime(OffsetDateTime.parse("2021-02-25T12:00:00.123Z"))
                    .build()
            )
        assertThat(body.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(body.origNetwork()).contains("ORIG")
        assertThat(body.rawFileUri()).contains("Example URI")
        assertThat(body.sourceDl()).contains("AXE")
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            AirTaskingOrderCreateParams.builder()
                .beginTs(OffsetDateTime.parse("2023-10-25T12:00:00.123Z"))
                .classificationMarking("U")
                .dataMode(AirTaskingOrderCreateParams.DataMode.TEST)
                .opExerName("DESERT WIND")
                .source("Bluestaq")
                .build()

        val body = params._body()

        assertThat(body.beginTs()).isEqualTo(OffsetDateTime.parse("2023-10-25T12:00:00.123Z"))
        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(AirTaskingOrderCreateParams.DataMode.TEST)
        assertThat(body.opExerName()).isEqualTo("DESERT WIND")
        assertThat(body.source()).isEqualTo("Bluestaq")
    }
}
