// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.trackroute

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class TrackRouteListResponseTest {

    @Test
    fun create() {
        val trackRouteListResponse =
            TrackRouteListResponse.builder()
                .classificationMarking("U")
                .dataMode(TrackRouteListResponse.DataMode.TEST)
                .lastUpdateDate(OffsetDateTime.parse("2024-09-17T16:00:00.123Z"))
                .source("Bluestaq")
                .type("AIR REFUELING")
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .addAltitudeBlock(
                    TrackRouteListResponse.AltitudeBlock.builder()
                        .altitudeSequenceId("A1")
                        .lowerAltitude(27000.1)
                        .upperAltitude(27200.5)
                        .build()
                )
                .apnSetting("1-3-1")
                .apxBeaconCode("5/1")
                .artccMessage("OAKLAND CTR/GUAM CERAP")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .creatingOrg("HQPAC")
                .direction("NE")
                .effectiveDate(OffsetDateTime.parse("2024-09-17T16:00:00.123Z"))
                .externalId("GDSSMH121004232315303094")
                .lastUsedDate(OffsetDateTime.parse("2024-09-17T16:00:00.123Z"))
                .locationTrackId("POACHR")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .addPoc(
                    TrackRouteListResponse.Poc.builder()
                        .office("A34")
                        .phone("8675309")
                        .pocName("Fred Smith")
                        .pocOrg("HQAF")
                        .pocSequenceId(1)
                        .pocTypeName("Originator")
                        .rank("Capt")
                        .remark("POC remark.")
                        .username("fgsmith")
                        .build()
                )
                .priFreq(357.5)
                .receiverTankerChCode("31/094")
                .regionCode("5")
                .regionName("North America")
                .reviewDate(OffsetDateTime.parse("2024-09-16T16:00:00.123Z"))
                .addRoutePoint(
                    TrackRouteListResponse.RoutePoint.builder()
                        .altCountryCode("IZ")
                        .countryCode("NL")
                        .dafifPt(true)
                        .magDec(7.35)
                        .navaid("HTO")
                        .navaidLength(100.2)
                        .navaidType("VORTAC")
                        .ptLat(45.23)
                        .ptLon(179.1)
                        .ptSequenceId(1)
                        .ptTypeCode("EP")
                        .ptTypeName("ENTRY POINT")
                        .waypointName("KCHS")
                        .build()
                )
                .schedulerOrgName("97 OSS/OSOS DSN 866-5555")
                .schedulerOrgUnit("612 AOC")
                .secFreq(319.7)
                .shortName("CH61")
                .sic("N")
                .sourceDl("AXE")
                .trackId("CH61A")
                .trackName("CH61 POST")
                .typeCode("V")
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .build()

        assertThat(trackRouteListResponse.classificationMarking()).isEqualTo("U")
        assertThat(trackRouteListResponse.dataMode())
            .isEqualTo(TrackRouteListResponse.DataMode.TEST)
        assertThat(trackRouteListResponse.lastUpdateDate())
            .isEqualTo(OffsetDateTime.parse("2024-09-17T16:00:00.123Z"))
        assertThat(trackRouteListResponse.source()).isEqualTo("Bluestaq")
        assertThat(trackRouteListResponse.type()).isEqualTo("AIR REFUELING")
        assertThat(trackRouteListResponse.id()).contains("026dd511-8ba5-47d3-9909-836149f87686")
        assertThat(trackRouteListResponse.altitudeBlocks().getOrNull())
            .containsExactly(
                TrackRouteListResponse.AltitudeBlock.builder()
                    .altitudeSequenceId("A1")
                    .lowerAltitude(27000.1)
                    .upperAltitude(27200.5)
                    .build()
            )
        assertThat(trackRouteListResponse.apnSetting()).contains("1-3-1")
        assertThat(trackRouteListResponse.apxBeaconCode()).contains("5/1")
        assertThat(trackRouteListResponse.artccMessage()).contains("OAKLAND CTR/GUAM CERAP")
        assertThat(trackRouteListResponse.createdAt())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(trackRouteListResponse.createdBy()).contains("some.user")
        assertThat(trackRouteListResponse.creatingOrg()).contains("HQPAC")
        assertThat(trackRouteListResponse.direction()).contains("NE")
        assertThat(trackRouteListResponse.effectiveDate())
            .contains(OffsetDateTime.parse("2024-09-17T16:00:00.123Z"))
        assertThat(trackRouteListResponse.externalId()).contains("GDSSMH121004232315303094")
        assertThat(trackRouteListResponse.lastUsedDate())
            .contains(OffsetDateTime.parse("2024-09-17T16:00:00.123Z"))
        assertThat(trackRouteListResponse.locationTrackId()).contains("POACHR")
        assertThat(trackRouteListResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(trackRouteListResponse.origNetwork()).contains("OPS1")
        assertThat(trackRouteListResponse.poc().getOrNull())
            .containsExactly(
                TrackRouteListResponse.Poc.builder()
                    .office("A34")
                    .phone("8675309")
                    .pocName("Fred Smith")
                    .pocOrg("HQAF")
                    .pocSequenceId(1)
                    .pocTypeName("Originator")
                    .rank("Capt")
                    .remark("POC remark.")
                    .username("fgsmith")
                    .build()
            )
        assertThat(trackRouteListResponse.priFreq()).contains(357.5)
        assertThat(trackRouteListResponse.receiverTankerChCode()).contains("31/094")
        assertThat(trackRouteListResponse.regionCode()).contains("5")
        assertThat(trackRouteListResponse.regionName()).contains("North America")
        assertThat(trackRouteListResponse.reviewDate())
            .contains(OffsetDateTime.parse("2024-09-16T16:00:00.123Z"))
        assertThat(trackRouteListResponse.routePoints().getOrNull())
            .containsExactly(
                TrackRouteListResponse.RoutePoint.builder()
                    .altCountryCode("IZ")
                    .countryCode("NL")
                    .dafifPt(true)
                    .magDec(7.35)
                    .navaid("HTO")
                    .navaidLength(100.2)
                    .navaidType("VORTAC")
                    .ptLat(45.23)
                    .ptLon(179.1)
                    .ptSequenceId(1)
                    .ptTypeCode("EP")
                    .ptTypeName("ENTRY POINT")
                    .waypointName("KCHS")
                    .build()
            )
        assertThat(trackRouteListResponse.schedulerOrgName()).contains("97 OSS/OSOS DSN 866-5555")
        assertThat(trackRouteListResponse.schedulerOrgUnit()).contains("612 AOC")
        assertThat(trackRouteListResponse.secFreq()).contains(319.7)
        assertThat(trackRouteListResponse.shortName()).contains("CH61")
        assertThat(trackRouteListResponse.sic()).contains("N")
        assertThat(trackRouteListResponse.sourceDl()).contains("AXE")
        assertThat(trackRouteListResponse.trackId()).contains("CH61A")
        assertThat(trackRouteListResponse.trackName()).contains("CH61 POST")
        assertThat(trackRouteListResponse.typeCode()).contains("V")
        assertThat(trackRouteListResponse.updatedAt())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(trackRouteListResponse.updatedBy()).contains("some.user")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val trackRouteListResponse =
            TrackRouteListResponse.builder()
                .classificationMarking("U")
                .dataMode(TrackRouteListResponse.DataMode.TEST)
                .lastUpdateDate(OffsetDateTime.parse("2024-09-17T16:00:00.123Z"))
                .source("Bluestaq")
                .type("AIR REFUELING")
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .addAltitudeBlock(
                    TrackRouteListResponse.AltitudeBlock.builder()
                        .altitudeSequenceId("A1")
                        .lowerAltitude(27000.1)
                        .upperAltitude(27200.5)
                        .build()
                )
                .apnSetting("1-3-1")
                .apxBeaconCode("5/1")
                .artccMessage("OAKLAND CTR/GUAM CERAP")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .creatingOrg("HQPAC")
                .direction("NE")
                .effectiveDate(OffsetDateTime.parse("2024-09-17T16:00:00.123Z"))
                .externalId("GDSSMH121004232315303094")
                .lastUsedDate(OffsetDateTime.parse("2024-09-17T16:00:00.123Z"))
                .locationTrackId("POACHR")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .addPoc(
                    TrackRouteListResponse.Poc.builder()
                        .office("A34")
                        .phone("8675309")
                        .pocName("Fred Smith")
                        .pocOrg("HQAF")
                        .pocSequenceId(1)
                        .pocTypeName("Originator")
                        .rank("Capt")
                        .remark("POC remark.")
                        .username("fgsmith")
                        .build()
                )
                .priFreq(357.5)
                .receiverTankerChCode("31/094")
                .regionCode("5")
                .regionName("North America")
                .reviewDate(OffsetDateTime.parse("2024-09-16T16:00:00.123Z"))
                .addRoutePoint(
                    TrackRouteListResponse.RoutePoint.builder()
                        .altCountryCode("IZ")
                        .countryCode("NL")
                        .dafifPt(true)
                        .magDec(7.35)
                        .navaid("HTO")
                        .navaidLength(100.2)
                        .navaidType("VORTAC")
                        .ptLat(45.23)
                        .ptLon(179.1)
                        .ptSequenceId(1)
                        .ptTypeCode("EP")
                        .ptTypeName("ENTRY POINT")
                        .waypointName("KCHS")
                        .build()
                )
                .schedulerOrgName("97 OSS/OSOS DSN 866-5555")
                .schedulerOrgUnit("612 AOC")
                .secFreq(319.7)
                .shortName("CH61")
                .sic("N")
                .sourceDl("AXE")
                .trackId("CH61A")
                .trackName("CH61 POST")
                .typeCode("V")
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .build()

        val roundtrippedTrackRouteListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(trackRouteListResponse),
                jacksonTypeRef<TrackRouteListResponse>(),
            )

        assertThat(roundtrippedTrackRouteListResponse).isEqualTo(trackRouteListResponse)
    }
}
