// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.aviationriskmanagement

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import com.unifieddatalibrary.api.models.aviationriskmanagement.AviationRiskManagementRetrieveResponse
import java.time.LocalDate
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AviationRiskManagementRetrieveResponseTest {

    @Test
    fun create() {
      val aviationRiskManagementRetrieveResponse = AviationRiskManagementRetrieveResponse.builder()
          .classificationMarking("U")
          .dataMode(AviationRiskManagementRetrieveResponse.DataMode.TEST)
          .idMission("fa18d96e-91ea-60da-a7a8-1af6500066c8")
          .source("Bluestaq")
          .id("026dd511-8ba5-47d3-9909-836149f87686")
          .addAviationRiskManagementWorksheetRecord(AviationRiskManagementRetrieveResponse.AviationRiskManagementWorksheetRecord.builder()
              .missionDate(LocalDate.parse("2024-11-25"))
              .aircraftMds("E-2C HAWKEYE")
              .approvalPending(true)
              .approved(false)
              .addAviationRiskManagementWorksheetScore(AviationRiskManagementRetrieveResponse.AviationRiskManagementWorksheetRecord.AviationRiskManagementWorksheetScore.builder()
                  .approvalDate(OffsetDateTime.parse("2024-11-01T16:00:00.123Z"))
                  .approvedBy("John Smith")
                  .approvedCode(0)
                  .addAviationRiskManagementSortie(AviationRiskManagementRetrieveResponse.AviationRiskManagementWorksheetRecord.AviationRiskManagementWorksheetScore.AviationRiskManagementSortie.builder()
                      .extSortieId("MB014313032022407540")
                      .idSortie("4ef3d1e8-ab08-ab70-498f-edc479734e5c")
                      .legNum(100)
                      .sortieScore(3)
                      .build())
                  .extScoreId("BM022301191649232740")
                  .riskCategory("Crew/Aircraft")
                  .riskDescription("Upgrade training")
                  .riskKey("26")
                  .riskName("Crew Qualification")
                  .score(1)
                  .scoreRemark("Worksheet score remark.")
                  .build())
              .dispositionComments("Disposition comment.")
              .extRecordId("B022401191649232716")
              .itinerary("RJTY-PGUA-RJTY")
              .lastUpdatedAt(OffsetDateTime.parse("2024-11-02T16:00:00.123Z"))
              .remarks("Worksheet record remark.")
              .severityLevel(0)
              .submissionDate(OffsetDateTime.parse("2024-11-01T16:00:00.123Z"))
              .tierNumber(2)
              .totalScore(11)
              .userId("TIER0SCORING")
              .build())
          .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
          .createdBy("some.user")
          .extMissionId("MCD04250106123509230")
          .missionNumber("LVM134412001")
          .orgId("50000002")
          .origin("THIRD_PARTY_DATASOURCE")
          .origNetwork("ORIG")
          .sourceDl("AXE")
          .unitId("63")
          .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
          .updatedBy("some.user")
          .build()

      assertThat(aviationRiskManagementRetrieveResponse.classificationMarking()).isEqualTo("U")
      assertThat(aviationRiskManagementRetrieveResponse.dataMode()).isEqualTo(AviationRiskManagementRetrieveResponse.DataMode.TEST)
      assertThat(aviationRiskManagementRetrieveResponse.idMission()).isEqualTo("fa18d96e-91ea-60da-a7a8-1af6500066c8")
      assertThat(aviationRiskManagementRetrieveResponse.source()).isEqualTo("Bluestaq")
      assertThat(aviationRiskManagementRetrieveResponse.id()).contains("026dd511-8ba5-47d3-9909-836149f87686")
      assertThat(aviationRiskManagementRetrieveResponse.aviationRiskManagementWorksheetRecord().getOrNull()).containsExactly(AviationRiskManagementRetrieveResponse.AviationRiskManagementWorksheetRecord.builder()
          .missionDate(LocalDate.parse("2024-11-25"))
          .aircraftMds("E-2C HAWKEYE")
          .approvalPending(true)
          .approved(false)
          .addAviationRiskManagementWorksheetScore(AviationRiskManagementRetrieveResponse.AviationRiskManagementWorksheetRecord.AviationRiskManagementWorksheetScore.builder()
              .approvalDate(OffsetDateTime.parse("2024-11-01T16:00:00.123Z"))
              .approvedBy("John Smith")
              .approvedCode(0)
              .addAviationRiskManagementSortie(AviationRiskManagementRetrieveResponse.AviationRiskManagementWorksheetRecord.AviationRiskManagementWorksheetScore.AviationRiskManagementSortie.builder()
                  .extSortieId("MB014313032022407540")
                  .idSortie("4ef3d1e8-ab08-ab70-498f-edc479734e5c")
                  .legNum(100)
                  .sortieScore(3)
                  .build())
              .extScoreId("BM022301191649232740")
              .riskCategory("Crew/Aircraft")
              .riskDescription("Upgrade training")
              .riskKey("26")
              .riskName("Crew Qualification")
              .score(1)
              .scoreRemark("Worksheet score remark.")
              .build())
          .dispositionComments("Disposition comment.")
          .extRecordId("B022401191649232716")
          .itinerary("RJTY-PGUA-RJTY")
          .lastUpdatedAt(OffsetDateTime.parse("2024-11-02T16:00:00.123Z"))
          .remarks("Worksheet record remark.")
          .severityLevel(0)
          .submissionDate(OffsetDateTime.parse("2024-11-01T16:00:00.123Z"))
          .tierNumber(2)
          .totalScore(11)
          .userId("TIER0SCORING")
          .build())
      assertThat(aviationRiskManagementRetrieveResponse.createdAt()).contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
      assertThat(aviationRiskManagementRetrieveResponse.createdBy()).contains("some.user")
      assertThat(aviationRiskManagementRetrieveResponse.extMissionId()).contains("MCD04250106123509230")
      assertThat(aviationRiskManagementRetrieveResponse.missionNumber()).contains("LVM134412001")
      assertThat(aviationRiskManagementRetrieveResponse.orgId()).contains("50000002")
      assertThat(aviationRiskManagementRetrieveResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
      assertThat(aviationRiskManagementRetrieveResponse.origNetwork()).contains("ORIG")
      assertThat(aviationRiskManagementRetrieveResponse.sourceDl()).contains("AXE")
      assertThat(aviationRiskManagementRetrieveResponse.unitId()).contains("63")
      assertThat(aviationRiskManagementRetrieveResponse.updatedAt()).contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
      assertThat(aviationRiskManagementRetrieveResponse.updatedBy()).contains("some.user")
    }

    @Test
    fun roundtrip() {
      val jsonMapper = jsonMapper()
      val aviationRiskManagementRetrieveResponse = AviationRiskManagementRetrieveResponse.builder()
          .classificationMarking("U")
          .dataMode(AviationRiskManagementRetrieveResponse.DataMode.TEST)
          .idMission("fa18d96e-91ea-60da-a7a8-1af6500066c8")
          .source("Bluestaq")
          .id("026dd511-8ba5-47d3-9909-836149f87686")
          .addAviationRiskManagementWorksheetRecord(AviationRiskManagementRetrieveResponse.AviationRiskManagementWorksheetRecord.builder()
              .missionDate(LocalDate.parse("2024-11-25"))
              .aircraftMds("E-2C HAWKEYE")
              .approvalPending(true)
              .approved(false)
              .addAviationRiskManagementWorksheetScore(AviationRiskManagementRetrieveResponse.AviationRiskManagementWorksheetRecord.AviationRiskManagementWorksheetScore.builder()
                  .approvalDate(OffsetDateTime.parse("2024-11-01T16:00:00.123Z"))
                  .approvedBy("John Smith")
                  .approvedCode(0)
                  .addAviationRiskManagementSortie(AviationRiskManagementRetrieveResponse.AviationRiskManagementWorksheetRecord.AviationRiskManagementWorksheetScore.AviationRiskManagementSortie.builder()
                      .extSortieId("MB014313032022407540")
                      .idSortie("4ef3d1e8-ab08-ab70-498f-edc479734e5c")
                      .legNum(100)
                      .sortieScore(3)
                      .build())
                  .extScoreId("BM022301191649232740")
                  .riskCategory("Crew/Aircraft")
                  .riskDescription("Upgrade training")
                  .riskKey("26")
                  .riskName("Crew Qualification")
                  .score(1)
                  .scoreRemark("Worksheet score remark.")
                  .build())
              .dispositionComments("Disposition comment.")
              .extRecordId("B022401191649232716")
              .itinerary("RJTY-PGUA-RJTY")
              .lastUpdatedAt(OffsetDateTime.parse("2024-11-02T16:00:00.123Z"))
              .remarks("Worksheet record remark.")
              .severityLevel(0)
              .submissionDate(OffsetDateTime.parse("2024-11-01T16:00:00.123Z"))
              .tierNumber(2)
              .totalScore(11)
              .userId("TIER0SCORING")
              .build())
          .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
          .createdBy("some.user")
          .extMissionId("MCD04250106123509230")
          .missionNumber("LVM134412001")
          .orgId("50000002")
          .origin("THIRD_PARTY_DATASOURCE")
          .origNetwork("ORIG")
          .sourceDl("AXE")
          .unitId("63")
          .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
          .updatedBy("some.user")
          .build()

      val roundtrippedAviationRiskManagementRetrieveResponse = jsonMapper.readValue(jsonMapper.writeValueAsString(aviationRiskManagementRetrieveResponse), jacksonTypeRef<AviationRiskManagementRetrieveResponse>())

      assertThat(roundtrippedAviationRiskManagementRetrieveResponse).isEqualTo(aviationRiskManagementRetrieveResponse)
    }
}
