// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.personnelrecovery

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class PersonnelrecoveryCreateParamsTest {

    @Test
    fun create() {
        PersonnelrecoveryCreateParams.builder()
            .classificationMarking("U")
            .dataMode(PersonnelrecoveryCreateParams.DataMode.TEST)
            .msgTime(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
            .pickupLat(75.1234)
            .pickupLon(175.1234)
            .source("Bluestaq")
            .type("MEDICAL")
            .id("PERSONNEL_RECOVERY-ID")
            .authMethod("PASSPORT")
            .authStatus("NO STATEMENT")
            .beaconInd(false)
            .callSign("BADGER")
            .commEq1("LL PHONE")
            .commEq2("LL PHONE")
            .commEq3("LL PHONE")
            .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
            .createdBy("some.user")
            .executionInfo(
                PersonnelrecoveryCreateParams.ExecutionInfo.builder()
                    .egress(66.53)
                    .addEgressPoint(107.23)
                    .addEgressPoint(30.455)
                    .escortVehicle(
                        PersonnelrecoveryCreateParams.ExecutionInfo.EscortVehicle.builder()
                            .callSign("FALCO")
                            .primaryFreq(34.55)
                            .strength(5)
                            .type("C17")
                            .build()
                    )
                    .ingress(35.66)
                    .addInitialPoint(103.23)
                    .addInitialPoint(30.445)
                    .objStrategy("Description of strategy plan.")
                    .recoveryVehicle(
                        PersonnelrecoveryCreateParams.ExecutionInfo.RecoveryVehicle.builder()
                            .callSign("FALCO")
                            .primaryFreq(34.55)
                            .strength(5)
                            .type("C17")
                            .build()
                    )
                    .build()
            )
            .identity("NEUTRAL CIVILIAN")
            .idWeatherReport("WEATHER_REPORT-ID")
            .milClass("CIVILIAN")
            .natAlliance(1)
            .natAlliance1(0)
            .numAmbulatory(1)
            .numAmbulatoryInjured(2)
            .numNonAmbulatory(0)
            .numPersons(1)
            .objectiveAreaInfo(
                PersonnelrecoveryCreateParams.ObjectiveAreaInfo.builder()
                    .addEnemyData(
                        PersonnelrecoveryCreateParams.ObjectiveAreaInfo.EnemyData.builder()
                            .dirToEnemy("NORTHWEST")
                            .friendliesRemarks("Comments from friendlies.")
                            .hlzRemarks("Hot Landing Zone remarks.")
                            .hostileFireType("SMALL ARMS")
                            .build()
                    )
                    .oscCallSign("STARFOX")
                    .oscFreq(12.55)
                    .pzDesc("Near the lake.")
                    .addPzLocation(103.23)
                    .addPzLocation(30.445)
                    .build()
            )
            .origin("THIRD_PARTY_DATASOURCE")
            .origNetwork("OPS1")
            .pickupAlt(30.1234)
            .recovId("RECOV-ID")
            .rxFreq(5.5)
            .survivorMessages("UNINJURED CANT MOVE HOSTILES NEARBY")
            .survivorRadio("NO STATEMENT")
            .termInd(true)
            .textMsg("Additional message from survivor.")
            .txFreq(5.5)
            .build()
    }

    @Test
    fun body() {
        val params =
            PersonnelrecoveryCreateParams.builder()
                .classificationMarking("U")
                .dataMode(PersonnelrecoveryCreateParams.DataMode.TEST)
                .msgTime(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                .pickupLat(75.1234)
                .pickupLon(175.1234)
                .source("Bluestaq")
                .type("MEDICAL")
                .id("PERSONNEL_RECOVERY-ID")
                .authMethod("PASSPORT")
                .authStatus("NO STATEMENT")
                .beaconInd(false)
                .callSign("BADGER")
                .commEq1("LL PHONE")
                .commEq2("LL PHONE")
                .commEq3("LL PHONE")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .executionInfo(
                    PersonnelrecoveryCreateParams.ExecutionInfo.builder()
                        .egress(66.53)
                        .addEgressPoint(107.23)
                        .addEgressPoint(30.455)
                        .escortVehicle(
                            PersonnelrecoveryCreateParams.ExecutionInfo.EscortVehicle.builder()
                                .callSign("FALCO")
                                .primaryFreq(34.55)
                                .strength(5)
                                .type("C17")
                                .build()
                        )
                        .ingress(35.66)
                        .addInitialPoint(103.23)
                        .addInitialPoint(30.445)
                        .objStrategy("Description of strategy plan.")
                        .recoveryVehicle(
                            PersonnelrecoveryCreateParams.ExecutionInfo.RecoveryVehicle.builder()
                                .callSign("FALCO")
                                .primaryFreq(34.55)
                                .strength(5)
                                .type("C17")
                                .build()
                        )
                        .build()
                )
                .identity("NEUTRAL CIVILIAN")
                .idWeatherReport("WEATHER_REPORT-ID")
                .milClass("CIVILIAN")
                .natAlliance(1)
                .natAlliance1(0)
                .numAmbulatory(1)
                .numAmbulatoryInjured(2)
                .numNonAmbulatory(0)
                .numPersons(1)
                .objectiveAreaInfo(
                    PersonnelrecoveryCreateParams.ObjectiveAreaInfo.builder()
                        .addEnemyData(
                            PersonnelrecoveryCreateParams.ObjectiveAreaInfo.EnemyData.builder()
                                .dirToEnemy("NORTHWEST")
                                .friendliesRemarks("Comments from friendlies.")
                                .hlzRemarks("Hot Landing Zone remarks.")
                                .hostileFireType("SMALL ARMS")
                                .build()
                        )
                        .oscCallSign("STARFOX")
                        .oscFreq(12.55)
                        .pzDesc("Near the lake.")
                        .addPzLocation(103.23)
                        .addPzLocation(30.445)
                        .build()
                )
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .pickupAlt(30.1234)
                .recovId("RECOV-ID")
                .rxFreq(5.5)
                .survivorMessages("UNINJURED CANT MOVE HOSTILES NEARBY")
                .survivorRadio("NO STATEMENT")
                .termInd(true)
                .textMsg("Additional message from survivor.")
                .txFreq(5.5)
                .build()

        val body = params._body()

        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(PersonnelrecoveryCreateParams.DataMode.TEST)
        assertThat(body.msgTime()).isEqualTo(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
        assertThat(body.pickupLat()).isEqualTo(75.1234)
        assertThat(body.pickupLon()).isEqualTo(175.1234)
        assertThat(body.source()).isEqualTo("Bluestaq")
        assertThat(body.type()).isEqualTo("MEDICAL")
        assertThat(body.id()).contains("PERSONNEL_RECOVERY-ID")
        assertThat(body.authMethod()).contains("PASSPORT")
        assertThat(body.authStatus()).contains("NO STATEMENT")
        assertThat(body.beaconInd()).contains(false)
        assertThat(body.callSign()).contains("BADGER")
        assertThat(body.commEq1()).contains("LL PHONE")
        assertThat(body.commEq2()).contains("LL PHONE")
        assertThat(body.commEq3()).contains("LL PHONE")
        assertThat(body.createdAt()).contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(body.createdBy()).contains("some.user")
        assertThat(body.executionInfo())
            .contains(
                PersonnelrecoveryCreateParams.ExecutionInfo.builder()
                    .egress(66.53)
                    .addEgressPoint(107.23)
                    .addEgressPoint(30.455)
                    .escortVehicle(
                        PersonnelrecoveryCreateParams.ExecutionInfo.EscortVehicle.builder()
                            .callSign("FALCO")
                            .primaryFreq(34.55)
                            .strength(5)
                            .type("C17")
                            .build()
                    )
                    .ingress(35.66)
                    .addInitialPoint(103.23)
                    .addInitialPoint(30.445)
                    .objStrategy("Description of strategy plan.")
                    .recoveryVehicle(
                        PersonnelrecoveryCreateParams.ExecutionInfo.RecoveryVehicle.builder()
                            .callSign("FALCO")
                            .primaryFreq(34.55)
                            .strength(5)
                            .type("C17")
                            .build()
                    )
                    .build()
            )
        assertThat(body.identity()).contains("NEUTRAL CIVILIAN")
        assertThat(body.idWeatherReport()).contains("WEATHER_REPORT-ID")
        assertThat(body.milClass()).contains("CIVILIAN")
        assertThat(body.natAlliance()).contains(1)
        assertThat(body.natAlliance1()).contains(0)
        assertThat(body.numAmbulatory()).contains(1)
        assertThat(body.numAmbulatoryInjured()).contains(2)
        assertThat(body.numNonAmbulatory()).contains(0)
        assertThat(body.numPersons()).contains(1)
        assertThat(body.objectiveAreaInfo())
            .contains(
                PersonnelrecoveryCreateParams.ObjectiveAreaInfo.builder()
                    .addEnemyData(
                        PersonnelrecoveryCreateParams.ObjectiveAreaInfo.EnemyData.builder()
                            .dirToEnemy("NORTHWEST")
                            .friendliesRemarks("Comments from friendlies.")
                            .hlzRemarks("Hot Landing Zone remarks.")
                            .hostileFireType("SMALL ARMS")
                            .build()
                    )
                    .oscCallSign("STARFOX")
                    .oscFreq(12.55)
                    .pzDesc("Near the lake.")
                    .addPzLocation(103.23)
                    .addPzLocation(30.445)
                    .build()
            )
        assertThat(body.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(body.origNetwork()).contains("OPS1")
        assertThat(body.pickupAlt()).contains(30.1234)
        assertThat(body.recovId()).contains("RECOV-ID")
        assertThat(body.rxFreq()).contains(5.5)
        assertThat(body.survivorMessages()).contains("UNINJURED CANT MOVE HOSTILES NEARBY")
        assertThat(body.survivorRadio()).contains("NO STATEMENT")
        assertThat(body.termInd()).contains(true)
        assertThat(body.textMsg()).contains("Additional message from survivor.")
        assertThat(body.txFreq()).contains(5.5)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            PersonnelrecoveryCreateParams.builder()
                .classificationMarking("U")
                .dataMode(PersonnelrecoveryCreateParams.DataMode.TEST)
                .msgTime(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                .pickupLat(75.1234)
                .pickupLon(175.1234)
                .source("Bluestaq")
                .type("MEDICAL")
                .build()

        val body = params._body()

        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(PersonnelrecoveryCreateParams.DataMode.TEST)
        assertThat(body.msgTime()).isEqualTo(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
        assertThat(body.pickupLat()).isEqualTo(75.1234)
        assertThat(body.pickupLon()).isEqualTo(175.1234)
        assertThat(body.source()).isEqualTo("Bluestaq")
        assertThat(body.type()).isEqualTo("MEDICAL")
    }
}
