// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.sensor.calibration

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CalibrationQueryResponseTest {

    @Test
    fun create() {
        val calibrationQueryResponse =
            CalibrationQueryResponse.builder()
                .classificationMarking("U")
                .dataMode(CalibrationQueryResponse.DataMode.TEST)
                .idSensor("09f2c68c-5e24-4b72-9cc8-ba9b1efa82f0")
                .source("Bluestaq")
                .startTime(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .azRaAccelBias(0.0123)
                .azRaAccelSigma(0.0123)
                .azRaBias(0.327883)
                .azRaRateBias(0.123)
                .azRaRateSigma(0.123)
                .azRaRms(0.605333)
                .azRaSigma(0.000381)
                .calAngleRef("AZEL")
                .calTrackMode("INTRA_TRACK")
                .calType("OPERATIONAL")
                .confidenceNoiseBias(0.001477)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .duration(14.125)
                .ecr(listOf(352815.1, -5852915.3, 3255189.0))
                .elDecAccelBias(0.0123)
                .elDecAccelSigma(0.0123)
                .elDecBias(0.012555)
                .elDecRateBias(0.123)
                .elDecRateSigma(0.123)
                .elDecRms(0.080505)
                .elDecSigma(0.00265)
                .endTime(OffsetDateTime.parse("2018-01-14T16:00:00.123Z"))
                .numAzRaObs(339)
                .numElDecObs(339)
                .numObs(341)
                .numPhotoObs(77)
                .numRangeObs(341)
                .numRangeRateObs(341)
                .numRcsObs(325)
                .numTimeObs(307)
                .numTracks(85)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .photoBias(0.123)
                .photoSigma(0.0123)
                .rangeAccelBias(0.123)
                .rangeAccelSigma(0.0123)
                .rangeBias(0.024777)
                .rangeRateBias(0.105333)
                .rangeRateRms(0.000227)
                .rangeRateSigma(0.000321)
                .rangeRms(0.0123)
                .rangeSigma(0.042644)
                .rcsBias(0.123)
                .rcsSigma(0.0123)
                .refTargets(listOf("xx", "yy", "zz"))
                .refType("SLR")
                .senType("PHASED ARRAY")
                .sourceDl("AXE")
                .timeBias(0.000372)
                .timeBiasSigma(15.333212)
                .build()

        assertThat(calibrationQueryResponse.classificationMarking()).isEqualTo("U")
        assertThat(calibrationQueryResponse.dataMode())
            .isEqualTo(CalibrationQueryResponse.DataMode.TEST)
        assertThat(calibrationQueryResponse.idSensor())
            .isEqualTo("09f2c68c-5e24-4b72-9cc8-ba9b1efa82f0")
        assertThat(calibrationQueryResponse.source()).isEqualTo("Bluestaq")
        assertThat(calibrationQueryResponse.startTime())
            .isEqualTo(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(calibrationQueryResponse.id()).contains("026dd511-8ba5-47d3-9909-836149f87686")
        assertThat(calibrationQueryResponse.azRaAccelBias()).contains(0.0123)
        assertThat(calibrationQueryResponse.azRaAccelSigma()).contains(0.0123)
        assertThat(calibrationQueryResponse.azRaBias()).contains(0.327883)
        assertThat(calibrationQueryResponse.azRaRateBias()).contains(0.123)
        assertThat(calibrationQueryResponse.azRaRateSigma()).contains(0.123)
        assertThat(calibrationQueryResponse.azRaRms()).contains(0.605333)
        assertThat(calibrationQueryResponse.azRaSigma()).contains(0.000381)
        assertThat(calibrationQueryResponse.calAngleRef()).contains("AZEL")
        assertThat(calibrationQueryResponse.calTrackMode()).contains("INTRA_TRACK")
        assertThat(calibrationQueryResponse.calType()).contains("OPERATIONAL")
        assertThat(calibrationQueryResponse.confidenceNoiseBias()).contains(0.001477)
        assertThat(calibrationQueryResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(calibrationQueryResponse.createdBy()).contains("some.user")
        assertThat(calibrationQueryResponse.duration()).contains(14.125)
        assertThat(calibrationQueryResponse.ecr().getOrNull())
            .containsExactly(352815.1, -5852915.3, 3255189.0)
        assertThat(calibrationQueryResponse.elDecAccelBias()).contains(0.0123)
        assertThat(calibrationQueryResponse.elDecAccelSigma()).contains(0.0123)
        assertThat(calibrationQueryResponse.elDecBias()).contains(0.012555)
        assertThat(calibrationQueryResponse.elDecRateBias()).contains(0.123)
        assertThat(calibrationQueryResponse.elDecRateSigma()).contains(0.123)
        assertThat(calibrationQueryResponse.elDecRms()).contains(0.080505)
        assertThat(calibrationQueryResponse.elDecSigma()).contains(0.00265)
        assertThat(calibrationQueryResponse.endTime())
            .contains(OffsetDateTime.parse("2018-01-14T16:00:00.123Z"))
        assertThat(calibrationQueryResponse.numAzRaObs()).contains(339)
        assertThat(calibrationQueryResponse.numElDecObs()).contains(339)
        assertThat(calibrationQueryResponse.numObs()).contains(341)
        assertThat(calibrationQueryResponse.numPhotoObs()).contains(77)
        assertThat(calibrationQueryResponse.numRangeObs()).contains(341)
        assertThat(calibrationQueryResponse.numRangeRateObs()).contains(341)
        assertThat(calibrationQueryResponse.numRcsObs()).contains(325)
        assertThat(calibrationQueryResponse.numTimeObs()).contains(307)
        assertThat(calibrationQueryResponse.numTracks()).contains(85)
        assertThat(calibrationQueryResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(calibrationQueryResponse.origNetwork()).contains("OPS1")
        assertThat(calibrationQueryResponse.photoBias()).contains(0.123)
        assertThat(calibrationQueryResponse.photoSigma()).contains(0.0123)
        assertThat(calibrationQueryResponse.rangeAccelBias()).contains(0.123)
        assertThat(calibrationQueryResponse.rangeAccelSigma()).contains(0.0123)
        assertThat(calibrationQueryResponse.rangeBias()).contains(0.024777)
        assertThat(calibrationQueryResponse.rangeRateBias()).contains(0.105333)
        assertThat(calibrationQueryResponse.rangeRateRms()).contains(0.000227)
        assertThat(calibrationQueryResponse.rangeRateSigma()).contains(0.000321)
        assertThat(calibrationQueryResponse.rangeRms()).contains(0.0123)
        assertThat(calibrationQueryResponse.rangeSigma()).contains(0.042644)
        assertThat(calibrationQueryResponse.rcsBias()).contains(0.123)
        assertThat(calibrationQueryResponse.rcsSigma()).contains(0.0123)
        assertThat(calibrationQueryResponse.refTargets().getOrNull())
            .containsExactly("xx", "yy", "zz")
        assertThat(calibrationQueryResponse.refType()).contains("SLR")
        assertThat(calibrationQueryResponse.senType()).contains("PHASED ARRAY")
        assertThat(calibrationQueryResponse.sourceDl()).contains("AXE")
        assertThat(calibrationQueryResponse.timeBias()).contains(0.000372)
        assertThat(calibrationQueryResponse.timeBiasSigma()).contains(15.333212)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val calibrationQueryResponse =
            CalibrationQueryResponse.builder()
                .classificationMarking("U")
                .dataMode(CalibrationQueryResponse.DataMode.TEST)
                .idSensor("09f2c68c-5e24-4b72-9cc8-ba9b1efa82f0")
                .source("Bluestaq")
                .startTime(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .azRaAccelBias(0.0123)
                .azRaAccelSigma(0.0123)
                .azRaBias(0.327883)
                .azRaRateBias(0.123)
                .azRaRateSigma(0.123)
                .azRaRms(0.605333)
                .azRaSigma(0.000381)
                .calAngleRef("AZEL")
                .calTrackMode("INTRA_TRACK")
                .calType("OPERATIONAL")
                .confidenceNoiseBias(0.001477)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .duration(14.125)
                .ecr(listOf(352815.1, -5852915.3, 3255189.0))
                .elDecAccelBias(0.0123)
                .elDecAccelSigma(0.0123)
                .elDecBias(0.012555)
                .elDecRateBias(0.123)
                .elDecRateSigma(0.123)
                .elDecRms(0.080505)
                .elDecSigma(0.00265)
                .endTime(OffsetDateTime.parse("2018-01-14T16:00:00.123Z"))
                .numAzRaObs(339)
                .numElDecObs(339)
                .numObs(341)
                .numPhotoObs(77)
                .numRangeObs(341)
                .numRangeRateObs(341)
                .numRcsObs(325)
                .numTimeObs(307)
                .numTracks(85)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .photoBias(0.123)
                .photoSigma(0.0123)
                .rangeAccelBias(0.123)
                .rangeAccelSigma(0.0123)
                .rangeBias(0.024777)
                .rangeRateBias(0.105333)
                .rangeRateRms(0.000227)
                .rangeRateSigma(0.000321)
                .rangeRms(0.0123)
                .rangeSigma(0.042644)
                .rcsBias(0.123)
                .rcsSigma(0.0123)
                .refTargets(listOf("xx", "yy", "zz"))
                .refType("SLR")
                .senType("PHASED ARRAY")
                .sourceDl("AXE")
                .timeBias(0.000372)
                .timeBiasSigma(15.333212)
                .build()

        val roundtrippedCalibrationQueryResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(calibrationQueryResponse),
                jacksonTypeRef<CalibrationQueryResponse>(),
            )

        assertThat(roundtrippedCalibrationQueryResponse).isEqualTo(calibrationQueryResponse)
    }
}
