// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.sensor.calibration

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CalibrationRetrieveResponseTest {

    @Test
    fun create() {
        val calibrationRetrieveResponse =
            CalibrationRetrieveResponse.builder()
                .classificationMarking("U")
                .dataMode(CalibrationRetrieveResponse.DataMode.TEST)
                .idSensor("09f2c68c-5e24-4b72-9cc8-ba9b1efa82f0")
                .source("Bluestaq")
                .startTime(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .azRaAccelBias(0.0123)
                .azRaAccelSigma(0.0123)
                .azRaBias(0.327883)
                .azRaRateBias(0.123)
                .azRaRateSigma(0.123)
                .azRaRms(0.605333)
                .azRaSigma(0.000381)
                .calAngleRef("AZEL")
                .calTrackMode("INTRA_TRACK")
                .calType("OPERATIONAL")
                .confidenceNoiseBias(0.001477)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .duration(14.125)
                .ecr(listOf(352815.1, -5852915.3, 3255189.0))
                .elDecAccelBias(0.0123)
                .elDecAccelSigma(0.0123)
                .elDecBias(0.012555)
                .elDecRateBias(0.123)
                .elDecRateSigma(0.123)
                .elDecRms(0.080505)
                .elDecSigma(0.00265)
                .endTime(OffsetDateTime.parse("2018-01-14T16:00:00.123Z"))
                .numAzRaObs(339)
                .numElDecObs(339)
                .numObs(341)
                .numPhotoObs(77)
                .numRangeObs(341)
                .numRangeRateObs(341)
                .numRcsObs(325)
                .numTimeObs(307)
                .numTracks(85)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .photoBias(0.123)
                .photoSigma(0.0123)
                .rangeAccelBias(0.123)
                .rangeAccelSigma(0.0123)
                .rangeBias(0.024777)
                .rangeRateBias(0.105333)
                .rangeRateRms(0.000227)
                .rangeRateSigma(0.000321)
                .rangeRms(0.0123)
                .rangeSigma(0.042644)
                .rcsBias(0.123)
                .rcsSigma(0.0123)
                .refTargets(listOf("xx", "yy", "zz"))
                .refType("SLR")
                .senType("PHASED ARRAY")
                .sourceDl("AXE")
                .timeBias(0.000372)
                .timeBiasSigma(15.333212)
                .build()

        assertThat(calibrationRetrieveResponse.classificationMarking()).isEqualTo("U")
        assertThat(calibrationRetrieveResponse.dataMode())
            .isEqualTo(CalibrationRetrieveResponse.DataMode.TEST)
        assertThat(calibrationRetrieveResponse.idSensor())
            .isEqualTo("09f2c68c-5e24-4b72-9cc8-ba9b1efa82f0")
        assertThat(calibrationRetrieveResponse.source()).isEqualTo("Bluestaq")
        assertThat(calibrationRetrieveResponse.startTime())
            .isEqualTo(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(calibrationRetrieveResponse.id())
            .contains("026dd511-8ba5-47d3-9909-836149f87686")
        assertThat(calibrationRetrieveResponse.azRaAccelBias()).contains(0.0123)
        assertThat(calibrationRetrieveResponse.azRaAccelSigma()).contains(0.0123)
        assertThat(calibrationRetrieveResponse.azRaBias()).contains(0.327883)
        assertThat(calibrationRetrieveResponse.azRaRateBias()).contains(0.123)
        assertThat(calibrationRetrieveResponse.azRaRateSigma()).contains(0.123)
        assertThat(calibrationRetrieveResponse.azRaRms()).contains(0.605333)
        assertThat(calibrationRetrieveResponse.azRaSigma()).contains(0.000381)
        assertThat(calibrationRetrieveResponse.calAngleRef()).contains("AZEL")
        assertThat(calibrationRetrieveResponse.calTrackMode()).contains("INTRA_TRACK")
        assertThat(calibrationRetrieveResponse.calType()).contains("OPERATIONAL")
        assertThat(calibrationRetrieveResponse.confidenceNoiseBias()).contains(0.001477)
        assertThat(calibrationRetrieveResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(calibrationRetrieveResponse.createdBy()).contains("some.user")
        assertThat(calibrationRetrieveResponse.duration()).contains(14.125)
        assertThat(calibrationRetrieveResponse.ecr().getOrNull())
            .containsExactly(352815.1, -5852915.3, 3255189.0)
        assertThat(calibrationRetrieveResponse.elDecAccelBias()).contains(0.0123)
        assertThat(calibrationRetrieveResponse.elDecAccelSigma()).contains(0.0123)
        assertThat(calibrationRetrieveResponse.elDecBias()).contains(0.012555)
        assertThat(calibrationRetrieveResponse.elDecRateBias()).contains(0.123)
        assertThat(calibrationRetrieveResponse.elDecRateSigma()).contains(0.123)
        assertThat(calibrationRetrieveResponse.elDecRms()).contains(0.080505)
        assertThat(calibrationRetrieveResponse.elDecSigma()).contains(0.00265)
        assertThat(calibrationRetrieveResponse.endTime())
            .contains(OffsetDateTime.parse("2018-01-14T16:00:00.123Z"))
        assertThat(calibrationRetrieveResponse.numAzRaObs()).contains(339)
        assertThat(calibrationRetrieveResponse.numElDecObs()).contains(339)
        assertThat(calibrationRetrieveResponse.numObs()).contains(341)
        assertThat(calibrationRetrieveResponse.numPhotoObs()).contains(77)
        assertThat(calibrationRetrieveResponse.numRangeObs()).contains(341)
        assertThat(calibrationRetrieveResponse.numRangeRateObs()).contains(341)
        assertThat(calibrationRetrieveResponse.numRcsObs()).contains(325)
        assertThat(calibrationRetrieveResponse.numTimeObs()).contains(307)
        assertThat(calibrationRetrieveResponse.numTracks()).contains(85)
        assertThat(calibrationRetrieveResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(calibrationRetrieveResponse.origNetwork()).contains("OPS1")
        assertThat(calibrationRetrieveResponse.photoBias()).contains(0.123)
        assertThat(calibrationRetrieveResponse.photoSigma()).contains(0.0123)
        assertThat(calibrationRetrieveResponse.rangeAccelBias()).contains(0.123)
        assertThat(calibrationRetrieveResponse.rangeAccelSigma()).contains(0.0123)
        assertThat(calibrationRetrieveResponse.rangeBias()).contains(0.024777)
        assertThat(calibrationRetrieveResponse.rangeRateBias()).contains(0.105333)
        assertThat(calibrationRetrieveResponse.rangeRateRms()).contains(0.000227)
        assertThat(calibrationRetrieveResponse.rangeRateSigma()).contains(0.000321)
        assertThat(calibrationRetrieveResponse.rangeRms()).contains(0.0123)
        assertThat(calibrationRetrieveResponse.rangeSigma()).contains(0.042644)
        assertThat(calibrationRetrieveResponse.rcsBias()).contains(0.123)
        assertThat(calibrationRetrieveResponse.rcsSigma()).contains(0.0123)
        assertThat(calibrationRetrieveResponse.refTargets().getOrNull())
            .containsExactly("xx", "yy", "zz")
        assertThat(calibrationRetrieveResponse.refType()).contains("SLR")
        assertThat(calibrationRetrieveResponse.senType()).contains("PHASED ARRAY")
        assertThat(calibrationRetrieveResponse.sourceDl()).contains("AXE")
        assertThat(calibrationRetrieveResponse.timeBias()).contains(0.000372)
        assertThat(calibrationRetrieveResponse.timeBiasSigma()).contains(15.333212)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val calibrationRetrieveResponse =
            CalibrationRetrieveResponse.builder()
                .classificationMarking("U")
                .dataMode(CalibrationRetrieveResponse.DataMode.TEST)
                .idSensor("09f2c68c-5e24-4b72-9cc8-ba9b1efa82f0")
                .source("Bluestaq")
                .startTime(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .azRaAccelBias(0.0123)
                .azRaAccelSigma(0.0123)
                .azRaBias(0.327883)
                .azRaRateBias(0.123)
                .azRaRateSigma(0.123)
                .azRaRms(0.605333)
                .azRaSigma(0.000381)
                .calAngleRef("AZEL")
                .calTrackMode("INTRA_TRACK")
                .calType("OPERATIONAL")
                .confidenceNoiseBias(0.001477)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .duration(14.125)
                .ecr(listOf(352815.1, -5852915.3, 3255189.0))
                .elDecAccelBias(0.0123)
                .elDecAccelSigma(0.0123)
                .elDecBias(0.012555)
                .elDecRateBias(0.123)
                .elDecRateSigma(0.123)
                .elDecRms(0.080505)
                .elDecSigma(0.00265)
                .endTime(OffsetDateTime.parse("2018-01-14T16:00:00.123Z"))
                .numAzRaObs(339)
                .numElDecObs(339)
                .numObs(341)
                .numPhotoObs(77)
                .numRangeObs(341)
                .numRangeRateObs(341)
                .numRcsObs(325)
                .numTimeObs(307)
                .numTracks(85)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .photoBias(0.123)
                .photoSigma(0.0123)
                .rangeAccelBias(0.123)
                .rangeAccelSigma(0.0123)
                .rangeBias(0.024777)
                .rangeRateBias(0.105333)
                .rangeRateRms(0.000227)
                .rangeRateSigma(0.000321)
                .rangeRms(0.0123)
                .rangeSigma(0.042644)
                .rcsBias(0.123)
                .rcsSigma(0.0123)
                .refTargets(listOf("xx", "yy", "zz"))
                .refType("SLR")
                .senType("PHASED ARRAY")
                .sourceDl("AXE")
                .timeBias(0.000372)
                .timeBiasSigma(15.333212)
                .build()

        val roundtrippedCalibrationRetrieveResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(calibrationRetrieveResponse),
                jacksonTypeRef<CalibrationRetrieveResponse>(),
            )

        assertThat(roundtrippedCalibrationRetrieveResponse).isEqualTo(calibrationRetrieveResponse)
    }
}
