// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.sensor.calibration

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CalibrationTupleResponseTest {

    @Test
    fun create() {
        val calibrationTupleResponse =
            CalibrationTupleResponse.builder()
                .classificationMarking("U")
                .dataMode(CalibrationTupleResponse.DataMode.TEST)
                .idSensor("09f2c68c-5e24-4b72-9cc8-ba9b1efa82f0")
                .source("Bluestaq")
                .startTime(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .azRaAccelBias(0.0123)
                .azRaAccelSigma(0.0123)
                .azRaBias(0.327883)
                .azRaRateBias(0.123)
                .azRaRateSigma(0.123)
                .azRaRms(0.605333)
                .azRaSigma(0.000381)
                .calAngleRef("AZEL")
                .calTrackMode("INTRA_TRACK")
                .calType("OPERATIONAL")
                .confidenceNoiseBias(0.001477)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .duration(14.125)
                .ecr(listOf(352815.1, -5852915.3, 3255189.0))
                .elDecAccelBias(0.0123)
                .elDecAccelSigma(0.0123)
                .elDecBias(0.012555)
                .elDecRateBias(0.123)
                .elDecRateSigma(0.123)
                .elDecRms(0.080505)
                .elDecSigma(0.00265)
                .endTime(OffsetDateTime.parse("2018-01-14T16:00:00.123Z"))
                .numAzRaObs(339)
                .numElDecObs(339)
                .numObs(341)
                .numPhotoObs(77)
                .numRangeObs(341)
                .numRangeRateObs(341)
                .numRcsObs(325)
                .numTimeObs(307)
                .numTracks(85)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .photoBias(0.123)
                .photoSigma(0.0123)
                .rangeAccelBias(0.123)
                .rangeAccelSigma(0.0123)
                .rangeBias(0.024777)
                .rangeRateBias(0.105333)
                .rangeRateRms(0.000227)
                .rangeRateSigma(0.000321)
                .rangeRms(0.0123)
                .rangeSigma(0.042644)
                .rcsBias(0.123)
                .rcsSigma(0.0123)
                .refTargets(listOf("xx", "yy", "zz"))
                .refType("SLR")
                .senType("PHASED ARRAY")
                .sourceDl("AXE")
                .timeBias(0.000372)
                .timeBiasSigma(15.333212)
                .build()

        assertThat(calibrationTupleResponse.classificationMarking()).isEqualTo("U")
        assertThat(calibrationTupleResponse.dataMode())
            .isEqualTo(CalibrationTupleResponse.DataMode.TEST)
        assertThat(calibrationTupleResponse.idSensor())
            .isEqualTo("09f2c68c-5e24-4b72-9cc8-ba9b1efa82f0")
        assertThat(calibrationTupleResponse.source()).isEqualTo("Bluestaq")
        assertThat(calibrationTupleResponse.startTime())
            .isEqualTo(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(calibrationTupleResponse.id()).contains("026dd511-8ba5-47d3-9909-836149f87686")
        assertThat(calibrationTupleResponse.azRaAccelBias()).contains(0.0123)
        assertThat(calibrationTupleResponse.azRaAccelSigma()).contains(0.0123)
        assertThat(calibrationTupleResponse.azRaBias()).contains(0.327883)
        assertThat(calibrationTupleResponse.azRaRateBias()).contains(0.123)
        assertThat(calibrationTupleResponse.azRaRateSigma()).contains(0.123)
        assertThat(calibrationTupleResponse.azRaRms()).contains(0.605333)
        assertThat(calibrationTupleResponse.azRaSigma()).contains(0.000381)
        assertThat(calibrationTupleResponse.calAngleRef()).contains("AZEL")
        assertThat(calibrationTupleResponse.calTrackMode()).contains("INTRA_TRACK")
        assertThat(calibrationTupleResponse.calType()).contains("OPERATIONAL")
        assertThat(calibrationTupleResponse.confidenceNoiseBias()).contains(0.001477)
        assertThat(calibrationTupleResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(calibrationTupleResponse.createdBy()).contains("some.user")
        assertThat(calibrationTupleResponse.duration()).contains(14.125)
        assertThat(calibrationTupleResponse.ecr().getOrNull())
            .containsExactly(352815.1, -5852915.3, 3255189.0)
        assertThat(calibrationTupleResponse.elDecAccelBias()).contains(0.0123)
        assertThat(calibrationTupleResponse.elDecAccelSigma()).contains(0.0123)
        assertThat(calibrationTupleResponse.elDecBias()).contains(0.012555)
        assertThat(calibrationTupleResponse.elDecRateBias()).contains(0.123)
        assertThat(calibrationTupleResponse.elDecRateSigma()).contains(0.123)
        assertThat(calibrationTupleResponse.elDecRms()).contains(0.080505)
        assertThat(calibrationTupleResponse.elDecSigma()).contains(0.00265)
        assertThat(calibrationTupleResponse.endTime())
            .contains(OffsetDateTime.parse("2018-01-14T16:00:00.123Z"))
        assertThat(calibrationTupleResponse.numAzRaObs()).contains(339)
        assertThat(calibrationTupleResponse.numElDecObs()).contains(339)
        assertThat(calibrationTupleResponse.numObs()).contains(341)
        assertThat(calibrationTupleResponse.numPhotoObs()).contains(77)
        assertThat(calibrationTupleResponse.numRangeObs()).contains(341)
        assertThat(calibrationTupleResponse.numRangeRateObs()).contains(341)
        assertThat(calibrationTupleResponse.numRcsObs()).contains(325)
        assertThat(calibrationTupleResponse.numTimeObs()).contains(307)
        assertThat(calibrationTupleResponse.numTracks()).contains(85)
        assertThat(calibrationTupleResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(calibrationTupleResponse.origNetwork()).contains("OPS1")
        assertThat(calibrationTupleResponse.photoBias()).contains(0.123)
        assertThat(calibrationTupleResponse.photoSigma()).contains(0.0123)
        assertThat(calibrationTupleResponse.rangeAccelBias()).contains(0.123)
        assertThat(calibrationTupleResponse.rangeAccelSigma()).contains(0.0123)
        assertThat(calibrationTupleResponse.rangeBias()).contains(0.024777)
        assertThat(calibrationTupleResponse.rangeRateBias()).contains(0.105333)
        assertThat(calibrationTupleResponse.rangeRateRms()).contains(0.000227)
        assertThat(calibrationTupleResponse.rangeRateSigma()).contains(0.000321)
        assertThat(calibrationTupleResponse.rangeRms()).contains(0.0123)
        assertThat(calibrationTupleResponse.rangeSigma()).contains(0.042644)
        assertThat(calibrationTupleResponse.rcsBias()).contains(0.123)
        assertThat(calibrationTupleResponse.rcsSigma()).contains(0.0123)
        assertThat(calibrationTupleResponse.refTargets().getOrNull())
            .containsExactly("xx", "yy", "zz")
        assertThat(calibrationTupleResponse.refType()).contains("SLR")
        assertThat(calibrationTupleResponse.senType()).contains("PHASED ARRAY")
        assertThat(calibrationTupleResponse.sourceDl()).contains("AXE")
        assertThat(calibrationTupleResponse.timeBias()).contains(0.000372)
        assertThat(calibrationTupleResponse.timeBiasSigma()).contains(15.333212)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val calibrationTupleResponse =
            CalibrationTupleResponse.builder()
                .classificationMarking("U")
                .dataMode(CalibrationTupleResponse.DataMode.TEST)
                .idSensor("09f2c68c-5e24-4b72-9cc8-ba9b1efa82f0")
                .source("Bluestaq")
                .startTime(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .azRaAccelBias(0.0123)
                .azRaAccelSigma(0.0123)
                .azRaBias(0.327883)
                .azRaRateBias(0.123)
                .azRaRateSigma(0.123)
                .azRaRms(0.605333)
                .azRaSigma(0.000381)
                .calAngleRef("AZEL")
                .calTrackMode("INTRA_TRACK")
                .calType("OPERATIONAL")
                .confidenceNoiseBias(0.001477)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .duration(14.125)
                .ecr(listOf(352815.1, -5852915.3, 3255189.0))
                .elDecAccelBias(0.0123)
                .elDecAccelSigma(0.0123)
                .elDecBias(0.012555)
                .elDecRateBias(0.123)
                .elDecRateSigma(0.123)
                .elDecRms(0.080505)
                .elDecSigma(0.00265)
                .endTime(OffsetDateTime.parse("2018-01-14T16:00:00.123Z"))
                .numAzRaObs(339)
                .numElDecObs(339)
                .numObs(341)
                .numPhotoObs(77)
                .numRangeObs(341)
                .numRangeRateObs(341)
                .numRcsObs(325)
                .numTimeObs(307)
                .numTracks(85)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .photoBias(0.123)
                .photoSigma(0.0123)
                .rangeAccelBias(0.123)
                .rangeAccelSigma(0.0123)
                .rangeBias(0.024777)
                .rangeRateBias(0.105333)
                .rangeRateRms(0.000227)
                .rangeRateSigma(0.000321)
                .rangeRms(0.0123)
                .rangeSigma(0.042644)
                .rcsBias(0.123)
                .rcsSigma(0.0123)
                .refTargets(listOf("xx", "yy", "zz"))
                .refType("SLR")
                .senType("PHASED ARRAY")
                .sourceDl("AXE")
                .timeBias(0.000372)
                .timeBiasSigma(15.333212)
                .build()

        val roundtrippedCalibrationTupleResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(calibrationTupleResponse),
                jacksonTypeRef<CalibrationTupleResponse>(),
            )

        assertThat(roundtrippedCalibrationTupleResponse).isEqualTo(calibrationTupleResponse)
    }
}
