// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.sensor.calibration

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CalibrationListResponseTest {

    @Test
    fun create() {
        val calibrationListResponse =
            CalibrationListResponse.builder()
                .classificationMarking("U")
                .dataMode(CalibrationListResponse.DataMode.TEST)
                .idSensor("09f2c68c-5e24-4b72-9cc8-ba9b1efa82f0")
                .source("Bluestaq")
                .startTime(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .azRaAccelBias(0.0123)
                .azRaAccelSigma(0.0123)
                .azRaBias(0.327883)
                .azRaRateBias(0.123)
                .azRaRateSigma(0.123)
                .azRaRms(0.605333)
                .azRaSigma(0.000381)
                .calAngleRef("AZEL")
                .calTrackMode("INTRA_TRACK")
                .calType("OPERATIONAL")
                .confidenceNoiseBias(0.001477)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .duration(14.125)
                .ecr(listOf(352815.1, -5852915.3, 3255189.0))
                .elDecAccelBias(0.0123)
                .elDecAccelSigma(0.0123)
                .elDecBias(0.012555)
                .elDecRateBias(0.123)
                .elDecRateSigma(0.123)
                .elDecRms(0.080505)
                .elDecSigma(0.00265)
                .endTime(OffsetDateTime.parse("2018-01-14T16:00:00.123Z"))
                .numAzRaObs(339)
                .numElDecObs(339)
                .numObs(341)
                .numPhotoObs(77)
                .numRangeObs(341)
                .numRangeRateObs(341)
                .numRcsObs(325)
                .numTimeObs(307)
                .numTracks(85)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .photoBias(0.123)
                .photoSigma(0.0123)
                .rangeAccelBias(0.123)
                .rangeAccelSigma(0.0123)
                .rangeBias(0.024777)
                .rangeRateBias(0.105333)
                .rangeRateRms(0.000227)
                .rangeRateSigma(0.000321)
                .rangeRms(0.0123)
                .rangeSigma(0.042644)
                .rcsBias(0.123)
                .rcsSigma(0.0123)
                .refTargets(listOf("xx", "yy", "zz"))
                .refType("SLR")
                .senType("PHASED ARRAY")
                .sourceDl("AXE")
                .timeBias(0.000372)
                .timeBiasSigma(15.333212)
                .build()

        assertThat(calibrationListResponse.classificationMarking()).isEqualTo("U")
        assertThat(calibrationListResponse.dataMode())
            .isEqualTo(CalibrationListResponse.DataMode.TEST)
        assertThat(calibrationListResponse.idSensor())
            .isEqualTo("09f2c68c-5e24-4b72-9cc8-ba9b1efa82f0")
        assertThat(calibrationListResponse.source()).isEqualTo("Bluestaq")
        assertThat(calibrationListResponse.startTime())
            .isEqualTo(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(calibrationListResponse.id()).contains("026dd511-8ba5-47d3-9909-836149f87686")
        assertThat(calibrationListResponse.azRaAccelBias()).contains(0.0123)
        assertThat(calibrationListResponse.azRaAccelSigma()).contains(0.0123)
        assertThat(calibrationListResponse.azRaBias()).contains(0.327883)
        assertThat(calibrationListResponse.azRaRateBias()).contains(0.123)
        assertThat(calibrationListResponse.azRaRateSigma()).contains(0.123)
        assertThat(calibrationListResponse.azRaRms()).contains(0.605333)
        assertThat(calibrationListResponse.azRaSigma()).contains(0.000381)
        assertThat(calibrationListResponse.calAngleRef()).contains("AZEL")
        assertThat(calibrationListResponse.calTrackMode()).contains("INTRA_TRACK")
        assertThat(calibrationListResponse.calType()).contains("OPERATIONAL")
        assertThat(calibrationListResponse.confidenceNoiseBias()).contains(0.001477)
        assertThat(calibrationListResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(calibrationListResponse.createdBy()).contains("some.user")
        assertThat(calibrationListResponse.duration()).contains(14.125)
        assertThat(calibrationListResponse.ecr().getOrNull())
            .containsExactly(352815.1, -5852915.3, 3255189.0)
        assertThat(calibrationListResponse.elDecAccelBias()).contains(0.0123)
        assertThat(calibrationListResponse.elDecAccelSigma()).contains(0.0123)
        assertThat(calibrationListResponse.elDecBias()).contains(0.012555)
        assertThat(calibrationListResponse.elDecRateBias()).contains(0.123)
        assertThat(calibrationListResponse.elDecRateSigma()).contains(0.123)
        assertThat(calibrationListResponse.elDecRms()).contains(0.080505)
        assertThat(calibrationListResponse.elDecSigma()).contains(0.00265)
        assertThat(calibrationListResponse.endTime())
            .contains(OffsetDateTime.parse("2018-01-14T16:00:00.123Z"))
        assertThat(calibrationListResponse.numAzRaObs()).contains(339)
        assertThat(calibrationListResponse.numElDecObs()).contains(339)
        assertThat(calibrationListResponse.numObs()).contains(341)
        assertThat(calibrationListResponse.numPhotoObs()).contains(77)
        assertThat(calibrationListResponse.numRangeObs()).contains(341)
        assertThat(calibrationListResponse.numRangeRateObs()).contains(341)
        assertThat(calibrationListResponse.numRcsObs()).contains(325)
        assertThat(calibrationListResponse.numTimeObs()).contains(307)
        assertThat(calibrationListResponse.numTracks()).contains(85)
        assertThat(calibrationListResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(calibrationListResponse.origNetwork()).contains("OPS1")
        assertThat(calibrationListResponse.photoBias()).contains(0.123)
        assertThat(calibrationListResponse.photoSigma()).contains(0.0123)
        assertThat(calibrationListResponse.rangeAccelBias()).contains(0.123)
        assertThat(calibrationListResponse.rangeAccelSigma()).contains(0.0123)
        assertThat(calibrationListResponse.rangeBias()).contains(0.024777)
        assertThat(calibrationListResponse.rangeRateBias()).contains(0.105333)
        assertThat(calibrationListResponse.rangeRateRms()).contains(0.000227)
        assertThat(calibrationListResponse.rangeRateSigma()).contains(0.000321)
        assertThat(calibrationListResponse.rangeRms()).contains(0.0123)
        assertThat(calibrationListResponse.rangeSigma()).contains(0.042644)
        assertThat(calibrationListResponse.rcsBias()).contains(0.123)
        assertThat(calibrationListResponse.rcsSigma()).contains(0.0123)
        assertThat(calibrationListResponse.refTargets().getOrNull())
            .containsExactly("xx", "yy", "zz")
        assertThat(calibrationListResponse.refType()).contains("SLR")
        assertThat(calibrationListResponse.senType()).contains("PHASED ARRAY")
        assertThat(calibrationListResponse.sourceDl()).contains("AXE")
        assertThat(calibrationListResponse.timeBias()).contains(0.000372)
        assertThat(calibrationListResponse.timeBiasSigma()).contains(15.333212)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val calibrationListResponse =
            CalibrationListResponse.builder()
                .classificationMarking("U")
                .dataMode(CalibrationListResponse.DataMode.TEST)
                .idSensor("09f2c68c-5e24-4b72-9cc8-ba9b1efa82f0")
                .source("Bluestaq")
                .startTime(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .azRaAccelBias(0.0123)
                .azRaAccelSigma(0.0123)
                .azRaBias(0.327883)
                .azRaRateBias(0.123)
                .azRaRateSigma(0.123)
                .azRaRms(0.605333)
                .azRaSigma(0.000381)
                .calAngleRef("AZEL")
                .calTrackMode("INTRA_TRACK")
                .calType("OPERATIONAL")
                .confidenceNoiseBias(0.001477)
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .duration(14.125)
                .ecr(listOf(352815.1, -5852915.3, 3255189.0))
                .elDecAccelBias(0.0123)
                .elDecAccelSigma(0.0123)
                .elDecBias(0.012555)
                .elDecRateBias(0.123)
                .elDecRateSigma(0.123)
                .elDecRms(0.080505)
                .elDecSigma(0.00265)
                .endTime(OffsetDateTime.parse("2018-01-14T16:00:00.123Z"))
                .numAzRaObs(339)
                .numElDecObs(339)
                .numObs(341)
                .numPhotoObs(77)
                .numRangeObs(341)
                .numRangeRateObs(341)
                .numRcsObs(325)
                .numTimeObs(307)
                .numTracks(85)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .photoBias(0.123)
                .photoSigma(0.0123)
                .rangeAccelBias(0.123)
                .rangeAccelSigma(0.0123)
                .rangeBias(0.024777)
                .rangeRateBias(0.105333)
                .rangeRateRms(0.000227)
                .rangeRateSigma(0.000321)
                .rangeRms(0.0123)
                .rangeSigma(0.042644)
                .rcsBias(0.123)
                .rcsSigma(0.0123)
                .refTargets(listOf("xx", "yy", "zz"))
                .refType("SLR")
                .senType("PHASED ARRAY")
                .sourceDl("AXE")
                .timeBias(0.000372)
                .timeBiasSigma(15.333212)
                .build()

        val roundtrippedCalibrationListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(calibrationListResponse),
                jacksonTypeRef<CalibrationListResponse>(),
            )

        assertThat(roundtrippedCalibrationListResponse).isEqualTo(calibrationListResponse)
    }
}
