// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.navigationalobstruction

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.LocalDate
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class NavigationalObstructionListResponseTest {

    @Test
    fun create() {
        val navigationalObstructionListResponse =
            NavigationalObstructionListResponse.builder()
                .classificationMarking("U")
                .cycleDate(LocalDate.parse("2024-06-13"))
                .dataMode(NavigationalObstructionListResponse.DataMode.TEST)
                .obstacleId("359655")
                .obstacleType("V")
                .source("Bluestaq")
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .actDelCode("A")
                .airacCycle(2406)
                .baseAiracCycle(2405)
                .baselineCutoffDate(LocalDate.parse("2024-04-23"))
                .boundNeLat(29.1)
                .boundNeLon(99.1)
                .boundSwLat(-44.1)
                .boundSwLon(-144.1)
                .countryCode("US")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .cutoffDate(LocalDate.parse("2024-05-21"))
                .dataSetRemarks("Data set remarks")
                .deletingOrg("ACME")
                .derivingOrg("ACME")
                .directivityCode(2)
                .elevation(840.1)
                .elevationAcc(17.1)
                .externalId("OU812")
                .facc("AT040")
                .featureCode("540")
                .featureDescription("Powerline Pylon, General")
                .featureName("PYLON")
                .featureType("540")
                .heightAgl(314.1)
                .heightAglAcc(30.1)
                .heightMsl(1154.1)
                .heightMslAcc(34.1)
                .horizAcc(8.1)
                .horizDatumCode("WGS-84")
                .initRecordDate(LocalDate.parse("1991-03-28"))
                .addKey("key1")
                .addKey("key2")
                .lightingCode("U")
                .lineNeLat(49.000584)
                .lineNeLon(-122.197891)
                .linesFilename("lines.txt")
                .lineSwLat(48.507027)
                .lineSwLon(-122.722946)
                .minHeightAgl(20.1)
                .multObs("S")
                .nextCycleDate(LocalDate.parse("2024-07-11"))
                .numLines(45993)
                .numObs(1)
                .numPoints(21830590)
                .obstacleRemarks("Obstacle remarks")
                .origId("L0000002289")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .ownerCountryCode("US")
                .pointLat(46.757211)
                .pointLon(-67.759494)
                .pointsFilename("points.txt")
                .processCode("OT")
                .producer("ACME")
                .provinceCode("23")
                .quality("0")
                .rawFileUri("Example URI")
                .revDate(LocalDate.parse("2020-02-26"))
                .segEndPoint(359655)
                .segNum(1)
                .segStartPoint(359655)
                .sourceDate(LocalDate.parse("2016-04-01"))
                .sourceDl("AXE")
                .surfaceMatCode("U")
                .transactionCode("V")
                .validationCode(3)
                .addValue("value1")
                .addValue("value2")
                .vectorsFilename("vectors.txt")
                .wac("262")
                .wacInnr("0409-00039")
                .build()

        assertThat(navigationalObstructionListResponse.classificationMarking()).isEqualTo("U")
        assertThat(navigationalObstructionListResponse.cycleDate())
            .isEqualTo(LocalDate.parse("2024-06-13"))
        assertThat(navigationalObstructionListResponse.dataMode())
            .isEqualTo(NavigationalObstructionListResponse.DataMode.TEST)
        assertThat(navigationalObstructionListResponse.obstacleId()).isEqualTo("359655")
        assertThat(navigationalObstructionListResponse.obstacleType()).isEqualTo("V")
        assertThat(navigationalObstructionListResponse.source()).isEqualTo("Bluestaq")
        assertThat(navigationalObstructionListResponse.id())
            .contains("026dd511-8ba5-47d3-9909-836149f87686")
        assertThat(navigationalObstructionListResponse.actDelCode()).contains("A")
        assertThat(navigationalObstructionListResponse.airacCycle()).contains(2406)
        assertThat(navigationalObstructionListResponse.baseAiracCycle()).contains(2405)
        assertThat(navigationalObstructionListResponse.baselineCutoffDate())
            .contains(LocalDate.parse("2024-04-23"))
        assertThat(navigationalObstructionListResponse.boundNeLat()).contains(29.1)
        assertThat(navigationalObstructionListResponse.boundNeLon()).contains(99.1)
        assertThat(navigationalObstructionListResponse.boundSwLat()).contains(-44.1)
        assertThat(navigationalObstructionListResponse.boundSwLon()).contains(-144.1)
        assertThat(navigationalObstructionListResponse.countryCode()).contains("US")
        assertThat(navigationalObstructionListResponse.createdAt())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(navigationalObstructionListResponse.createdBy()).contains("some.user")
        assertThat(navigationalObstructionListResponse.cutoffDate())
            .contains(LocalDate.parse("2024-05-21"))
        assertThat(navigationalObstructionListResponse.dataSetRemarks())
            .contains("Data set remarks")
        assertThat(navigationalObstructionListResponse.deletingOrg()).contains("ACME")
        assertThat(navigationalObstructionListResponse.derivingOrg()).contains("ACME")
        assertThat(navigationalObstructionListResponse.directivityCode()).contains(2)
        assertThat(navigationalObstructionListResponse.elevation()).contains(840.1)
        assertThat(navigationalObstructionListResponse.elevationAcc()).contains(17.1)
        assertThat(navigationalObstructionListResponse.externalId()).contains("OU812")
        assertThat(navigationalObstructionListResponse.facc()).contains("AT040")
        assertThat(navigationalObstructionListResponse.featureCode()).contains("540")
        assertThat(navigationalObstructionListResponse.featureDescription())
            .contains("Powerline Pylon, General")
        assertThat(navigationalObstructionListResponse.featureName()).contains("PYLON")
        assertThat(navigationalObstructionListResponse.featureType()).contains("540")
        assertThat(navigationalObstructionListResponse.heightAgl()).contains(314.1)
        assertThat(navigationalObstructionListResponse.heightAglAcc()).contains(30.1)
        assertThat(navigationalObstructionListResponse.heightMsl()).contains(1154.1)
        assertThat(navigationalObstructionListResponse.heightMslAcc()).contains(34.1)
        assertThat(navigationalObstructionListResponse.horizAcc()).contains(8.1)
        assertThat(navigationalObstructionListResponse.horizDatumCode()).contains("WGS-84")
        assertThat(navigationalObstructionListResponse.initRecordDate())
            .contains(LocalDate.parse("1991-03-28"))
        assertThat(navigationalObstructionListResponse.keys().getOrNull())
            .containsExactly("key1", "key2")
        assertThat(navigationalObstructionListResponse.lightingCode()).contains("U")
        assertThat(navigationalObstructionListResponse.lineNeLat()).contains(49.000584)
        assertThat(navigationalObstructionListResponse.lineNeLon()).contains(-122.197891)
        assertThat(navigationalObstructionListResponse.linesFilename()).contains("lines.txt")
        assertThat(navigationalObstructionListResponse.lineSwLat()).contains(48.507027)
        assertThat(navigationalObstructionListResponse.lineSwLon()).contains(-122.722946)
        assertThat(navigationalObstructionListResponse.minHeightAgl()).contains(20.1)
        assertThat(navigationalObstructionListResponse.multObs()).contains("S")
        assertThat(navigationalObstructionListResponse.nextCycleDate())
            .contains(LocalDate.parse("2024-07-11"))
        assertThat(navigationalObstructionListResponse.numLines()).contains(45993)
        assertThat(navigationalObstructionListResponse.numObs()).contains(1)
        assertThat(navigationalObstructionListResponse.numPoints()).contains(21830590)
        assertThat(navigationalObstructionListResponse.obstacleRemarks())
            .contains("Obstacle remarks")
        assertThat(navigationalObstructionListResponse.origId()).contains("L0000002289")
        assertThat(navigationalObstructionListResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(navigationalObstructionListResponse.origNetwork()).contains("OPS1")
        assertThat(navigationalObstructionListResponse.ownerCountryCode()).contains("US")
        assertThat(navigationalObstructionListResponse.pointLat()).contains(46.757211)
        assertThat(navigationalObstructionListResponse.pointLon()).contains(-67.759494)
        assertThat(navigationalObstructionListResponse.pointsFilename()).contains("points.txt")
        assertThat(navigationalObstructionListResponse.processCode()).contains("OT")
        assertThat(navigationalObstructionListResponse.producer()).contains("ACME")
        assertThat(navigationalObstructionListResponse.provinceCode()).contains("23")
        assertThat(navigationalObstructionListResponse.quality()).contains("0")
        assertThat(navigationalObstructionListResponse.rawFileUri()).contains("Example URI")
        assertThat(navigationalObstructionListResponse.revDate())
            .contains(LocalDate.parse("2020-02-26"))
        assertThat(navigationalObstructionListResponse.segEndPoint()).contains(359655)
        assertThat(navigationalObstructionListResponse.segNum()).contains(1)
        assertThat(navigationalObstructionListResponse.segStartPoint()).contains(359655)
        assertThat(navigationalObstructionListResponse.sourceDate())
            .contains(LocalDate.parse("2016-04-01"))
        assertThat(navigationalObstructionListResponse.sourceDl()).contains("AXE")
        assertThat(navigationalObstructionListResponse.surfaceMatCode()).contains("U")
        assertThat(navigationalObstructionListResponse.transactionCode()).contains("V")
        assertThat(navigationalObstructionListResponse.validationCode()).contains(3)
        assertThat(navigationalObstructionListResponse.values().getOrNull())
            .containsExactly("value1", "value2")
        assertThat(navigationalObstructionListResponse.vectorsFilename()).contains("vectors.txt")
        assertThat(navigationalObstructionListResponse.wac()).contains("262")
        assertThat(navigationalObstructionListResponse.wacInnr()).contains("0409-00039")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val navigationalObstructionListResponse =
            NavigationalObstructionListResponse.builder()
                .classificationMarking("U")
                .cycleDate(LocalDate.parse("2024-06-13"))
                .dataMode(NavigationalObstructionListResponse.DataMode.TEST)
                .obstacleId("359655")
                .obstacleType("V")
                .source("Bluestaq")
                .id("026dd511-8ba5-47d3-9909-836149f87686")
                .actDelCode("A")
                .airacCycle(2406)
                .baseAiracCycle(2405)
                .baselineCutoffDate(LocalDate.parse("2024-04-23"))
                .boundNeLat(29.1)
                .boundNeLon(99.1)
                .boundSwLat(-44.1)
                .boundSwLon(-144.1)
                .countryCode("US")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .cutoffDate(LocalDate.parse("2024-05-21"))
                .dataSetRemarks("Data set remarks")
                .deletingOrg("ACME")
                .derivingOrg("ACME")
                .directivityCode(2)
                .elevation(840.1)
                .elevationAcc(17.1)
                .externalId("OU812")
                .facc("AT040")
                .featureCode("540")
                .featureDescription("Powerline Pylon, General")
                .featureName("PYLON")
                .featureType("540")
                .heightAgl(314.1)
                .heightAglAcc(30.1)
                .heightMsl(1154.1)
                .heightMslAcc(34.1)
                .horizAcc(8.1)
                .horizDatumCode("WGS-84")
                .initRecordDate(LocalDate.parse("1991-03-28"))
                .addKey("key1")
                .addKey("key2")
                .lightingCode("U")
                .lineNeLat(49.000584)
                .lineNeLon(-122.197891)
                .linesFilename("lines.txt")
                .lineSwLat(48.507027)
                .lineSwLon(-122.722946)
                .minHeightAgl(20.1)
                .multObs("S")
                .nextCycleDate(LocalDate.parse("2024-07-11"))
                .numLines(45993)
                .numObs(1)
                .numPoints(21830590)
                .obstacleRemarks("Obstacle remarks")
                .origId("L0000002289")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .ownerCountryCode("US")
                .pointLat(46.757211)
                .pointLon(-67.759494)
                .pointsFilename("points.txt")
                .processCode("OT")
                .producer("ACME")
                .provinceCode("23")
                .quality("0")
                .rawFileUri("Example URI")
                .revDate(LocalDate.parse("2020-02-26"))
                .segEndPoint(359655)
                .segNum(1)
                .segStartPoint(359655)
                .sourceDate(LocalDate.parse("2016-04-01"))
                .sourceDl("AXE")
                .surfaceMatCode("U")
                .transactionCode("V")
                .validationCode(3)
                .addValue("value1")
                .addValue("value2")
                .vectorsFilename("vectors.txt")
                .wac("262")
                .wacInnr("0409-00039")
                .build()

        val roundtrippedNavigationalObstructionListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(navigationalObstructionListResponse),
                jacksonTypeRef<NavigationalObstructionListResponse>(),
            )

        assertThat(roundtrippedNavigationalObstructionListResponse)
            .isEqualTo(navigationalObstructionListResponse)
    }
}
