// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.tdoafdoa.diffofarrival

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class DiffofarrivalAbridgedTest {

    @Test
    fun create() {
        val diffofarrivalAbridged =
            DiffofarrivalAbridged.builder()
                .classificationMarking("U")
                .dataMode(DiffofarrivalAbridged.DataMode.TEST)
                .obTime(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
                .source("Bluestaq")
                .id("DIFFOFARRIVAL-ID")
                .azimuth1(40.9)
                .azimuth2(43.4)
                .bandwidth(500000.1)
                .collectionMode("SURVEY")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .deltaRange(1.7)
                .deltaRangeRate(0.018)
                .deltaRangeRateUnc(0.001)
                .deltaRangeUnc(0.2)
                .descriptor("Example descriptor")
                .elevation1(65.4)
                .elevation2(65.9)
                .fdoa(970.8)
                .fdoaUnc(20.1)
                .frequency(2240000000.0)
                .idOnOrbit("ONORBIT-ID")
                .idSensor1("SENSOR1-ID")
                .idSensor2("SENSOR2-ID")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .origObjectId("ORIGOBJECT-ID")
                .origSensorId1("ORIGSENSOR1-ID")
                .origSensorId2("ORIGSENSOR2-ID")
                .polarityType("V")
                .satNo(25544)
                .sen2alt(770.1)
                .sen2lat(32.2)
                .sen2lon(-110.9)
                .senalt(783.1)
                .senlat(45.1)
                .senlon(120.1)
                .sensor1Delay(0.000004)
                .sensor2Delay(0.000004)
                .snr(18.1)
                .sourceDl("AXE")
                .taskId("TASK-ID")
                .tdoa(0.0000136)
                .tdoaAmb(1)
                .tdoaUnc(2e-7)
                .transactionId("TRANSACTION-ID")
                .uct(false)
                .build()

        assertThat(diffofarrivalAbridged.classificationMarking()).isEqualTo("U")
        assertThat(diffofarrivalAbridged.dataMode()).isEqualTo(DiffofarrivalAbridged.DataMode.TEST)
        assertThat(diffofarrivalAbridged.obTime())
            .isEqualTo(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
        assertThat(diffofarrivalAbridged.source()).isEqualTo("Bluestaq")
        assertThat(diffofarrivalAbridged.id()).contains("DIFFOFARRIVAL-ID")
        assertThat(diffofarrivalAbridged.azimuth1()).contains(40.9)
        assertThat(diffofarrivalAbridged.azimuth2()).contains(43.4)
        assertThat(diffofarrivalAbridged.bandwidth()).contains(500000.1)
        assertThat(diffofarrivalAbridged.collectionMode()).contains("SURVEY")
        assertThat(diffofarrivalAbridged.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(diffofarrivalAbridged.createdBy()).contains("some.user")
        assertThat(diffofarrivalAbridged.deltaRange()).contains(1.7)
        assertThat(diffofarrivalAbridged.deltaRangeRate()).contains(0.018)
        assertThat(diffofarrivalAbridged.deltaRangeRateUnc()).contains(0.001)
        assertThat(diffofarrivalAbridged.deltaRangeUnc()).contains(0.2)
        assertThat(diffofarrivalAbridged.descriptor()).contains("Example descriptor")
        assertThat(diffofarrivalAbridged.elevation1()).contains(65.4)
        assertThat(diffofarrivalAbridged.elevation2()).contains(65.9)
        assertThat(diffofarrivalAbridged.fdoa()).contains(970.8)
        assertThat(diffofarrivalAbridged.fdoaUnc()).contains(20.1)
        assertThat(diffofarrivalAbridged.frequency()).contains(2240000000.0)
        assertThat(diffofarrivalAbridged.idOnOrbit()).contains("ONORBIT-ID")
        assertThat(diffofarrivalAbridged.idSensor1()).contains("SENSOR1-ID")
        assertThat(diffofarrivalAbridged.idSensor2()).contains("SENSOR2-ID")
        assertThat(diffofarrivalAbridged.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(diffofarrivalAbridged.origNetwork()).contains("OPS1")
        assertThat(diffofarrivalAbridged.origObjectId()).contains("ORIGOBJECT-ID")
        assertThat(diffofarrivalAbridged.origSensorId1()).contains("ORIGSENSOR1-ID")
        assertThat(diffofarrivalAbridged.origSensorId2()).contains("ORIGSENSOR2-ID")
        assertThat(diffofarrivalAbridged.polarityType()).contains("V")
        assertThat(diffofarrivalAbridged.satNo()).contains(25544)
        assertThat(diffofarrivalAbridged.sen2alt()).contains(770.1)
        assertThat(diffofarrivalAbridged.sen2lat()).contains(32.2)
        assertThat(diffofarrivalAbridged.sen2lon()).contains(-110.9)
        assertThat(diffofarrivalAbridged.senalt()).contains(783.1)
        assertThat(diffofarrivalAbridged.senlat()).contains(45.1)
        assertThat(diffofarrivalAbridged.senlon()).contains(120.1)
        assertThat(diffofarrivalAbridged.sensor1Delay()).contains(0.000004)
        assertThat(diffofarrivalAbridged.sensor2Delay()).contains(0.000004)
        assertThat(diffofarrivalAbridged.snr()).contains(18.1)
        assertThat(diffofarrivalAbridged.sourceDl()).contains("AXE")
        assertThat(diffofarrivalAbridged.taskId()).contains("TASK-ID")
        assertThat(diffofarrivalAbridged.tdoa()).contains(0.0000136)
        assertThat(diffofarrivalAbridged.tdoaAmb()).contains(1)
        assertThat(diffofarrivalAbridged.tdoaUnc()).contains(2e-7)
        assertThat(diffofarrivalAbridged.transactionId()).contains("TRANSACTION-ID")
        assertThat(diffofarrivalAbridged.uct()).contains(false)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val diffofarrivalAbridged =
            DiffofarrivalAbridged.builder()
                .classificationMarking("U")
                .dataMode(DiffofarrivalAbridged.DataMode.TEST)
                .obTime(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
                .source("Bluestaq")
                .id("DIFFOFARRIVAL-ID")
                .azimuth1(40.9)
                .azimuth2(43.4)
                .bandwidth(500000.1)
                .collectionMode("SURVEY")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .deltaRange(1.7)
                .deltaRangeRate(0.018)
                .deltaRangeRateUnc(0.001)
                .deltaRangeUnc(0.2)
                .descriptor("Example descriptor")
                .elevation1(65.4)
                .elevation2(65.9)
                .fdoa(970.8)
                .fdoaUnc(20.1)
                .frequency(2240000000.0)
                .idOnOrbit("ONORBIT-ID")
                .idSensor1("SENSOR1-ID")
                .idSensor2("SENSOR2-ID")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .origObjectId("ORIGOBJECT-ID")
                .origSensorId1("ORIGSENSOR1-ID")
                .origSensorId2("ORIGSENSOR2-ID")
                .polarityType("V")
                .satNo(25544)
                .sen2alt(770.1)
                .sen2lat(32.2)
                .sen2lon(-110.9)
                .senalt(783.1)
                .senlat(45.1)
                .senlon(120.1)
                .sensor1Delay(0.000004)
                .sensor2Delay(0.000004)
                .snr(18.1)
                .sourceDl("AXE")
                .taskId("TASK-ID")
                .tdoa(0.0000136)
                .tdoaAmb(1)
                .tdoaUnc(2e-7)
                .transactionId("TRANSACTION-ID")
                .uct(false)
                .build()

        val roundtrippedDiffofarrivalAbridged =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(diffofarrivalAbridged),
                jacksonTypeRef<DiffofarrivalAbridged>(),
            )

        assertThat(roundtrippedDiffofarrivalAbridged).isEqualTo(diffofarrivalAbridged)
    }
}
