// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.tdoafdoa.diffofarrival

import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class DiffofarrivalCreateParamsTest {

    @Test
    fun create() {
        DiffofarrivalCreateParams.builder()
            .classificationMarking("U")
            .dataMode(DiffofarrivalCreateParams.DataMode.TEST)
            .obTime(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
            .source("Bluestaq")
            .id("DIFFOFARRIVAL-ID")
            .azimuth1(40.9)
            .azimuth2(43.4)
            .bandwidth(500000.1)
            .collectionMode("SURVEY")
            .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
            .createdBy("some.user")
            .deltaRange(1.7)
            .deltaRangeRate(0.018)
            .deltaRangeRateUnc(0.001)
            .deltaRangeUnc(0.2)
            .descriptor("Example descriptor")
            .elevation1(65.4)
            .elevation2(65.9)
            .fdoa(970.8)
            .fdoaUnc(20.1)
            .frequency(2240000000.0)
            .idOnOrbit("ONORBIT-ID")
            .idSensor1("SENSOR1-ID")
            .idSensor2("SENSOR2-ID")
            .origin("THIRD_PARTY_DATASOURCE")
            .origNetwork("OPS1")
            .origObjectId("ORIGOBJECT-ID")
            .origSensorId1("ORIGSENSOR1-ID")
            .origSensorId2("ORIGSENSOR2-ID")
            .polarityType("V")
            .rawFileUri("/DOA/2026/01/01/filename.txt")
            .satNo(25544)
            .sen2alt(770.1)
            .sen2lat(32.2)
            .sen2lon(-110.9)
            .senalt(783.1)
            .senlat(45.1)
            .senlon(120.1)
            .sensor1Delay(0.000004)
            .sensor2Delay(0.000004)
            .snr(18.1)
            .sourceDl("AXE")
            .addTag("TAG1")
            .addTag("TAG2")
            .taskId("TASK-ID")
            .tdoa(0.0000136)
            .tdoaAmb(1)
            .tdoaUnc(2e-7)
            .transactionId("TRANSACTION-ID")
            .uct(false)
            .build()
    }

    @Test
    fun body() {
        val params =
            DiffofarrivalCreateParams.builder()
                .classificationMarking("U")
                .dataMode(DiffofarrivalCreateParams.DataMode.TEST)
                .obTime(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
                .source("Bluestaq")
                .id("DIFFOFARRIVAL-ID")
                .azimuth1(40.9)
                .azimuth2(43.4)
                .bandwidth(500000.1)
                .collectionMode("SURVEY")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .deltaRange(1.7)
                .deltaRangeRate(0.018)
                .deltaRangeRateUnc(0.001)
                .deltaRangeUnc(0.2)
                .descriptor("Example descriptor")
                .elevation1(65.4)
                .elevation2(65.9)
                .fdoa(970.8)
                .fdoaUnc(20.1)
                .frequency(2240000000.0)
                .idOnOrbit("ONORBIT-ID")
                .idSensor1("SENSOR1-ID")
                .idSensor2("SENSOR2-ID")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .origObjectId("ORIGOBJECT-ID")
                .origSensorId1("ORIGSENSOR1-ID")
                .origSensorId2("ORIGSENSOR2-ID")
                .polarityType("V")
                .rawFileUri("/DOA/2026/01/01/filename.txt")
                .satNo(25544)
                .sen2alt(770.1)
                .sen2lat(32.2)
                .sen2lon(-110.9)
                .senalt(783.1)
                .senlat(45.1)
                .senlon(120.1)
                .sensor1Delay(0.000004)
                .sensor2Delay(0.000004)
                .snr(18.1)
                .sourceDl("AXE")
                .addTag("TAG1")
                .addTag("TAG2")
                .taskId("TASK-ID")
                .tdoa(0.0000136)
                .tdoaAmb(1)
                .tdoaUnc(2e-7)
                .transactionId("TRANSACTION-ID")
                .uct(false)
                .build()

        val body = params._body()

        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(DiffofarrivalCreateParams.DataMode.TEST)
        assertThat(body.obTime()).isEqualTo(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
        assertThat(body.source()).isEqualTo("Bluestaq")
        assertThat(body.id()).contains("DIFFOFARRIVAL-ID")
        assertThat(body.azimuth1()).contains(40.9)
        assertThat(body.azimuth2()).contains(43.4)
        assertThat(body.bandwidth()).contains(500000.1)
        assertThat(body.collectionMode()).contains("SURVEY")
        assertThat(body.createdAt()).contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(body.createdBy()).contains("some.user")
        assertThat(body.deltaRange()).contains(1.7)
        assertThat(body.deltaRangeRate()).contains(0.018)
        assertThat(body.deltaRangeRateUnc()).contains(0.001)
        assertThat(body.deltaRangeUnc()).contains(0.2)
        assertThat(body.descriptor()).contains("Example descriptor")
        assertThat(body.elevation1()).contains(65.4)
        assertThat(body.elevation2()).contains(65.9)
        assertThat(body.fdoa()).contains(970.8)
        assertThat(body.fdoaUnc()).contains(20.1)
        assertThat(body.frequency()).contains(2240000000.0)
        assertThat(body.idOnOrbit()).contains("ONORBIT-ID")
        assertThat(body.idSensor1()).contains("SENSOR1-ID")
        assertThat(body.idSensor2()).contains("SENSOR2-ID")
        assertThat(body.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(body.origNetwork()).contains("OPS1")
        assertThat(body.origObjectId()).contains("ORIGOBJECT-ID")
        assertThat(body.origSensorId1()).contains("ORIGSENSOR1-ID")
        assertThat(body.origSensorId2()).contains("ORIGSENSOR2-ID")
        assertThat(body.polarityType()).contains("V")
        assertThat(body.rawFileUri()).contains("/DOA/2026/01/01/filename.txt")
        assertThat(body.satNo()).contains(25544)
        assertThat(body.sen2alt()).contains(770.1)
        assertThat(body.sen2lat()).contains(32.2)
        assertThat(body.sen2lon()).contains(-110.9)
        assertThat(body.senalt()).contains(783.1)
        assertThat(body.senlat()).contains(45.1)
        assertThat(body.senlon()).contains(120.1)
        assertThat(body.sensor1Delay()).contains(0.000004)
        assertThat(body.sensor2Delay()).contains(0.000004)
        assertThat(body.snr()).contains(18.1)
        assertThat(body.sourceDl()).contains("AXE")
        assertThat(body.tags().getOrNull()).containsExactly("TAG1", "TAG2")
        assertThat(body.taskId()).contains("TASK-ID")
        assertThat(body.tdoa()).contains(0.0000136)
        assertThat(body.tdoaAmb()).contains(1)
        assertThat(body.tdoaUnc()).contains(2e-7)
        assertThat(body.transactionId()).contains("TRANSACTION-ID")
        assertThat(body.uct()).contains(false)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            DiffofarrivalCreateParams.builder()
                .classificationMarking("U")
                .dataMode(DiffofarrivalCreateParams.DataMode.TEST)
                .obTime(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
                .source("Bluestaq")
                .build()

        val body = params._body()

        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(DiffofarrivalCreateParams.DataMode.TEST)
        assertThat(body.obTime()).isEqualTo(OffsetDateTime.parse("2018-01-01T16:00:00.123456Z"))
        assertThat(body.source()).isEqualTo("Bluestaq")
    }
}
