// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.organizationdetails

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class OrganizationdetailFindBySourceResponseTest {

    @Test
    fun create() {
        val organizationdetailFindBySourceResponse =
            OrganizationdetailFindBySourceResponse.builder()
                .classificationMarking("U")
                .dataMode(OrganizationdetailFindBySourceResponse.DataMode.TEST)
                .idOrganization("ORGANIZATION-ID")
                .name("some.user")
                .source("some.user")
                .id("ORGANIZATIONDETAILS-ID")
                .address1("123 Main Street")
                .address2("Apt 4B")
                .address3("Colorado Springs CO, 80903")
                .broker("some.user")
                .ceo("some.user")
                .cfo("some.user")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .cto("some.user")
                .description("Example description")
                .ebitda(123.4)
                .email("some_organization@organization.com")
                .financialNotes("Example notes")
                .financialYearEndDate(OffsetDateTime.parse("2021-01-01T01:01:01.123Z"))
                .fleetPlanNotes("Example notes")
                .formerOrgId("FORMERORG-ID")
                .ftes(123)
                .geoAdminLevel1("Colorado")
                .geoAdminLevel2("El Paso County")
                .geoAdminLevel3("Colorado Springs")
                .massRanking(123)
                .origin("some.user")
                .origNetwork("OPS1")
                .parentOrgId("PARENTORG-ID")
                .postalCode("80903")
                .profit(123.4)
                .revenue(123.4)
                .revenueRanking(123)
                .riskManager("some.user")
                .servicesNotes("Example notes")
                .build()

        assertThat(organizationdetailFindBySourceResponse.classificationMarking()).isEqualTo("U")
        assertThat(organizationdetailFindBySourceResponse.dataMode())
            .isEqualTo(OrganizationdetailFindBySourceResponse.DataMode.TEST)
        assertThat(organizationdetailFindBySourceResponse.idOrganization())
            .isEqualTo("ORGANIZATION-ID")
        assertThat(organizationdetailFindBySourceResponse.name()).isEqualTo("some.user")
        assertThat(organizationdetailFindBySourceResponse.source()).isEqualTo("some.user")
        assertThat(organizationdetailFindBySourceResponse.id()).contains("ORGANIZATIONDETAILS-ID")
        assertThat(organizationdetailFindBySourceResponse.address1()).contains("123 Main Street")
        assertThat(organizationdetailFindBySourceResponse.address2()).contains("Apt 4B")
        assertThat(organizationdetailFindBySourceResponse.address3())
            .contains("Colorado Springs CO, 80903")
        assertThat(organizationdetailFindBySourceResponse.broker()).contains("some.user")
        assertThat(organizationdetailFindBySourceResponse.ceo()).contains("some.user")
        assertThat(organizationdetailFindBySourceResponse.cfo()).contains("some.user")
        assertThat(organizationdetailFindBySourceResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(organizationdetailFindBySourceResponse.createdBy()).contains("some.user")
        assertThat(organizationdetailFindBySourceResponse.cto()).contains("some.user")
        assertThat(organizationdetailFindBySourceResponse.description())
            .contains("Example description")
        assertThat(organizationdetailFindBySourceResponse.ebitda()).contains(123.4)
        assertThat(organizationdetailFindBySourceResponse.email())
            .contains("some_organization@organization.com")
        assertThat(organizationdetailFindBySourceResponse.financialNotes())
            .contains("Example notes")
        assertThat(organizationdetailFindBySourceResponse.financialYearEndDate())
            .contains(OffsetDateTime.parse("2021-01-01T01:01:01.123Z"))
        assertThat(organizationdetailFindBySourceResponse.fleetPlanNotes())
            .contains("Example notes")
        assertThat(organizationdetailFindBySourceResponse.formerOrgId()).contains("FORMERORG-ID")
        assertThat(organizationdetailFindBySourceResponse.ftes()).contains(123)
        assertThat(organizationdetailFindBySourceResponse.geoAdminLevel1()).contains("Colorado")
        assertThat(organizationdetailFindBySourceResponse.geoAdminLevel2())
            .contains("El Paso County")
        assertThat(organizationdetailFindBySourceResponse.geoAdminLevel3())
            .contains("Colorado Springs")
        assertThat(organizationdetailFindBySourceResponse.massRanking()).contains(123)
        assertThat(organizationdetailFindBySourceResponse.origin()).contains("some.user")
        assertThat(organizationdetailFindBySourceResponse.origNetwork()).contains("OPS1")
        assertThat(organizationdetailFindBySourceResponse.parentOrgId()).contains("PARENTORG-ID")
        assertThat(organizationdetailFindBySourceResponse.postalCode()).contains("80903")
        assertThat(organizationdetailFindBySourceResponse.profit()).contains(123.4)
        assertThat(organizationdetailFindBySourceResponse.revenue()).contains(123.4)
        assertThat(organizationdetailFindBySourceResponse.revenueRanking()).contains(123)
        assertThat(organizationdetailFindBySourceResponse.riskManager()).contains("some.user")
        assertThat(organizationdetailFindBySourceResponse.servicesNotes()).contains("Example notes")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val organizationdetailFindBySourceResponse =
            OrganizationdetailFindBySourceResponse.builder()
                .classificationMarking("U")
                .dataMode(OrganizationdetailFindBySourceResponse.DataMode.TEST)
                .idOrganization("ORGANIZATION-ID")
                .name("some.user")
                .source("some.user")
                .id("ORGANIZATIONDETAILS-ID")
                .address1("123 Main Street")
                .address2("Apt 4B")
                .address3("Colorado Springs CO, 80903")
                .broker("some.user")
                .ceo("some.user")
                .cfo("some.user")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .cto("some.user")
                .description("Example description")
                .ebitda(123.4)
                .email("some_organization@organization.com")
                .financialNotes("Example notes")
                .financialYearEndDate(OffsetDateTime.parse("2021-01-01T01:01:01.123Z"))
                .fleetPlanNotes("Example notes")
                .formerOrgId("FORMERORG-ID")
                .ftes(123)
                .geoAdminLevel1("Colorado")
                .geoAdminLevel2("El Paso County")
                .geoAdminLevel3("Colorado Springs")
                .massRanking(123)
                .origin("some.user")
                .origNetwork("OPS1")
                .parentOrgId("PARENTORG-ID")
                .postalCode("80903")
                .profit(123.4)
                .revenue(123.4)
                .revenueRanking(123)
                .riskManager("some.user")
                .servicesNotes("Example notes")
                .build()

        val roundtrippedOrganizationdetailFindBySourceResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(organizationdetailFindBySourceResponse),
                jacksonTypeRef<OrganizationdetailFindBySourceResponse>(),
            )

        assertThat(roundtrippedOrganizationdetailFindBySourceResponse)
            .isEqualTo(organizationdetailFindBySourceResponse)
    }
}
