// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.surface

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SurfaceGetResponseTest {

    @Test
    fun create() {
        val surfaceGetResponse =
            SurfaceGetResponse.builder()
                .classificationMarking("U")
                .dataMode(SurfaceGetResponse.DataMode.TEST)
                .name("West lot")
                .source("Bluestaq")
                .type("PARKING")
                .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                .altSiteId("ORIG-SITE-ID")
                .condition("GOOD")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .ddtWtKip(833.5)
                .ddtWtKipMod(625.125)
                .ddtWtKipModNote("Observed 25% reduction in surface integrity.")
                .ddtWtKn(3705.44)
                .ddWtKip(416.25)
                .ddWtKipMod(312.1875)
                .ddWtKipModNote("Observed 25% reduction in surface integrity.")
                .ddWtKn(1850.1)
                .endLat(45.844)
                .endLon(-67.0094)
                .idSite("SITE-ID")
                .lcn(50)
                .ldaFt(475.2)
                .ldaM(145.75)
                .lengthFt(1500.75)
                .lengthM(457.5)
                .lighting(true)
                .lightsAprch(true)
                .lightsCl(true)
                .lightsOls(true)
                .lightsPapi(true)
                .lightsReil(true)
                .lightsRwy(true)
                .lightsSeqfl(true)
                .lightsTdzl(true)
                .lightsUnkn(false)
                .lightsVasi(true)
                .material("Concrete")
                .obstacle(true)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .pcn("73RBWT")
                .pointReference("Reference Point Example")
                .primary(true)
                .rawWbc("LCN 42")
                .sbttWtKip(603.025)
                .sbttWtKipMod(452.269)
                .sbttWtKipModNote("Observed 25% reduction in surface integrity.")
                .sbttWtKn(2682.05)
                .startLat(46.757211)
                .startLon(-67.759494)
                .stWtKip(195.75)
                .stWtKipMod(146.8125)
                .stWtKipModNote("Observed 25% reduction in surface integrity.")
                .stWtKn(867.6)
                .addSurfaceObstruction(
                    SurfaceGetResponse.SurfaceObstruction.builder()
                        .classificationMarking("U")
                        .dataMode(SurfaceGetResponse.SurfaceObstruction.DataMode.TEST)
                        .idSurface("be831d39-1822-da9f-7ace-6cc5643397dc")
                        .source("Bluestaq")
                        .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                        .addAdvisoryRequired("C20")
                        .addAdvisoryRequired("C17")
                        .addApprovalRequired("C20")
                        .addApprovalRequired("C17")
                        .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                        .createdBy("some.user")
                        .distanceFromCenterLine(17.8)
                        .distanceFromEdge(15.8)
                        .distanceFromThreshold(19.5)
                        .idNavigationalObstruction("a2831d39-1822-da9f-7ace-6cc5643397da")
                        .obstructionDesc("PYLON")
                        .obstructionHeight(35.25)
                        .obstructionSideCode("F")
                        .origin("THIRD_PARTY_DATASOURCE")
                        .origNetwork("OPS1")
                        .sourceDl("AXE")
                        .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                        .updatedBy("some.user")
                        .build()
                )
                .sWtKip(143.5)
                .sWtKipMod(107.625)
                .sWtKipModNote("Observed 25% reduction in surface integrity.")
                .sWtKn(636.4)
                .tdtWtkip(870.2)
                .tdtWtKipMod(652.65)
                .tdtWtKipModNote("Serious 25 percent reduction.")
                .tdtWtKn(3870.05)
                .trtWtKip(622.85)
                .trtWtKipMod(467.1375)
                .trtWtKipModNote("Observed 25% reduction in surface integrity.")
                .trtWtKn(2767.15)
                .ttWtKip(414.9)
                .ttWtKipMod(311.175)
                .ttWtKipModNote("Observed 25% reduction in surface integrity.")
                .ttWtKn(1842.55)
                .tWtKip(188.2)
                .tWtKipMod(141.15)
                .tWtKipModNote("Observed 25% reduction in surface integrity.")
                .tWtKn(836.45)
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .widthFt(220.3)
                .widthM(67.25)
                .build()

        assertThat(surfaceGetResponse.classificationMarking()).isEqualTo("U")
        assertThat(surfaceGetResponse.dataMode()).isEqualTo(SurfaceGetResponse.DataMode.TEST)
        assertThat(surfaceGetResponse.name()).isEqualTo("West lot")
        assertThat(surfaceGetResponse.source()).isEqualTo("Bluestaq")
        assertThat(surfaceGetResponse.type()).isEqualTo("PARKING")
        assertThat(surfaceGetResponse.id()).contains("be831d39-1822-da9f-7ace-6cc5643397dc")
        assertThat(surfaceGetResponse.altSiteId()).contains("ORIG-SITE-ID")
        assertThat(surfaceGetResponse.condition()).contains("GOOD")
        assertThat(surfaceGetResponse.createdAt())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(surfaceGetResponse.createdBy()).contains("some.user")
        assertThat(surfaceGetResponse.ddtWtKip()).contains(833.5)
        assertThat(surfaceGetResponse.ddtWtKipMod()).contains(625.125)
        assertThat(surfaceGetResponse.ddtWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceGetResponse.ddtWtKn()).contains(3705.44)
        assertThat(surfaceGetResponse.ddWtKip()).contains(416.25)
        assertThat(surfaceGetResponse.ddWtKipMod()).contains(312.1875)
        assertThat(surfaceGetResponse.ddWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceGetResponse.ddWtKn()).contains(1850.1)
        assertThat(surfaceGetResponse.endLat()).contains(45.844)
        assertThat(surfaceGetResponse.endLon()).contains(-67.0094)
        assertThat(surfaceGetResponse.idSite()).contains("SITE-ID")
        assertThat(surfaceGetResponse.lcn()).contains(50)
        assertThat(surfaceGetResponse.ldaFt()).contains(475.2)
        assertThat(surfaceGetResponse.ldaM()).contains(145.75)
        assertThat(surfaceGetResponse.lengthFt()).contains(1500.75)
        assertThat(surfaceGetResponse.lengthM()).contains(457.5)
        assertThat(surfaceGetResponse.lighting()).contains(true)
        assertThat(surfaceGetResponse.lightsAprch()).contains(true)
        assertThat(surfaceGetResponse.lightsCl()).contains(true)
        assertThat(surfaceGetResponse.lightsOls()).contains(true)
        assertThat(surfaceGetResponse.lightsPapi()).contains(true)
        assertThat(surfaceGetResponse.lightsReil()).contains(true)
        assertThat(surfaceGetResponse.lightsRwy()).contains(true)
        assertThat(surfaceGetResponse.lightsSeqfl()).contains(true)
        assertThat(surfaceGetResponse.lightsTdzl()).contains(true)
        assertThat(surfaceGetResponse.lightsUnkn()).contains(false)
        assertThat(surfaceGetResponse.lightsVasi()).contains(true)
        assertThat(surfaceGetResponse.material()).contains("Concrete")
        assertThat(surfaceGetResponse.obstacle()).contains(true)
        assertThat(surfaceGetResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(surfaceGetResponse.origNetwork()).contains("OPS1")
        assertThat(surfaceGetResponse.pcn()).contains("73RBWT")
        assertThat(surfaceGetResponse.pointReference()).contains("Reference Point Example")
        assertThat(surfaceGetResponse.primary()).contains(true)
        assertThat(surfaceGetResponse.rawWbc()).contains("LCN 42")
        assertThat(surfaceGetResponse.sbttWtKip()).contains(603.025)
        assertThat(surfaceGetResponse.sbttWtKipMod()).contains(452.269)
        assertThat(surfaceGetResponse.sbttWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceGetResponse.sbttWtKn()).contains(2682.05)
        assertThat(surfaceGetResponse.startLat()).contains(46.757211)
        assertThat(surfaceGetResponse.startLon()).contains(-67.759494)
        assertThat(surfaceGetResponse.stWtKip()).contains(195.75)
        assertThat(surfaceGetResponse.stWtKipMod()).contains(146.8125)
        assertThat(surfaceGetResponse.stWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceGetResponse.stWtKn()).contains(867.6)
        assertThat(surfaceGetResponse.surfaceObstructions().getOrNull())
            .containsExactly(
                SurfaceGetResponse.SurfaceObstruction.builder()
                    .classificationMarking("U")
                    .dataMode(SurfaceGetResponse.SurfaceObstruction.DataMode.TEST)
                    .idSurface("be831d39-1822-da9f-7ace-6cc5643397dc")
                    .source("Bluestaq")
                    .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                    .addAdvisoryRequired("C20")
                    .addAdvisoryRequired("C17")
                    .addApprovalRequired("C20")
                    .addApprovalRequired("C17")
                    .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                    .createdBy("some.user")
                    .distanceFromCenterLine(17.8)
                    .distanceFromEdge(15.8)
                    .distanceFromThreshold(19.5)
                    .idNavigationalObstruction("a2831d39-1822-da9f-7ace-6cc5643397da")
                    .obstructionDesc("PYLON")
                    .obstructionHeight(35.25)
                    .obstructionSideCode("F")
                    .origin("THIRD_PARTY_DATASOURCE")
                    .origNetwork("OPS1")
                    .sourceDl("AXE")
                    .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                    .updatedBy("some.user")
                    .build()
            )
        assertThat(surfaceGetResponse.sWtKip()).contains(143.5)
        assertThat(surfaceGetResponse.sWtKipMod()).contains(107.625)
        assertThat(surfaceGetResponse.sWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceGetResponse.sWtKn()).contains(636.4)
        assertThat(surfaceGetResponse.tdtWtkip()).contains(870.2)
        assertThat(surfaceGetResponse.tdtWtKipMod()).contains(652.65)
        assertThat(surfaceGetResponse.tdtWtKipModNote()).contains("Serious 25 percent reduction.")
        assertThat(surfaceGetResponse.tdtWtKn()).contains(3870.05)
        assertThat(surfaceGetResponse.trtWtKip()).contains(622.85)
        assertThat(surfaceGetResponse.trtWtKipMod()).contains(467.1375)
        assertThat(surfaceGetResponse.trtWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceGetResponse.trtWtKn()).contains(2767.15)
        assertThat(surfaceGetResponse.ttWtKip()).contains(414.9)
        assertThat(surfaceGetResponse.ttWtKipMod()).contains(311.175)
        assertThat(surfaceGetResponse.ttWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceGetResponse.ttWtKn()).contains(1842.55)
        assertThat(surfaceGetResponse.tWtKip()).contains(188.2)
        assertThat(surfaceGetResponse.tWtKipMod()).contains(141.15)
        assertThat(surfaceGetResponse.tWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceGetResponse.tWtKn()).contains(836.45)
        assertThat(surfaceGetResponse.updatedAt())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(surfaceGetResponse.updatedBy()).contains("some.user")
        assertThat(surfaceGetResponse.widthFt()).contains(220.3)
        assertThat(surfaceGetResponse.widthM()).contains(67.25)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val surfaceGetResponse =
            SurfaceGetResponse.builder()
                .classificationMarking("U")
                .dataMode(SurfaceGetResponse.DataMode.TEST)
                .name("West lot")
                .source("Bluestaq")
                .type("PARKING")
                .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                .altSiteId("ORIG-SITE-ID")
                .condition("GOOD")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .ddtWtKip(833.5)
                .ddtWtKipMod(625.125)
                .ddtWtKipModNote("Observed 25% reduction in surface integrity.")
                .ddtWtKn(3705.44)
                .ddWtKip(416.25)
                .ddWtKipMod(312.1875)
                .ddWtKipModNote("Observed 25% reduction in surface integrity.")
                .ddWtKn(1850.1)
                .endLat(45.844)
                .endLon(-67.0094)
                .idSite("SITE-ID")
                .lcn(50)
                .ldaFt(475.2)
                .ldaM(145.75)
                .lengthFt(1500.75)
                .lengthM(457.5)
                .lighting(true)
                .lightsAprch(true)
                .lightsCl(true)
                .lightsOls(true)
                .lightsPapi(true)
                .lightsReil(true)
                .lightsRwy(true)
                .lightsSeqfl(true)
                .lightsTdzl(true)
                .lightsUnkn(false)
                .lightsVasi(true)
                .material("Concrete")
                .obstacle(true)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .pcn("73RBWT")
                .pointReference("Reference Point Example")
                .primary(true)
                .rawWbc("LCN 42")
                .sbttWtKip(603.025)
                .sbttWtKipMod(452.269)
                .sbttWtKipModNote("Observed 25% reduction in surface integrity.")
                .sbttWtKn(2682.05)
                .startLat(46.757211)
                .startLon(-67.759494)
                .stWtKip(195.75)
                .stWtKipMod(146.8125)
                .stWtKipModNote("Observed 25% reduction in surface integrity.")
                .stWtKn(867.6)
                .addSurfaceObstruction(
                    SurfaceGetResponse.SurfaceObstruction.builder()
                        .classificationMarking("U")
                        .dataMode(SurfaceGetResponse.SurfaceObstruction.DataMode.TEST)
                        .idSurface("be831d39-1822-da9f-7ace-6cc5643397dc")
                        .source("Bluestaq")
                        .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                        .addAdvisoryRequired("C20")
                        .addAdvisoryRequired("C17")
                        .addApprovalRequired("C20")
                        .addApprovalRequired("C17")
                        .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                        .createdBy("some.user")
                        .distanceFromCenterLine(17.8)
                        .distanceFromEdge(15.8)
                        .distanceFromThreshold(19.5)
                        .idNavigationalObstruction("a2831d39-1822-da9f-7ace-6cc5643397da")
                        .obstructionDesc("PYLON")
                        .obstructionHeight(35.25)
                        .obstructionSideCode("F")
                        .origin("THIRD_PARTY_DATASOURCE")
                        .origNetwork("OPS1")
                        .sourceDl("AXE")
                        .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                        .updatedBy("some.user")
                        .build()
                )
                .sWtKip(143.5)
                .sWtKipMod(107.625)
                .sWtKipModNote("Observed 25% reduction in surface integrity.")
                .sWtKn(636.4)
                .tdtWtkip(870.2)
                .tdtWtKipMod(652.65)
                .tdtWtKipModNote("Serious 25 percent reduction.")
                .tdtWtKn(3870.05)
                .trtWtKip(622.85)
                .trtWtKipMod(467.1375)
                .trtWtKipModNote("Observed 25% reduction in surface integrity.")
                .trtWtKn(2767.15)
                .ttWtKip(414.9)
                .ttWtKipMod(311.175)
                .ttWtKipModNote("Observed 25% reduction in surface integrity.")
                .ttWtKn(1842.55)
                .tWtKip(188.2)
                .tWtKipMod(141.15)
                .tWtKipModNote("Observed 25% reduction in surface integrity.")
                .tWtKn(836.45)
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .widthFt(220.3)
                .widthM(67.25)
                .build()

        val roundtrippedSurfaceGetResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(surfaceGetResponse),
                jacksonTypeRef<SurfaceGetResponse>(),
            )

        assertThat(roundtrippedSurfaceGetResponse).isEqualTo(surfaceGetResponse)
    }
}
