// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.surface

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SurfaceTupleResponseTest {

    @Test
    fun create() {
        val surfaceTupleResponse =
            SurfaceTupleResponse.builder()
                .classificationMarking("U")
                .dataMode(SurfaceTupleResponse.DataMode.TEST)
                .name("West lot")
                .source("Bluestaq")
                .type("PARKING")
                .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                .altSiteId("ORIG-SITE-ID")
                .condition("GOOD")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .ddtWtKip(833.5)
                .ddtWtKipMod(625.125)
                .ddtWtKipModNote("Observed 25% reduction in surface integrity.")
                .ddtWtKn(3705.44)
                .ddWtKip(416.25)
                .ddWtKipMod(312.1875)
                .ddWtKipModNote("Observed 25% reduction in surface integrity.")
                .ddWtKn(1850.1)
                .endLat(45.844)
                .endLon(-67.0094)
                .idSite("SITE-ID")
                .lcn(50)
                .ldaFt(475.2)
                .ldaM(145.75)
                .lengthFt(1500.75)
                .lengthM(457.5)
                .lighting(true)
                .lightsAprch(true)
                .lightsCl(true)
                .lightsOls(true)
                .lightsPapi(true)
                .lightsReil(true)
                .lightsRwy(true)
                .lightsSeqfl(true)
                .lightsTdzl(true)
                .lightsUnkn(false)
                .lightsVasi(true)
                .material("Concrete")
                .obstacle(true)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .pcn("73RBWT")
                .pointReference("Reference Point Example")
                .primary(true)
                .rawWbc("LCN 42")
                .sbttWtKip(603.025)
                .sbttWtKipMod(452.269)
                .sbttWtKipModNote("Observed 25% reduction in surface integrity.")
                .sbttWtKn(2682.05)
                .startLat(46.757211)
                .startLon(-67.759494)
                .stWtKip(195.75)
                .stWtKipMod(146.8125)
                .stWtKipModNote("Observed 25% reduction in surface integrity.")
                .stWtKn(867.6)
                .addSurfaceObstruction(
                    SurfaceTupleResponse.SurfaceObstruction.builder()
                        .classificationMarking("U")
                        .dataMode(SurfaceTupleResponse.SurfaceObstruction.DataMode.TEST)
                        .idSurface("be831d39-1822-da9f-7ace-6cc5643397dc")
                        .source("Bluestaq")
                        .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                        .addAdvisoryRequired("C20")
                        .addAdvisoryRequired("C17")
                        .addApprovalRequired("C20")
                        .addApprovalRequired("C17")
                        .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                        .createdBy("some.user")
                        .distanceFromCenterLine(17.8)
                        .distanceFromEdge(15.8)
                        .distanceFromThreshold(19.5)
                        .idNavigationalObstruction("a2831d39-1822-da9f-7ace-6cc5643397da")
                        .obstructionDesc("PYLON")
                        .obstructionHeight(35.25)
                        .obstructionSideCode("F")
                        .origin("THIRD_PARTY_DATASOURCE")
                        .origNetwork("OPS1")
                        .sourceDl("AXE")
                        .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                        .updatedBy("some.user")
                        .build()
                )
                .sWtKip(143.5)
                .sWtKipMod(107.625)
                .sWtKipModNote("Observed 25% reduction in surface integrity.")
                .sWtKn(636.4)
                .tdtWtkip(870.2)
                .tdtWtKipMod(652.65)
                .tdtWtKipModNote("Serious 25 percent reduction.")
                .tdtWtKn(3870.05)
                .trtWtKip(622.85)
                .trtWtKipMod(467.1375)
                .trtWtKipModNote("Observed 25% reduction in surface integrity.")
                .trtWtKn(2767.15)
                .ttWtKip(414.9)
                .ttWtKipMod(311.175)
                .ttWtKipModNote("Observed 25% reduction in surface integrity.")
                .ttWtKn(1842.55)
                .tWtKip(188.2)
                .tWtKipMod(141.15)
                .tWtKipModNote("Observed 25% reduction in surface integrity.")
                .tWtKn(836.45)
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .widthFt(220.3)
                .widthM(67.25)
                .build()

        assertThat(surfaceTupleResponse.classificationMarking()).isEqualTo("U")
        assertThat(surfaceTupleResponse.dataMode()).isEqualTo(SurfaceTupleResponse.DataMode.TEST)
        assertThat(surfaceTupleResponse.name()).isEqualTo("West lot")
        assertThat(surfaceTupleResponse.source()).isEqualTo("Bluestaq")
        assertThat(surfaceTupleResponse.type()).isEqualTo("PARKING")
        assertThat(surfaceTupleResponse.id()).contains("be831d39-1822-da9f-7ace-6cc5643397dc")
        assertThat(surfaceTupleResponse.altSiteId()).contains("ORIG-SITE-ID")
        assertThat(surfaceTupleResponse.condition()).contains("GOOD")
        assertThat(surfaceTupleResponse.createdAt())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(surfaceTupleResponse.createdBy()).contains("some.user")
        assertThat(surfaceTupleResponse.ddtWtKip()).contains(833.5)
        assertThat(surfaceTupleResponse.ddtWtKipMod()).contains(625.125)
        assertThat(surfaceTupleResponse.ddtWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceTupleResponse.ddtWtKn()).contains(3705.44)
        assertThat(surfaceTupleResponse.ddWtKip()).contains(416.25)
        assertThat(surfaceTupleResponse.ddWtKipMod()).contains(312.1875)
        assertThat(surfaceTupleResponse.ddWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceTupleResponse.ddWtKn()).contains(1850.1)
        assertThat(surfaceTupleResponse.endLat()).contains(45.844)
        assertThat(surfaceTupleResponse.endLon()).contains(-67.0094)
        assertThat(surfaceTupleResponse.idSite()).contains("SITE-ID")
        assertThat(surfaceTupleResponse.lcn()).contains(50)
        assertThat(surfaceTupleResponse.ldaFt()).contains(475.2)
        assertThat(surfaceTupleResponse.ldaM()).contains(145.75)
        assertThat(surfaceTupleResponse.lengthFt()).contains(1500.75)
        assertThat(surfaceTupleResponse.lengthM()).contains(457.5)
        assertThat(surfaceTupleResponse.lighting()).contains(true)
        assertThat(surfaceTupleResponse.lightsAprch()).contains(true)
        assertThat(surfaceTupleResponse.lightsCl()).contains(true)
        assertThat(surfaceTupleResponse.lightsOls()).contains(true)
        assertThat(surfaceTupleResponse.lightsPapi()).contains(true)
        assertThat(surfaceTupleResponse.lightsReil()).contains(true)
        assertThat(surfaceTupleResponse.lightsRwy()).contains(true)
        assertThat(surfaceTupleResponse.lightsSeqfl()).contains(true)
        assertThat(surfaceTupleResponse.lightsTdzl()).contains(true)
        assertThat(surfaceTupleResponse.lightsUnkn()).contains(false)
        assertThat(surfaceTupleResponse.lightsVasi()).contains(true)
        assertThat(surfaceTupleResponse.material()).contains("Concrete")
        assertThat(surfaceTupleResponse.obstacle()).contains(true)
        assertThat(surfaceTupleResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(surfaceTupleResponse.origNetwork()).contains("OPS1")
        assertThat(surfaceTupleResponse.pcn()).contains("73RBWT")
        assertThat(surfaceTupleResponse.pointReference()).contains("Reference Point Example")
        assertThat(surfaceTupleResponse.primary()).contains(true)
        assertThat(surfaceTupleResponse.rawWbc()).contains("LCN 42")
        assertThat(surfaceTupleResponse.sbttWtKip()).contains(603.025)
        assertThat(surfaceTupleResponse.sbttWtKipMod()).contains(452.269)
        assertThat(surfaceTupleResponse.sbttWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceTupleResponse.sbttWtKn()).contains(2682.05)
        assertThat(surfaceTupleResponse.startLat()).contains(46.757211)
        assertThat(surfaceTupleResponse.startLon()).contains(-67.759494)
        assertThat(surfaceTupleResponse.stWtKip()).contains(195.75)
        assertThat(surfaceTupleResponse.stWtKipMod()).contains(146.8125)
        assertThat(surfaceTupleResponse.stWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceTupleResponse.stWtKn()).contains(867.6)
        assertThat(surfaceTupleResponse.surfaceObstructions().getOrNull())
            .containsExactly(
                SurfaceTupleResponse.SurfaceObstruction.builder()
                    .classificationMarking("U")
                    .dataMode(SurfaceTupleResponse.SurfaceObstruction.DataMode.TEST)
                    .idSurface("be831d39-1822-da9f-7ace-6cc5643397dc")
                    .source("Bluestaq")
                    .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                    .addAdvisoryRequired("C20")
                    .addAdvisoryRequired("C17")
                    .addApprovalRequired("C20")
                    .addApprovalRequired("C17")
                    .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                    .createdBy("some.user")
                    .distanceFromCenterLine(17.8)
                    .distanceFromEdge(15.8)
                    .distanceFromThreshold(19.5)
                    .idNavigationalObstruction("a2831d39-1822-da9f-7ace-6cc5643397da")
                    .obstructionDesc("PYLON")
                    .obstructionHeight(35.25)
                    .obstructionSideCode("F")
                    .origin("THIRD_PARTY_DATASOURCE")
                    .origNetwork("OPS1")
                    .sourceDl("AXE")
                    .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                    .updatedBy("some.user")
                    .build()
            )
        assertThat(surfaceTupleResponse.sWtKip()).contains(143.5)
        assertThat(surfaceTupleResponse.sWtKipMod()).contains(107.625)
        assertThat(surfaceTupleResponse.sWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceTupleResponse.sWtKn()).contains(636.4)
        assertThat(surfaceTupleResponse.tdtWtkip()).contains(870.2)
        assertThat(surfaceTupleResponse.tdtWtKipMod()).contains(652.65)
        assertThat(surfaceTupleResponse.tdtWtKipModNote()).contains("Serious 25 percent reduction.")
        assertThat(surfaceTupleResponse.tdtWtKn()).contains(3870.05)
        assertThat(surfaceTupleResponse.trtWtKip()).contains(622.85)
        assertThat(surfaceTupleResponse.trtWtKipMod()).contains(467.1375)
        assertThat(surfaceTupleResponse.trtWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceTupleResponse.trtWtKn()).contains(2767.15)
        assertThat(surfaceTupleResponse.ttWtKip()).contains(414.9)
        assertThat(surfaceTupleResponse.ttWtKipMod()).contains(311.175)
        assertThat(surfaceTupleResponse.ttWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceTupleResponse.ttWtKn()).contains(1842.55)
        assertThat(surfaceTupleResponse.tWtKip()).contains(188.2)
        assertThat(surfaceTupleResponse.tWtKipMod()).contains(141.15)
        assertThat(surfaceTupleResponse.tWtKipModNote())
            .contains("Observed 25% reduction in surface integrity.")
        assertThat(surfaceTupleResponse.tWtKn()).contains(836.45)
        assertThat(surfaceTupleResponse.updatedAt())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(surfaceTupleResponse.updatedBy()).contains("some.user")
        assertThat(surfaceTupleResponse.widthFt()).contains(220.3)
        assertThat(surfaceTupleResponse.widthM()).contains(67.25)
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val surfaceTupleResponse =
            SurfaceTupleResponse.builder()
                .classificationMarking("U")
                .dataMode(SurfaceTupleResponse.DataMode.TEST)
                .name("West lot")
                .source("Bluestaq")
                .type("PARKING")
                .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                .altSiteId("ORIG-SITE-ID")
                .condition("GOOD")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .ddtWtKip(833.5)
                .ddtWtKipMod(625.125)
                .ddtWtKipModNote("Observed 25% reduction in surface integrity.")
                .ddtWtKn(3705.44)
                .ddWtKip(416.25)
                .ddWtKipMod(312.1875)
                .ddWtKipModNote("Observed 25% reduction in surface integrity.")
                .ddWtKn(1850.1)
                .endLat(45.844)
                .endLon(-67.0094)
                .idSite("SITE-ID")
                .lcn(50)
                .ldaFt(475.2)
                .ldaM(145.75)
                .lengthFt(1500.75)
                .lengthM(457.5)
                .lighting(true)
                .lightsAprch(true)
                .lightsCl(true)
                .lightsOls(true)
                .lightsPapi(true)
                .lightsReil(true)
                .lightsRwy(true)
                .lightsSeqfl(true)
                .lightsTdzl(true)
                .lightsUnkn(false)
                .lightsVasi(true)
                .material("Concrete")
                .obstacle(true)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .pcn("73RBWT")
                .pointReference("Reference Point Example")
                .primary(true)
                .rawWbc("LCN 42")
                .sbttWtKip(603.025)
                .sbttWtKipMod(452.269)
                .sbttWtKipModNote("Observed 25% reduction in surface integrity.")
                .sbttWtKn(2682.05)
                .startLat(46.757211)
                .startLon(-67.759494)
                .stWtKip(195.75)
                .stWtKipMod(146.8125)
                .stWtKipModNote("Observed 25% reduction in surface integrity.")
                .stWtKn(867.6)
                .addSurfaceObstruction(
                    SurfaceTupleResponse.SurfaceObstruction.builder()
                        .classificationMarking("U")
                        .dataMode(SurfaceTupleResponse.SurfaceObstruction.DataMode.TEST)
                        .idSurface("be831d39-1822-da9f-7ace-6cc5643397dc")
                        .source("Bluestaq")
                        .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                        .addAdvisoryRequired("C20")
                        .addAdvisoryRequired("C17")
                        .addApprovalRequired("C20")
                        .addApprovalRequired("C17")
                        .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                        .createdBy("some.user")
                        .distanceFromCenterLine(17.8)
                        .distanceFromEdge(15.8)
                        .distanceFromThreshold(19.5)
                        .idNavigationalObstruction("a2831d39-1822-da9f-7ace-6cc5643397da")
                        .obstructionDesc("PYLON")
                        .obstructionHeight(35.25)
                        .obstructionSideCode("F")
                        .origin("THIRD_PARTY_DATASOURCE")
                        .origNetwork("OPS1")
                        .sourceDl("AXE")
                        .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                        .updatedBy("some.user")
                        .build()
                )
                .sWtKip(143.5)
                .sWtKipMod(107.625)
                .sWtKipModNote("Observed 25% reduction in surface integrity.")
                .sWtKn(636.4)
                .tdtWtkip(870.2)
                .tdtWtKipMod(652.65)
                .tdtWtKipModNote("Serious 25 percent reduction.")
                .tdtWtKn(3870.05)
                .trtWtKip(622.85)
                .trtWtKipMod(467.1375)
                .trtWtKipModNote("Observed 25% reduction in surface integrity.")
                .trtWtKn(2767.15)
                .ttWtKip(414.9)
                .ttWtKipMod(311.175)
                .ttWtKipModNote("Observed 25% reduction in surface integrity.")
                .ttWtKn(1842.55)
                .tWtKip(188.2)
                .tWtKipMod(141.15)
                .tWtKipModNote("Observed 25% reduction in surface integrity.")
                .tWtKn(836.45)
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .widthFt(220.3)
                .widthM(67.25)
                .build()

        val roundtrippedSurfaceTupleResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(surfaceTupleResponse),
                jacksonTypeRef<SurfaceTupleResponse>(),
            )

        assertThat(roundtrippedSurfaceTupleResponse).isEqualTo(surfaceTupleResponse)
    }
}
