// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.surface

import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class SurfaceCreateParamsTest {

    @Test
    fun create() {
        SurfaceCreateParams.builder()
            .classificationMarking("U")
            .dataMode(SurfaceCreateParams.DataMode.TEST)
            .name("West lot")
            .source("Bluestaq")
            .type("PARKING")
            .id("be831d39-1822-da9f-7ace-6cc5643397dc")
            .altSiteId("ORIG-SITE-ID")
            .condition("GOOD")
            .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
            .createdBy("some.user")
            .ddtWtKip(833.5)
            .ddtWtKipMod(625.125)
            .ddtWtKipModNote("Observed 25% reduction in surface integrity.")
            .ddtWtKn(3705.44)
            .ddWtKip(416.25)
            .ddWtKipMod(312.1875)
            .ddWtKipModNote("Observed 25% reduction in surface integrity.")
            .ddWtKn(1850.1)
            .endLat(45.844)
            .endLon(-67.0094)
            .idSite("SITE-ID")
            .lcn(50)
            .ldaFt(475.2)
            .ldaM(145.75)
            .lengthFt(1500.75)
            .lengthM(457.5)
            .lighting(true)
            .lightsAprch(true)
            .lightsCl(true)
            .lightsOls(true)
            .lightsPapi(true)
            .lightsReil(true)
            .lightsRwy(true)
            .lightsSeqfl(true)
            .lightsTdzl(true)
            .lightsUnkn(false)
            .lightsVasi(true)
            .material("Concrete")
            .obstacle(true)
            .origin("THIRD_PARTY_DATASOURCE")
            .origNetwork("OPS1")
            .pcn("73RBWT")
            .pointReference("Reference Point Example")
            .primary(true)
            .rawWbc("LCN 42")
            .sbttWtKip(603.025)
            .sbttWtKipMod(452.269)
            .sbttWtKipModNote("Observed 25% reduction in surface integrity.")
            .sbttWtKn(2682.05)
            .startLat(46.757211)
            .startLon(-67.759494)
            .stWtKip(195.75)
            .stWtKipMod(146.8125)
            .stWtKipModNote("Observed 25% reduction in surface integrity.")
            .stWtKn(867.6)
            .sWtKip(143.5)
            .sWtKipMod(107.625)
            .sWtKipModNote("Observed 25% reduction in surface integrity.")
            .sWtKn(636.4)
            .tdtWtkip(870.2)
            .tdtWtKipMod(652.65)
            .tdtWtKipModNote("Serious 25 percent reduction.")
            .tdtWtKn(3870.05)
            .trtWtKip(622.85)
            .trtWtKipMod(467.1375)
            .trtWtKipModNote("Observed 25% reduction in surface integrity.")
            .trtWtKn(2767.15)
            .ttWtKip(414.9)
            .ttWtKipMod(311.175)
            .ttWtKipModNote("Observed 25% reduction in surface integrity.")
            .ttWtKn(1842.55)
            .tWtKip(188.2)
            .tWtKipMod(141.15)
            .tWtKipModNote("Observed 25% reduction in surface integrity.")
            .tWtKn(836.45)
            .widthFt(220.3)
            .widthM(67.25)
            .build()
    }

    @Test
    fun body() {
        val params =
            SurfaceCreateParams.builder()
                .classificationMarking("U")
                .dataMode(SurfaceCreateParams.DataMode.TEST)
                .name("West lot")
                .source("Bluestaq")
                .type("PARKING")
                .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                .altSiteId("ORIG-SITE-ID")
                .condition("GOOD")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .ddtWtKip(833.5)
                .ddtWtKipMod(625.125)
                .ddtWtKipModNote("Observed 25% reduction in surface integrity.")
                .ddtWtKn(3705.44)
                .ddWtKip(416.25)
                .ddWtKipMod(312.1875)
                .ddWtKipModNote("Observed 25% reduction in surface integrity.")
                .ddWtKn(1850.1)
                .endLat(45.844)
                .endLon(-67.0094)
                .idSite("SITE-ID")
                .lcn(50)
                .ldaFt(475.2)
                .ldaM(145.75)
                .lengthFt(1500.75)
                .lengthM(457.5)
                .lighting(true)
                .lightsAprch(true)
                .lightsCl(true)
                .lightsOls(true)
                .lightsPapi(true)
                .lightsReil(true)
                .lightsRwy(true)
                .lightsSeqfl(true)
                .lightsTdzl(true)
                .lightsUnkn(false)
                .lightsVasi(true)
                .material("Concrete")
                .obstacle(true)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .pcn("73RBWT")
                .pointReference("Reference Point Example")
                .primary(true)
                .rawWbc("LCN 42")
                .sbttWtKip(603.025)
                .sbttWtKipMod(452.269)
                .sbttWtKipModNote("Observed 25% reduction in surface integrity.")
                .sbttWtKn(2682.05)
                .startLat(46.757211)
                .startLon(-67.759494)
                .stWtKip(195.75)
                .stWtKipMod(146.8125)
                .stWtKipModNote("Observed 25% reduction in surface integrity.")
                .stWtKn(867.6)
                .sWtKip(143.5)
                .sWtKipMod(107.625)
                .sWtKipModNote("Observed 25% reduction in surface integrity.")
                .sWtKn(636.4)
                .tdtWtkip(870.2)
                .tdtWtKipMod(652.65)
                .tdtWtKipModNote("Serious 25 percent reduction.")
                .tdtWtKn(3870.05)
                .trtWtKip(622.85)
                .trtWtKipMod(467.1375)
                .trtWtKipModNote("Observed 25% reduction in surface integrity.")
                .trtWtKn(2767.15)
                .ttWtKip(414.9)
                .ttWtKipMod(311.175)
                .ttWtKipModNote("Observed 25% reduction in surface integrity.")
                .ttWtKn(1842.55)
                .tWtKip(188.2)
                .tWtKipMod(141.15)
                .tWtKipModNote("Observed 25% reduction in surface integrity.")
                .tWtKn(836.45)
                .widthFt(220.3)
                .widthM(67.25)
                .build()

        val body = params._body()

        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(SurfaceCreateParams.DataMode.TEST)
        assertThat(body.name()).isEqualTo("West lot")
        assertThat(body.source()).isEqualTo("Bluestaq")
        assertThat(body.type()).isEqualTo("PARKING")
        assertThat(body.id()).contains("be831d39-1822-da9f-7ace-6cc5643397dc")
        assertThat(body.altSiteId()).contains("ORIG-SITE-ID")
        assertThat(body.condition()).contains("GOOD")
        assertThat(body.createdAt()).contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(body.createdBy()).contains("some.user")
        assertThat(body.ddtWtKip()).contains(833.5)
        assertThat(body.ddtWtKipMod()).contains(625.125)
        assertThat(body.ddtWtKipModNote()).contains("Observed 25% reduction in surface integrity.")
        assertThat(body.ddtWtKn()).contains(3705.44)
        assertThat(body.ddWtKip()).contains(416.25)
        assertThat(body.ddWtKipMod()).contains(312.1875)
        assertThat(body.ddWtKipModNote()).contains("Observed 25% reduction in surface integrity.")
        assertThat(body.ddWtKn()).contains(1850.1)
        assertThat(body.endLat()).contains(45.844)
        assertThat(body.endLon()).contains(-67.0094)
        assertThat(body.idSite()).contains("SITE-ID")
        assertThat(body.lcn()).contains(50)
        assertThat(body.ldaFt()).contains(475.2)
        assertThat(body.ldaM()).contains(145.75)
        assertThat(body.lengthFt()).contains(1500.75)
        assertThat(body.lengthM()).contains(457.5)
        assertThat(body.lighting()).contains(true)
        assertThat(body.lightsAprch()).contains(true)
        assertThat(body.lightsCl()).contains(true)
        assertThat(body.lightsOls()).contains(true)
        assertThat(body.lightsPapi()).contains(true)
        assertThat(body.lightsReil()).contains(true)
        assertThat(body.lightsRwy()).contains(true)
        assertThat(body.lightsSeqfl()).contains(true)
        assertThat(body.lightsTdzl()).contains(true)
        assertThat(body.lightsUnkn()).contains(false)
        assertThat(body.lightsVasi()).contains(true)
        assertThat(body.material()).contains("Concrete")
        assertThat(body.obstacle()).contains(true)
        assertThat(body.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(body.origNetwork()).contains("OPS1")
        assertThat(body.pcn()).contains("73RBWT")
        assertThat(body.pointReference()).contains("Reference Point Example")
        assertThat(body.primary()).contains(true)
        assertThat(body.rawWbc()).contains("LCN 42")
        assertThat(body.sbttWtKip()).contains(603.025)
        assertThat(body.sbttWtKipMod()).contains(452.269)
        assertThat(body.sbttWtKipModNote()).contains("Observed 25% reduction in surface integrity.")
        assertThat(body.sbttWtKn()).contains(2682.05)
        assertThat(body.startLat()).contains(46.757211)
        assertThat(body.startLon()).contains(-67.759494)
        assertThat(body.stWtKip()).contains(195.75)
        assertThat(body.stWtKipMod()).contains(146.8125)
        assertThat(body.stWtKipModNote()).contains("Observed 25% reduction in surface integrity.")
        assertThat(body.stWtKn()).contains(867.6)
        assertThat(body.sWtKip()).contains(143.5)
        assertThat(body.sWtKipMod()).contains(107.625)
        assertThat(body.sWtKipModNote()).contains("Observed 25% reduction in surface integrity.")
        assertThat(body.sWtKn()).contains(636.4)
        assertThat(body.tdtWtkip()).contains(870.2)
        assertThat(body.tdtWtKipMod()).contains(652.65)
        assertThat(body.tdtWtKipModNote()).contains("Serious 25 percent reduction.")
        assertThat(body.tdtWtKn()).contains(3870.05)
        assertThat(body.trtWtKip()).contains(622.85)
        assertThat(body.trtWtKipMod()).contains(467.1375)
        assertThat(body.trtWtKipModNote()).contains("Observed 25% reduction in surface integrity.")
        assertThat(body.trtWtKn()).contains(2767.15)
        assertThat(body.ttWtKip()).contains(414.9)
        assertThat(body.ttWtKipMod()).contains(311.175)
        assertThat(body.ttWtKipModNote()).contains("Observed 25% reduction in surface integrity.")
        assertThat(body.ttWtKn()).contains(1842.55)
        assertThat(body.tWtKip()).contains(188.2)
        assertThat(body.tWtKipMod()).contains(141.15)
        assertThat(body.tWtKipModNote()).contains("Observed 25% reduction in surface integrity.")
        assertThat(body.tWtKn()).contains(836.45)
        assertThat(body.widthFt()).contains(220.3)
        assertThat(body.widthM()).contains(67.25)
    }

    @Test
    fun bodyWithoutOptionalFields() {
        val params =
            SurfaceCreateParams.builder()
                .classificationMarking("U")
                .dataMode(SurfaceCreateParams.DataMode.TEST)
                .name("West lot")
                .source("Bluestaq")
                .type("PARKING")
                .build()

        val body = params._body()

        assertThat(body.classificationMarking()).isEqualTo("U")
        assertThat(body.dataMode()).isEqualTo(SurfaceCreateParams.DataMode.TEST)
        assertThat(body.name()).isEqualTo("West lot")
        assertThat(body.source()).isEqualTo("Bluestaq")
        assertThat(body.type()).isEqualTo("PARKING")
    }
}
