// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class CrewFullTest {

    @Test
    fun create() {
        val crewFull =
            CrewFull.builder()
                .classificationMarking("U")
                .dataMode(CrewFull.DataMode.TEST)
                .origCrewId("JHJDHjhuu929o92")
                .source("Bluestaq")
                .id("bdad6945-c9e4-b829-f7be-1ad075541921")
                .adjReturnTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                .adjReturnTimeApprover("Smith")
                .aircraftMds("C017A")
                .alertedTime(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .alertType("ALPHA")
                .armsCrewUnit("00016ALSQ")
                .addAssignedQualCode("AL")
                .addAssignedQualCode("CS")
                .commanderId("763a1c1e8d2f3c16af825a11e3f1f579")
                .commanderLast4Ssn("1234")
                .commanderName("John Doe")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .crewHome(false)
                .addCrewMember(
                    CrewFull.CrewMember.builder()
                        .alerted(true)
                        .allSortie(true)
                        .approved(true)
                        .attached(true)
                        .branch("Air Force")
                        .civilian(false)
                        .commander(false)
                        .crewPosition("EP A")
                        .dodId("0123456789")
                        .dutyPosition("IP")
                        .dutyStatus("AGR")
                        .emailed(true)
                        .extraTime(true)
                        .firstName("Freddie")
                        .fltCurrencyExp(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .fltCurrencyExpId("SS05AM")
                        .fltRecDate(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .fltRecDue(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .flySquadron("141ARS")
                        .funded(true)
                        .gender("F")
                        .gndCurrencyExp(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .gndCurrencyExpId("AH03YM")
                        .grounded(true)
                        .guestStart(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .guestStop(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .last4Ssn("1234")
                        .lastFltDate(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .lastName("Smith")
                        .loanedTo("Thunderbirds")
                        .lodging("Peterson SFB")
                        .memberActualAlertTime(OffsetDateTime.parse("2024-02-26T09:15:00.123Z"))
                        .memberAdjReturnTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .memberAdjReturnTimeApprover("Smith")
                        .memberId("12345678abc")
                        .memberInitStartTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .memberLastAlertTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .memberLegalAlertTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .memberPickupTime(OffsetDateTime.parse("2024-02-26T10:15:00.123Z"))
                        .memberPostRestOffset("+05:00")
                        .memberPostRestTime(OffsetDateTime.parse("2024-01-02T16:00:00.123Z"))
                        .memberPreRestTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .memberRemarks("Crew member remark")
                        .memberReturnTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .memberSchedAlertTime(OffsetDateTime.parse("2024-02-26T09:15:00.123Z"))
                        .memberSource("ACTIVE")
                        .memberStageName("Falcon Squadron")
                        .memberTransportReq(true)
                        .memberType("AIRCREW")
                        .middleInitial("G")
                        .notified(true)
                        .phoneNumber("+14155552671")
                        .physAvCode("D")
                        .physAvStatus("OVERDUE")
                        .physDue(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .rank("Capt")
                        .remarkCode("ABE33")
                        .rmsMds("C017A")
                        .showTime(OffsetDateTime.parse("2024-02-26T10:15:00.123Z"))
                        .squadron("21AS")
                        .trainingDate(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .username("fgsmith")
                        .wing("60AMW")
                        .build()
                )
                .crewName("falcon")
                .crewRms("ARMS")
                .crewRole("DEADHEAD")
                .crewSource("ACTIVE")
                .crewSquadron("21AS")
                .crewType("AIRLAND")
                .crewUnit("00016ALSQ")
                .crewWing("60AMW")
                .currentIcao("KCOS")
                .fdpEligType("A")
                .fdpType("A")
                .femaleEnlistedQty(2)
                .femaleOfficerQty(1)
                .fltAuthNum("KT001")
                .idSiteCurrent("b677cf3b-d44d-450e-8b8f-d23f997f8778")
                .idSortie("4ef3d1e8-ab08-ab70-498f-edc479734e5c")
                .initStartTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                .lastAlertTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                .legalAlertTime(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .legalBravoTime(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .linkedTask(false)
                .maleEnlistedQty(3)
                .maleOfficerQty(1)
                .missionAlias("PACIFIC DEPLOY / CHAP 3 MOVEMENT")
                .missionId("AJM123456123")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .personnelType("AIRCREW")
                .pickupTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                .postRestApplied(false)
                .postRestEnd(OffsetDateTime.parse("2024-01-02T16:00:00.123Z"))
                .postRestOffset("+05:00")
                .preRestApplied(false)
                .preRestStart(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                .addReqQualCode("AL")
                .addReqQualCode("CS")
                .returnTime(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .sourceDl("AXE")
                .stage1Qual("1AXXX")
                .stage2Qual("2AXXX")
                .stage3Qual("3AXXX")
                .stageName("Falcon Squadron")
                .stageTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                .status("APPROVED")
                .transportReq(true)
                .tripKit("TK-1234")
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .build()

        assertThat(crewFull.classificationMarking()).isEqualTo("U")
        assertThat(crewFull.dataMode()).isEqualTo(CrewFull.DataMode.TEST)
        assertThat(crewFull.origCrewId()).isEqualTo("JHJDHjhuu929o92")
        assertThat(crewFull.source()).isEqualTo("Bluestaq")
        assertThat(crewFull.id()).contains("bdad6945-c9e4-b829-f7be-1ad075541921")
        assertThat(crewFull.adjReturnTime())
            .contains(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
        assertThat(crewFull.adjReturnTimeApprover()).contains("Smith")
        assertThat(crewFull.aircraftMds()).contains("C017A")
        assertThat(crewFull.alertedTime())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(crewFull.alertType()).contains("ALPHA")
        assertThat(crewFull.armsCrewUnit()).contains("00016ALSQ")
        assertThat(crewFull.assignedQualCode().getOrNull()).containsExactly("AL", "CS")
        assertThat(crewFull.commanderId()).contains("763a1c1e8d2f3c16af825a11e3f1f579")
        assertThat(crewFull.commanderLast4Ssn()).contains("1234")
        assertThat(crewFull.commanderName()).contains("John Doe")
        assertThat(crewFull.createdAt()).contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(crewFull.createdBy()).contains("some.user")
        assertThat(crewFull.crewHome()).contains(false)
        assertThat(crewFull.crewMembers().getOrNull())
            .containsExactly(
                CrewFull.CrewMember.builder()
                    .alerted(true)
                    .allSortie(true)
                    .approved(true)
                    .attached(true)
                    .branch("Air Force")
                    .civilian(false)
                    .commander(false)
                    .crewPosition("EP A")
                    .dodId("0123456789")
                    .dutyPosition("IP")
                    .dutyStatus("AGR")
                    .emailed(true)
                    .extraTime(true)
                    .firstName("Freddie")
                    .fltCurrencyExp(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .fltCurrencyExpId("SS05AM")
                    .fltRecDate(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .fltRecDue(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .flySquadron("141ARS")
                    .funded(true)
                    .gender("F")
                    .gndCurrencyExp(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .gndCurrencyExpId("AH03YM")
                    .grounded(true)
                    .guestStart(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .guestStop(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .last4Ssn("1234")
                    .lastFltDate(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .lastName("Smith")
                    .loanedTo("Thunderbirds")
                    .lodging("Peterson SFB")
                    .memberActualAlertTime(OffsetDateTime.parse("2024-02-26T09:15:00.123Z"))
                    .memberAdjReturnTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .memberAdjReturnTimeApprover("Smith")
                    .memberId("12345678abc")
                    .memberInitStartTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .memberLastAlertTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .memberLegalAlertTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .memberPickupTime(OffsetDateTime.parse("2024-02-26T10:15:00.123Z"))
                    .memberPostRestOffset("+05:00")
                    .memberPostRestTime(OffsetDateTime.parse("2024-01-02T16:00:00.123Z"))
                    .memberPreRestTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .memberRemarks("Crew member remark")
                    .memberReturnTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .memberSchedAlertTime(OffsetDateTime.parse("2024-02-26T09:15:00.123Z"))
                    .memberSource("ACTIVE")
                    .memberStageName("Falcon Squadron")
                    .memberTransportReq(true)
                    .memberType("AIRCREW")
                    .middleInitial("G")
                    .notified(true)
                    .phoneNumber("+14155552671")
                    .physAvCode("D")
                    .physAvStatus("OVERDUE")
                    .physDue(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .rank("Capt")
                    .remarkCode("ABE33")
                    .rmsMds("C017A")
                    .showTime(OffsetDateTime.parse("2024-02-26T10:15:00.123Z"))
                    .squadron("21AS")
                    .trainingDate(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                    .username("fgsmith")
                    .wing("60AMW")
                    .build()
            )
        assertThat(crewFull.crewName()).contains("falcon")
        assertThat(crewFull.crewRms()).contains("ARMS")
        assertThat(crewFull.crewRole()).contains("DEADHEAD")
        assertThat(crewFull.crewSource()).contains("ACTIVE")
        assertThat(crewFull.crewSquadron()).contains("21AS")
        assertThat(crewFull.crewType()).contains("AIRLAND")
        assertThat(crewFull.crewUnit()).contains("00016ALSQ")
        assertThat(crewFull.crewWing()).contains("60AMW")
        assertThat(crewFull.currentIcao()).contains("KCOS")
        assertThat(crewFull.fdpEligType()).contains("A")
        assertThat(crewFull.fdpType()).contains("A")
        assertThat(crewFull.femaleEnlistedQty()).contains(2)
        assertThat(crewFull.femaleOfficerQty()).contains(1)
        assertThat(crewFull.fltAuthNum()).contains("KT001")
        assertThat(crewFull.idSiteCurrent()).contains("b677cf3b-d44d-450e-8b8f-d23f997f8778")
        assertThat(crewFull.idSortie()).contains("4ef3d1e8-ab08-ab70-498f-edc479734e5c")
        assertThat(crewFull.initStartTime())
            .contains(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
        assertThat(crewFull.lastAlertTime())
            .contains(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
        assertThat(crewFull.legalAlertTime())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(crewFull.legalBravoTime())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(crewFull.linkedTask()).contains(false)
        assertThat(crewFull.maleEnlistedQty()).contains(3)
        assertThat(crewFull.maleOfficerQty()).contains(1)
        assertThat(crewFull.missionAlias()).contains("PACIFIC DEPLOY / CHAP 3 MOVEMENT")
        assertThat(crewFull.missionId()).contains("AJM123456123")
        assertThat(crewFull.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(crewFull.origNetwork()).contains("OPS1")
        assertThat(crewFull.personnelType()).contains("AIRCREW")
        assertThat(crewFull.pickupTime()).contains(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
        assertThat(crewFull.postRestApplied()).contains(false)
        assertThat(crewFull.postRestEnd())
            .contains(OffsetDateTime.parse("2024-01-02T16:00:00.123Z"))
        assertThat(crewFull.postRestOffset()).contains("+05:00")
        assertThat(crewFull.preRestApplied()).contains(false)
        assertThat(crewFull.preRestStart())
            .contains(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
        assertThat(crewFull.reqQualCode().getOrNull()).containsExactly("AL", "CS")
        assertThat(crewFull.returnTime()).contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(crewFull.sourceDl()).contains("AXE")
        assertThat(crewFull.stage1Qual()).contains("1AXXX")
        assertThat(crewFull.stage2Qual()).contains("2AXXX")
        assertThat(crewFull.stage3Qual()).contains("3AXXX")
        assertThat(crewFull.stageName()).contains("Falcon Squadron")
        assertThat(crewFull.stageTime()).contains(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
        assertThat(crewFull.status()).contains("APPROVED")
        assertThat(crewFull.transportReq()).contains(true)
        assertThat(crewFull.tripKit()).contains("TK-1234")
        assertThat(crewFull.updatedAt()).contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(crewFull.updatedBy()).contains("some.user")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val crewFull =
            CrewFull.builder()
                .classificationMarking("U")
                .dataMode(CrewFull.DataMode.TEST)
                .origCrewId("JHJDHjhuu929o92")
                .source("Bluestaq")
                .id("bdad6945-c9e4-b829-f7be-1ad075541921")
                .adjReturnTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                .adjReturnTimeApprover("Smith")
                .aircraftMds("C017A")
                .alertedTime(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .alertType("ALPHA")
                .armsCrewUnit("00016ALSQ")
                .addAssignedQualCode("AL")
                .addAssignedQualCode("CS")
                .commanderId("763a1c1e8d2f3c16af825a11e3f1f579")
                .commanderLast4Ssn("1234")
                .commanderName("John Doe")
                .createdAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .crewHome(false)
                .addCrewMember(
                    CrewFull.CrewMember.builder()
                        .alerted(true)
                        .allSortie(true)
                        .approved(true)
                        .attached(true)
                        .branch("Air Force")
                        .civilian(false)
                        .commander(false)
                        .crewPosition("EP A")
                        .dodId("0123456789")
                        .dutyPosition("IP")
                        .dutyStatus("AGR")
                        .emailed(true)
                        .extraTime(true)
                        .firstName("Freddie")
                        .fltCurrencyExp(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .fltCurrencyExpId("SS05AM")
                        .fltRecDate(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .fltRecDue(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .flySquadron("141ARS")
                        .funded(true)
                        .gender("F")
                        .gndCurrencyExp(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .gndCurrencyExpId("AH03YM")
                        .grounded(true)
                        .guestStart(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .guestStop(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .last4Ssn("1234")
                        .lastFltDate(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .lastName("Smith")
                        .loanedTo("Thunderbirds")
                        .lodging("Peterson SFB")
                        .memberActualAlertTime(OffsetDateTime.parse("2024-02-26T09:15:00.123Z"))
                        .memberAdjReturnTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .memberAdjReturnTimeApprover("Smith")
                        .memberId("12345678abc")
                        .memberInitStartTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .memberLastAlertTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .memberLegalAlertTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .memberPickupTime(OffsetDateTime.parse("2024-02-26T10:15:00.123Z"))
                        .memberPostRestOffset("+05:00")
                        .memberPostRestTime(OffsetDateTime.parse("2024-01-02T16:00:00.123Z"))
                        .memberPreRestTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .memberRemarks("Crew member remark")
                        .memberReturnTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .memberSchedAlertTime(OffsetDateTime.parse("2024-02-26T09:15:00.123Z"))
                        .memberSource("ACTIVE")
                        .memberStageName("Falcon Squadron")
                        .memberTransportReq(true)
                        .memberType("AIRCREW")
                        .middleInitial("G")
                        .notified(true)
                        .phoneNumber("+14155552671")
                        .physAvCode("D")
                        .physAvStatus("OVERDUE")
                        .physDue(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .rank("Capt")
                        .remarkCode("ABE33")
                        .rmsMds("C017A")
                        .showTime(OffsetDateTime.parse("2024-02-26T10:15:00.123Z"))
                        .squadron("21AS")
                        .trainingDate(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                        .username("fgsmith")
                        .wing("60AMW")
                        .build()
                )
                .crewName("falcon")
                .crewRms("ARMS")
                .crewRole("DEADHEAD")
                .crewSource("ACTIVE")
                .crewSquadron("21AS")
                .crewType("AIRLAND")
                .crewUnit("00016ALSQ")
                .crewWing("60AMW")
                .currentIcao("KCOS")
                .fdpEligType("A")
                .fdpType("A")
                .femaleEnlistedQty(2)
                .femaleOfficerQty(1)
                .fltAuthNum("KT001")
                .idSiteCurrent("b677cf3b-d44d-450e-8b8f-d23f997f8778")
                .idSortie("4ef3d1e8-ab08-ab70-498f-edc479734e5c")
                .initStartTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                .lastAlertTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                .legalAlertTime(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .legalBravoTime(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .linkedTask(false)
                .maleEnlistedQty(3)
                .maleOfficerQty(1)
                .missionAlias("PACIFIC DEPLOY / CHAP 3 MOVEMENT")
                .missionId("AJM123456123")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .personnelType("AIRCREW")
                .pickupTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                .postRestApplied(false)
                .postRestEnd(OffsetDateTime.parse("2024-01-02T16:00:00.123Z"))
                .postRestOffset("+05:00")
                .preRestApplied(false)
                .preRestStart(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                .addReqQualCode("AL")
                .addReqQualCode("CS")
                .returnTime(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .sourceDl("AXE")
                .stage1Qual("1AXXX")
                .stage2Qual("2AXXX")
                .stage3Qual("3AXXX")
                .stageName("Falcon Squadron")
                .stageTime(OffsetDateTime.parse("2024-01-01T16:00:00.123Z"))
                .status("APPROVED")
                .transportReq(true)
                .tripKit("TK-1234")
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .build()

        val roundtrippedCrewFull =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(crewFull),
                jacksonTypeRef<CrewFull>(),
            )

        assertThat(roundtrippedCrewFull).isEqualTo(crewFull)
    }
}
