// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import com.unifieddatalibrary.api.models.EopFull
import java.time.OffsetDateTime
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EopFullTest {

    @Test
    fun create() {
      val eopFull = EopFull.builder()
          .classificationMarking("U")
          .dataMode(EopFull.DataMode.TEST)
          .eopDate(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
          .source("Bluestaq")
          .id("EOP-ID")
          .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
          .createdBy("some.user")
          .dEpsilon(-0.917)
          .dEpsilonB(-1.7)
          .dEpsilonUnc(0.165)
          .dPsi(-10.437)
          .dPsib(-9.9)
          .dPsiUnc(0.507)
          .dX(-0.086)
          .dXb(0.129)
          .dXUnc(0.202)
          .dY(0.13)
          .dYb(-0.653)
          .dYUnc(0.165)
          .lod(1.8335)
          .lodUnc(0.0201)
          .nutationState(EopFull.NutationState.I)
          .origin("THIRD_PARTY_DATASOURCE")
          .origNetwork("ORIG")
          .polarMotionState(EopFull.PolarMotionState.I)
          .polarMotionX(0.182987)
          .polarMotionXb(0.1824)
          .polarMotionXUnc(0.000672)
          .polarMotionY(0.168775)
          .polarMotionYb(0.1679)
          .polarMotionYUnc(0.000345)
          .precessionNutationStd("IAU1980")
          .rawFileUri("Example URI")
          .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
          .updatedBy("some.user")
          .ut1Utc(-0.1251659)
          .ut1Utcb(-0.1253)
          .ut1UtcState(EopFull.Ut1UtcState.I)
          .ut1UtcUnc(0.0000207)
          .build()

      assertThat(eopFull.classificationMarking()).isEqualTo("U")
      assertThat(eopFull.dataMode()).isEqualTo(EopFull.DataMode.TEST)
      assertThat(eopFull.eopDate()).isEqualTo(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
      assertThat(eopFull.source()).isEqualTo("Bluestaq")
      assertThat(eopFull.id()).contains("EOP-ID")
      assertThat(eopFull.createdAt()).contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
      assertThat(eopFull.createdBy()).contains("some.user")
      assertThat(eopFull.dEpsilon()).contains(-0.917)
      assertThat(eopFull.dEpsilonB()).contains(-1.7)
      assertThat(eopFull.dEpsilonUnc()).contains(0.165)
      assertThat(eopFull.dPsi()).contains(-10.437)
      assertThat(eopFull.dPsib()).contains(-9.9)
      assertThat(eopFull.dPsiUnc()).contains(0.507)
      assertThat(eopFull.dX()).contains(-0.086)
      assertThat(eopFull.dXb()).contains(0.129)
      assertThat(eopFull.dXUnc()).contains(0.202)
      assertThat(eopFull.dY()).contains(0.13)
      assertThat(eopFull.dYb()).contains(-0.653)
      assertThat(eopFull.dYUnc()).contains(0.165)
      assertThat(eopFull.lod()).contains(1.8335)
      assertThat(eopFull.lodUnc()).contains(0.0201)
      assertThat(eopFull.nutationState()).contains(EopFull.NutationState.I)
      assertThat(eopFull.origin()).contains("THIRD_PARTY_DATASOURCE")
      assertThat(eopFull.origNetwork()).contains("ORIG")
      assertThat(eopFull.polarMotionState()).contains(EopFull.PolarMotionState.I)
      assertThat(eopFull.polarMotionX()).contains(0.182987)
      assertThat(eopFull.polarMotionXb()).contains(0.1824)
      assertThat(eopFull.polarMotionXUnc()).contains(0.000672)
      assertThat(eopFull.polarMotionY()).contains(0.168775)
      assertThat(eopFull.polarMotionYb()).contains(0.1679)
      assertThat(eopFull.polarMotionYUnc()).contains(0.000345)
      assertThat(eopFull.precessionNutationStd()).contains("IAU1980")
      assertThat(eopFull.rawFileUri()).contains("Example URI")
      assertThat(eopFull.updatedAt()).contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
      assertThat(eopFull.updatedBy()).contains("some.user")
      assertThat(eopFull.ut1Utc()).contains(-0.1251659)
      assertThat(eopFull.ut1Utcb()).contains(-0.1253)
      assertThat(eopFull.ut1UtcState()).contains(EopFull.Ut1UtcState.I)
      assertThat(eopFull.ut1UtcUnc()).contains(0.0000207)
    }

    @Test
    fun roundtrip() {
      val jsonMapper = jsonMapper()
      val eopFull = EopFull.builder()
          .classificationMarking("U")
          .dataMode(EopFull.DataMode.TEST)
          .eopDate(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
          .source("Bluestaq")
          .id("EOP-ID")
          .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
          .createdBy("some.user")
          .dEpsilon(-0.917)
          .dEpsilonB(-1.7)
          .dEpsilonUnc(0.165)
          .dPsi(-10.437)
          .dPsib(-9.9)
          .dPsiUnc(0.507)
          .dX(-0.086)
          .dXb(0.129)
          .dXUnc(0.202)
          .dY(0.13)
          .dYb(-0.653)
          .dYUnc(0.165)
          .lod(1.8335)
          .lodUnc(0.0201)
          .nutationState(EopFull.NutationState.I)
          .origin("THIRD_PARTY_DATASOURCE")
          .origNetwork("ORIG")
          .polarMotionState(EopFull.PolarMotionState.I)
          .polarMotionX(0.182987)
          .polarMotionXb(0.1824)
          .polarMotionXUnc(0.000672)
          .polarMotionY(0.168775)
          .polarMotionYb(0.1679)
          .polarMotionYUnc(0.000345)
          .precessionNutationStd("IAU1980")
          .rawFileUri("Example URI")
          .updatedAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
          .updatedBy("some.user")
          .ut1Utc(-0.1251659)
          .ut1Utcb(-0.1253)
          .ut1UtcState(EopFull.Ut1UtcState.I)
          .ut1UtcUnc(0.0000207)
          .build()

      val roundtrippedEopFull = jsonMapper.readValue(jsonMapper.writeValueAsString(eopFull), jacksonTypeRef<EopFull>())

      assertThat(roundtrippedEopFull).isEqualTo(eopFull)
    }
}
