// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class EvacFullTest {

    @Test
    fun create() {
        val evacFull =
            EvacFull.builder()
                .classificationMarking("U")
                .dataMode(EvacFull.DataMode.TEST)
                .pickupLat(75.1234)
                .pickupLon(175.1234)
                .reqTime(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                .source("Bluestaq")
                .type(EvacFull.Type.REQUEST)
                .id("MEDEVACEVENT-ID")
                .addCasualtyInfo(
                    EvacFull.CasualtyInfo.builder()
                        .age(35)
                        .addAllergy(
                            EvacFull.CasualtyInfo.Allergy.builder()
                                .comments("Comments on the patient's allergies.")
                                .type("PENICILLIN")
                                .build()
                        )
                        .bloodType("O NEG")
                        .bodyPart("FACE")
                        .burialLocation(listOf(-33.123, 150.33, 0.24))
                        .callSign("SHARK")
                        .careProviderUrn("CARE_PROVIDER-1")
                        .casualtyKey("casualty-007")
                        .casualtyType("DENTAL")
                        .collectionPoint(listOf(12.44, 122.55, 0.98))
                        .comments("Comments relating to this casualty info.")
                        .addCondition(
                            EvacFull.CasualtyInfo.Condition.builder()
                                .bodyPart("ANKLE LEFT FRONT")
                                .comments("Comments on the patient's condition.")
                                .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                                .type("ACTIVITY LOW")
                                .build()
                        )
                        .contamType("NONE")
                        .disposition("EVACUATE WOUNDED")
                        .dispositionType("EVACUATE")
                        .addEtiology(
                            EvacFull.CasualtyInfo.Etiology.builder()
                                .bodyPart("ARM LEFT FRONT")
                                .comments("Comments on the etiology info.")
                                .time(OffsetDateTime.parse("2021-10-16T16:00:00.123Z"))
                                .type("BURN")
                                .build()
                        )
                        .evacType("GROUND")
                        .gender("MALE")
                        .addHealthState(
                            EvacFull.CasualtyInfo.HealthState.builder()
                                .healthStateCode("BLUE")
                                .medConfFactor(1)
                                .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                                .type("COGNITIVE")
                                .build()
                        )
                        .addInjury(
                            EvacFull.CasualtyInfo.Injury.builder()
                                .bodyPart("ARM LEFT FRONT")
                                .comments("Comments on the patient's injury.")
                                .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                                .type("ABRASION")
                                .build()
                        )
                        .last4Ssn("1234")
                        .addMedication(
                            EvacFull.CasualtyInfo.Medication.builder()
                                .adminRoute("ORAL")
                                .bodyPart("ARM LEFT BACK")
                                .comments("Comments on the patient's medication information.")
                                .dose("800mg")
                                .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                                .type("TYLENOL")
                                .build()
                        )
                        .name("John Smith")
                        .nationality("US")
                        .occSpeciality("Healthcare")
                        .patientIdentity("FRIEND CIVILIAN")
                        .patientStatus("US CIVILIAN")
                        .payGrade("CIVILIAN")
                        .priority("ROUTINE")
                        .reportGen("DEVICE")
                        .reportTime(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                        .service("CIV")
                        .addSpecMedEquip("OXYGEN")
                        .addSpecMedEquip("HOIST")
                        .addTreatment(
                            EvacFull.CasualtyInfo.Treatment.builder()
                                .bodyPart("CHEST")
                                .comments("Comments on the treatment info.")
                                .time(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                                .type("BREATHING CHEST TUBE")
                                .build()
                        )
                        .addVitalSignData(
                            EvacFull.CasualtyInfo.VitalSignData.builder()
                                .medConfFactor(1)
                                .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                                .vitalSign("HEART RATE")
                                .vitalSign1(120.0)
                                .vitalSign2(80.0)
                                .build()
                        )
                        .build()
                )
                .ce(10.1234)
                .cntctFreq(3.11)
                .comments("Comments concerning mission")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .addEnemyData(
                    EvacFull.EnemyData.builder()
                        .dirToEnemy("NORTH")
                        .friendliesRemarks("Comments from friendlies.")
                        .hlzRemarks("Remarks about hot landing zone.")
                        .hostileFireType("SMALL ARMS")
                        .build()
                )
                .idWeatherReport("WeatherReport-ID")
                .le(5.1234)
                .medevacId("MedEvac-ID")
                .medicReq(true)
                .missionType("GROUND")
                .numAmbulatory(5)
                .numCasualties(5)
                .numKia(0)
                .numLitter(0)
                .numWia(3)
                .obstaclesRemarks("N/A")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .pickupAlt(30.1234)
                .pickupTime(OffsetDateTime.parse("2021-10-20T16:00:00.123Z"))
                .addRelatedDoc(
                    RelatedDocumentFull.builder()
                        .addDataSourceRef(
                            SofDataSourceRefFull.builder()
                                .dataSourceId("dataSourceId")
                                .endPosition("endPosition")
                                .paragraphNumber("paragraphNumber")
                                .sentenceNumber("sentenceNumber")
                                .startPosition("startPosition")
                                .build()
                        )
                        .documentId("documentId")
                        .build()
                )
                .reqCallSign("Bravo")
                .reqNum("MED.1.223908")
                .terrain("ROCKY")
                .terrainRemarks("N/A")
                .zoneContrCallSign("Tango")
                .zoneHot(false)
                .zoneMarking("ILLUMINATION")
                .zoneMarkingColor("RED")
                .zoneName("example-zone")
                .zoneSecurity("NO ENEMY")
                .build()

        assertThat(evacFull.classificationMarking()).isEqualTo("U")
        assertThat(evacFull.dataMode()).isEqualTo(EvacFull.DataMode.TEST)
        assertThat(evacFull.pickupLat()).isEqualTo(75.1234)
        assertThat(evacFull.pickupLon()).isEqualTo(175.1234)
        assertThat(evacFull.reqTime()).isEqualTo(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
        assertThat(evacFull.source()).isEqualTo("Bluestaq")
        assertThat(evacFull.type()).isEqualTo(EvacFull.Type.REQUEST)
        assertThat(evacFull.id()).contains("MEDEVACEVENT-ID")
        assertThat(evacFull.casualtyInfo().getOrNull())
            .containsExactly(
                EvacFull.CasualtyInfo.builder()
                    .age(35)
                    .addAllergy(
                        EvacFull.CasualtyInfo.Allergy.builder()
                            .comments("Comments on the patient's allergies.")
                            .type("PENICILLIN")
                            .build()
                    )
                    .bloodType("O NEG")
                    .bodyPart("FACE")
                    .burialLocation(listOf(-33.123, 150.33, 0.24))
                    .callSign("SHARK")
                    .careProviderUrn("CARE_PROVIDER-1")
                    .casualtyKey("casualty-007")
                    .casualtyType("DENTAL")
                    .collectionPoint(listOf(12.44, 122.55, 0.98))
                    .comments("Comments relating to this casualty info.")
                    .addCondition(
                        EvacFull.CasualtyInfo.Condition.builder()
                            .bodyPart("ANKLE LEFT FRONT")
                            .comments("Comments on the patient's condition.")
                            .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                            .type("ACTIVITY LOW")
                            .build()
                    )
                    .contamType("NONE")
                    .disposition("EVACUATE WOUNDED")
                    .dispositionType("EVACUATE")
                    .addEtiology(
                        EvacFull.CasualtyInfo.Etiology.builder()
                            .bodyPart("ARM LEFT FRONT")
                            .comments("Comments on the etiology info.")
                            .time(OffsetDateTime.parse("2021-10-16T16:00:00.123Z"))
                            .type("BURN")
                            .build()
                    )
                    .evacType("GROUND")
                    .gender("MALE")
                    .addHealthState(
                        EvacFull.CasualtyInfo.HealthState.builder()
                            .healthStateCode("BLUE")
                            .medConfFactor(1)
                            .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                            .type("COGNITIVE")
                            .build()
                    )
                    .addInjury(
                        EvacFull.CasualtyInfo.Injury.builder()
                            .bodyPart("ARM LEFT FRONT")
                            .comments("Comments on the patient's injury.")
                            .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                            .type("ABRASION")
                            .build()
                    )
                    .last4Ssn("1234")
                    .addMedication(
                        EvacFull.CasualtyInfo.Medication.builder()
                            .adminRoute("ORAL")
                            .bodyPart("ARM LEFT BACK")
                            .comments("Comments on the patient's medication information.")
                            .dose("800mg")
                            .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                            .type("TYLENOL")
                            .build()
                    )
                    .name("John Smith")
                    .nationality("US")
                    .occSpeciality("Healthcare")
                    .patientIdentity("FRIEND CIVILIAN")
                    .patientStatus("US CIVILIAN")
                    .payGrade("CIVILIAN")
                    .priority("ROUTINE")
                    .reportGen("DEVICE")
                    .reportTime(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                    .service("CIV")
                    .addSpecMedEquip("OXYGEN")
                    .addSpecMedEquip("HOIST")
                    .addTreatment(
                        EvacFull.CasualtyInfo.Treatment.builder()
                            .bodyPart("CHEST")
                            .comments("Comments on the treatment info.")
                            .time(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                            .type("BREATHING CHEST TUBE")
                            .build()
                    )
                    .addVitalSignData(
                        EvacFull.CasualtyInfo.VitalSignData.builder()
                            .medConfFactor(1)
                            .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                            .vitalSign("HEART RATE")
                            .vitalSign1(120.0)
                            .vitalSign2(80.0)
                            .build()
                    )
                    .build()
            )
        assertThat(evacFull.ce()).contains(10.1234)
        assertThat(evacFull.cntctFreq()).contains(3.11)
        assertThat(evacFull.comments()).contains("Comments concerning mission")
        assertThat(evacFull.createdAt()).contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(evacFull.createdBy()).contains("some.user")
        assertThat(evacFull.enemyData().getOrNull())
            .containsExactly(
                EvacFull.EnemyData.builder()
                    .dirToEnemy("NORTH")
                    .friendliesRemarks("Comments from friendlies.")
                    .hlzRemarks("Remarks about hot landing zone.")
                    .hostileFireType("SMALL ARMS")
                    .build()
            )
        assertThat(evacFull.idWeatherReport()).contains("WeatherReport-ID")
        assertThat(evacFull.le()).contains(5.1234)
        assertThat(evacFull.medevacId()).contains("MedEvac-ID")
        assertThat(evacFull.medicReq()).contains(true)
        assertThat(evacFull.missionType()).contains("GROUND")
        assertThat(evacFull.numAmbulatory()).contains(5)
        assertThat(evacFull.numCasualties()).contains(5)
        assertThat(evacFull.numKia()).contains(0)
        assertThat(evacFull.numLitter()).contains(0)
        assertThat(evacFull.numWia()).contains(3)
        assertThat(evacFull.obstaclesRemarks()).contains("N/A")
        assertThat(evacFull.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(evacFull.origNetwork()).contains("OPS1")
        assertThat(evacFull.pickupAlt()).contains(30.1234)
        assertThat(evacFull.pickupTime()).contains(OffsetDateTime.parse("2021-10-20T16:00:00.123Z"))
        assertThat(evacFull.relatedDocs().getOrNull())
            .containsExactly(
                RelatedDocumentFull.builder()
                    .addDataSourceRef(
                        SofDataSourceRefFull.builder()
                            .dataSourceId("dataSourceId")
                            .endPosition("endPosition")
                            .paragraphNumber("paragraphNumber")
                            .sentenceNumber("sentenceNumber")
                            .startPosition("startPosition")
                            .build()
                    )
                    .documentId("documentId")
                    .build()
            )
        assertThat(evacFull.reqCallSign()).contains("Bravo")
        assertThat(evacFull.reqNum()).contains("MED.1.223908")
        assertThat(evacFull.terrain()).contains("ROCKY")
        assertThat(evacFull.terrainRemarks()).contains("N/A")
        assertThat(evacFull.zoneContrCallSign()).contains("Tango")
        assertThat(evacFull.zoneHot()).contains(false)
        assertThat(evacFull.zoneMarking()).contains("ILLUMINATION")
        assertThat(evacFull.zoneMarkingColor()).contains("RED")
        assertThat(evacFull.zoneName()).contains("example-zone")
        assertThat(evacFull.zoneSecurity()).contains("NO ENEMY")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val evacFull =
            EvacFull.builder()
                .classificationMarking("U")
                .dataMode(EvacFull.DataMode.TEST)
                .pickupLat(75.1234)
                .pickupLon(175.1234)
                .reqTime(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                .source("Bluestaq")
                .type(EvacFull.Type.REQUEST)
                .id("MEDEVACEVENT-ID")
                .addCasualtyInfo(
                    EvacFull.CasualtyInfo.builder()
                        .age(35)
                        .addAllergy(
                            EvacFull.CasualtyInfo.Allergy.builder()
                                .comments("Comments on the patient's allergies.")
                                .type("PENICILLIN")
                                .build()
                        )
                        .bloodType("O NEG")
                        .bodyPart("FACE")
                        .burialLocation(listOf(-33.123, 150.33, 0.24))
                        .callSign("SHARK")
                        .careProviderUrn("CARE_PROVIDER-1")
                        .casualtyKey("casualty-007")
                        .casualtyType("DENTAL")
                        .collectionPoint(listOf(12.44, 122.55, 0.98))
                        .comments("Comments relating to this casualty info.")
                        .addCondition(
                            EvacFull.CasualtyInfo.Condition.builder()
                                .bodyPart("ANKLE LEFT FRONT")
                                .comments("Comments on the patient's condition.")
                                .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                                .type("ACTIVITY LOW")
                                .build()
                        )
                        .contamType("NONE")
                        .disposition("EVACUATE WOUNDED")
                        .dispositionType("EVACUATE")
                        .addEtiology(
                            EvacFull.CasualtyInfo.Etiology.builder()
                                .bodyPart("ARM LEFT FRONT")
                                .comments("Comments on the etiology info.")
                                .time(OffsetDateTime.parse("2021-10-16T16:00:00.123Z"))
                                .type("BURN")
                                .build()
                        )
                        .evacType("GROUND")
                        .gender("MALE")
                        .addHealthState(
                            EvacFull.CasualtyInfo.HealthState.builder()
                                .healthStateCode("BLUE")
                                .medConfFactor(1)
                                .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                                .type("COGNITIVE")
                                .build()
                        )
                        .addInjury(
                            EvacFull.CasualtyInfo.Injury.builder()
                                .bodyPart("ARM LEFT FRONT")
                                .comments("Comments on the patient's injury.")
                                .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                                .type("ABRASION")
                                .build()
                        )
                        .last4Ssn("1234")
                        .addMedication(
                            EvacFull.CasualtyInfo.Medication.builder()
                                .adminRoute("ORAL")
                                .bodyPart("ARM LEFT BACK")
                                .comments("Comments on the patient's medication information.")
                                .dose("800mg")
                                .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                                .type("TYLENOL")
                                .build()
                        )
                        .name("John Smith")
                        .nationality("US")
                        .occSpeciality("Healthcare")
                        .patientIdentity("FRIEND CIVILIAN")
                        .patientStatus("US CIVILIAN")
                        .payGrade("CIVILIAN")
                        .priority("ROUTINE")
                        .reportGen("DEVICE")
                        .reportTime(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                        .service("CIV")
                        .addSpecMedEquip("OXYGEN")
                        .addSpecMedEquip("HOIST")
                        .addTreatment(
                            EvacFull.CasualtyInfo.Treatment.builder()
                                .bodyPart("CHEST")
                                .comments("Comments on the treatment info.")
                                .time(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                                .type("BREATHING CHEST TUBE")
                                .build()
                        )
                        .addVitalSignData(
                            EvacFull.CasualtyInfo.VitalSignData.builder()
                                .medConfFactor(1)
                                .time(OffsetDateTime.parse("2021-10-15T16:00:00.123Z"))
                                .vitalSign("HEART RATE")
                                .vitalSign1(120.0)
                                .vitalSign2(80.0)
                                .build()
                        )
                        .build()
                )
                .ce(10.1234)
                .cntctFreq(3.11)
                .comments("Comments concerning mission")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .addEnemyData(
                    EvacFull.EnemyData.builder()
                        .dirToEnemy("NORTH")
                        .friendliesRemarks("Comments from friendlies.")
                        .hlzRemarks("Remarks about hot landing zone.")
                        .hostileFireType("SMALL ARMS")
                        .build()
                )
                .idWeatherReport("WeatherReport-ID")
                .le(5.1234)
                .medevacId("MedEvac-ID")
                .medicReq(true)
                .missionType("GROUND")
                .numAmbulatory(5)
                .numCasualties(5)
                .numKia(0)
                .numLitter(0)
                .numWia(3)
                .obstaclesRemarks("N/A")
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .pickupAlt(30.1234)
                .pickupTime(OffsetDateTime.parse("2021-10-20T16:00:00.123Z"))
                .addRelatedDoc(
                    RelatedDocumentFull.builder()
                        .addDataSourceRef(
                            SofDataSourceRefFull.builder()
                                .dataSourceId("dataSourceId")
                                .endPosition("endPosition")
                                .paragraphNumber("paragraphNumber")
                                .sentenceNumber("sentenceNumber")
                                .startPosition("startPosition")
                                .build()
                        )
                        .documentId("documentId")
                        .build()
                )
                .reqCallSign("Bravo")
                .reqNum("MED.1.223908")
                .terrain("ROCKY")
                .terrainRemarks("N/A")
                .zoneContrCallSign("Tango")
                .zoneHot(false)
                .zoneMarking("ILLUMINATION")
                .zoneMarkingColor("RED")
                .zoneName("example-zone")
                .zoneSecurity("NO ENEMY")
                .build()

        val roundtrippedEvacFull =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(evacFull),
                jacksonTypeRef<EvacFull>(),
            )

        assertThat(roundtrippedEvacFull).isEqualTo(evacFull)
    }
}
