// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.airfieldslotconsumptions

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AirfieldslotconsumptionAbridgedTest {

    @Test
    fun create() {
        val airfieldslotconsumptionAbridged =
            AirfieldslotconsumptionAbridged.builder()
                .classificationMarking("U")
                .dataMode(AirfieldslotconsumptionAbridged.DataMode.TEST)
                .idAirfieldSlot("3136498f-2969-3535-1432-e984b2e2e686")
                .numAircraft(1)
                .source("Bluestaq")
                .startTime(OffsetDateTime.parse("2023-01-01T01:01:01.123Z"))
                .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                .altArrSortieId("ALT-SORTIE-ID")
                .altDepSortieId("ALT-SORTIE-ID")
                .appComment("The request was denied due to inoperable fuel pumps.")
                .appInitials("CB")
                .appOrg("KCHS/BOPS")
                .callSigns(listOf("RCH123", "ABC123", "LLS442"))
                .consumer("APRON1-230401001")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .endTime(OffsetDateTime.parse("2023-01-01T01:01:01.123Z"))
                .idArrSortie("be831d39-1822-da9f-7ace-6cc5643397dc")
                .idDepSortie("1e6edeec-72e9-aaec-d33c-51147cb5ffdd")
                .missionId("AJM123456123")
                .occAircraftMds("C017A")
                .occStartTime(OffsetDateTime.parse("2023-01-01T01:01:03.123Z"))
                .occTailNumber("N702JG")
                .occupied(true)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("ORIG")
                .reqComment("Sorry for the late notice.")
                .reqInitials("CB")
                .reqOrg("TACC")
                .resAircraftMds("C017A")
                .resMissionId("AJM123456123")
                .resReason("Maintenance needed")
                .resTailNumber("N702JG")
                .resType("M")
                .sourceDl("AXE")
                .status(AirfieldslotconsumptionAbridged.Status.APPROVED)
                .targetTime(OffsetDateTime.parse("2023-01-01T01:01:01.123Z"))
                .build()

        assertThat(airfieldslotconsumptionAbridged.classificationMarking()).isEqualTo("U")
        assertThat(airfieldslotconsumptionAbridged.dataMode())
            .isEqualTo(AirfieldslotconsumptionAbridged.DataMode.TEST)
        assertThat(airfieldslotconsumptionAbridged.idAirfieldSlot())
            .isEqualTo("3136498f-2969-3535-1432-e984b2e2e686")
        assertThat(airfieldslotconsumptionAbridged.numAircraft()).isEqualTo(1)
        assertThat(airfieldslotconsumptionAbridged.source()).isEqualTo("Bluestaq")
        assertThat(airfieldslotconsumptionAbridged.startTime())
            .isEqualTo(OffsetDateTime.parse("2023-01-01T01:01:01.123Z"))
        assertThat(airfieldslotconsumptionAbridged.id())
            .contains("be831d39-1822-da9f-7ace-6cc5643397dc")
        assertThat(airfieldslotconsumptionAbridged.altArrSortieId()).contains("ALT-SORTIE-ID")
        assertThat(airfieldslotconsumptionAbridged.altDepSortieId()).contains("ALT-SORTIE-ID")
        assertThat(airfieldslotconsumptionAbridged.appComment())
            .contains("The request was denied due to inoperable fuel pumps.")
        assertThat(airfieldslotconsumptionAbridged.appInitials()).contains("CB")
        assertThat(airfieldslotconsumptionAbridged.appOrg()).contains("KCHS/BOPS")
        assertThat(airfieldslotconsumptionAbridged.callSigns().getOrNull())
            .containsExactly("RCH123", "ABC123", "LLS442")
        assertThat(airfieldslotconsumptionAbridged.consumer()).contains("APRON1-230401001")
        assertThat(airfieldslotconsumptionAbridged.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(airfieldslotconsumptionAbridged.createdBy()).contains("some.user")
        assertThat(airfieldslotconsumptionAbridged.endTime())
            .contains(OffsetDateTime.parse("2023-01-01T01:01:01.123Z"))
        assertThat(airfieldslotconsumptionAbridged.idArrSortie())
            .contains("be831d39-1822-da9f-7ace-6cc5643397dc")
        assertThat(airfieldslotconsumptionAbridged.idDepSortie())
            .contains("1e6edeec-72e9-aaec-d33c-51147cb5ffdd")
        assertThat(airfieldslotconsumptionAbridged.missionId()).contains("AJM123456123")
        assertThat(airfieldslotconsumptionAbridged.occAircraftMds()).contains("C017A")
        assertThat(airfieldslotconsumptionAbridged.occStartTime())
            .contains(OffsetDateTime.parse("2023-01-01T01:01:03.123Z"))
        assertThat(airfieldslotconsumptionAbridged.occTailNumber()).contains("N702JG")
        assertThat(airfieldslotconsumptionAbridged.occupied()).contains(true)
        assertThat(airfieldslotconsumptionAbridged.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(airfieldslotconsumptionAbridged.origNetwork()).contains("ORIG")
        assertThat(airfieldslotconsumptionAbridged.reqComment())
            .contains("Sorry for the late notice.")
        assertThat(airfieldslotconsumptionAbridged.reqInitials()).contains("CB")
        assertThat(airfieldslotconsumptionAbridged.reqOrg()).contains("TACC")
        assertThat(airfieldslotconsumptionAbridged.resAircraftMds()).contains("C017A")
        assertThat(airfieldslotconsumptionAbridged.resMissionId()).contains("AJM123456123")
        assertThat(airfieldslotconsumptionAbridged.resReason()).contains("Maintenance needed")
        assertThat(airfieldslotconsumptionAbridged.resTailNumber()).contains("N702JG")
        assertThat(airfieldslotconsumptionAbridged.resType()).contains("M")
        assertThat(airfieldslotconsumptionAbridged.sourceDl()).contains("AXE")
        assertThat(airfieldslotconsumptionAbridged.status())
            .contains(AirfieldslotconsumptionAbridged.Status.APPROVED)
        assertThat(airfieldslotconsumptionAbridged.targetTime())
            .contains(OffsetDateTime.parse("2023-01-01T01:01:01.123Z"))
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val airfieldslotconsumptionAbridged =
            AirfieldslotconsumptionAbridged.builder()
                .classificationMarking("U")
                .dataMode(AirfieldslotconsumptionAbridged.DataMode.TEST)
                .idAirfieldSlot("3136498f-2969-3535-1432-e984b2e2e686")
                .numAircraft(1)
                .source("Bluestaq")
                .startTime(OffsetDateTime.parse("2023-01-01T01:01:01.123Z"))
                .id("be831d39-1822-da9f-7ace-6cc5643397dc")
                .altArrSortieId("ALT-SORTIE-ID")
                .altDepSortieId("ALT-SORTIE-ID")
                .appComment("The request was denied due to inoperable fuel pumps.")
                .appInitials("CB")
                .appOrg("KCHS/BOPS")
                .callSigns(listOf("RCH123", "ABC123", "LLS442"))
                .consumer("APRON1-230401001")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .endTime(OffsetDateTime.parse("2023-01-01T01:01:01.123Z"))
                .idArrSortie("be831d39-1822-da9f-7ace-6cc5643397dc")
                .idDepSortie("1e6edeec-72e9-aaec-d33c-51147cb5ffdd")
                .missionId("AJM123456123")
                .occAircraftMds("C017A")
                .occStartTime(OffsetDateTime.parse("2023-01-01T01:01:03.123Z"))
                .occTailNumber("N702JG")
                .occupied(true)
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("ORIG")
                .reqComment("Sorry for the late notice.")
                .reqInitials("CB")
                .reqOrg("TACC")
                .resAircraftMds("C017A")
                .resMissionId("AJM123456123")
                .resReason("Maintenance needed")
                .resTailNumber("N702JG")
                .resType("M")
                .sourceDl("AXE")
                .status(AirfieldslotconsumptionAbridged.Status.APPROVED)
                .targetTime(OffsetDateTime.parse("2023-01-01T01:01:01.123Z"))
                .build()

        val roundtrippedAirfieldslotconsumptionAbridged =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(airfieldslotconsumptionAbridged),
                jacksonTypeRef<AirfieldslotconsumptionAbridged>(),
            )

        assertThat(roundtrippedAirfieldslotconsumptionAbridged)
            .isEqualTo(airfieldslotconsumptionAbridged)
    }
}
