// File generated from our OpenAPI spec by Stainless.

package com.unifieddatalibrary.api.models.logisticssupport

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import com.unifieddatalibrary.api.core.jsonMapper
import java.time.OffsetDateTime
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class LogisticsSupportListResponseTest {

    @Test
    fun create() {
        val logisticsSupportListResponse =
            LogisticsSupportListResponse.builder()
                .classificationMarking("U")
                .dataMode(LogisticsSupportListResponse.DataMode.TEST)
                .rptCreatedTime(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
                .source("Bluestaq")
                .id("LOGISTICS-SUPPORT-DETAILS UUID")
                .aircraftMds("CO17A")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .currIcao("KCOS")
                .etic(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
                .etmc(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
                .extSystemId("GDSSBL012307131347070165")
                .logisticAction("WA")
                .addLogisticsDiscrepancyInfo(
                    LogisticsSupportListResponse.LogisticsDiscrepancyInfo.builder()
                        .closureTime(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                        .discrepancyInfo(
                            "PILOT WINDSHIELD PANEL ASSY CRACKED, AND ARCING REQ R2 IAW 56.11.10"
                        )
                        .jcn("231942400")
                        .jobStTime(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                        .build()
                )
                .logisticsRecordId("L62017")
                .addLogisticsRemark(
                    LogisticsRemarksAbridged.builder()
                        .lastChanged(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                        .remark("EXAMPLE REMARK")
                        .username("JSMITH")
                        .build()
                )
                .addLogisticsSupportItem(
                    LogisticsSupportListResponse.LogisticsSupportItem.builder()
                        .cannibalized(true)
                        .deployPlanNumber("T89003")
                        .description("HOIST ADAPTER KIT")
                        .itemLastChangedDate(OffsetDateTime.parse("2023-07-17T19:04:00.123Z"))
                        .jobControlNumber("231942400")
                        .addLogisticsPart(
                            LogisticsSupportListResponse.LogisticsSupportItem.LogisticsPart
                                .builder()
                                .figureNumber("3")
                                .indexNumber("4")
                                .locationVerifier("JANE DOE")
                                .addLogisticsStock(
                                    LogisticsSupportListResponse.LogisticsSupportItem.LogisticsPart
                                        .LogisticsStock
                                        .builder()
                                        .quantity(4)
                                        .sourceIcao("PHIK")
                                        .stockCheckTime(
                                            OffsetDateTime.parse("2023-07-13T13:47:00.123Z")
                                        )
                                        .stockPoc("SMITH, JOHN J")
                                        .build()
                                )
                                .measurementUnitCode("EA")
                                .nationalStockNumber("5310-00-045-3299")
                                .partNumber("MS35338-42")
                                .requestVerifier("JOHN SMITH")
                                .supplyDocumentNumber("J223FU31908300")
                                .technicalOrderText("1C-17A-4")
                                .workUnitCode("5611UU001")
                                .build()
                        )
                        .addLogisticsRemark(
                            LogisticsRemarksAbridged.builder()
                                .lastChanged(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                                .remark("EXAMPLE REMARK")
                                .username("JSMITH")
                                .build()
                        )
                        .addLogisticsSpecialty(
                            LogisticsSupportListResponse.LogisticsSupportItem.LogisticsSpecialty
                                .builder()
                                .firstName("JOHN")
                                .last4Ssn("9999")
                                .lastName("SMITH")
                                .rankCode("MAJ")
                                .roleTypeCode("TC")
                                .skillLevel(3)
                                .specialty("ELEN")
                                .build()
                        )
                        .quantity(1)
                        .readyTime(OffsetDateTime.parse("2023-07-17T19:04:00.123Z"))
                        .receivedTime(OffsetDateTime.parse("2023-07-17T19:04:00.123Z"))
                        .recoveryRequestTypeCode("E")
                        .redeployPlanNumber("T89003")
                        .redeployShipmentUnitId("X400LA31949108")
                        .requestNumber("89208")
                        .resupportFlag(true)
                        .shipmentUnitId("FB44273196X501XXX")
                        .siPoc("SMITH, JOHN J")
                        .sourceIcao("PHIK")
                        .build()
                )
                .addLogisticsTransportationPlan(
                    LogisticsSupportListResponse.LogisticsTransportationPlan.builder()
                        .actDepTime(OffsetDateTime.parse("2023-07-14T19:37:00.123Z"))
                        .aircraftStatus("NMCMU")
                        .approxArrTime(OffsetDateTime.parse("2023-07-14T20:37:00.123Z"))
                        .cancelledDate(OffsetDateTime.parse("2023-07-14T20:37:00.123Z"))
                        .closedDate(OffsetDateTime.parse("2023-07-14T20:37:00.123Z"))
                        .coordinator("SMITH, JOHN")
                        .coordinatorUnit("TACC")
                        .destinationIcao("YBCS")
                        .duration("086:20")
                        .estArrTime(OffsetDateTime.parse("2023-07-15T14:25:00.123Z"))
                        .estDepTime(OffsetDateTime.parse("2023-07-15T14:25:00.123Z"))
                        .lastChangedDate(OffsetDateTime.parse("2023-07-14T20:37:00.123Z"))
                        .logisticMasterRecordId("L62126")
                        .addLogisticsSegment(
                            LogisticsSupportListResponse.LogisticsTransportationPlan
                                .LogisticsSegment
                                .builder()
                                .arrivalIcao("YBCS")
                                .departureIcao("PHIK")
                                .extMissionId("2001101RF01202307062205")
                                .idMission("EXAMPLE-UUID")
                                .itin(200)
                                .missionNumber("TAM308901196")
                                .missionType("SAAM")
                                .modeCode("A")
                                .segActArrTime(OffsetDateTime.parse("2023-07-17T19:20:00.123Z"))
                                .segActDepTime(OffsetDateTime.parse("2023-07-17T19:20:00.123Z"))
                                .segAircraftMds("B7772E")
                                .segEstArrTime(OffsetDateTime.parse("2023-07-17T19:20:00.123Z"))
                                .segEstDepTime(OffsetDateTime.parse("2023-07-17T19:20:00.123Z"))
                                .segmentNumber(3)
                                .segTailNumber("N819AX")
                                .build()
                        )
                        .addLogisticsTransportationPlansRemark(
                            LogisticsRemarksAbridged.builder()
                                .lastChanged(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                                .remark("EXAMPLE REMARK")
                                .username("JSMITH")
                                .build()
                        )
                        .majcom("HQAMC")
                        .missionChange(false)
                        .numEnrouteStops(4)
                        .numTransLoads(3)
                        .originIcao("KATL")
                        .planDefinition("DEPLOY")
                        .plansNumber("T89002")
                        .serialNumber("9009209")
                        .statusCode("N")
                        .tpAircraftMds("C17A")
                        .tpTailNumber("99209")
                        .build()
                )
                .maintStatusCode("NMCMU")
                .mcTime(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
                .meTime(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .owner("EXAMPLE_OWNER")
                .reopenFlag(true)
                .rptClosedTime(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
                .suppIcao("KCOS")
                .tailNumber("99290")
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .build()

        assertThat(logisticsSupportListResponse.classificationMarking()).isEqualTo("U")
        assertThat(logisticsSupportListResponse.dataMode())
            .isEqualTo(LogisticsSupportListResponse.DataMode.TEST)
        assertThat(logisticsSupportListResponse.rptCreatedTime())
            .isEqualTo(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
        assertThat(logisticsSupportListResponse.source()).isEqualTo("Bluestaq")
        assertThat(logisticsSupportListResponse.id()).contains("LOGISTICS-SUPPORT-DETAILS UUID")
        assertThat(logisticsSupportListResponse.aircraftMds()).contains("CO17A")
        assertThat(logisticsSupportListResponse.createdAt())
            .contains(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
        assertThat(logisticsSupportListResponse.createdBy()).contains("some.user")
        assertThat(logisticsSupportListResponse.currIcao()).contains("KCOS")
        assertThat(logisticsSupportListResponse.etic())
            .contains(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
        assertThat(logisticsSupportListResponse.etmc())
            .contains(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
        assertThat(logisticsSupportListResponse.extSystemId()).contains("GDSSBL012307131347070165")
        assertThat(logisticsSupportListResponse.logisticAction()).contains("WA")
        assertThat(logisticsSupportListResponse.logisticsDiscrepancyInfos().getOrNull())
            .containsExactly(
                LogisticsSupportListResponse.LogisticsDiscrepancyInfo.builder()
                    .closureTime(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                    .discrepancyInfo(
                        "PILOT WINDSHIELD PANEL ASSY CRACKED, AND ARCING REQ R2 IAW 56.11.10"
                    )
                    .jcn("231942400")
                    .jobStTime(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                    .build()
            )
        assertThat(logisticsSupportListResponse.logisticsRecordId()).contains("L62017")
        assertThat(logisticsSupportListResponse.logisticsRemarks().getOrNull())
            .containsExactly(
                LogisticsRemarksAbridged.builder()
                    .lastChanged(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                    .remark("EXAMPLE REMARK")
                    .username("JSMITH")
                    .build()
            )
        assertThat(logisticsSupportListResponse.logisticsSupportItems().getOrNull())
            .containsExactly(
                LogisticsSupportListResponse.LogisticsSupportItem.builder()
                    .cannibalized(true)
                    .deployPlanNumber("T89003")
                    .description("HOIST ADAPTER KIT")
                    .itemLastChangedDate(OffsetDateTime.parse("2023-07-17T19:04:00.123Z"))
                    .jobControlNumber("231942400")
                    .addLogisticsPart(
                        LogisticsSupportListResponse.LogisticsSupportItem.LogisticsPart.builder()
                            .figureNumber("3")
                            .indexNumber("4")
                            .locationVerifier("JANE DOE")
                            .addLogisticsStock(
                                LogisticsSupportListResponse.LogisticsSupportItem.LogisticsPart
                                    .LogisticsStock
                                    .builder()
                                    .quantity(4)
                                    .sourceIcao("PHIK")
                                    .stockCheckTime(
                                        OffsetDateTime.parse("2023-07-13T13:47:00.123Z")
                                    )
                                    .stockPoc("SMITH, JOHN J")
                                    .build()
                            )
                            .measurementUnitCode("EA")
                            .nationalStockNumber("5310-00-045-3299")
                            .partNumber("MS35338-42")
                            .requestVerifier("JOHN SMITH")
                            .supplyDocumentNumber("J223FU31908300")
                            .technicalOrderText("1C-17A-4")
                            .workUnitCode("5611UU001")
                            .build()
                    )
                    .addLogisticsRemark(
                        LogisticsRemarksAbridged.builder()
                            .lastChanged(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                            .remark("EXAMPLE REMARK")
                            .username("JSMITH")
                            .build()
                    )
                    .addLogisticsSpecialty(
                        LogisticsSupportListResponse.LogisticsSupportItem.LogisticsSpecialty
                            .builder()
                            .firstName("JOHN")
                            .last4Ssn("9999")
                            .lastName("SMITH")
                            .rankCode("MAJ")
                            .roleTypeCode("TC")
                            .skillLevel(3)
                            .specialty("ELEN")
                            .build()
                    )
                    .quantity(1)
                    .readyTime(OffsetDateTime.parse("2023-07-17T19:04:00.123Z"))
                    .receivedTime(OffsetDateTime.parse("2023-07-17T19:04:00.123Z"))
                    .recoveryRequestTypeCode("E")
                    .redeployPlanNumber("T89003")
                    .redeployShipmentUnitId("X400LA31949108")
                    .requestNumber("89208")
                    .resupportFlag(true)
                    .shipmentUnitId("FB44273196X501XXX")
                    .siPoc("SMITH, JOHN J")
                    .sourceIcao("PHIK")
                    .build()
            )
        assertThat(logisticsSupportListResponse.logisticsTransportationPlans().getOrNull())
            .containsExactly(
                LogisticsSupportListResponse.LogisticsTransportationPlan.builder()
                    .actDepTime(OffsetDateTime.parse("2023-07-14T19:37:00.123Z"))
                    .aircraftStatus("NMCMU")
                    .approxArrTime(OffsetDateTime.parse("2023-07-14T20:37:00.123Z"))
                    .cancelledDate(OffsetDateTime.parse("2023-07-14T20:37:00.123Z"))
                    .closedDate(OffsetDateTime.parse("2023-07-14T20:37:00.123Z"))
                    .coordinator("SMITH, JOHN")
                    .coordinatorUnit("TACC")
                    .destinationIcao("YBCS")
                    .duration("086:20")
                    .estArrTime(OffsetDateTime.parse("2023-07-15T14:25:00.123Z"))
                    .estDepTime(OffsetDateTime.parse("2023-07-15T14:25:00.123Z"))
                    .lastChangedDate(OffsetDateTime.parse("2023-07-14T20:37:00.123Z"))
                    .logisticMasterRecordId("L62126")
                    .addLogisticsSegment(
                        LogisticsSupportListResponse.LogisticsTransportationPlan.LogisticsSegment
                            .builder()
                            .arrivalIcao("YBCS")
                            .departureIcao("PHIK")
                            .extMissionId("2001101RF01202307062205")
                            .idMission("EXAMPLE-UUID")
                            .itin(200)
                            .missionNumber("TAM308901196")
                            .missionType("SAAM")
                            .modeCode("A")
                            .segActArrTime(OffsetDateTime.parse("2023-07-17T19:20:00.123Z"))
                            .segActDepTime(OffsetDateTime.parse("2023-07-17T19:20:00.123Z"))
                            .segAircraftMds("B7772E")
                            .segEstArrTime(OffsetDateTime.parse("2023-07-17T19:20:00.123Z"))
                            .segEstDepTime(OffsetDateTime.parse("2023-07-17T19:20:00.123Z"))
                            .segmentNumber(3)
                            .segTailNumber("N819AX")
                            .build()
                    )
                    .addLogisticsTransportationPlansRemark(
                        LogisticsRemarksAbridged.builder()
                            .lastChanged(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                            .remark("EXAMPLE REMARK")
                            .username("JSMITH")
                            .build()
                    )
                    .majcom("HQAMC")
                    .missionChange(false)
                    .numEnrouteStops(4)
                    .numTransLoads(3)
                    .originIcao("KATL")
                    .planDefinition("DEPLOY")
                    .plansNumber("T89002")
                    .serialNumber("9009209")
                    .statusCode("N")
                    .tpAircraftMds("C17A")
                    .tpTailNumber("99209")
                    .build()
            )
        assertThat(logisticsSupportListResponse.maintStatusCode()).contains("NMCMU")
        assertThat(logisticsSupportListResponse.mcTime())
            .contains(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
        assertThat(logisticsSupportListResponse.meTime())
            .contains(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
        assertThat(logisticsSupportListResponse.origin()).contains("THIRD_PARTY_DATASOURCE")
        assertThat(logisticsSupportListResponse.origNetwork()).contains("OPS1")
        assertThat(logisticsSupportListResponse.owner()).contains("EXAMPLE_OWNER")
        assertThat(logisticsSupportListResponse.reopenFlag()).contains(true)
        assertThat(logisticsSupportListResponse.rptClosedTime())
            .contains(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
        assertThat(logisticsSupportListResponse.suppIcao()).contains("KCOS")
        assertThat(logisticsSupportListResponse.tailNumber()).contains("99290")
        assertThat(logisticsSupportListResponse.updatedAt())
            .contains(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
        assertThat(logisticsSupportListResponse.updatedBy()).contains("some.user")
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val logisticsSupportListResponse =
            LogisticsSupportListResponse.builder()
                .classificationMarking("U")
                .dataMode(LogisticsSupportListResponse.DataMode.TEST)
                .rptCreatedTime(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
                .source("Bluestaq")
                .id("LOGISTICS-SUPPORT-DETAILS UUID")
                .aircraftMds("CO17A")
                .createdAt(OffsetDateTime.parse("2018-01-01T16:00:00.123Z"))
                .createdBy("some.user")
                .currIcao("KCOS")
                .etic(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
                .etmc(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
                .extSystemId("GDSSBL012307131347070165")
                .logisticAction("WA")
                .addLogisticsDiscrepancyInfo(
                    LogisticsSupportListResponse.LogisticsDiscrepancyInfo.builder()
                        .closureTime(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                        .discrepancyInfo(
                            "PILOT WINDSHIELD PANEL ASSY CRACKED, AND ARCING REQ R2 IAW 56.11.10"
                        )
                        .jcn("231942400")
                        .jobStTime(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                        .build()
                )
                .logisticsRecordId("L62017")
                .addLogisticsRemark(
                    LogisticsRemarksAbridged.builder()
                        .lastChanged(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                        .remark("EXAMPLE REMARK")
                        .username("JSMITH")
                        .build()
                )
                .addLogisticsSupportItem(
                    LogisticsSupportListResponse.LogisticsSupportItem.builder()
                        .cannibalized(true)
                        .deployPlanNumber("T89003")
                        .description("HOIST ADAPTER KIT")
                        .itemLastChangedDate(OffsetDateTime.parse("2023-07-17T19:04:00.123Z"))
                        .jobControlNumber("231942400")
                        .addLogisticsPart(
                            LogisticsSupportListResponse.LogisticsSupportItem.LogisticsPart
                                .builder()
                                .figureNumber("3")
                                .indexNumber("4")
                                .locationVerifier("JANE DOE")
                                .addLogisticsStock(
                                    LogisticsSupportListResponse.LogisticsSupportItem.LogisticsPart
                                        .LogisticsStock
                                        .builder()
                                        .quantity(4)
                                        .sourceIcao("PHIK")
                                        .stockCheckTime(
                                            OffsetDateTime.parse("2023-07-13T13:47:00.123Z")
                                        )
                                        .stockPoc("SMITH, JOHN J")
                                        .build()
                                )
                                .measurementUnitCode("EA")
                                .nationalStockNumber("5310-00-045-3299")
                                .partNumber("MS35338-42")
                                .requestVerifier("JOHN SMITH")
                                .supplyDocumentNumber("J223FU31908300")
                                .technicalOrderText("1C-17A-4")
                                .workUnitCode("5611UU001")
                                .build()
                        )
                        .addLogisticsRemark(
                            LogisticsRemarksAbridged.builder()
                                .lastChanged(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                                .remark("EXAMPLE REMARK")
                                .username("JSMITH")
                                .build()
                        )
                        .addLogisticsSpecialty(
                            LogisticsSupportListResponse.LogisticsSupportItem.LogisticsSpecialty
                                .builder()
                                .firstName("JOHN")
                                .last4Ssn("9999")
                                .lastName("SMITH")
                                .rankCode("MAJ")
                                .roleTypeCode("TC")
                                .skillLevel(3)
                                .specialty("ELEN")
                                .build()
                        )
                        .quantity(1)
                        .readyTime(OffsetDateTime.parse("2023-07-17T19:04:00.123Z"))
                        .receivedTime(OffsetDateTime.parse("2023-07-17T19:04:00.123Z"))
                        .recoveryRequestTypeCode("E")
                        .redeployPlanNumber("T89003")
                        .redeployShipmentUnitId("X400LA31949108")
                        .requestNumber("89208")
                        .resupportFlag(true)
                        .shipmentUnitId("FB44273196X501XXX")
                        .siPoc("SMITH, JOHN J")
                        .sourceIcao("PHIK")
                        .build()
                )
                .addLogisticsTransportationPlan(
                    LogisticsSupportListResponse.LogisticsTransportationPlan.builder()
                        .actDepTime(OffsetDateTime.parse("2023-07-14T19:37:00.123Z"))
                        .aircraftStatus("NMCMU")
                        .approxArrTime(OffsetDateTime.parse("2023-07-14T20:37:00.123Z"))
                        .cancelledDate(OffsetDateTime.parse("2023-07-14T20:37:00.123Z"))
                        .closedDate(OffsetDateTime.parse("2023-07-14T20:37:00.123Z"))
                        .coordinator("SMITH, JOHN")
                        .coordinatorUnit("TACC")
                        .destinationIcao("YBCS")
                        .duration("086:20")
                        .estArrTime(OffsetDateTime.parse("2023-07-15T14:25:00.123Z"))
                        .estDepTime(OffsetDateTime.parse("2023-07-15T14:25:00.123Z"))
                        .lastChangedDate(OffsetDateTime.parse("2023-07-14T20:37:00.123Z"))
                        .logisticMasterRecordId("L62126")
                        .addLogisticsSegment(
                            LogisticsSupportListResponse.LogisticsTransportationPlan
                                .LogisticsSegment
                                .builder()
                                .arrivalIcao("YBCS")
                                .departureIcao("PHIK")
                                .extMissionId("2001101RF01202307062205")
                                .idMission("EXAMPLE-UUID")
                                .itin(200)
                                .missionNumber("TAM308901196")
                                .missionType("SAAM")
                                .modeCode("A")
                                .segActArrTime(OffsetDateTime.parse("2023-07-17T19:20:00.123Z"))
                                .segActDepTime(OffsetDateTime.parse("2023-07-17T19:20:00.123Z"))
                                .segAircraftMds("B7772E")
                                .segEstArrTime(OffsetDateTime.parse("2023-07-17T19:20:00.123Z"))
                                .segEstDepTime(OffsetDateTime.parse("2023-07-17T19:20:00.123Z"))
                                .segmentNumber(3)
                                .segTailNumber("N819AX")
                                .build()
                        )
                        .addLogisticsTransportationPlansRemark(
                            LogisticsRemarksAbridged.builder()
                                .lastChanged(OffsetDateTime.parse("2023-07-17T10:30:00.123Z"))
                                .remark("EXAMPLE REMARK")
                                .username("JSMITH")
                                .build()
                        )
                        .majcom("HQAMC")
                        .missionChange(false)
                        .numEnrouteStops(4)
                        .numTransLoads(3)
                        .originIcao("KATL")
                        .planDefinition("DEPLOY")
                        .plansNumber("T89002")
                        .serialNumber("9009209")
                        .statusCode("N")
                        .tpAircraftMds("C17A")
                        .tpTailNumber("99209")
                        .build()
                )
                .maintStatusCode("NMCMU")
                .mcTime(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
                .meTime(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
                .origin("THIRD_PARTY_DATASOURCE")
                .origNetwork("OPS1")
                .owner("EXAMPLE_OWNER")
                .reopenFlag(true)
                .rptClosedTime(OffsetDateTime.parse("2023-07-13T13:47:00.123Z"))
                .suppIcao("KCOS")
                .tailNumber("99290")
                .updatedAt(OffsetDateTime.parse("2022-01-01T16:00:00.123Z"))
                .updatedBy("some.user")
                .build()

        val roundtrippedLogisticsSupportListResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(logisticsSupportListResponse),
                jacksonTypeRef<LogisticsSupportListResponse>(),
            )

        assertThat(roundtrippedLogisticsSupportListResponse).isEqualTo(logisticsSupportListResponse)
    }
}
